### ISSUE TITLE
AMD target - wildcard malfunction

### ISSUE THREAD

**Issue by cmichaelgraham** [aurelia/framework#1]
Hmmm... I'm looking at the [generated AMD](https://github.com/aurelia/framework/blob/master/dist/amd/index.js#L12) and it seems to me like _exportsWildcard's check is backwards. 

It only assigns the export if it isn't undefined. I would think it would assign it if it IS undefined. I found this because Property (and many other items weren't defined on the exports) so it blows up in `skeleton-navigation` `nav-bar` when it tries to new up a Property.

If I change the line to === (from !==), it seems to work properly.

Same issue occures in [binding](https://github.com/aurelia/binding) repo --> [here](https://github.com/aurelia/binding/blob/master/dist/amd/index.js#L12)

**Comment by EisenbergEffect** [comment]
Fixed in the 6to5 compiler. I will update the compiler and re-build each library as part of the next cycle of releases.
