### ISSUE TITLE
Cannot find where click.trigger is handled in the code?

### ISSUE THREAD

**Issue by Serhioromano** [aurelia/framework#10]
I was trying to fire double click event. I tried `dbclick.trigger="edit()"` but with no result. then I tried to look where this is in the code but could not find a line with `click` keyword. How do I use other events like doubleclick?

**Comment by PWKad** [comment]
@Serhioromano I believe you are looking for `dblclick.trigger` not `dbclick.trigger`, any event should work.

**Comment by EisenbergEffect** [comment]
Correct. Thanks  @PWKad!

**Comment by Serhioromano** [comment]
@PWKad stupid me! What a shame :blush:
