### ISSUE TITLE
checkbox if.bind behavior

### ISSUE THREAD

**Issue by chandmk** [aurelia/framework#101]
```html
<input type="checkbox" if.bind="status" >My CheckBox</input>
<input type="checkbox" show.bind="status" >My CheckBox</input>
```
In both the above examples, if status is false, "My CheckBox" text is not being removed/hidden.  

if.bind works fine when I wrap checkbox element with template.  However show.bind has no effect on the template.  And in this case Checkbox element is always hidden.

``` html
<template show.bind="status" >
   <input type="checkbox">My CheckBox</input>
</template>
```

**Comment by EisenbergEffect** [comment]
I believe that this is due to incorrect html. The input element is a self-closing tag. So, it is written as follows: `<input type="checkbox" if.bind="status" >` So the binding does remove it.

**Comment by chandmk** [comment]
Ok, it makes sense that the following code requires <template> wrapping to completely hide the element along with the label.

```
 <input type="checkbox" if.bind="toggle" /> My Check Box
```
The following is not working.

``` html
<template show.bind="status" >
   <input type="checkbox" />My CheckBox
</template>
```

**Comment by EisenbergEffect** [comment]
Ok, that is a different story. We will investigate that.

**Comment by EisenbergEffect** [comment]
Apologies. I didn't see the details of your question very clearly. You cannot use show.bind on a template element. It's meant to be placed directly on the elements it should show only.
