### ISSUE TITLE
Where is your support forum ?

### ISSUE THREAD

**Issue by warrenbell** [aurelia/framework#104]
Where do I ask direct questions about using Aurelia. Am I suppose to do it here or on that noisy gitter.im chat room.

Thanks,

Warren

**Comment by PWKad** [comment]
We prefer pre-release questions in the gitter room as there is a ton of community support there to help.  Post-release we plan to have additional avenues that are more re-usable.  Feel free to ask your questions on gitter or StackOverflow.  Github issues are for feature requests or reporting bugs.

**Comment by warrenbell** [comment]
That chat room is noisy, trying to figure out if someone has answered my question or who has answered it is impossible. Maybe I just don't know how to use gitter.im yet, I will give it another try.

Thanks,

Warren

**Comment by EisenbergEffect** [comment]
We will add other channels in the future most likely.

**Comment by THuffam** [comment]
Just to add my 2c worth..  I find Gitter extremely ineffective..  A huge waste of time - both when trying to find something, and also being subscribed is very noisey, unless you know all about the content, then can comment.  Sure it might be flavour of the month or ok as a dev-team-chat tool like Slack, but as a knowledge base/knowledge sharing/forum/help tool, its pails even compared to even 20 year old discussion groups.

**Comment by MarcWeber** [comment]
For those who read the last comment first: http://aurelia.io/support.html -> stackoverflow. @THuffam Your comment was outdated. The thread talked about stackoverflow

**Comment by EisenbergEffect** [comment]
FYI, we are investigating and hoping to add a community forum in the near future.

**Comment by MarcWeber** [comment]
I was mistaken: The last comment on github was wrong, because that
person missed stackoverflow. I fixed it by adding another comment and
telling that. So there is a place to put questions.

SRY for this noise.

Marc Weber

**Comment by wallaceturner** [comment]
@EisenbergEffect  what is the reluctance to add a google group? stackoverflow is not suitable for some discussions/suggestions and gitter is, imo, mostly unhelpful. It has been 2+ yrs now without a forum - even if it was not an official support forum just a general community forum it would be helpful.

**Comment by AshleyGrant** [comment]
A forum is being prepped and will be released very soon.
