### ISSUE TITLE
Difference between import statements

### ISSUE THREAD

**Issue by chandmk** [aurelia/framework#106]
When using a 3rd party library import statement looks like the following
```
import _ from 'lodash'
```
But aurelia is similar to lodash above

```
import {inject} from 'aurelia-framework';
```
And your local module imports are
```
import {areEqual} from 'utils';
```

Why is this syntax difference?  What are those curly braces actually mean?

**Comment by PWKad** [comment]
Please feel free to ask these types of questions on our official gitter - gitter.im/aurelia/discuss

This is how ES6 module importing works with default exports and named exports.

**Comment by chandmk** [comment]
Thanks for the 'discussion board link".  Will do that.
