### ISSUE TITLE
Re: #14 Optional Bluebird plugin guidance is suspect

### ISSUE THREAD

**Issue by netaisllc** [aurelia/framework#108]
I'm not sure the guidance about how to drop-in Bluebird as a replacement still works as expected.

#### Background
I have a small project that includes a recent rev of Bluebird as a plain script tag, ahead of System.js and the Aurelia bootstrapping. (Image attached).

#### To Reproduce
I made a simple promise, caused it to "reject" in code and inspected the call stack.  There are references to es6-promises, but nothing from Bluebird.  (Image attached) 

Additionally, in the console the command **Promise.promisify** returns undefined (which I assume is because the es6.promise library doesn't support this feature.)

Maybe this is not an error, but its isn't what I expected. I expected to see references to Bluebird.
Any thoughts?

---
es6-module-loader v0.16.5
aurelia/framework@0.11.0

#### index.html
![selection_096](https://cloud.githubusercontent.com/assets/1242423/7553247/87fe68c4-f6a1-11e4-8351-9199752aef3b.png)

#### console (Chrome)
![selection_097](https://cloud.githubusercontent.com/assets/1242423/7553249/ab9c53f4-f6a1-11e4-8db2-3201846968bb.png)

**Comment by dpinart** [comment]
Could anyone drop bluebird in as a replacement of ES6 promises?

**Comment by netaisllc** [comment]
@NateRedding +1, great info, thanks.  I think my original casting of this concern as Aurelia is incorrect.  I, too, believe the root cause of my confusion was not understanding the shimming behavior of Babel with regard to polyfilling promises.
Thanks for the sample code.

(Also, If you are open to it, I'd like to bounce a Bluebird question off you, but this thread isn't the place. I'm at @netaisllc on Twitter)

**Comment by NateRedding** [comment]
The more I looked into it, I think it is likely the shim from Core.js that is causing the conflict instead of Babel. I am brand new to Bluebird myself, so I may not be able to help beyond basic usage. Also, I don't use Twitter, but you send an email to my gmail -- user name nateredding.

**Comment by EisenbergEffect** [comment]
We've added an update about this to our docs. It will be released soon.

**Comment by ohjames** [comment]
The docs say to load Bluebird before systemjs, which means I can't bundle bluebird?  The technique described above by @NateRedding leads to breakages in Edge... I think it doesn't like the promise implementation being switched while there are outstanding native promises.

Given how important bluebird is for performance I kinda feel it should be handled without needing to include an unbundled copy prior to systemjs.

**Comment by Gheoan** [comment]
@ohjames you can still load the same number of `.js` files by concatenating `bluebird` and `systemjs` and even the `systemjs` config

Example with `gulp-useref`:

```html
...
  <body aurelia-app>
    <!-- build:js main.js-->
    <script src="jspm_packages/npm/bluebird@3.4.0/js/browser/bluebi
rd.min.js"></script>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <!-- endbuild -->
    <script>
      SystemJS.import('aurelia-bootstrapper');
    </script>
  </body>
...
```

```js
gulp.task('bundle-index', function () {
  return gulp.src(paths.index)
    .pipe(useref())
    .pipe(gulp.dest(paths.exportSrv));
});
```
