### ISSUE TITLE
Documentation for DI is lacking for multiple dependencies.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/framework#109]
I have a class with two dependencies (Foo and Bar).  Foo must be transient.  Bar must be singleton.

To complicate matters, I can't use decorators at the moment (though, I don't know how to do it even with decorators).

If I do `static inject = [Foo, Bar];` I will get singletons of both Foo and Bar.

If I do `static decorators = Decorators.inject(Foo);` I will get a singleton Foo.

If I do `static decorators = Decorators.transient().inject(Foo);` I will get a transient Foo.

If I do `static decorators = Decorators.inject(Foo).inject(Bar);` I will get a singleton Bar.

If I do `static decorators = Decorators.inject([Foo, Bar]);` I get a runtime error (something about failing to instantiate due to `[Foo, Bar]` not being a function).

I'm not sure what else to try in order to get both injected, one as a transient and one as a singleton.

**Comment by kokhans** [comment]
Hi Zoltu,

As I understand from your question you should do next:
 - Decorate your injected module with @transient()

Example:
File foo.js:
```javascript
import {transient} from 'aurelia-framework';
@transient()
export class Foo {
   constructor() {
      console.log('Foo constructor was called');
   }
}
```
File main.js:
```javascript
import {inject} from 'aurelia-framework';
import {Foo} from 'foo';
@inject(Foo)
export class Main{
   constructor() {
      console.log('Main constructor was called');
   }
}
```

**Comment by Zoltu** [comment]
Is it not possible to have lifetimes decided by the class receiving the injection rather than the class being injected?  In my use case, `HttpClient` is setup as singleton lifetime.  I would like one of my classes to get a new instance of it every time.  Would I need to create a wrapper class around `HttpClient` like `HttpClientTransient` which has an `@transient()` decorator on it and then `@inject(HttpClientTransient)`?

**Comment by Zoltu** [comment]
```ts
// sometimes transient, sometimes static
export class Foo {
	constructor() { }
}
```
```ts
@inject(Foo) // should be injected as transient
export class Bar {
	constructor(foo: Foo) { }
}
```
```ts
@inject(Foo) // should be injected as singleton
export class baz{
	constructor(foo: Foo) { }
}
```

**Comment by EisenbergEffect** [comment]
You can accomplish this with a custom Resolver.
