### ISSUE TITLE
bower amd/index.js reference to System.js causes exception

### ISSUE THREAD

**Issue by sujesharukil** [aurelia/framework#110]
trying to get aurelia setup via bower and require js. require(["aurelia-bootstrapper"]) throws an exception 

Uncaught (in promise) ReferenceError: 
System is not defined {stack: (...), message: "System is not defined"}message: "System is not defined"stack: "ReferenceError: System is not defined↵    at ensureLoader (http://localhost:59184/bower_components/aurelia-bootstrapper/dist/amd/index.js:62:14)↵    at http://localhost:59184/bower_components/aurelia-bootstrapper/dist/amd/index.js:225:14"get stack: function () { [native code] }arguments: nullcaller: nulllength: 0name: ""prototype: StackTraceGetterconstructor: function () { [native code] }__proto__: Object__proto__: function Empty() {}<function scope>set stack: function () { [native code] }__proto__: ErrorensureLoader @ index.js:62(anonymous function) @ index.js:225

Do we need System JS even when loading from bower? Or am I missing something?

**Comment by EisenbergEffect** [comment]
This appears to be a bug.

**Comment by npelletm** [comment]
In loader-default a light shim for System is defined here : https://github.com/aurelia/loader-default/blob/master/src/index.js#L6-L16 but in there is no explicit dependency on aurelia-loader-default  here https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L1-L3 module.
It implies an error on System reference call when aurelia-bootstrapper load here : https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L65

I think that add an import statement to aurelia-default-laoder in header could solved the issue but I'm not sure f it is compliant with the aurelia-bootstapper design ?

**Comment by EisenbergEffect** [comment]
I'll take this issue. I'd like to see if there's a way to resolve this without a hard connection to the default-loader.

**Comment by EisenbergEffect** [comment]
I just pushed the fix to the bootstrapper. I'm about to make a bootstrapper release. This should be available in just a few minutes.
