### ISSUE TITLE
Hello World example not working in IE11

### ISSUE THREAD

**Issue by Manuel-S** [aurelia/framework#113]
I set up a hello world example for evaluation, but while it worked in chrome, I had no luck in IE. 
The exception I get is "Die Eigenschaft "Symbol(id)_i.22alybn8ccc" kann nicht definiert werden: Das Objekt ist nicht erweiterbar" (The Property "..." cannot be defined: The object is not extendable) But it's hard to trace the source of it.
Asked the guys from babel.js if they know what's going on, and one said that it's either "Map or Set in core-js module", but that it should be covered by tests. So without further ado, here's the minimal example:

run `npm init` with defaults, `jspm init` with defaults (babel), `jspm install aurelia-bootstrapper`

file index.html

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Test-App</title>
    </head>
    <body aurelia-app>
        <script src="jspm_packages/system.js"></script>
        <script src="config.js"></script>
        <script>
            System.import('aurelia-bootstrapper');
        </script>
    </body>
</html>
```

file app.html

```html
<template>
  <section>
    <h2>${heading}</h2>

    <form role="form" submit.delegate="welcome()">
      <div class="form-group">
        <label for="fn">First Name</label>
        <input type="text" value.bind="firstName" class="form-control" id="fn" placeholder="first name">
      </div>
      <div class="form-group">
        <label for="ln">Last Name</label>
        <input type="text" value.bind="lastName" class="form-control" id="ln" placeholder="last name">
      </div>
      <div class="form-group">
        <label>Full Name</label>
        <p class="help-block">${fullName}</p>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </section>
</template>
```

file app.js

```javascript
export class Welcome{
  constructor(){
  this.heading = 'Hello World!';
  this.firstName = 'John';
  this.lastName = 'Doe';
  }

  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }

  welcome(){
    alert(`Welcome, ${this.fullName}!`);
  }
}
```

In hope that you guys find what's going on here.

**Comment by zloirock** [comment]
As I wrote, looks like `traceur` runtime breaks [this simple function](https://github.com/zloirock/core-js/blob/v0.9.10/modules/%24.collection-strong.js#L21-L33) in `core-js` collections:

![scr](http://habrastorage.org/files/bde/2c4/7b1/bde2c47b1c594c54ba410a29f6747f37.png)

**Comment by Manuel-S** [comment]
I don't understand, is babel using traceur under the hood?

**Comment by zloirock** [comment]
@Manuel-S I don't know from whence here `traceur`, but in this example added `traceur` runtime and it's breaks `core-js`.

**Comment by EisenbergEffect** [comment]
We don't use Tracuer. It's possible that jspm added it for runtime compilation, but if you are using Gulp to pre-compile, then that shouldn't be coming into play. Check in your package.json and your config.js and see if the jspm section is referencing a tracuer dev dependency. Maybe that is somehow related?

**Comment by Manuel-S** [comment]
I am using babel, as I said:

```
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

**Comment by zloirock** [comment]
Looks I was wrong. I install `jspm` with default parameters, as you said in gitter, with `traceur`.

**Comment by Manuel-S** [comment]
Hm it set babel as default for me. [confusion intensifies]

**Comment by zloirock** [comment]
Possible `jspm` issue. I copied `modules` and  `library` path from `npm`  package to `jspm` and it works correct.

**Comment by zloirock** [comment]
Works correct with `core-js` 0.9.11, already was fixed in master branch.
