### ISSUE TITLE
Combining SailsJS with aurelia.io

### ISSUE THREAD

**Issue by RobertDiebels** [aurelia/framework#116]
Hi guys,

I don't know if this is the appropriate please to ask for some assistance but I'm going to do so anyway.

I'm trying to get SailsJS and aurelia into a combined platform. I've gotten pretty far but I've hit a snafu.

I got aurelia kinda running and it displays some debug information:

INFO [aurelia] Aurelia Starting
index.js:41 DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.11.0.
index.js:41 DEBUG [aurelia] Configured plugin github:aurelia/templating-binding@0.11.0.
index.js:41 DEBUG [aurelia] Loading plugin github:aurelia/templating-resources@0.11.1.

But while loading the templating-resources I get this error:

Uncaught Error loading "aurelia-task-queue" at http://localhost:1337/aurelia-task-queue.js
Error loading "aurelia-task-queue" from "github:aurelia/templating-resources@0.11.1" at http://localhost:1337/jspm_packages/github/aurelia/templating-resources@0.11.1.js
Not Found: http://localhost:1337/aurelia-task-queue.js(anonymous function) @ index.js:204

For some reason aurelia is trying to locate "aurelia-task-queue" in my root. I have no idea why. If you need my system.js config file I'll give it to you, but maybe you'll know what's wrong at a first glance.

Also, I'm kind of new to the whole web thing (Java background (2,5 years), and for the past 2 months I've been a web front-end developer), but I learn fast. So please shoot at this if you can :P.

Thanks in advance, Robert.

**Comment by RobertDiebels** [comment]
You can consider the above invalid. I've already solved it. Was a simple matter of configuration options.

**Comment by kristianmandrup** [comment]
@RobertDiebels would love to see you Aurelia Sails integration and build on it for a standard solution :)

**Comment by RobertDiebels** [comment]
I actually have it working right now. The only obstacle I have remaining is that I can't seem to get babel to work with Sails (yet). 

I know there is a hook available but for some reason it is not transpiling the app.js file (the standard one from your "get started" section). 
So I just used the "Try it "-section on the babel website to get some transpiled javascript. After that everything worked.

Haven't done requests to Sails Controllers/Models but I don't think that would be much of a hassle.

I would write a blog about it. But I intend to use this combo to build my blog haha.

**Comment by RobertDiebels** [comment]
@kristianmandrup Hey, I would like to notify you that I managed to get it working. (I've not worked with Aurelia or Sails before the past week so it took me longer than it should have).

However everything is running. I'll see if I can get something posted on my github if people are interested in this.

**Comment by kristianmandrup** [comment]
@RobertDiebels I'd be very interested to have a look and help improve it further ;)

**Comment by Mordred** [comment]
@kristianmandrup @RobertDiebels Check my example: https://github.com/Mordred/aurelia-sails-socket-client/tree/master/example
