### ISSUE TITLE
Combining Sails with Aurelia

### ISSUE THREAD

**Issue by RobertDiebels** [aurelia/framework#117]
Hi guys,

I would like to submit something you may find useful. I just created a Gist on how to set up a Dev environment for SailsJS to serve an Aurelia app.

It's over here: https://gist.github.com/RobertDiebels/f5f76b874bd8ecfe1e9b

If you can please punch some holes in it. If not, feel free to use it. Any feedback is welcome.

Thanks, Robert.

**Comment by kristianmandrup** [comment]
Awesome, thanks :)

**Comment by RomainLanz** [comment]
That's nice @RobertDiebels, but we also need to have gulp to build JS files. :/
