### ISSUE TITLE
bindable property with Compose element 

### ISSUE THREAD

**Issue by CarlosOnline** [aurelia/framework#118]
In the following I want to pass the parent object into the composed view model.  Is that possible?

        <template repeat.for="comp of form.components">
            <Compose
                    parent.bind="$parent"
                    model.bind="comp"
                    view-model="component"
                    
                    />
        </template>

**Comment by jdanyow** [comment]
Please direct these types of questions to the gitter:  https://gitter.im/Aurelia/Discuss

There are many community members ready and able to consider your use case and propose solutions.  If you don't get a satisfactory resolution on the gitter, go ahead an re-open the issue with a link to the conversation in the gitter.

Thank you!

**Comment by marknutter** [comment]
The problem with using gitter.im is that the answer may be given by a community member but there's no way for other people to view that answer as far as I can tell. I would very much like to know the asnwer to @CarlosOnline's question but alas, it's gone (if it ever existed). I also tried to ask the question in gitter.im but didn't receive an answer.

**Comment by Ruchir-zealous** [comment]
Any update on this issue? I am having the same issue, let me know if you got the solution.
