### ISSUE TITLE
Parameterized child routes

### ISSUE THREAD

**Issue by mandulov** [aurelia/framework#119]
The documentation is very lacking on the subject.
I want to create a child router with optional **id** parameter, which will handle the following example routes: **user/create**, **user/:id/edit**, **user/:id/roles**, etc.

Here is an another issue (with activate method's params object):
```
{ route: 'user/:id', moduleId: './user/index', nav: false }
```
With this code, the activate method of the **user/index** module recieves the params object, with the **id** property set to the given value. But the module has a child router:
```
{ route: ['', 'edit'], moduleId: './edit/edit', nav: true, title: 'Edit user' },
{ route: 'roles', moduleId: './roles/roles', nav: true, title: 'Edit user roles' }
```
Now the activate methods of **user/edit/edit** and **user/roles/roles** params objects do not have an **id** property, which I need for the views.

**Comment by dpinart** [comment]
you can get id parameter with:
activate(params, config, instruction){
    var id = instruction.params.$parent.id;
}

hope it helps

**Comment by bryanrsmith** [comment]
@EisenbergEffect What do you think of merging the current and ancestor params into a flat object for the first argument to `activate`, and leaving the current object with `$parent` chain available on the `instruction` in case it's needed?

**Comment by EisenbergEffect** [comment]
I think that would work. So, on the params object you have your immediate parameters, plus anything from parent routes. I like that. If we can do that and leave $parent around, perhaps to resolve conflicts, I think that would be nice and also backwards compatible. Let's do it.

**Comment by bryanrsmith** [comment]
I was thinking we'd also pull $parent off of the object passed to `activate`, to make it safe for things like iteration & serialization. You'd have to use instruction.params and instruction.params.$parent for the separated objects. You're right that it would be a breaking change, so maybe it's not worth removing the property.

**Comment by EisenbergEffect** [comment]
It's ok. I think it's still a small change and not many people are using it. Let's go ahead and make the breaking change since that results in a better final product. We'll be sure to include it in the blog post so people know.
