### ISSUE TITLE
Internet Explorer classList support

### ISSUE THREAD

**Issue by jdanyow** [aurelia/framework#121]
Components such as the `ViewSlot`, the `show` binding command and the new `ClassObserver` use [Element.classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList).

Internet Explorer [support for `classList` is spotty](http://caniuse.com/#search=classList), especially with SVG elements.

How do we want to handle this?  Direct users to a [polyfill](https://github.com/eligrey/classList.js)?  *Note this polyfill has an open PR for the SVG support aspect.*

**Comment by EisenbergEffect** [comment]
We should probably include the polyfill in our binding library, including the patch for SVG. We don't need to link to it, we can just include the source directly since it's a small polyfill. We would just need to add ot to the acknowledgments document.

**Comment by jdanyow** [comment]
sounds good- will do.
