### ISSUE TITLE
Exception for delegated event ?

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/framework#122]
I have a custom element to display alerts, in which the click event is delegated. Alerts are correctly getting added and displayed. When click to close the alert, the alert is closed but exception triggered:
Uncaught Error: closeAlert is not a function

Any ideas what could be wrong here, not sure if framework issue or mine ?

```html
<template>
    <div repeat.for="alert of Alerts" class="alert alert-${alert.type} alert-dismissible" role="alert"
         click.delegate="closeAlert($index)">
        <button type="button" aria-label="Close" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <p>${alert.msg}</p>
    </div>
</template>
```

```javascript
import {customElement } from 'aurelia-framework';

@customElement('Xalerts')
export class XAlerts {

  constructor() {
    this.Alerts = [];
  }

  bind(bindingContext) {
    // inject the reference into parent view (or use messages ... _todo)
    bindingContext.__alerter__ = this;
  }

  addAlert(alert) {
    this.Alerts.push(alert);
  }

  closeAlert(index) {
    this.Alerts.splice(index, 1);
  }
}
```

**Comment by EisenbergEffect** [comment]
In this case, you need to use $parent.closeAlert since the closeAlert method does not exist on the alert itself, but on the xalerts class. We will be improving this in the future, but $parent is needed to reach the parent binding scope for now.

**Comment by bsrdjan** [comment]
thanks, works.
