### ISSUE TITLE
Aurelia Todo MVC not working in Safari

### ISSUE THREAD

**Issue by Krabaul** [aurelia/framework#124]
The Aurelia Todo MVC is not working in Safari Version 8.0.6 (10600.6.3).
![aurelia todo mvc](https://cloud.githubusercontent.com/assets/11362494/7982036/8b7b7878-0b07-11e5-9f2d-87aaa898614b.png)

  In Chrome the Todo app works and the Navigation App is woking completely fine in both browsers.

**Comment by RomainLanz** [comment]
I have got the same problem in by Firefox client when I have try to developp an application.

@RobertDiebels, did you investigate about this problem?

**Comment by EisenbergEffect** [comment]
The error shown above relates to a bad release of the web components library which was missing the HTMLImports polyfill. That should be fixed. I'm going to close this issue. I suspect this sample may have other issues. I haven't reviewed it thoroughly myself yet. If you find anything else let me know.

**Comment by RobertDiebels** [comment]
Responding a bit late here, but I didn't write up the TodoMVC example. @RomainLanz I made a much more barebone version which simply combines Sails and Aurelia into a really simple application which requires you to enter your name etc.

Also as Mr. Eisenberg mentioned the HTMLImports bug is already fixed.
