### ISSUE TITLE
Delegate custom element event handler logic to parent view method

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/framework#126]
I have a custom element whose `rowSelect`click handler logic shall be delegated to parent view method.

Here is the custom element

```html
<template>
    <div class="row">
      <table id="_header" class="table tableHeader table-condensed">
        <thead>
        <tr>
          <th repeat.for="header of headers" click.delegate="$parent.headerClick($index)" width="${header.len}" class="carret">${header.text}</th>
        </tr>
        </thead>
      </table>

      <div class="bodycontainer scrollable">
        <table id="_body" class="table table-hover table-striped table-condensed table-bordered">
          <tbody>
          <tr repeat.for="record of records" click.delegate="$parent.rowSelect($index, $event)">
            <td repeat.for="header of $parent.headers">${$parent.record[header.id]}</td>
          </tr>
          </tbody>
        </table>
      </div>

    </div>
</template>
```

and how it is used in a parent view:

```html
<uitable headers.bind="Headers" records.bind="Model.TOITEMDATA" rowselect="itemSelect"></uitable>
```

The `itemSelect` is the parent view method:

```javascript
  itemSelect(index, event) {
    console.log(index, event, this, this.Model);
    this.Model.itemDetail = this.Model.TRANSFERORDERITEM[index];
  }
```

In a custom element I try to get the function from the parent view and call it from custom element click handler:

```javascript
 bind(bindingContext) {
    this.$parent = bindingContext;
    let rowselect = this.element.getAttribute('rowselect');
    if (rowselect !== null) {
      console.log('binding', rowselect, 'of', bindingContext, bindingContext[rowselect]);
      this.rowSelector = bindingContext[rowselect];
    }
 }

  rowSelect(index, event) {
    // console.log('rowSelect:', index, event);
    if (this.rowSelector !== null)
      this.rowSelector(index, event)
  }
```

This way, the itemSelect method of the parent view is called from the `rowSelect` method of the custom element but the console log of `this`, in `itemSelect`, shows the `this` of the custom element, not the parent, as I would expect. It looks like `this` of the parent model got replaced with `this` of the custom element ?

Any ideas why this happens and how to accomplish the desired behaviour, in a simpler way perhaps ?

**Comment by wshayes** [comment]
I think this blog explains the solution http://blog.durandal.io/2015/06/05/building-aurelias-focus-attribute/

at this point in the doc: 'solve this issue by creating instance functions that capture this in their scope'

**Comment by bsrdjan** [comment]
thanks, it really solved the problem and learning more JavaScript is always good:

```javascript
  constructor(sessionSettings) {
    this.sessionSettings = sessionSettings;

    this.itemSelect = (index, event) => {
      this.Model.itemDetail = this.Model. TRANSFERORDERITEM[index];
    };
```
