### ISSUE TITLE
Aurelia looks for html equivalents in templating-router and templating-resources

### ISSUE THREAD

**Issue by danielheddelin** [aurelia/framework#128]
404's on if.html, compose.html, if.html, router-view.html etc.
When renaming if.html to if.js just for fun, you get a 404 on if.js, just as if naming convention was used to match views and viewmodels.

**Comment by zewa666** [comment]
this seems related to this issue https://github.com/aurelia/loader-default/issues/6

**Comment by danielheddelin** [comment]
Indeed it does. I'll be running some more jspm tasks then. 
Just for information: My method was to follow Rob's advise, which means I went and uninstalled each jspm aurelia package and then performed a jspm install of each package again. I also did a jspm update which didn't resolve the issue.

**Comment by zewa666** [comment]
ok, so try the following:

inside your project folder run
```
jspm install aurelia-framework aurelia-bootstrapper aurelia-dependency-injection aurelia-http-client aurelia-router
```

that should now update your package.json to contain the latest version requirements. If that doesn't help, try deleting the folder `jspm_packages` and running ``jspm install` afterwards

**Comment by danielheddelin** [comment]
Fiddling with jspm to try to get it working. Also followed your steps but still no luck.

      "aurelia-animator-css": "github:aurelia/animator-css@^0.3.0",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.13.0",
      "aurelia-computed": "github:jdanyow/aurelia-computed@^0.1.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.8.1",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@^0.5.0",
      "aurelia-framework": "github:aurelia/framework@^0.12.0",
      "aurelia-http-client": "github:aurelia/http-client@^0.9.1",
      "aurelia-router": "github:aurelia/router@^0.9.0",
      "aurelia-validation": "github:aurelia/validation@^0.2.4",

I'll keep you posted if I manage to find the quirk.

**Comment by zewa666** [comment]
see the above referenced issue, @mordred seems to have solved his issue

**Comment by Mordred** [comment]
You have override dependencies for `aurelia-validation`.

Place this inside our `package.json`:
```json
{
    "jspm": {
        ...
        "overrides": {
            "github:aurelia/validation@0.2.4": {
                "dependencies": {
                    "aurelia-binding": "github:aurelia/binding@^0.7.0",
                    "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.8.0",
                    "aurelia-templating": "github:aurelia/templating@^0.12.0"
                }
            }
        }
        ...
    }
}
```

Then remove your `config.js` and `jspm_packages` and run `jspm install`.

Or manually modify versions inside your `config.js`. But this changes will be rewritten. Override option is more permanent.

**Comment by danielheddelin** [comment]
Thanks. config.js was definitely the root cause.
