### ISSUE TITLE
Could not find view model for composed views

### ISSUE THREAD

**Issue by shamresh** [aurelia/framework#129]
Hi, for a custom element I found the viewmodel for my drag event as : this.parentElement.primaryBehavior.executionContext
However for a view from a route I was unable to find any element with had the primaryBehavior property. Is this as expected?

EisenbergEffect 2 minutes ago  
Create an issue for that and we can probably address it. It would probably be stored as a special property on the router-view and compose elements themselves.
Because these views don’t have a wrapper element of their own, there’s no place to put that data other than the composition container itself. We could add it there though.

**Comment by EisenbergEffect** [comment]
To locate the data for a router view, you need to find the router-view first. Look for an element that has `element.au.controller.model` with a typeof RouterView. Then, using that value you can do `routerView.view.owner.model`
