### ISSUE TITLE
ES6 / ES7 requirements

### ISSUE THREAD

**Issue by romulof** [aurelia/framework#130]
What are the features from ES6, ES7 and Web Components required to run Aurelia without polyfills or transpiling?

I could make a test page to people check how browser support is going.

**Comment by EisenbergEffect** [comment]
From Web Components, we need HTMLTemplateElement and optionally ShadowDOM.
From ES6 we use classes, arrows, promises and various library functions.  We would need to review our code thoroughly to get the full list.
For ES7 we use property initializers for classes and decorators.

**Comment by romulof** [comment]
Thanks!
