### ISSUE TITLE
aurelia-skeleton-navigation. Switching Views quickly can cause views to appear combined

### ISSUE THREAD

**Issue by greeny1000** [aurelia/framework#132]
Hi,
Using Windows 7, node V0.12.4, npm 2.10.1, jspm 0.15.7, aurelia-skeleton-navigation 0.14.0, Firefox 38.0.5 or Chrome Version 43.0.2357.124 m

When viewing a clean install of the skeleton-navigation, if i click quickly between "Flickr" & "Child-Router" a few times not allowing the views to fully load, the view becomes corrupt. 
It is as if the old view is not clearing and the new view is being appended to it.
Views stay "corrupted" when any further view switching is done until browser is refereshed.
There are no errors in the console.

This occurs when viewing standard 'gulp watch', but i can also reproduce this from a standalone server with no browsersync "in the middle"

Discussed this on Gitter, it seems at least one other person can reproduce this, but others can not.

Below is an screenshot, notice router is on "Child Router" view, but flickr images are above it.

![aurelia](https://cloud.githubusercontent.com/assets/9608005/8114675/1a1f2a50-106e-11e5-8051-1c0b0cd7cbcd.jpg)
cheers

**Comment by francoishill** [comment]
Yes I can also reproduce this. Easiest for me to reproduce is load the page "freshly" at the home url. Then click on "Flickr" and basically instantly click on "Child". Then there will already be two views loaded. Then it stays corrupt until refreshing (F5) again.

**Comment by zewa666** [comment]
I think that might be related to the view-swap implementation and a sideeffect from the css-animator. See some details here https://github.com/aurelia/animator-css/issues/7

**Comment by greeny1000** [comment]
@zewa666 is correct.
Removing the css-animator plugin stops this issue, so it would seem very likely the cause is there.

**Comment by greeny1000** [comment]
Possibly related to https://github.com/aurelia/router/issues/110

**Comment by EisenbergEffect** [comment]
I believe this is fixed now.
