### ISSUE TITLE
Case for Aurelia and Why Two databinding is essential?

### ISSUE THREAD

**Issue by vairam-svs** [aurelia/framework#133]
Questions: Case for Aurelia and Why Two databinding is essential?
Why yet another framework?
http://xkcd.com/927/
I was able to find why is it better than Angular 2.0 is documented
Why no ReactJS is documented?
Looking to find help on compare https://muut.com/riotjs/
Also, a UI framework Aurelia does not have UI API (tags/widgets - button, list, grid, etc) or does it in one of the packages? or is it a commercial version?
I am evaluating a modern library/framework/platform/package - does not matter. But the one that will work very well in modern browser, but gracefully work in >IE9.
Tooling - ASP.NET MVC Helpers to build javascript code with strong code time binding with C# Models/WebApi
Any help much appreciated.
Thanks

**Comment by EisenbergEffect** [comment]
Please ask questions in our official gitter channel.
