### ISSUE TITLE
no clear way documented for wrapping content in custom elements

### ISSUE THREAD

**Issue by mgenev** [aurelia/framework#134]
This is a core function and I can't find a simple way to do it.
```
<custom-element>wrapped content</custom-element>
```
When I asked this in the chat I was given some resources, but neither was a straightforward way to do this.
In ember there's a very easy way to do this with 1 keyword - yield which specifies where the wrapped content lands
http://guides.emberjs.com/v1.10.0/components/wrapping-content-in-a-component/

This would make things a lot easier.

```
<script type="text/x-handlebars" id="components/blog-post">
  <h1>{{title}}</h1>
  <div class="body">{{yield}}</div>
</script>
```
```
{{#blog-post title=title}}
  <p class="author">by {{author}}</p>
  {{body}}
{{/blog-post}}
```

**Comment by Aaike** [comment]
This is probably related to https://github.com/aurelia/templating/issues/85

**Comment by EisenbergEffect** [comment]
For this you want to use content selectors.
Simply place a `<content></content>` tag in your view's markup. That will be where the content of the custom element gets re-projected. You are right, we need lots more documentation on that. It's coming. For the time being, here's a blog post on the subject: http://blog.durandal.io/2015/04/24/aurelia-custom-elements-and-content-selectors/
