### ISSUE TITLE
is there any kind of automatic teardown per route change or component ceasing being rendered

### ISSUE THREAD

**Issue by mgenev** [aurelia/framework#135]
I have a situation in which I'm using the event aggregator to fire an event, and multiple routes have the need to listen for that event, but the problem is that multiple routes also respond to it even though only 1 is active. Is it that Aurelia keeps all the bindings alive even though the route's inactive? Is there no automatic teardown upon changing route?

I'm seeing this in the docs:
> Note: All forms of the subscribe method return a dispose function. You can call this function to dispose of the subscription and discontinue receiving messages. A good place to dispose is either in a view-model's deactivate callback if it is managed by a router, or in its detached callback if it is any other view-model.

But still the question remains is there any kind of teardown out of the box or should it all be manual? If manual, then it'd be really beneficial to learners if it's well described in the docs, because it leads to pretty bad bugs if done incorrectly...

**Comment by EisenbergEffect** [comment]
When you subscribe for events on the event aggregator, the aggregator must keep a reference to the subscriber. As a result, even when the router tears down a view model, the event aggregator still has the reference. This is a good place to use the deactivate hook in the navigation lifecycle, so you can unsubscribe from the events when the router deactivates the view model.
