### ISSUE TITLE
polluting view-models with observers

### ISSUE THREAD

**Issue by KenRmk** [aurelia/framework#137]
Hello, while logging my view-model I noticed it's polluted by observers (__ array_observer__, __ observer__, __ observers__) and it clogs up my console.
It'd be nice to not enumerate them or, better yet, put it somewhere else (maybe WeakMap)

![](http://ctrlv.cz/shots/2015/06/19/ay17.png)

PS: Thanks for all the work on Aurelia. I Decided to switch while waiting for Angular 2 and discovering all the nasty changes (forms, two-way binding) and couldn't be happier

**Comment by EisenbergEffect** [comment]
Unfortunately WeakMap isn't widely supported and there's no way to polyfill it that doesn't memory leak. That's primarily why those properties live there now.
