### ISSUE TITLE
Binding breaks when using datepicker from JQuery UI

### ISSUE THREAD

**Issue by whtdrgn101** [aurelia/framework#138]
Hello, I'm trying to create a custom attribute ('date-picker') that lets me attach a JQuery UI datepicker to a form element. The problem I'm having is that the binding is not detecting the when the date picker UI changes the date. 

**The markup looks like this:**
`<input type="text" value.bind="round.recordedDate" onChange.bind="handleDateChanged"  date-picker="value.two-way: round.recordedDate" class="form-control" id="roundDate" placeholder="" />`

**date-picker.js:**

```javascript
import {customAttribute, bindable, inject} from 'aurelia-framework';
import $ from 'jquery';
import {datepicker} from 'jquery-ui';

@inject(Element)
@customAttribute('date-picker')
@bindable('value')
export class DatePicker {
  constructor(element) {
    this.element = element;
  }

  bind() {
    $(this.element).datepicker({
      format: 'mm/dd/yyyy',
      onSelect: function(date, element) {
        $(element).datepicker("setDate", date);
      }
    });
  }

  valueChanged(newValue){
    $(this.element).datepicker("setDate", newValue);
  }
}

**Comment by jdanyow** [comment]
Aurelia is [listening](https://github.com/aurelia/binding/blob/master/src/event-manager.js#L82) for the input's `change` or `input` event.  JQuery UI's datepicker doesn't fire events when it updates the input's value.  Try changing your `onSelect` callback to this:

```
function() {
  $(this).change();
}
```
http://stackoverflow.com/a/6471992/725866

**Comment by mikeobrien** [comment]
BTW, this is/was a huge issue with Angular 1.x, esp when it comes to browser auto fill. Something to be aware of: https://github.com/angular/angular.js/issues/1460

**Comment by whtdrgn101** [comment]
I actually solved it by using the aurelia-flux plugin and focusing my design around messages being dispatched from my components.

**Comment by mikeobrien** [comment]
Oh nice, thx!

**Comment by krokofant** [comment]
I'm having almost the same problem with Metro-UI's datepicker. I found this link useful https://www.danyow.net/jquery-ui-datepicker-with-aurelia/

My solution looks like this, inspired by the link above:
```js
export class DateFilterCustomElement {
    selectedDateNode: HTMLElement

    selectedDateChanged() {
        console.log('date changed', this.selectedDate)
    }

    attached() {
        console.log('attached date filter')
        $(this.selectedDateNode).on('change', e => e.target.dispatchEvent(new Event('input')))
    }
}
```

```html
<template>
    <div class="input-control text" data-role="datepicker" data-format="yyyy-mm-dd" data-week-start="1">
        <input value.bind="selectedDate" ref="selectedDateNode" type="text" placeholder="Välj datum">
        <button class="button"><span class="mif-calendar"></span></button>
    </div>
</template>
```

Note the `ref="selectedDateNode"`.
