### ISSUE TITLE
Bluebird optional plugin

### ISSUE THREAD

**Issue by delaman** [aurelia/framework#14]
Please consider [Bluebird](https://github.com/petkaantonov/bluebird) as an optional plugin.

Offers greating debugging while development.
Is able to automatically create promises from callbacks.
Error handling. 
Faster than native promises.

**Comment by benjamingr** [comment]
Adding what I said in the chat: this requires zero work on your side. Bluebird is a drop in replacement for native promises which has performance and debuggability gains. 

Simply including bluebird before Aurelia should do the trick :) 

(Including it later would also work but only for user-land code)

**Comment by petkaantonov** [comment]
> Offers greating debugging while development.

You can use long stack traces in production too, as long as it's 2.8.0+

**Comment by Mayho** [comment]
:+1:

**Comment by EisenbergEffect** [comment]
Thanks all! I've added a note about this in the docs! I'm anxious to try this myself in combination with 6to5 coroutines.
