### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by heruan** [aurelia/framework#141]
What about multi-tenancy support in Aurelia? Basically a single application with some per-tenant customized elements (e.g. logo, title, `http-client` base url), where the tenant is identified by the hostname:
- http://lorem.example.org/app
- http://ipsum.example.org/app
- http://dolor.example.org/app

**Comment by smolinari** [comment]
Isn't multi-tenancy a server side concern?

Scott

**Comment by EisenbergEffect** [comment]
The first real Aurelia app I built, before we even announced the framework, was a multitenant app. There shouldn't be any problems with this.
