### ISSUE TITLE
Value Converter rebinding - translation

### ISSUE THREAD

**Issue by stephenlautier** [aurelia/framework#144]
Hi,

I've been experimenting with Aurelia and I've tried to implement a **ValueConverter** for translations (along some other basic stuff :) ).
I'm not too sure whether its the most appropriate component to be dealt with, however it makes it very efficient/clean to use as I've been using similar approach in my SPA. 

Usage wise would be something like the following:
```
${ "welcome" | translate }
 => [en] "Welcome"
 => [it] "Accoglienza" (im not Italian :D)
```

In a nut shell this is what I did:
- Created a service named **TranslationService** to store translation table (data), store current language, get by key (for current language).
- Created value converter which uses Translation service (via DI), to get value by key.

So far so good - it works and it was really easy to implement. However the issue happens when switching language at run-time, the value converters won't rebind. NOTE: I have a dropdown list to be able to change the language.

Is there a way to force them rebind, or observe? I tried to use the **ObserverLocator** within the Value Converter, however I don't think its the way to do it, my converter looks like this:
```
@inject(TranslationService, ObserverLocator)
export class TranslateValueConverter {


	constructor(translationService, observerLocator) {
		this.translationService = translationService;

		var subscription = observerLocator
			.getObserver(translationService, "currentLanguage")
			.subscribe(this.onLanguageChange);
	}

	onLanguageChange(newValue, oldValue) {
		console.log(`Language changed! ${newValue} <- ${oldValue}`);
		//TODO: rebind?
		//this.toView(newValue);		
	}

	toView(value) {
		return this.translationService.get(value) || value;
	}
}
```
Is there a way to handle this? or the Value Converters always have to be stateless? If so how would you handle something like this?

P.S. I had forked the skeleton-navigation and have my source available here if needed:
https://github.com/stephenlautier/skeleton-navigation/blob/master/src/translation/translation.convertor.js

Thanks!

**Comment by jdanyow** [comment]
A way to handle that is coming- the feature is called binding "signals" (a sub-feature of binding behaviors).  The thought is you'd be able to name binding instances and "signal" them to re-bind as-need (ie when the user chooses a different language).

You can track the binding-behavior feature set here:  https://github.com/aurelia/templating-binding/issues/25

**Comment by stephenlautier** [comment]
Thanks for the fast reply! Will keep an eye on that feature. Thanks once again.

**Comment by EisenbergEffect** [comment]
@jdanyow beat me to it! Nice :)

**Comment by wardbell** [comment]
The rebind idea is great.  So many bound values are inert most of the time ... until something relatively rare happens (e.g., language change, user logs out and back in as someone else, ...).

I was thinking of an event of some sort. I wouldn't want to have to name every binding uniquely. But I could attach them to a common event-name of my choosing. Then ... bam!

Is that how it works?

**Comment by jdanyow** [comment]
yep- exactly like that :+1:  You'd tag a bunch of bindings with a signal name like "language changed" and then signal "language changed" when you want the bindings to re-evaluate.  The binding behavior model allowed for other interesting binding customization scenarios like throttle, debounce, etc
