### ISSUE TITLE
Using Aurelia for a new website, should I?

### ISSUE THREAD

**Issue by ronagam** [aurelia/framework#148]
Hi,
We are finalizing architecture for a social website that includes profile, profile matching and video chatting. The team likes Aurelia, but I am a bit worried. Website launches in limited beta Sept 2015. Can you try and best answer these questions:

Choice & Benefits
•	What are the alternatives to Aurelia
•	What are the benefit we are getting vs. above?
•	What are the drawbacks (page load time, restricted add-ons etc.)?
•	How much time do you estimate it will take a developer to become productive on Aurelia?

Technology maturity & stability
•	Is Aurelia GA (i.e. v1.0 and above)? If not what is the state, alpha/beta and so on.
•	If above yes. How many live applications are GA with Aurelia?
•	How many contributions and contributors?
•	What technology company is backing Aurelia?
•	Any missing features that you know you need for the pilot and waiting for Aurelia roadmap?
•	How is the operability and security of Aurelia?
•	Is it verified that it supports current popular platforms – MAC and Windows Desktop (v7 and up), iPAD (ios 7 and above) and Tablet (Jellybean 4.1 and above)
•	Is there any website built with Aurelia that I can access??

Mitigation
•	What are 2 other alternatives we can use
•	What would be the cost of switching to these technologies – time and dev. effort
•	What would be the impact on our users if we had to do this after its deployed (graphics or any behavior will change)?

I often use these set of question, and it served me well in taking educated risks.
Thanks.

**Comment by donovanmuller** [comment]
Perhaps this https://github.com/aurelia/framework/issues/74#issuecomment-116808034 will be of some help.

**Comment by ronagam** [comment]
Thanks, I read through this post and it provides a couple of answers (e.g. backed by... and contributors) but couldn't find anything to answer most other questions.

**Comment by The1nternet** [comment]
@ronagam I'd suggest building a simple example app with some basic functionality so that you can get a feel for using Aurelia.  Aurelia's focus is on a great developer experience, so your team'll love using it, and it's backed by an amazing company and core team, so there's really not any risk in choosing it.

**Comment by Martin-Andersen** [comment]
Try take a look at Meteor
https://www.meteor.com
