### ISSUE TITLE
Using directly typescript in jspm/systemJs for a better typescript experience.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/framework#149]
I'm experienced in the compiled world (c#) and I'm not a javascript guru.
I'm convinced that the future of javascript will be typescript and that aurelia, as a developer centered framework should embrace typescript. The type checking together with classical code refactoring features are key for professional (web) development.
The examples I have seen so far where aurelia is used together with typescript are sub optimal and not leveraging the power of systemJs because it needs other module loader mechanisms.
I have seen samples where the typescript code is first compiled to ES6 and then handed over to babel...

Apparantly, as we can learn from the examples on systemjs and jspm in these branches in the typescript samples from microsoft, systemJs/jspm can handle now directly typescript or can let the browser do the typescript compilation.
https://github.com/Microsoft/TypeScriptSamples/tree/jspm
https://github.com/Microsoft/TypeScriptSamples/tree/systemjsSample
Both samples need jspm@beta.

I'm not too much into the details of jspm/systemjs, but I'm wondering if the above samples can lead to a better typescript experience.
We should really envision the scenario where a simple code editor is used together with gulp as well the usage of an IDE like webstorm where compilation is done by the IDE in such a way the refactoring tools can be used.
Cheers
paul.

**Comment by EisenbergEffect** [comment]
The releases coming this week will have WIP versions of d.ts files for all aurelia libraries. That is our first step towards better TS support. However, it's not a good idea to go to production with system.js compiling your TS on the fly. That will provide very poor performance. If you want to do that during development, you can configure that today.

**Comment by paulvanbladel** [comment]
Hi Rob,
Thanks for the prompt reply.
Completely agree that in browser compilation can never be a production scenario.
I like to debug javascript code in the browser (for nodejs I never use the node-debug tool in the browser, but I use an IDE). I like the transparency of seeing only the the code in the browser which you wrote, i.e. the ts code.
The other example from the typescript samples uses typscript with systemjs rather than the other module loaders. Do you see this as a potential improvement for aurelia?  As far i can see, systemJs is superior to the other systems.

**Comment by EisenbergEffect** [comment]
We have used system.js from the beginning. It's our standard, recommended module loader. It's the best out there.

**Comment by wardbell** [comment]
Debugging TS in the browser (with pretranspiled JS) is a pretty comfortable experience thanks to source maps. 

Can't say that yet about debugging production-ready bundled code but folks are working on making that a better experience.

Examples will help. My point is that you can expect this to work.

**Comment by paulvanbladel** [comment]
My point is that when looking to the current aurelia typescript samples (https://github.com/cmichaelgraham/aurelia-typescript), "require" is used instead of systemjs and it uses kind of precompiled aurelia-bundle.js.
It would be much nicer if these kind of typescript based projects would work in the same manner as a non-typescript project in the sense that you can setup things simply with jspm install aurelia-framework aurelia-...  (as far as I can see you can't do this when using typescript)
The new jspm@beta seems to support directly typescript.
See here an extract from jspm init :

![image](https://cloud.githubusercontent.com/assets/4886272/8451424/79135322-1fe3-11e5-8aed-3cc781821c6c.png)

**Comment by csrow** [comment]
Here is a sample Visual Studio hybrid project which is close to what you are looking for.

By running Task Explorer to execute gulp tasks, this project uses VS Typescript 1.5 to compile and map TS files and Babel to compile ES6 codes.   

There are some problems with trying to write code both in TS and ES6 at the same time in a same project but the whole code can be written only in TS.  The mix was only done to see if it would work.

https://github.com/csrow/VSH-Aurelia-sample

**Comment by dpinart** [comment]
I'm currently developping aurelia projects with TypeScript and using system as module loader in Atom and Webstorm IDEs. 
I got the idea from https://github.com/pyarmak/aurelia-electron-starter. Just install globally and localyy typescript via npm and edit tsconfig.json file, in root folder, replacing "amd" by "system" at compilerOptions.module setting.

It works really great on Webstorm and Atom. You can even use "autoinject" decorator. (It was working till today, when an npm install and jspm install broke all autoinject dependencies)

**Comment by paulvanbladel** [comment]
@csrow and @dpinart  thanks for the input. I'll check carefully.
