### ISSUE TITLE
Stak with events.

### ISSUE THREAD

**Issue by Serhioromano** [aurelia/framework#15]
Here I am again working on todo app.

Here is my HTML part `todo.html`

```html
  <div class="row">
    <div class="col-md-10">
      <input type="text" class="input-lg form-control" value.bind="newtask"/>
    </div>
    <div class="col-md-2">
    <button click.trigger="add()" class="btn btn-primary btn-lg btn-block">Add</button>
    </div>
  </div>
<li class="list-group-item  ${task.done ? 'list-group-item-warning' : ''}" repeat.for="task of tasks">
  <label dblclick.trigger="edit(task)">
    <input type="checkbox" checked.bind="task.done"/>
    ${task.name}
  </label>
</li>
```

and here is `todo.js`

```js
export class Todo{
  constructor(){
    this.tasks = [{name: 'Task 1', done: 0}];
  }

  edit(task) {
    console.log(task);
  }

  add() {
    if(!this.newtask) {
      return;
    }
    this.tasks.push({name: this.newtask, done:0});
    this.newtask = '';
  }
}
```

The strange thing which I cannot understand is that `click.trigger="add()" ` is working and `dblclick.trigger="edit(task)"` is not. It says  _edit is not a function_. I also tried `dblclick.delegate="edit(task)"` but same result.

What do I do wrong?

**Comment by EisenbergEffect** [comment]
In this case you need `$parent.edit(task)` since its outside the repeater. This is temporary. We are planning to fix this.

**Comment by Serhioromano** [comment]
What is better to use in this case `delegate` or `trigger`?

**Comment by EisenbergEffect** [comment]
I recommend to use delegate unless you have a special reason not to.
