### ISSUE TITLE
using Aurelia with MVC6 routes and .cshtml razor files

### ISSUE THREAD

**Issue by gordon-matt** [aurelia/framework#150]
Aurelia looks really awesome and I want to start using it for a new version of a CMS I have, but I am not sure if it's a viable solution due to my setup. The CMS is built on **ASP.NET MVC5** and the structure of the solution is as follows:

- Solution
	- CMS Project
	- Library 1
	- Library 2
	- Library (N)
	- etc...
	- Plugins Folder
		- Plugin 1
		- Plugin 2
		- Plugin (N)
		- etc..
		
There are routes in all projects - almost all of the plugins and some of the libraries. I am considering the following for a new version:

- Aurelia
- MVC6 (Targeting .NET Core)
- Possibly TypeScript 1.5 as well (but ES6 is fine too)

I definitely need to make Aurelia work 100% with my Razor (.cshtml) files, this is absolutely required, so I can't just use regular ".html" files. In MVC, I have access to the all the routes via **actionContext.RequestContext.Configuration.Routes**, so I am wondering if I can return a list of these via JSON from an action method that Aurelia can make a call to. Perhaps something like this:

Create an AJAX function to call "/get-routes" on the server and transform the result to the proper json format for **config.map()** in **app.js**... and of course somehow tell Aurelia to use my **.cshtml** files instead of html files.

is such a thing possible? If not, how would I go about doing something like this? Ideally an example project would be best. So far I have *Googled* to no avail.

**Comment by EisenbergEffect** [comment]
It should be possible. You may need to customize the view location strategy. See the documentation section on customization which explains how to do that.

**Comment by wardbell** [comment]
Your client has no idea that a .chtml file is behind the .html file. MVC routing picks up the request, sends it to razor, razor generates the html, back it goes to the client.  The client knows none of this.

You should be fine. 

P.s., this isn't even an Aurelia issue *per se*. It works like this for all client frameworks. Aurelia view localization strategies simply offer you the ability to route the views where you find them to be most convenient from a server perspective

Obviously an example would help. TBD.

**Comment by gordon-matt** [comment]
@wardbell , thanks. I am aware of what you mentioned; I just have no idea how to begin doing what I would like to do. Until recently I have not done much work on the client side; mostly server side coding. Now with all the changes happening in MVC6 (it being geared more toward client side development and all), now is the time to start learning. Suffice it to say this is quite a steep learning curve I am on... and yes; a real, working example would indeed be of great help. I suspect once Aurelia is actually released, tutorials will start popping up all over the net. Until then... guys like me find ourselves swimming in the deep end...  :-D

**Comment by wardbell** [comment]
Tell me about it. I'm just trying to give you realistic encouragement.

Here is more of the same kind of "*works on my machine*" encouragement. I recently presented an ASP.NET 5, MVC 6, EF7, Breeze, Angular v.1 demo. 

I didn't write it. I [forked it](https://github.com/wardbell/UnicornStore/tree/DevIntersections/CompletedSource/UnicornStore) from Rowan Miller's "UnicornStore" sample and extended this mostly-MVC-6 app with a Breeze/Angular SPA page. 

In my simplistic approach, the server only delivers a single SPA view web page, *ManageProductsSpa/index.cshtml*, which is the "host" page for the SPA silo in this app.  I suppose I could have had more of these *.cshtml* files for templates or broken it into *.cshtml* partials. There really wasn't much call for that.

My point is that the stack worked ... and the client had very little idea what I was doing back there on the server. There is no difference between Angular and Aurelia (or anything else) in this respect.

So take heart!  This is going to work and it isn't going to be hard. We all just have to grind out the patterns and examples.

... and bleed a little as we cope with all of these edge technologies arriving at the same time.  It will be fun!

**Comment by diegohb** [comment]
This may help: http://nojaf.com/2015/05/06/using-razor-partials-cshtml-with-aurelia-components/

**Comment by alteredstudio** [comment]
[http://blog.developers.ba/getting-user-friendly-routes-with-aurelia-in-asp-net-5/](url)

So if you made your auth as a Microsoft server side rest API you could just direct to Aurelia app right away. It could handle calling the API and you would have smooth page animations and no hard refresh correct? One other advantage I could see is for pages that are not auth gated. About, Contact etc. If someone could make this with Core 1.0 when it's done after June 27th this could be a great starting point for a lot of devs like me just starting out.
