### ISSUE TITLE
Constraining a custom attribute to be used only on certain tags?

### ISSUE THREAD

**Issue by grofit** [aurelia/framework#152]
So for example I have a gravatar based plugin which currently uses a custom element, but in some cases it would be handy to just have a custom attribute that could be attached to an `img` tag.

As this would only really effect the `src` attribute there would be no point supporting it on any other tags, so is there a way to constrain the tag types it should be available for? as I could imagine this being a useful addition if it is not already supported. Such as if people only wanted to target `textarea` tags etc.

**Comment by EisenbergEffect** [comment]
Currently you could handle this by having the element injected into your attribute, checking it's tagName and then throwing if it's not on a compatible tag. We could add another annotation to do this during the compilation process. Maybe something like

`@elementConstraint('img')`

**Comment by EisenbergEffect** [comment]
Thoughts?

**Comment by grofit** [comment]
sorry as always I am on another computer so miss the messages.

I did think about the former approach for the moment, but the latter approach would be a nice addition imo, I would ask some others though, see what their thoughts are as I don't want to bloat Aurelia, but at the same time I don't want to have to write my own instances of cross cutting concerns.

**Comment by EisenbergEffect** [comment]
I'm going to close this for now since the element injection and tag check is very little code and can be accomplished easily, especially since custom attributes usually inject the element.
