### ISSUE TITLE
Aurelia views get recreated with each navigation event

### ISSUE THREAD

**Issue by bychkov** [aurelia/framework#153]
In Durandal default behavior was to keep the state of the view, in Aurelia views are created from scratch on every navigation event. There's an option to create a singleton view-model and it will be created only once but no such option for view. This causes problems when I try to use Google maps on the Aurelia view. On the initial call, Google map gets created and then user populates it with different features, but if user navigates away and then returns back to the view I need to recreate map and all the map features, and that provides poor performance and user experience.

**Comment by EisenbergEffect** [comment]
Can you  move this to the templating-router repo. This is specifically a new feature request which would be implemented as part of router-view.
