### ISSUE TITLE
Errors when working with MVC6 routes

### ISSUE THREAD

**Issue by gordon-matt** [aurelia/framework#155]
This question is related to #150. I am having trouble with overriding the ConventionalViewStrategy.

Basically what I have done is the following:

**app.js** is as follows:

===
```
export class App {
    configureRouter(config, router) {
        config.title = 'Aurelia';
        config.map([
            { route: [''], name: 'index', moduleId: './index', nav: true, title: 'Home' },
            { route: 'flickr', name: 'flickr', moduleId: './flickr', nav: true, title:'Flickr' },
            { route: 'child-router', name: 'child-router', moduleId: './child-router', nav: true, title:'Child Router' }
        ]);
        this.router = router;
    };
}
```
===
Also added a **main.js** as follows:

===
```
import {LogManager} from "aurelia-framework";
import {ConsoleAppender} from "aurelia-logging-console";
import {ConventionalViewStrategy} from "aurelia-framework";

LogManager.addAppender(new ConsoleAppender());
LogManager.setLevel(LogManager.logLevel.debug);

export function configure(aurelia) {
    aurelia.use
        .standardConfiguration()
        .developmentLogging();

    ConventionalViewStrategy.convertModuleIdToViewUrl = function(moduleId){
        var url = moduleId;
        console.log('trying to locate view for: ' + url);
        return url;
    };

    aurelia.start().then(a => a.setRoot("./app", document.body));
}
```
===
Then in my **<body>** tag in the **_Layout.cshtml** file I referenced it as follows:
`<body aurelia-app="main">`

and added action methods in the home controller as follows:

===
```
public class HomeController : Controller
{
	[Route("")]
	public IActionResult Index()
	{
		return View();
	}

	[Route("index")]
	public IActionResult IndexForAurelia()
	{
		return View("Index");
	}

	[Route("app")]
	public IActionResult App()
	{
		return View();
	}

	[Route("nav-bar")]
	public IActionResult NavBar()
	{
		return View();
	}
}
```
===
Of course the **.cshtml** views have the exact same content as what you would have expected in the plain **.html** files.

When I run the app, I would expect that it would now look for **app** instead of **app.html** and **index** instead of **index.html**, etc.. and it does, but I get the following errors that I don't know how to solve:

First:
```
Potentially unhandled rejection [3] n/e.instantiate@http://localhost:34769/jspm_packages/system.js:1:7829
i/e.instantiate@http://localhost:34769/jspm_packages/system.js:1:11671
s/e.instantiate@http://localhost:34769/jspm_packages/system.js:1:13280
l/e.instantiate@http://localhost:34769/jspm_packages/system.js:1:16530
d/e.instantiate@http://localhost:34769/jspm_packages/system.js:1:19458
f/</<@http://localhost:34769/jspm_packages/es6-module-loader.js:7:14271
O@http://localhost:34769/jspm_packages/es6-module-loader.js:7:7437
K@http://localhost:34769/jspm_packages/es6-module-loader.js:7:7071
[7]</</</</y.prototype.when@http://localhost:34769/jspm_packages/es6-module-loader.js:7:10745
[7]</</</</v.prototype.run@http://localhost:34769/jspm_packages/es6-module-loader.js:7:9779
[3]</</</a.prototype._drain@http://localhost:34769/jspm_packages/es6-module-loader.js:7:1725
a/this.drain@http://localhost:34769/jspm_packages/es6-module-loader.js:7:1392
b@http://localhost:34769/jspm_packages/es6-module-loader.js:7:3302
```
Second (I'm assuming it's related to the first one above):
```
Unhandled promise rejection
TypeError: Error loading "github:aurelia/framework@0.12.0" at http://localhost:34769/jspm_packages/github/aurelia/framework@0.12.0.js Error loading "github:aurelia/framework@0.12.0" from "nav-bar" at http://localhost:34769/nav-bar.js github:aurelia/framework@0.12.0 detected as System.register but didn't execute.
```

Also, note that for the moment the **.js** files are still inside **./wwwroot** since I'm not certain if we can even override their location anyway.

**Comment by gordon-matt** [comment]
For the moment (until Aurelia is production ready), I am learning Durandal instead with my MVC5 apps. I figured that makes sense since Aurelia is an evolution of Durandal and designed by the same guy. I already can see various similarities in them. I would like to keep this issue open for the moment though because I am having the same problem in Durandal 2 (see: http://stackoverflow.com/questions/31258042/durandal-and-a-plugin-architecture) and I fear that unless it is addressed early on, that Aurelia too may be incapable of working with a plugin-style architecture.

**Comment by EisenbergEffect** [comment]
@gordon-matt The error you have above doesn't seem to have anything to do with MVC. It looks like your framework install may be corrupt or incomplete.

Aurelia works fine with plugin architectures and so does Durandal. We've built some of the most complex, dynamic plugin systems I've ever heard of with Durandal. It's likely a configuration issue or an issue of not using front-end/back-end technologies correctly together.

**Comment by EisenbergEffect** [comment]
You should seek assistance in the gittern channel from someone familiar with the nuances of MVC6.

**Comment by gordon-matt** [comment]
Thanks Rob. I really admire your work. And I am sure there are indeed people who like you say, have developed fantastic plugin systems using Durandal. However, for guys like me who are not so experienced in frontend development and only beginning our journey with frontend frameworks, there seems to be nothing in the way of examples to get us started. There are endless tutorials for the simplest apps which in most cases is perfectly fine; but when it comes to plugin architectures, we're severely lacking in examples (if you know of any, please provide a link) and I have no idea where to start. I will try the gittern channel as you suggested. Thanks  :-)

**Comment by EisenbergEffect** [comment]
Someone else is having a similar issue int he gitter channel. So, you might find an answer there soon.

**Comment by gordon-matt** [comment]
Thanks, Rob.. but that someone else was me..  :-)
I think I have what I need in order to give it a try.. if I am successful, I will make a tutorial on CodeProject or something and post a link back here for anyone with a similar situation.

**Comment by EisenbergEffect** [comment]
LOL Sorry. I realized that after the fact. Please let me know more about the solution when it's worked out. You are right that more examples like you seek need to be made available. We would be happy to feature any blog posts or articles you write on the subject.

**Comment by chovy** [comment]
I think it would be cool to have an `aurelia-cookbook` repo with one-off examples of common things.
