### ISSUE TITLE
Is it possible to use Aurelia with Node-Webkit?

### ISSUE THREAD

**Issue by lforge** [aurelia/framework#16]
Is there any gotcha to use Aurelia with Node-webkit?

**Comment by EisenbergEffect** [comment]
I haven't tested it yet...but I would really love to support that use case. I love Node-Webkit. Give it a try and see what happens. We can help work out the issues if you find some.

**Comment by lforge** [comment]
I am kind of new to web dev in general.  My background is Oracle/back office ERP type.  But I have a personal project that I would like to use node-webkit to build an app.  With that said, I may need a bit more support on wiring everything together.  I will give it a try and see what happen.

**Comment by EisenbergEffect** [comment]
I will support you through questions on this issue. Node-Webkit is important for us to support. Ask questions as you need here. When we are all done, we can take that and format it and put it in the docs for others. Thanks!

**Comment by lforge** [comment]
Thanks!

**Comment by xbenjii** [comment]
I guess the main thing it'd have to support is the `file://` protocol.

**Comment by kevinrenskers** [comment]
I was looking for a SPA framework that was available as CommonJS modules from NPM to use with node-webkit or atom-shell. I even [asked about this on stackoverflow](http://stackoverflow.com/questions/28142581/spa-frameworks-that-use-the-commonjs-module-format) shortly before I "found out" about Aurelia. Still need to start my project, any day now. Expect questions and feedback about using Aurelia for this purpose :)

**Comment by EisenbergEffect** [comment]
I'm closing this for now. Please contact me or update here if you try it out.

**Comment by lforge** [comment]
Rob,

I have taken your Flickr tutorial and make it work with node-webkit.  I do have a few questions.  

1.  What is the minimum libraries that I need to be included to make Aurelia to work?  I have copied everything in the "dist" folder, plus jspm_packages to the main node-webkit app folder.  But I think that I can trim the jspm_packages down a bit.  Some of the Bootstrap css can be moved to style and update my index.html file.  But I am not sure how many of those files in jspm_packages are truly needed by Aurelia.

2.  This is not really a node-webkit porting question, but more or less a general question for sub-menu, can I do second line of tabs when I click on the first menu tabs in Aurelia?  I think that this may be a child-router type update.  But I am still learning web development overall.  So I may be missing something simple here.  Anyway, let me know when you have a chance please.  If you want me to use a different channel for questions like this (e.g. Google group), let me know.  Thanks.

**Comment by EisenbergEffect** [comment]
* If you want a second level menu, that's usually a good job for child routers.
* You probably need all the aurelia libraries for this exmaple. But if you wanted to use Node's http, then you don't need Aurelia's HttpClient. If you don't want to use the router, then you can remove route and templating-router. If you don't want to use the event-aggregator, you can remove that.

Were there any tricks to getting it working with nw? Can you share the setup? Any interest in writing some documentation on getting it set up for us?

**Comment by lforge** [comment]
Rob,

For your flickr tutorial, there is not much of a trick.  Like I said, I just move the "dist" folder and the jspm_packages folder to the the node-webkit folder, zip them up like normal node-webkit distribution and rename the .zip to .nw file.  It works out of the box.  In my Mac, somehow my node-webkit can't run it directly.  So I have to copy my entire node-webkit.app folder into the same folder of the node-webkit app.  But from my Win7 virtual environment, I can just run it without any extra work.  So all of these are just node-webkit side, has nothing to do with Aurelia.

Anyway, will keep experiment this on my spare time.  For doc, I am not really sure that I am qualified for it because I am very new to web dev in general.  But what I have described in this issue is what I did and it seems to work.  I would like to do it to a point where I can save/retrieve data from a sqlite3 database with node-webkit running Aurelia.  If I can get this example to work, then I don't mind to put that out somehow.  Thanks.

**Comment by EisenbergEffect** [comment]
Excellent!

**Comment by ryanwischkaemper** [comment]
@EisenbergEffect @lforge @kevinrenskers I put together a demo-project using Aurelia with NW.js - it's [available on GitHub](https://github.com/ryanwischkaemper/aurelia-nw) with a corresponding [post](http://ryanstech.net/archive/2015/05/25/aurelia-nw-part-2/) describing it.

It has gulp tasks for dev/release builds and running tests. There is no gulp watch task yet, but I'll add it soon. I also need to properly bundle and distribute any need jspm packages - right now I'm copying the entire **jspm_packages** folder into the release build.

**Comment by ramesh-daffodil** [comment]
@ryanwischkaemper @EisenbergEffect 

I am using this repo (https://github.com/ryanwischkaemper/aurelia-nw.git ) --> nw.js with aurelia .. I am able to require("nw.gui") as you did in window bar.js 
. But I am not able to create new gui.Menu() .
Some code for reference
var gui = require('nw.gui');
export class App {
add_collection () {
console.log("add collection called");
}
attached() {
console.log("attached called",gui);
var menu = new gui.Menu();
menu.append(new gui.MenuItem({
label: 'Add Collection',
click: this.add_collection
}));
$("body").bind('contextmenu', function(ev) {
ev.preventDefault();
menu.popup(ev.pageX, ev.pageY);
return false;
});
}
}

**Comment by EisenbergEffect** [comment]
I haven't personally used NWJS with Aurelia. I've only used Electron. I don't see why this issue would be related to Aurelia. In any case, we would  need some more information, such as an error message, etc.

**Comment by himanshu-daffodil** [comment]
i have same issue that mentioned above . i m also not able to create instance of  "var gui = require('nw.gui')"
