### ISSUE TITLE
Use packages that cannot be installed through JSPM?

### ISSUE THREAD

**Issue by Busata** [aurelia/framework#161]
When installing the openlayers npm package for example, it fails as JSPM cannot install the jsdoc package, which has a tarball dependency. Is there a way to import this npm package without using jspm?  Is it possible to provide an example on how to do this in the (I assume?) config.js map & paths section?

**Comment by EisenbergEffect** [comment]
Firstly, you should definitely report this issue to jspm to see if they can fix it on their on.

You can alway use the library directly, the same way you would without jspm by adding a script reference.
