### ISSUE TITLE
Aurelia appears to discard other elements inside a <body> tag when <body> marked with "aurelia-app" attribute.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/framework#162]
By convention I tend to place <script> tags at the end of my <body> section, just before the closing </body> tag.

My current app has the <router-view> inside the body, and some scripts. The <router-view> remains, but the scripts seem to disappear. The original page contained the script tags as evidenced through Fiddler.

**Comment by EisenbergEffect** [comment]
Yes. But you don't have to place that attribute on the body. You can place it on any html element you want.
