### ISSUE TITLE
cordova img src seem  work error

### ISSUE THREAD

**Issue by tomsean** [aurelia/framework#163]
i use 
```html
   <img src="../images/sgcc.jpg" alt="" class="circle responsive-img"  />
  ```   
it is work in web browser,but when i deploy to android app use cordova ,it is not right,and then i debug find error"GET file:///android_asset/images/sgcc.jpg net::ERR_FILE_NOT_FOUND" ,it is should be file:///android_asset/www/images/sgcc.jpg.

**Comment by Lorthirk** [comment]
I don't see how this could be related to the framework. Just remove the "../".
