### ISSUE TITLE
possible bug: @computedFrom for getter property is not working on 2-nd tier observables

### ISSUE THREAD

**Issue by bychkov** [aurelia/framework#165]
I have a 2 dropdowns where values of the second dropdown depend on the current value of the first dropdown. I store the current values in an object (Model) and databind it to the value of corresponding dropdown. Options of the second dropdown are databound to the getter property that selects sub-array depending on the selected value of the first dropdown. But when that value changes the change is not reflected on the UI (second dropdown keeps original options). I created a splunker that reproduces this behavior: http://plnkr.co/edit/H6ZUiqBTavyV1Wzp6kNV

Also here's the code in case Splunker wouldn't work:
welcome.js
....
  Model = new Model();

  Lookup1 = [{ name: "One", value: 1}, { name: "Two", value: 2}]; 
  Lookup2 = [[{ name: "One - A", value: 1}, { name: "One - B", value: 2 }],[{ name: "Two - C", value: 3}, { name: "Two - D", value: 4}]];

  @computedFrom("Model.Lookup1Value") 
  get CurrentLookup2(){
      return this.Lookup2[this.Model.Lookup1Value - 1];
  }  
.....
export class Model {
    Lookup1Value: int = 1;
    Lookup2Value: int = 1;
}

welcome.html
....
        <div class="form-group">
            <label for="lookup1">Lookup</label>
            <select value.bind="Model.Lookup1Value" id="lookup1" class="form-control">
                <option repeat.for="l1 of Lookup1" value.bind="l1.value">${l1.name}</option>
            </select>
        </div>
        <div class="form-group">
            <label for="lookup2">${Lookup1[Model.Lookup1Value-1].name} Type</label>
            <select value.bind="Model.Lookup2Value" id="lookup2" class="form-control">
                <option repeat.for="l2 of CurrentLookup2" value.bind="l2.value">${l2.name}</option>
            </select>
        </div>
....

**Comment by EisenbergEffect** [comment]
The current computedFrom is not designed to work in that way. For that functionality, you will need to use the computed plugin, which can handle that. As we approach release, we will consider whether or not to merge that plugin into our core ad a default behavior. Your feedback is welcome.

**Comment by bychkov** [comment]
Is there an example with parent-child dropdowns on Aurelia I could reference for?
