### ISSUE TITLE
How can I tell aurelia to refresh something bound to a function?

### ISSUE THREAD

**Issue by sapiens** [aurelia/framework#167]
I have this 
```html
  <p class="error" if.bind="loginState.hasError('name')">${loginState.getError('name')}</p>
```

`loginState` is a view model property of type `CommandResult`. basically I'm binding to a function of a model property. Now, I need a way to tell aurelia to re-assess the value of the function.  

I could have exposed directly the `errors` objects but `hasError()` looks better than `loginState.errors['name']!=null`. Is there a way or am I stuck with the 'ugly' approach?

```javascript

//in view model
   private loginState:CommandResult;

export class CommandResult implements  ICommandResult {
    _errors= {};
    hasErrors: boolean;
    constructor() {
        
    }

    get errors() {
        return this._errors;
    }
    getError(key: string) {
        return this._errors[key];
    }

    set errors(errors: any) {
        this._errors = errors;
        this.updateState();
    }

    private updateState() {
        if (this.errors.keys.length > 0) {
            this.hasErrors = true;
        }
    }

    merge(other: ICommandResult) {
        _.merge(this._errors, other.errors);
        this.updateState();
    }

    hasError(key:string):boolean{
        return this._errors[key] != null;
    }

    clearError(key: string) {
        this._errors[key] = null;
        this.updateState();
    }

    setError(key: string, value: string) {
        this._errors[key] = value;
        this.hasErrors = true;
    }
}
```

**Comment by EisenbergEffect** [comment]
We are working on a feature called "binding behaviors". One of the things that will enable is sending "signals" to refresh bindings. It's not ready yet. We are doing some refactoring on the binding system first. There are several issues related to this which you can track if you are interested to know when it's ready.
