### ISSUE TITLE
Trouble with array binding when using filters

### ISSUE THREAD

**Issue by akircher** [aurelia/framework#168]
The code below works exactly as expected

```
newDonation() {
    this.donations.unshift('new Donation')
}

<md-button repeat.for="donation of donations>${ donation }</md-button>
```

The code below doesn't work because the valueConverter is never re-activated.  There is no error the view is just never updated...

```
newDonation() {
    this.donations.unshift('new Donation')
}

export class filterValueConverter {
  toView(donations = [], filter = ''){
    filter = filter.toLowerCase()
    return donations.filter(donation => {
         return ~ `${donation}`.toLowerCase().indexOf(filter)
    })
  }
}

<md-button repeat.for="donation of donations | filter:filter>${ donation }</md-button>
```

Now I think you are planning to fix that eventually, but right now the workaround for this is not working either. I have tried various combinations of this workaround below (e.g. temp variable)

```
 newDonation() {
    this.donations.unshift('new Donation')

    //force valueConverter to re-activate
    this.donations = this.donations.slice(0)
  }
```
All of the workarounds throw this same error

```
Uncaught TypeError: Cannot read property 'length' of undefined index.js:132 
removeAt @ VM253462 index.js:687
contentSelectorRemoveAll @ VM253462 index.js:1002
removeAll @ repeat.js:388
processItems @ repeat.js:105
itemsChanged @ repeat.js:97
BindableProperty.createObserver.selfSubscriber @ VM253462 index.js:1911
call @ VM253462 index.js:2061
flushMicroTaskQueue @ index.js:107
(anonymous function) @ index.js:48
```

**Comment by jdanyow** [comment]
@akircher would you mind setting up a repro using the [aurelia plunkr](http://plnkr.co/edit/sak5db?p=info)?

**Comment by akircher** [comment]
@jdanyow sorry for some reason missed your response.  Here it is http://plnkr.co/edit/nPuzAZJIpybtTLQZaog4?p=preview

Remove the `<container></container>` Custom Element and everything works well again

**Comment by akircher** [comment]
Any progress here?  This is beginning to bottleneck my development.

**Comment by EisenbergEffect** [comment]
@jdanyow Did we ever resolve this error?

**Comment by akircher** [comment]
Yes, I didn't test intermediate versions, but v19.0 of skeleton seems to have this fixed.  Thanks!
