### ISSUE TITLE
Lack of stack trace from templates

### ISSUE THREAD

**Issue by eric-basley** [aurelia/framework#169]
It seems that when Aurelia encounter a problem when "compiling" views we cannot get precisely error's stack trace but just an error relative to it's consequence (ex: Router navigation failed, and no previous location could be restored)

To try it, write a wrong binding, or use a wrong value converter: 

```
repeat.for="elt in list" ...
${date | wrongValueConvert}
```

And you will get, if this is your first view:

"Router navigation failed, and no previous location could be restored"

How to get real stack trace, this lack of error management is very annoying and time consuming.

NB: Aurelia main.js is setup like this:

```
aurelia.use
   .standardConfiguration()
   .developmentLogging();
```

**Comment by 4imble** [comment]
I believe this is because it is failing to build and aborting the attempt to build the other files which results in the message you are seeing.

If you look at the cmd shell that is running your "gulp watch" you will likely see a more informative error message along the lines of this:

```
Starting 'build-system'...
[13:47:39] Plumber found unhandled error:
 SyntaxError in plugin 'gulp-babel'
Message:
    c:/../src/Game/Components/someFile.js: Unexpected token (20:12)
[13:47:39] Finished 'build-system' after 55 ms
[BS] Reloading Browsers...
```

**Comment by eric-basley** [comment]
templates are interpreted client side, so it has nothing to do with gulp.
 In a template do

```
<tr  repeat.for="value in values" ></tr>
```

You will have an error in your brower console similare to "Router navigation failed, ....' but without a stack trace relative to your html file

**Comment by EisenbergEffect** [comment]
I'm closing this issue for now. We are tracking an issue related to the router which will address surfacing the original error message stack trace better. You can follow it here: https://github.com/aurelia/router/issues/159
