### ISSUE TITLE
Ignore "cannot read property 'fuu' of undefined in template"

### ISSUE THREAD

**Issue by olanod** [aurelia/framework#17]
When doing a binding on the HTML of a property of a nonexistent object(can exist later) it shouldn't throw an error stopping the script execution, it should show nothing instead.
```
<p>
    ${willExist.fuu}
</p>
```
throws `Uncaught TypeError: Cannot read property 'fuu' of undefined`

**Comment by EisenbergEffect** [comment]
Fixed in 68ab50738e1a77b23bff96a86c1f017d9c39f91b
