### ISSUE TITLE
SEO problem

### ISSUE THREAD

**Issue by devmondo** [aurelia/framework#170]
as we know Aurelia is based on javascript, and except for google, no other crawlers like facebook bot, tiwtter bot,bing, etc...  crawlers javascript 

personally i think the  ultimate solution would be server side rendering, but until Aurelia supports that, there are services like Prerender.io, it works very well, and it works fine with Angular.js apps, but not with Aurelia.

i think it it is bootstrapping aurelia or system.js

i really hope the team would consider this, as right now none of the websites we make with Aurelia is SEO friendly.

thanks in advanced.

**Comment by Aaike** [comment]
A simple solution to make it work with prerender.io is to create a timeout of 10 seconds when the first page is loaded before you tell prerenderer that the page is actually ready, that will make sure the rendered html is correct.

here is another link to help with this : http://stackoverflow.com/questions/18530258/how-to-make-a-spa-seo-crawlable/18530259#18530259

thanks for the tips @leon-andria !

**Comment by EisenbergEffect** [comment]
We are certainly considering all sorts of things. I think this is a duplicate though. So, I'm going to close it for now.
