### ISSUE TITLE
Multiple method definitions

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/framework#171]
If two or more callback methods defined in custom element, compiler see no errors. Expect an error should be found for:
```javascript
  attached() {
  }
  attached() {
  }
```

**Comment by francoishill** [comment]
I don't believe this has anything to do with Aurelia. This seems like the transpiler you're using, perhaps Babel?

**Comment by PWKad** [comment]
Babeljs currently prevents the constructor method from being duplicated but I'm not sure if it should block other methods but you could open an issue on the transpiler to enforce this at compile time.  As @francoishill this belongs as an issue for the compiler to look at.
