### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by dpinart** [aurelia/framework#172]
Hi 

Till now I've bee developping aurelia applications in Webstorm and using gulp typescipt plugin in order to compile typescripts code from src folder to dist one following a similar apprach than https://github.com/pyarmak/aurelia-electron-starter. Since last upgrade, after executing an npm install and a jspm install for all aurelia plugins I'm starting having issues like autoinject is no longer owrking or some funky errors when building with later typescript version 1.5.3.

Can someone recommend a way or configuration (what plugins do I need) to build typescript aurelia applications in webstorm. Thanks in advance

**Comment by vec2k4** [comment]
I think this refers to https://github.com/Microsoft/TypeScript/issues/3663. You could try to use the typescript master branch since it should be fixed there.

**Comment by dpinart** [comment]
thanks vec2k4. Can you indicate how can I use typescritp master branch? In my package.json file I have "typescript": "git://github.com/Microsoft/TypeScript",

**Comment by vec2k4** [comment]
Since I'm not using Webstorm I cannot tell you exactly what to do. Regarding the package.json this seems ok to me. When I got home from work I will have a look at your repository and see if I can help.

**Comment by dpinart** [comment]
thanks so much. I don't think webstorm makes any difference, I guess is just an npm issue.

Anyway, if I'm already using typescript master branch, is not working pretty fine for me. It seems data emitDecoratorMetadata flag for TypeScript builder or autoinject decorator from aurelia or both are not working properly.

Another thing about last aurelia version, what kind of module loader is reccomended right now : system or amd?

**Comment by sapiens** [comment]
I had the same problem, autoinject worked for a bit (Visual studio 2013) then that's it. But `@inject` works properly so I'm using just that.

**Comment by atsu85** [comment]
For me @autoinject worked with visual studio only with project build, but not with incremental build(Ctrl+S). Now i'm using Atom IDE and gulp (both build autoinject without any problems).

**Comment by dpinart** [comment]
Hi @atsu85 . Can you share how are you building your project with atom and your package.json file so I can see what versions of node modules are you using?

**Comment by atsu85** [comment]
Hi,
as i'm using RequireJS module loader instead of SystemJS, my package.json is really minimalistic - it only includes dev dependencies used by gulp:
``` json
{
...,
  "repository": {
    "type": "git",
    "url": "http://github.com/aurelia/skeleton-navigation"
  },
  "devDependencies": {
    "gulp-typescript": "*",
    "typescript": "Microsoft/TypeScript",
    "merge2": "*"
  }
}
```

**Comment by EisenbergEffect** [comment]
TypeScript 1.5 was released. Closing this issue.
