### ISSUE TITLE
Aurelia & Wordpress

### ISSUE THREAD

**Issue by joDelicious** [aurelia/framework#173]
Hi dear, 

It would be awesome if there could be some documentation about how it can live together.
I haven't found anything out there.  I am pretty sure it would greatly help overall diffusion of Aurelia.

Any tip is more than welcome, thank you.

Best regards,
Johan

**Comment by EisenbergEffect** [comment]
@joDelicious You might ask in our gitter channel and see if anyone has done the integration yet. https://gitter.im/Aurelia/Discuss
