### ISSUE TITLE
Is it possible to add top level components without using the router

### ISSUE THREAD

**Issue by thelgevold** [aurelia/framework#175]
I am trying to add a top level component without using the router. Is that possible?
Basically - add the component directly on my index.html landing page.

More details here:http://stackoverflow.com/questions/31767216/aurelia-top-level-component-without-routing

**Comment by EisenbergEffect** [comment]
The router is completely optional. The skeleton's top level component is not controlled the router in any Aurelia app and it doesn't have to use a router internally. I recommend you read the documentation on custom elements and also look into the compose custom element. That said, you cannot just put a component in your index.html page just yet. That will be enabled in a future release though.

**Comment by thelgevold** [comment]
Yes I have been using custom elements as part of my components and it's been working out well as long as the root component is loaded. 
I will watch for a release that enables me to place my root component directly in the index.html page. Any estimates for when that might come available?

Anyway, great progress on the framework so far. The starter project is really great to work with - especially the built in ES6 transpiling and the auto browser reload on change.

**Comment by EisenbergEffect** [comment]
There is a new api in master on the aurelia object called `enhance`. It is an alternative to setRoot. What it does is "enhance" an element or section of the dom by "bringing to l life" elements in the dom. It was just added on Friday morning. It's still volatile so you use that at your own risk. It's not released yet either. It is likely to change.
