### ISSUE TITLE
TypeScript d.ts errors with corejs@0.9.18

### ISSUE THREAD

**Issue by davismj** [aurelia/framework#177]
For all generated d.ts files in Aurelia explicitly using core-js, core js is imported as 

`import core from 'core-js'`

This throws the following TypeScript compiler error, for example

`jspm_packages/github/aurelia/templating@0.13.15/aurelia-templating.d.ts(2,10): error TS1192: External module '"core-js"' has no default export.`

Changing the first line to the following resolves the error. This change is consistent with the d.ts fetched from tsd for corejs@0.9.18

`import * as core from 'core-js';`

**Comment by EisenbergEffect** [comment]
I'm wondering if we could actually just do `import from 'core-js'` since it's all just polyfills?

**Comment by davismj** [comment]
Yea, `import 'core-js'` also works, which is what you meant, I think.

**Comment by EisenbergEffect** [comment]
Yes. I bet we could switch all the libraries over to that.

**Comment by davismj** [comment]
I can take a look at it tomorrow morning.

**Comment by davismj** [comment]
It seems that `import 'core-js'` generates invalid output in the babel-dts-generator.

https://github.com/YoloDev/babel-dts-generator/issues/22

**Comment by davismj** [comment]
Any chance we can pull these in for now? I can revisit this if we want to move to `import 'core-js'` down the line.
