### ISSUE TITLE
Aurelia features that can be used with ReactJS

### ISSUE THREAD

**Issue by varghesep** [aurelia/framework#179]
I'm reasoning myself what Aurelia feature that I can use with ReactJS. Aurelia has excellent framework features and ReactJS has excellent view management. 

ReactJS already has **state** which takes care of the binding aspects of the application. May be data models, services & factory developed in Aurelia and use in ReactJS JSX so they are separated out?

I would appreciate some design pattern where both can be integrated.

**Comment by Vheissu** [comment]
@varghesep I am using React.js with Aurelia and the way I am using it is for specific use-cases where the performance benefits of React.js will help mitigate any potential UI issues as a result of redraws, paints or inefficient bindings.

Inside of repeat.for I tend to use React. Aurelia passes in the data down to the React component, so bindings are mostly one-way to keep things efficient and help eliminate dirty-checking.
