### ISSUE TITLE
Use pieces of Aurelia without loading full framework

### ISSUE THREAD

**Issue by chrismichaels84** [aurelia/framework#180]
This is more of a question and I didn't know where else to ask it. I am investigating different frameworks for an upcoming project and love the design of Aurelia. Just wanted to know the best way to use Aurelia components (views) on pages that **aren't** single-page apps, hopefully without loading all kinds of extra resources.

This is the situation. The site we are working on (mmirevolution.com) has many different aspects, some features that are single-page-apps (with client-side routing and all). Other features are traditional pages that that must be refreshed on each update.

The thing is, we have certain elements (notification bar, message system, widgets) that are used across the site on both SPAs and traditional pages.

So, what is the best way to be able to include, say, an aurelia-powered notification bar (component/view) on a page that does not use the rest of the aurelia framework. I suppose that notification bar would only really need the http-client (or we could use jQuery) and the model-view loader. No routing.

Or, is this even a big enough problem to worry about? I'm just trying to minimize the scripts used on each page and the number of round-trips to the server for assets.

My appreciated.

**Comment by EisenbergEffect** [comment]
We have a new feature called `enhance` as part of the aurelia api. It's talked about in our recent blog post a bit: http://blog.durandal.io/2015/08/05/aurelia-release-for-jspm-beta/  It lets you put custom elements, attributes and bindings directly in your html page. Then, instead of calling `aurelia.setRoot()` you call `aurelia.enhance()` and it will progressively enhance the content of the page. So, you don't need a router, history, ea or any of the plugins. Instead  you use this new api, having previously "globalized" any custom elements you want it to detect. This is a new feature and may undergo some changes over the next few weeks, and it's not well documented yet. That will all improve, but I wanted to let you know that your use case is being covered.

**Comment by chrismichaels84** [comment]
Thank you. That is exactly what I needed. You've just sold me and my team on Aurelia.

**Comment by AStoker** [comment]
Hate to comment on an old thread. Is there any documentation on how to actually use the enhance feature? I'm trying to enhance an old durandal page, and am having the hardest time trying to configure it.

**Comment by EisenbergEffect** [comment]
We are writing docs on that right now. It will be part of next week's docs release. Basically, if you have a main.js for Aurelia, you can do something like this:

```
configure(aurelia) {
  aurelia.use.standardConfiguration();
  aurelia.start().then(() => aurelia.enhance());
}
```

That will enhance the entire body of your app. If you need to specify more options, this signature is as follows:

```
enhance(bindingContext: Object = {}, applicationHost: string | Element = null)
```

**Comment by AStoker** [comment]
How about getting it to work with a different project (Durandal)? My understanding of the last article about the enhance feature is that you can use it to just enhance certain parts of your page progressively, without having to load up all of Aurelia. Perhaps I misunderstood that, does it still need to happen inside an Aurelia "app"? Or can I have a separate app (durandal based) and trigger the Aurelia enhance from there?

**Comment by AStoker** [comment]
The end goal is to transition the durandal app to aurelia anyway, but timetables are making us try and just slowly start putting aurelia features into the app, and later transition the whole thing.

**Comment by EisenbergEffect** [comment]
You still nee Aurelia..but in the case above...you are just telling it to "turn on" aurelia for a particular element. You can use aurelia's TemplatingEngine to enhance repeatedly. If you aren't using Aurelia router, then you probably don't want to use the standard configuration. Instead you need a more basic configuration. See the docs for the optoins. Just don't include the router, history or ea.
