### ISSUE TITLE
aurelia/loader-default in IE and Edge

### ISSUE THREAD

**Issue by takazm** [aurelia/framework#181]
I am getting an error in IE11 and Edge but works fine in Firefox and Chrome : Unhandled promise rejection ReferenceError: Error loading "github:aurelia/loader-default@0.9.3" at http://localhost:54994/jspm_packages/github/aurelia/loader-default@0.9.3.js

**Comment by EisenbergEffect** [comment]
Make sure you have jspm beta installed. Make sure you re-install the framework after you have installed jspm beta.
