### ISSUE TITLE
Not getting the aurelia-composed event when first loading a new URL in E2E tests

### ISSUE THREAD

**Issue by mattyellen** [aurelia/framework#183]
Not sure if this is an issue with the aurelia framework or with the E2E tests, but I reproduced it in a fork of the skeleton-navigation app here:
https://github.com/mattyellen/skeleton-navigation

In demo.spec.js I removed the test which navigate to the Users page and moved it into a new spec file like this:

```javascript
  beforeEach( () => {
    po_skeleton = new PageObject_Skeleton();
    po_welcome = new PageObject_Welcome();

    console.log("load - 2");
    browser.loadAndWaitForAureliaPage("http://localhost:9000/#/users");
  });

  it('should navigate to users page', () => {
    expect(po_skeleton.getCurrentPageTitle()).toBe('Github Users | Aurelia');
  });
```

Then when I run these tests everything works find until first time it tries to load the "Users" page.  It never seems to get the "aurelia-composed" event and the test fails due to a ScriptTimeoutError.

```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
load - 1
Aurelia App composed
.load - 1
Aurelia App composed
.load - 1
Aurelia App composed
.load - 1
Aurelia App composed
.load - 2
F

Failures:

  1) aurelia skeleton app should navigate to users page
   Message:
     ScriptTimeoutError: asynchronous script timeout: result was not received in 11 seconds
  (Session info: chrome=42.0.2311.90)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Windows NT 6.1 SP1 x86_64)
```

The test is running under Chrome Version 42.0.2311.90 m.

After doing a bit more testing I've narrowed this down to happening anytime it loaded a different URL.
* Multiple tests in the same spec each loading the same URL -- works fine
* Switching to a different spec file that loads the same URL -- works fine
* Switching to a different spec file that loads a different URL that routes to the same page -- FAILS
* Switch to a different spec file that load a different URL that routes to a different page -- FAILS

**Comment by EisenbergEffect** [comment]
@bryanrsmith I believe this is related to not raising the proper event in the fetch-client that the http-client does. Can you look into this?

**Comment by mattyellen** [comment]
If it helps, I've found I can work around the issue by wrapping the "loadAndWaitForAureliaPage" in an extra browser.get(<url>).then(...);

It double loads the page, but then then event comes through fine.

**Comment by bryanrsmith** [comment]
@EisenbergEffect How do you feel about this solution? aurelia/skeleton-navigation#145

I'd like to avoid adding a custom event to fetch-client if possible.

**Comment by EisenbergEffect** [comment]
@bryanrsmith I like that, however, it does assume that there's an aurelia object attached to the selected element...which there usually is. Although, there is a way to bootstrap the framework where that might not be the case. I suppose that if anyone wanted to use the other bootstrapping technique they could update the protractor helper to find the element that  hosts the app. So, I think that's ok. If you feel better about this, then I'd say, let's do it.

**Comment by zewa666** [comment]
@bryanrsmith could you explain why you'd like to avoid a custom event? What is the benefit of the new way?

Your new implementation is ok, but as @EisenbergEffect mentioned, there is a hard dependency on that Aurelia object. Yeah of course this can be adjusted when you're utilizing a different bootstrapping technique, but it feels like adding more complexity for no obvious benefit.

**Comment by bryanrsmith** [comment]
It would add a dependency on the DOM, which I think is inappropriate in an
http library. It's also a hack for a specific testing scenario and not an
API that makes sense for the library to provide in any other context.

I also think the http requests are an implementation detail that the e2e
tests shouldn't care about.

**Comment by zewa666** [comment]
@EisenbergEffect, @mattyellen now that the PR from @bryanrsmith is merged, can we close this issue?

**Comment by EisenbergEffect** [comment]
Sure thing.

**Comment by bpierce88** [comment]
Newbie here ...to both Web development and Auralia. So far seems like it'll be fantastic to work with.
 
I'm playing with the aps.net5 skeleton, and it seems like this issue still isn't fully resolved. I added a new page to the nav that does nothing except set and render the heading, and I added an e2e test just to check the title (a copy/paste of the users page test that does the same). Running the e2e tests repeatedly, they will sporadically fail with an "asynchronous script timeout" error. If I copy/paste the e2e tests into another file (eg: demo2.spec.ts) such that they run twice ...then it almost always fails if I run the e2e tests even 2 or 3 times in a row. It is the script in "waitForRouterToComplete" that times out.

This may not be a practical issue, as maybe it won't fail as I add more functionality to my pages ...but wanted to let you know in case there is something going on that could impact more than just e2e tests. Btw, apologies if there are protocols I'm not following ...I don't think I've ever actually posted on a dev board like this.

**Comment by atsu85** [comment]
@bryanrsmith
> How do you feel about this solution? aurelia/skeleton-navigation#145

Do i understand correctly, that router navigation completes before content of custom elements are bound and populated from data fetched from the server? If so, then this workaround isn't going to be usable for e2e testing in most cases in real life, or am i missing smth?

**Comment by EisenbergEffect** [comment]
If you return a promise from the navigation activate callback. The data will be sure to load before routing completes.

**Comment by bpierce88** [comment]
Sorry to be daft, but are you saying just implement the activate method in every view model and return a promise that performs a noop? Something like this: activate() { return new Promise(() => { }); }?

**Comment by EisenbergEffect** [comment]
No. If you have a screen that loads data, one that is controlled by the router, then in that view model you should load your data in the activate callback and return the promise from that method.

Here's an example:

```javascript
import {inject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-http-client';

@inject(HttpClient)
export class CustomerEditScreen {
  constructor(http) {
    this.http = http;
  }

  activate(params) {
    return this.http.get('customer/' + params.id).then(c => this.customer = c);
  }
}

**Comment by bpierce88** [comment]
Thanks. It's just a minor annoyance for the workflow: I'd like to start with e2e test that just checks that the page loads and the title is correct before even implementing the api that provides the data.

I think my noop (which I corrected in my last post) was being optimized away, as all is well if I do something like this:

    activate() {
        return new Promise(f => {
            this.heading = 'blah';
            f();
        });
    }

This is fine, since it's simple enough for me to paste that in temporarily when I build a new page.

**Comment by EisenbergEffect** [comment]
You don't need a promise for that. You only need a promise if you are doing something asynchronous. Your e2e tests should work fine without data. Also, make sure you have the latest versions of aurelia via `jspm update` because there were some improvements in composition that would affect this scenario.

**Comment by bpierce88** [comment]
Ah - did a jspm update, and now all is well if I remove that activate method altogether. Thanks again.

**Comment by atsu85** [comment]
@EisenbergEffect 
> If you return a promise from the navigation activate callback. The data will be sure to load before routing completes.

I knew that, view activation works like that, but my question was related to **custom elements** used in view that is getting activated through navigation:
> Do i understand correctly, that router navigation completes before content of custom elements are bound and populated from data fetched from the server?

So i guess my concern is still probably valid:
> If so, then this workaround isn't going to be usable for e2e testing in most cases in real life, or am i missing smth?

**Comment by EisenbergEffect** [comment]
It should not. If it does then we have a bug.

**Comment by chriscantu** [comment]
FYI:  For a work around, I move the `browser.waitForRouterComplete()` command into my first `it` block.  This work-around has worked consistently.    

Important Notes:
* Based on  aurelia-skeleton-es6 
* demo.spec.js executed first
* utilized `browser.waitforRouterComplete()` inside `it` block instead of `beforeEach`

```
  it('App should navigate to login page by default', () => {
    let href = '';
    element(by.css('a[href="#/' + href + '"]')).click();
    browser.waitForRouterComplete();
    
   expect(loginPage.getPageTitle()).toBe('Login | Client Services');
  });
```

I am curious as to why this would work.
