### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Penderis** [aurelia/framework#188]
Hi, I just cannot get Aurelia to work properly unless starting with the navigation app example, loading from the framework I was missing the bootstrapper and then it gulp build never sends files to dist folder, tried comparing what is diff with nav example but it does seem that almost everything is different; this makes it hard to understand the pieces and what settings truly matter.

Anyone maybe have a nice point list of instructions to get this working? 
Current problem , hour 7 ... looking for app.js in root directory instead of wherever it is suppose to. makes no sense.

**Comment by EisenbergEffect** [comment]
Did you follow the getting started guide? Also, the best place to ask questions is in the gitter chat room. There are 1800 developers there and someone can likely help you.
