### ISSUE TITLE
Inaccurate type parameters for FrameworkConfiguration.plugin

### ISSUE THREAD

**Issue by ntilwalli** [aurelia/framework#189]
The parameters for `FrameworkConfiguration.plugin` are incorrect.  It should be `plugin(plugin: string|Object, config?: any)`.  The function actually requires an `Object` in the `plugin` parameter for something to be pushed onto the `info` array.  When a string is sent, `plugin` is recursively called with an `Object`, meaning the function accepts both types.  Also the `config` parameter is optional as referenced in #184.

The current code is inserted below for reference.  Both `string` and `Object` are valid first arguments...

```
plugin(plugin:string, config:any):FrameworkConfiguration{
    assertProcessed(this);

    if(typeof(plugin) === 'string'){
      plugin = plugin.endsWith('.js') || plugin.endsWith('.ts') ? plugin.substring(0, plugin.length - 3) : plugin;
      return this.plugin({ moduleId: plugin, resourcesRelativeTo: plugin, config: config || {} });
    }

    this.info.push(plugin);
    return this;
  }
```

I feel like this may be less an issue than a pull request, but there are already a few pull requests set up for these files and I don't want to clutter...  Plus I'm not clear on whether the typings are inserted automagically by some parser, in which case this issue has to do with that parser and can't be fixed with a PR.

**Comment by EisenbergEffect** [comment]
We add the typings ourselves. I didn't initially think of this being an API that would be called with an object externally, but there might not be any harm in opening that up.

**Comment by ntilwalli** [comment]
Actually, I was just reading the code and saw how it was used and thought the parameters were inaccurate.  I never thought of the declared parameters as the external interface with internal functions possibly using it differently, but that does seem like a reasonable way to approach declared typings (as the external interface).  I can withdraw this if you want...  Thanks for getting back. :)

**Comment by EisenbergEffect** [comment]
No need to withdraw this. I think it's worth continuing to think about. I'm not sure if someone would use the api with an object directly. But, I am a fan of making things as open as possible in the event that someone has a scenario. I suppose we could keep it as is...technically they can still call the function with an object. If we hear a lot of requests we could change the signature. Need to consider it a bit...

**Comment by EisenbergEffect** [comment]
I'm going to keep the api as is for now. Thanks!
