### ISSUE TITLE
content does not work inside select elements

### ISSUE THREAD

**Issue by danfma** [aurelia/framework#192]
I created this simple element `dropdown-field`:

```html
<template>
    <div ref="field" class="field">
        <label>${label}</label>
        <select class="ui fluid selection dropdown">
            <content select="*"></content>
        </select>
    </div>
</template>
```

And when I use it as the following:

```html
<dropdown-field label="Estados">
    <option value="1">Um</option>
    <option value="2">Dois</option>
</dropdown-field>
```

The options are not copied to inside the select element. The strange part is that, outside the select, it works.

**Comment by EisenbergEffect** [comment]
This could either be a bug in our implementation or a flaw with the web components shadow dom or html specifications. In order for us to determine that, can you test this in Chrome with the `@useShadowDOM` decorator on your component class? If doing that makes it work, then it's a bug in our code. If it still doesn't work, then it's an issue with the design/implementation of the native specs and there isn't anything we can do directly. If it's a flaw in the spec, I can make some recommendations for how to enable this scenario in a slightly different way though.

Please let me know. Thanks!

**Comment by danfma** [comment]
Ok, @EisenbergEffect! I will try with that and report again! Thanks!

**Comment by danfma** [comment]
@EisenbergEffect , I tried with the decorator and it does not worked too. So, we are in the second option.

**Comment by EisenbergEffect** [comment]
Ok, I recommend that you don't use the native option, but instead use your own custom option element with your dropdown. Then place the content tag in your element somewhere inside a div that is display: none. Basically, you are going to use those options as a data source to render the real options. Next use `@sync('my-option') options;` as a property in your custom element. Make sure the selector matches your custom option element name. Finally, use a repeater over the options property to generate the native options.

**Comment by jdanyow** [comment]
The browser doesn't allow a `<content>` element inside of a `<select>` element:

![issue](http://i.imgur.com/0cg0sl6.png)
