### ISSUE TITLE
Button click submits the form in each tab

### ISSUE THREAD

**Issue by paritoshmmmec** [aurelia/framework#194]
I have created a sample app as instructed in starter kit, One problem I noticed that even if I opened two different tab and clicked the button on one tab it is firing all the forms button with focus.

Not sure if I am doing anything wrong or it is an expected behavior(does not seems so ). 

Most probably some concept is not clear to me. 

I have attached both snapshots

Please correct me If I am wrong .
![firsttab](https://cloud.githubusercontent.com/assets/1858630/9438208/bfe8d9fa-4a79-11e5-9337-2c7ae6f1ed6a.PNG)
![secondtab](https://cloud.githubusercontent.com/assets/1858630/9438210/c5310f4a-4a79-11e5-9515-e5dcd5b339b7.PNG)

**Comment by jdanyow** [comment]
Aurelia's gulp watch task uses Browser Sync to mirror clicks/scrolls/form inputs on all devices for testing purposes.  You can configure this behavior:

http://www.browsersync.io/docs/options/#option-ghostMode

**Comment by paritoshmmmec** [comment]
ok cool, was not aware of it. Thanks for your time

**Comment by jdanyow** [comment]
No problem- please hit up the Aurelia gitter for Aurelia questions- there are over 1,800 members, someone is almost always available to help: https://gitter.im/Aurelia/Discuss
