### ISSUE TITLE
aurelia.globalizeResources() after v0.15.0

### ISSUE THREAD

**Issue by heruan** [aurelia/framework#197]
I noticed `aurelia.globalizeResources()` is gone in v0.15.0; how to make local plugins/converters/elements globally available now?

**Comment by wshayes** [comment]
Hi heruan,

It's been renamed to aurelia.globalResources, but for local plugins, you now need to use feature instead of plugin.  Good place to ask about this is on Gitter though.  Details on this are here: http://blog.durandal.io/2015/08/05/aurelia-release-for-jspm-beta/

**Comment by EisenbergEffect** [comment]
@heruan Definitely follow our official blog. blog.durandal.io Whenever we have releases with breaking changes we make sure to document them in a post.
