### ISSUE TITLE
Binding to key and enter events?

### ISSUE THREAD

**Issue by ericnograles** [aurelia/framework#20]
Hey Rob, 

Great work so far on Aurelia, I'm really liking it so far and am in the process of writing an application to get familiar with it.

One silly question: how do I syntactically bind a plain ol' HTML input textbox's afterKeyDown or enterKey event to a function in the ViewModel?  KnockoutJS has this type of convention: 

    <input type="text" data-bind="value:sendMessageText, valueUpdate: 'afterkeydown', enterkey: sendMessage"  />
 
Does Aurelia something offer something similar that I may have missed in the documentation?

Thanks, hope you and the Durandal.io team keep up the awesome work!

**Comment by EisenbergEffect** [comment]
The binding updates after key presses by default. We haven't introduced binding triggers into the syntax yet, but it's on the todo list. Regarding the enter key, you could create an attached behavior to do that, what would attach the event and then call a function on the vm when it happens.

**Comment by EisenbergEffect** [comment]
There might be other ways to handle this in the future. Key bindings are interesting. Can you create a separate issue on the binding repo to investigate shortcut-type bindings? Maybe we can make that really easy.

**Comment by gbreeze** [comment]
Sad thing is, that i can't combine a value binding with trigger or delegate bindings like

`    <input type="text" value.bind="toDoItem.name" keypress.trigger="InputKeyPress($event)" />    `

Hope this will change some day.

Best regards

**Comment by Thanood** [comment]
@gbreeze Well, there is [updateTrigger](http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.3.5/doc/article/binding-binding-behaviors/4) at least.

**Comment by stsje** [comment]
@gbreeze This is an old issue, and as @Thanood pointed out, you can use updateTrigger's to do exactly what you're looking for.
