### ISSUE TITLE
Trouble with two way binding of date picker

### ISSUE THREAD

**Issue by samelamin** [aurelia/framework#201]
Hi guy

I have been trying to create a datepicker custom element. The datepicker loads and I can pick the date. But when I save the form the date doesnt change from what it was originally

datepicker code

< template >
  < div class="input-group date" id='datetimepicker'>
    < input type="text" value.bind="datevalue" class="form-control">< span class="input-group-addon">< i class="glyphicon glyphicon-calendar"></i></span>
  < /div>
<  /template >

import {inject, customElement, bindable} from 'aurelia-framework';
import moment from 'moment';
import {datepicker} from 'Eonasdan/bootstrap-datetimepicker';
import $ from "jquery";

@inject(Element)
export class DatePicker {
    @bindable datevalue = '';

    constructor(element) {
        this.element = element;
    }

    attached() {
        $('#datetimepicker').datetimepicker({
                showClose: true,
                showTodayButton: true
            });

        $('#datetimepicker').on('dp.change', function (e) {
                $(this).change();
                $(this).data("DateTimePicker").minDate(e.date);
                this.datevalue = e.date;
            alert(this.datevalue);
        });
   
    }
}

And I am calling it this way 

< date-picker value.bind="validFrom"  >< /date-picker >

**Comment by EisenbergEffect** [comment]
You are going to need to provide more information for us.

**Comment by nomack84** [comment]
Usually you provide a description for your issue...Only the name isn't enough. Provide a description and if possible a live example with code so the core team con figure out what's failing

**Comment by samelamin** [comment]
sorry guys I was still editing the comment! didnt expect such a lightning reply! :D

**Comment by nomack84** [comment]
no problem :D

**Comment by EisenbergEffect** [comment]
@samelamin Can you show me how you are using your date picker? I have a suspicion. Aurelia uses one-way databindng by default unless it's working with a form control value. Your custom date picker would then not have two-way binding on its datevalue property. This would cause the problem you are describing. If you wish two-way to be used, you can either use that in your binding command where the date picker is used or you can make it the default by providing options to your bindable. Here's an example of that:

```
import {bindable, bindingMode} from 'aurelia-framework';

...
@bindable({defaultBindingMode: bindingMode.twoWay}) datevalue;
...

```

**Comment by samelamin** [comment]
I just tried that, same problem I am afraid

well I am calling the datepicker custom element like this 
< date-picker value.bind="validFrom" ><  /date-picker >



and the actual element is done this way 


< div class="input-group date" id='datetimepicker'>
< input type="text" value.bind="datevalue" class="form-control">< span class="input-group-addon">< i class="glyphicon glyphicon-calendar">
< /div>

**Comment by dpinart** [comment]
I would suggest to:
<date-picker datevalue .two-way="validFrom"></date-picker>

**Comment by jdanyow** [comment]
this won't solve your issue but change `$('#datetimepicker')` to `$(this.element.firstElementChild)` or `$('#datetimepicker', this.element)` to enable using multiple datepickers on a page

**Comment by samelamin** [comment]
@dpinart  I realised that now thanks!

Could it be the way I am binding? more speicifcally should it be 

[code]
  <date-picker datevalue.bind="validFrom" ></date-picker>
[/code]

or

[code]
  <date-picker value.bind="validFrom" ></date-picker>
[/code]

or

[code]
  <date-picker datevalue="validFrom" ></date-picker>
[/code]

**Comment by samelamin** [comment]
I could try creating it in a js fiddle if that might help ?

**Comment by dpinart** [comment]
@samelamin  I guess it would be helpful

**Comment by jdanyow** [comment]
here's the link if you want to setup a plunker (our version of jsfiddle):

http://bit.ly/aurelia-plunker

**Comment by samelamin** [comment]
thank you @jdanyow I was just thinking this wont work on jsfiddle!

Ill do it when I get home. Regardless whether I get this working or not, have to say the community support you guys provide is awesome!

**Comment by samelamin** [comment]
@jdanyow any idea how I can install Eonasdan/bootstrap-datetimepicker in plunker

**Comment by ajdisalvo72** [comment]
Can you show what your html template ended up looking like? I am trying to use this date time picker for an app that I am working on and it is causing the app to break. 

I have also been testing out the version from [Charles Pocket](https://gist.github.com/CharlesPockert/6a1fef3f546f6d37d1dc) and it was throwing an error when trying to load the CSS that is being imported in the javascript. 

Also is the jspm install of 'Eonasdan/bootstrap-datetimepicker' case sensitive? I imported it as 'eonasdan/bootstrap-datetimepicker'. Does this matter? 

Also, I do not see a reference to jquery anymore. Why did you not need to reference the jquery library?

Thanks for any help..
