### ISSUE TITLE
Typescript definitions: core-js

### ISSUE THREAD

**Issue by jods4** [aurelia/framework#202]
I am not sure in which repo to put this, but is it possible to strip out the
`import * as core from 'core-js'`
(sometimes just `import 'core-js'`).
that is found in most `.d.ts` files distributed with Aurelia? It creates error because I don't have `core-js` definitions (I'm using `lib.es6.d.ts`). 

Because it is not used directly, it makes no difference to remove it (but you probably need to have either `lib.es6.d.ts` or `core-js` to define some of the newer global stuff).

**Comment by EisenbergEffect** [comment]
That makes sense to me. @cmichaelgraham Can you comment on this?

**Comment by cmichaelgraham** [comment]
hmmmm...  not sure about that.  i think the import loads the polyfils.  (even though it isn't referenced directly later in the code)

**Comment by EisenbergEffect** [comment]
I think he's referring directly to the d.ts files, not our source.

**Comment by jods4** [comment]
@cmichaelgraham This might be true from the sourcecode, but is irrelevant in the TS definitions.

**Comment by cmichaelgraham** [comment]
right - but the .d.ts files are generated from the source files

**Comment by EisenbergEffect** [comment]
Yes, but that import isn't needed for the d.ts right? So, I think he's asking if it could be removed as part of the d.ts generation.

**Comment by cmichaelgraham** [comment]
have the babel-dts-generator remove it?  that should be possible.  another regex for imports to remove?

**Comment by jods4** [comment]
Yes, I was asking to strip them from the `.d.ts` files if it's possible.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham that sounds like it would work.

**Comment by cmichaelgraham** [comment]
roger that - i'll put it on the todo list :+1:

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Any progress on this?

**Comment by cmichaelgraham** [comment]
@EisenbergEffect no progress yet.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Have you had time to address this? It would be nice to fix up our d.ts files for the beta.

**Comment by jdanyow** [comment]
closing- aurelia no longer has a dependency on core-js
