### ISSUE TITLE
Can't put anything outside of template tag in template file

### ISSUE THREAD

**Issue by tsimons** [aurelia/framework#203]
To replicate:
1. Start with the skeleton navigation
2. Open any template file
3. Add a style tag outside the `<template></template>` tag
4. Run and load app on a route using that file
5. Route will not work, and console error appear:

    ERROR [app-router] Error: Cannot read property 'querySelectorAll' of undefined
        error @ aurelia-logging-console.js:62
        log @ aurelia-logging.js:56
        error @ aurelia-logging.js:89
        processResult @ aurelia-router.js:1726
        (anonymous function) @ aurelia-router.js:1582
        f @ shim.min.js:1415
        (anonymous function) @ shim.min.js:1423
        b.exports @ shim.min.js:453b.
        (anonymous function) @ shim.min.js:1625
        f @ shim.min.js:1596
        q @ shim.min.js:1600

The code that throws the error is line 38 of aurelia-loader.js:

    useResources = template.content.querySelectorAll('require');

I traced it back a little ways to where it should be set in aurelia-loader-default.js in this function:

    TextTemplateLoader.prototype._createTemplateFromMarkup = function _createTemplateFromMarkup(markup) {
      var parser = document.createElement('div');
      parser.innerHTML = markup;
    
      var template = parser.firstElementChild;
    
      if (this.hasTemplateElement) {
        return template;
      }
    
      template.content = document.createDocumentFragment();
    
      while (template.firstChild) {
        template.content.appendChild(template.firstChild);
      }
    
      HTMLTemplateElement.bootstrap(template);
      return template;
    };

However, it has a template tag, so it returns early and `template.content` never gets set.

**Comment by EisenbergEffect** [comment]
Why would you put something outside the template tag? I'm not sure that makes sense. If you are trying to use html imports, then you need to switch the html imports plugins for that. Bear in mind, that is no longer going to be implemented as a standard in its current form.

**Comment by tsimons** [comment]
It's just a pattern we've observed from other web components where style tags live outside the template tag. It worked fine in previous versions, but no longer works after this update. I wanted to make an issue in case others ran in to this and also see if this is really a bug or something we need to change in our project.

**Comment by EisenbergEffect** [comment]
It worked when html imports were used to load views. However, html imports is not going to be standardized in its current form and there is no current plan to fix it. So, we have pulled that out of our framework. The new version uses a simpler loading strategy and requires all content to be inside a template tag. If you wish to return to the non-standard html imports technology, or you wish to use polymer, you can run `jspm install aurelia-html-import-template-loader` and then in your main.js configure method add this code `aurelia.use.plugin('aurelia-html-import-template-loader');` That will restore the original behavior.
