### ISSUE TITLE
Bundled app not working on the phone.

### ISSUE THREAD

**Issue by robertsundstrom** [aurelia/framework#204]
I try to bundle my app using JSPM directly (not "aurelia bundle"). It seems successful when running the app on the desktop but when  run it on a smartphone (Android and Chrome browser) it just don't work - and no errors are detected.

What might I be doing wrong?

Is there a guide for doing this the correct way?

**Comment by EisenbergEffect** [comment]
We have our own bundling library and the article on how to use it is coming out today.

**Comment by robertsundstrom** [comment]
OK. Thanks. I'm looking forward to reading it.
