### ISSUE TITLE
Blank screen when running in IE10 or below

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/framework#208]
When running the a clean install of the skeleton, and applying the polyfill as mentioned in http://aurelia.io/docs.html#browser-support, in IE10 and below I get a blank screen. After it is done loading, the body tag is empty. No errors are shown in the console.

![image](https://cloud.githubusercontent.com/assets/2189477/9912548/7f82a6d4-5ca8-11e5-869f-d76779c708fa.png)

**Comment by DevBrosTeam** [comment]
I'm having the same issue, on windows 8.1, if that helps

**Comment by RowanBrough** [comment]
Same Issue.
1) downloaded and unzipped aurelia-skeleton-navigation v0.18.1 (https://github.com/aurelia/skeleton-navigation/releases/tag/0.18.1)
2) ran in console at project directory: npm install -g gulp, npm install -g jspm, npm install, jspm install -y, jspm install github:polymer/mutationobservers
3) edited index page: http://screencast.com/t/B0wkODLp as of http://aurelia.io/docs.html#browser-support
4) gulp watch
5) navigate to http://localhost:9000/ in IE (set to emulate IE10) shows loading: http://screencast.com/t/8MVbiVIGOWuG
6) screen goes blank
     - screenshot of console: http://screencast.com/t/JcA9l4dh
     - screenshot of DOM Explorer: http://screencast.com/t/zY2q7cNs

**Comment by dpinart** [comment]
I think I've found the issue and a possible solution.

The issue i located at _createTemplateFromMarkup method of TextTemplateLoader in aurelia-loader-default plugin.

To summarize, IE10 does not has built in support for templates so aurèlia has to 'manually' handle templates. The text passed as the template in createTemplateFromMarkup method is the string loaded from the template file (xxx.html) and it contains break lines. That causes that firstChidle of the template is just a text node with the line break text.

below I'm pasting a fix that it's wotking for me right now. I'm sure aurèlia team will be able to provide a much more elegant workaround

TextTemplateLoader.prototype._createTemplateFromMarkup = function _createTemplateFromMarkup(markup) {
      var parser = document.createElement('div');
      if (typeof MSApp != 'undefined') {
        MSApp.execUnsafeLocalFunction(function() {
          parser.innerHTML = markup;
        });
      } else
        parser.innerHTML = markup;
      var template = parser.firstElementChild;
      if (this.hasTemplateElement) {
        return template;
      }
      if (typeof MSApp != 'undefined') {
        MSApp.execUnsafeLocalFunction(function () {
          parser.innerHTML = parser.firstElementChild.innerHTML.trim();
        });
      } else
        parser.innerHTML = parser.firstElementChild.innerHTML.trim();

      template = parser;
      template.content = document.createDocumentFragment();
      while (template.firstChild) {
        template.content.appendChild(template.firstChild);
      }
      HTMLTemplateElement.bootstrap(template);
      return template;
    };

**Comment by RowanBrough** [comment]
Hey Nice Work! got the templates working :) however it looks like the nav-bar is now not rendering in any IE. It is still working perfectly in the decent browsers. Perhaps it might have something to do with child <template> tags (although your code does seem to loop through the firstChild). or maybe the <template bindable="router"> bindable functionality is now overlooked by ie not showing the router items.

**Comment by dpinart** [comment]
hmm
Let me investigate further.Maybe trim on every line in the template is needed

**Comment by dpinart** [comment]
It's working fine for me. Can you share the html of your navbar template

**Comment by RowanBrough** [comment]
I'm just using the the base aurelia-skeleton-navigation v0.18.1 just a basic setup to test IE
nav-bar code: https://github.com/aurelia/skeleton-navigation/blob/0.18.1/src/nav-bar.html
the only change i have made is added 

<script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      // Loads WeakMap polyfill needed by MutationObservers
      System.import('core-js').then(function() {
        // Imports MutationObserver polyfill
        return System.import('polymer/mutationobservers');
      }).then(function() {
        // Ensures start of Aurelia when all required IE9 dependencies are loaded
        System.import('aurelia-bootstrapper');
      });
    </script>

to the index.html as of http://aurelia.io/docs.html#browser-support

**Comment by dpinart** [comment]
Hmm

I'm not using the navbar supplied by skeleton app. I'm not sure if there's any issue with nav tag in ie10 and maybe you need some polyfill or modernizr.... Try to replace nav tag by a simple div...

**Comment by dpinart** [comment]
@EisenbergEffect  Would be nice in someone from aurelia's team could help us on this topic

**Comment by EisenbergEffect** [comment]
I've been monitoring. Even if I don't say something...I'm always lurking ;)
I have been traveling and other team members have been busy on other tasks, which is why nothing was said. It looks like some good progress has been made here in getting down to the problem. I think there are a few related tickets open now for templating in IE-type scenarios. I *think* we know how to fix them all. I've assigned this to me and will update as the issue advances. If you discover any other information related to windows store app idiosyncrasies, please let us know.

**Comment by dpinart** [comment]
Thanks @EisenbergEffect. The solution I've found is working pretty fine right now. I'm sure I'll find some more issues in the next few days but nowadays I can progress.

It seems there are some issues with Windows Stores App (they use IE10 internally) and worklight/phonegap. I've had to dix some polyfills, like WeakMap in HtmlImports and the Worklight library and others and very likely I'll have to do some more fixes.

The main issue, that I think it has an easy fix is the fact that Windows Store apps do not allow to dinamically modify html content. Fixing this issue is as easy as wrap the code within MSApp.execUnsafeLocalFunction. I'm a newby in javascript so I don't know if there's a way to override innerHTML attribute in order to fix this issue.

I will share all the stuff I'll need to make the application run in worklight and Windows Store App

**Comment by EisenbergEffect** [comment]
Please keep sharing that. We can address the issues in our code base that make sense. In addition to that, this would be a great topic for our documentation. So, after you have collected everything together, perhaps you would think about writing an article. We could feature you on our official blog and then later migrate the content into the docs as well. It's up to you. Think about it.

**Comment by RowanBrough** [comment]
@dpinart so i was looking into the "\aurelia\templating-resources@0.15.2\repeat.js" it seems IE doesn't pick up anything binded to the template. as seen in this example http://screencast.com/t/FaBVAXeN.
I was just quickly testing my earlier hypothesis, i will look deeper into to it now.

**Comment by RowanBrough** [comment]
jspm_packages\github\aurelia\templating-resources@0.15.2\aurelia-templating-resources.js
round about line 18 we have this line:
"var bindable = registryEntry.template.getAttribute('bindable');"
registryEntry.template is not read correctly by IE. it displays as <div></div>
where chrome displays the nav-var html.
which makes the call "bindable" null.

**Comment by mbernard** [comment]
Same issue here. Any ETA when this will be fixed?

**Comment by EisenbergEffect** [comment]
The plan is to have it in the next release, either Friday or Monday.

On Wed, Oct 7, 2015 at 1:19 PM, Miguel Bernard <notifications@github.com>
wrote:

> Same issue here. Any ETA when this will be fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/framework/issues/208#issuecomment-146267726>.
>



-- 
Rob Eisenberg,
President - Blue Spire
aurelia.io

**Comment by dpinart** [comment]
I've been busy in the last 3 weeks so didn't have much time to dedicate to this issue. @EisenbergEffect does your comment mean that we can expect some fixes in order to solve IE10 templating issues?

**Comment by EisenbergEffect** [comment]
Yes. But also, after this release it will be much easier for us to address
issues like this faster going forward. I'm really sorry it's taken this
long.

**Comment by nomack84** [comment]
> But also, after this release it will be much easier for us to address issues like this faster going forward

@EisenbergEffect is this due to the `pal-browser` component?

**Comment by EisenbergEffect** [comment]
It does relate to it in that implementing the PAL across all the libraries has taken us a bit longer than we hoped...so that has delayed this release a bit. It does make it easy for us to update that independent of the templating library for different platforms though. But mainly, this is the last set of sweeping changes before beta, so once that is done, we will be making much smaller changes and it will be easier for us to rev those faster.

**Comment by EisenbergEffect** [comment]
@dpinart What is the purpose of this?

```
  if (typeof MSApp != 'undefined') {
    MSApp.execUnsafeLocalFunction(function () {
      parser.innerHTML = parser.firstElementChild.innerHTML.trim();
    });
  } else parser.innerHTML = parser.firstElementChild.innerHTML.trim();

  template = parser;
```

This seems incorrect.

**Comment by EisenbergEffect** [comment]
Working in master. Next release will have the fix, probably tomorrow or Tuesday. Again, apologies for the delay...this is a big release.
