### ISSUE TITLE
Add support for Windows 8.1 hybrid applications

### ISSUE THREAD

**Issue by dpinart** [aurelia/framework#209]
Hi,

I'm trying to build an hybrid application that targets Windows 8 App Store applications. The main issue with this applications is that is not allowed to directly add dynamic content to html nodes. That affects at all methods that user element.innerHTML = markup.

I think that fix this issue would be as easy as wrapping innerHTML sets wihtin a  MSApp.execUnsafeLocalFunction, something similar to
</code>
``` javascript

if(typeof MSApp != 'undefined'){
           MSApp.execUnsafeLocalFunction(function () {
              element.innerHTML = markup;
          });
}
else
   element.innerHTML = markup;
````
</code>

**Comment by EisenbergEffect** [comment]
There is a new abstraction `pal` and a default implementation `pal-browser` that implements the template parsing code and all platform-specific code. To add support for Windows Store Apps, you should only need to monkey patch the pal's DOM.createTemplateFromMarkup() method. If you want to submit a PR to add a helper method to pal-browser to dynamically patch the method, I would be open to that. Bottom line is that our next release supports these types of platform-specific fixups much better.
