### ISSUE TITLE
CSS class order issue

### ISSUE THREAD

**Issue by smoothblur** [aurelia/framework#211]
I ran into an issue with how Aurelia is adding css class names to markup. It seems to be automatically sorting them alphabetically when it adds its own classes to tags. For example here is my template:

```html
<div class="four-wide-button-row padded">
    <a href="#" class="btn btn-medium btn-red ${showAll ? 'active' : ''}">
      <div class="vertical-center">All</div>
    </a>
    ...
</div>
```
As you can see the css classes on the anchor tag are in the order:
"btn btn-medium btn-red" and the "active" class is added at the end dynamically.

On the client-side (in the latest Google Chrome) it ends up generating the following markup:
```html
<div class="four-wide-button-row padded">
    <a href="#" class="au-target active btn-red btn-medium btn" au-target-id="2">
      <div class="vertical-center">All</div>
    </a>
    ...
</div>
```
Notice how the classes are now sorted alphabetically:
"au-target active btn-red btn-medium btn"

This has the negative side effect of altering the cascade in the CSS and in the wrong order the active class has no effect.

I can work around this but it seems like a bug/issue that should be addressed. The classes should stay in the order they were added in the template or various design issues can be introduced.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look at this?

**Comment by smoothblur** [comment]
Actually it seems more like they are inverted not alphabetic. At first glance it seemed like they where alphabetic but its more coincidental to how these classes are named. Regardless there is a sort issue of some kind. I will try it with some other class name combos and see what pattern shakes out.

**Comment by smoothblur** [comment]
I can confirm that the order is being inverted. If I reverse the order of the classes in the template they end up in the rendered HTML in the correct order. If I take the template binding out of the anchor tags as it is in my example above then the order of the classes on the anchor is not altered.

**Comment by jdanyow** [comment]
Looked into this... 

Aurelia's class binding uses [`element.classList.add(...)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) and `.remove(...)` under the covers.  I think the order might be reversed due to a [`while(i--) {`](https://github.com/aurelia/binding/blob/master/src/class-observer.js#L22) loop.  We could probably change the order but [it wouldn't impact the computed style of the element](http://stackoverflow.com/questions/15670631/does-the-order-of-classes-listed-on-an-item-affect-the-css).

@smoothblur / @EisenbergEffect thoughts?

**Comment by EisenbergEffect** [comment]
@jdanyow If changing that to a for loop would preserve the ordering, that's probably ok. The performance difference is probably ok.

**Comment by adriatic** [comment]
Impressive focus on performance :-)

**Comment by EisenbergEffect** [comment]
The particular while loop that is used there is the fastest loop you can do in JS. It is a bit of a micro-optimization, so if we can't use it, then it's not a huge deal. There are other optimizations we're working on that are *much* more significant. Jeremy's been doing some great work there. The next release will start to include some significant improvements in that area.

**Comment by jdanyow** [comment]
fixed in https://github.com/aurelia/binding/commit/52de0824f8f3fd5b0c1e0628c58de8954d983fdb
