### ISSUE TITLE
write components more intuitive

### ISSUE THREAD

**Issue by TsumiNa** [aurelia/framework#213]
Hi! Thank you for your great works, I really love this framework. this is not a issue but a suggestion about write components more __intuitive__.

This framework based on ES6/7 and typescript. Compare with Angular2 which have many fussy designs, aurelia is extremely clean and user friendly. That's good! But when I wrote some components, I felt something confusion. I use C like syntax working with class but consumed it like javascript do. which I mean I wrote classes but don't know where are they from and how they will be used. Angular2 use decorator to markup classes as a component like
```javascript
@Component({
  selector: 'my-component'
})
@View({
  template: '<h1>Hello world</h1>'
})
class MyComponent { }
```
Yes, it's too long I don't like that. but this show a logic to the user directly. When I see that, I will know this is a component and will be used to replace \<my-component\> tag. so I think if there is a way to make aurelia more intuitive to use. for example something like this:
```javascript
export class MyComponent extends aurelia.Component {
    // some codes here
}

class MyStore extends aurelia.Store {
    // some codes here
}
```
It's like react did. If I use typescript, the override member function will have a auto-complete.

In fact I'm not a front-end engineer but a physicist study on calculation physics. Maybe I say something wrong, but I use computer everyday and write C/python code by myself. For this reason, I think a framework should be designed to tell users everything even there are not docs/manual. Less override means intuitive, more strict means IDE/tools friendly.

**Comment by zewa666** [comment]
The difference with Aurelia is that it focuses on reducing the workload you as a developer are having by removing all unnecessary bulk. If on the other hand you like the additional expressiveness you can use the full declaration way with decorators `@customAttribute('yourAttribute')` and `@customElement('yourElement')`. So what makes that possible is Aurelias use of Convention over Configuration, but again if you prefer you still can place all the additional information.

**Comment by TsumiNa** [comment]
@zewa666 Thanks for your reply. Now I can decide what to do. Again, Aurelia is amazing！

**Comment by EisenbergEffect** [comment]
@TsumiNa One of the neat things about Aurelia, is that because of our conventions, it allows you to turn any plain JavaScript class into a UI component.

**Comment by atsu85** [comment]
Just a note about the example You gave:
```javascript
export class MyComponent extends aurelia.Component {
    // some codes here
}
```
Forcing to extend our custom components from aurelia base class isn't the best approach.

I'd rather suggest You to use interfaces for custom components (and views) that will define optional lifecicle methods such as created, bind, unbind, attached, detached (and see http://aurelia.io/docs.html#the-screen-activation-lifecycle for views).

That way IDE could help You and You are not forced to use base classes from Aurelia

**Comment by TsumiNa** [comment]
@atsu85 thank you for you suggestion. I read this docs, it's usefull.

It seems I should change my mind to dive in this framewrok. as @EisenbergEffect said, conventions is a good approach to make things clean and easy. remember less do more :)
