### ISSUE TITLE
How to implement a ViewModel/View selector?

### ISSUE THREAD

**Issue by hoangcuongvn** [aurelia/framework#215]
I know recent css libraries/frameworks work fine to make responsive UI. But a real app usually has complicated UI for some pages and then that requires to separate the ViewModel/View into several dedicated UIs for dedicated devices.

I want to have a ViewModel/View selector which is capable to load ViewModel/View accordingly on device screens. For example, supposing the module MyModule is required
- If the app runs in a phone. It will try to look for MyModule.mobile.js, MyModule.mobile.html firstly. If these files do not exists, it will use the default files MyModule.js, MyModule.html.
- If the app runs in a tablet. It will try to look for MyModule.tablet.js, MyModule.tablet.html firstly. If these files do not exists, it will use the default files MyModule.js, MyModule.html.
- If the app runs in a PC. It will use the default files MyModule.js, MyModule.html.

Asp.net Web Pages has built-in support for this feature when it process Razor (.cshtml, .vbhtml) files. But because it runs on server-side so it's easy to check if a file exists. The client-side seems much more complicated.

I'd like to know if it is possible to implement this ViewModel/View selector in Aurelia? Any suggestion or advice are greatly appreciated.

**Comment by EisenbergEffect** [comment]
Yes, it is possible by using a ViewStrategy that detects the device and returns different views accordingly. There isn't much in the docs on how to do this yet. I'll try to follow up here soon with some more details.

**Comment by zewa666** [comment]
@hoangcuongvn in an article I wrote for Sitepoint, the usage of getViewStrategy, a hook to determine which actual View to render, was depicted. That might help.
http://www.sitepoint.com/composition-aurelia-report-builder/

**Comment by hoangcuongvn** [comment]
@EisenbergEffect, @zewa666 

I have a look in the docs about getViewStrategy and ViewStrategy. It seems they can be only used to detect a View (not ViewModel) from a given module id? Is there any way to let Aurelia detect both View/ViewModel from a module id? As in my example above, Aurelia should load both MyModule.mobile.js and MyModule.mobile.html?

Another problem that is how to determine if a file (i.e MyModel.mobile.js or MyModel.mobile.html) exists in client-side? I am thinking to add properties i.e hasMobile, hasTablet into the VM in MyModel.js. These properties will help to detect correct ViewModel/View files. But there might be simpler and better solution?

**Comment by zewa666** [comment]
I personally wouldn't create alternative versions of a viewmodel, but try to exclude the logic into services (simple classes) and request the necessary implementation based on your conditions. This may be done during the activate hook as its one of the first to appear or in the class constructor itself.

An alternative would be to use manual composition where you decide which view / viewmodel to load (take a look at mentioned article for a demo). And yet another one would be to dynamically construct your router paths with the correct moduleId if you're using the router.

In general those questions are better suited in the official gitter channel as they are no real issues per se.
