### ISSUE TITLE
FrameworkConfiguration bug,  globalResources doesn't look correct

### ISSUE THREAD

**Issue by ntilwalli** [aurelia/framework#216]
The `globalResources` method in FrameworkConfiguration looks like it has a bug.  It's in the line:

``` 
      this.resourcesToLoad[path] = this.resourcesToLoad[path];
```

It should actually read:

```
      this.resourcesToLoad[path] = resource;
```

As it currently stands, IMHO, that line seems to do nothing. I posted about this in Gitter a while ago, but didn't follow up.  Am I right that this is a problem that needs to be fixed?

**Comment by jdanyow** [comment]
https://github.com/aurelia/framework/blob/master/src/framework-configuration.js#L164

**Comment by ntilwalli** [comment]
Yeah, that's the line that seems odd.

**Comment by ntilwalli** [comment]
I just realized this line is confusing, but it's not actually a bug.  That line causes the `resourcesToLoad` property of Framework to being filled with key-value pairs that consist of `(some-resource-path, undefined)`, which is actually correct since that Object is being used to call  `ViewEngine.loadResources` which, uses the value in the second argument as an alias, for renaming purpose.  In this case no rename is desired, so having the value set to `undefined` is the correct behavior.  I'll withdraw this.
