### ISSUE TITLE
Keyboard typing leaking between browsers

### ISSUE THREAD

**Issue by txels** [aurelia/framework#218]
I have this weird problem with Aurelia apps. If I have the same app open in multiple browsers (either browser tabs or even different manufacturers' browsers), then what I type on forms in one browser leaks to the other one. This is one example with Chrome and Firefox:

![leak](https://cloud.githubusercontent.com/assets/874958/10129962/fca43f32-65c3-11e5-8363-4e70d2e1e97d.gif)

It doesn't even have to be the same page from the app and the same form. It happens across different pages.

There is nothing particular with my app and forms rather than using the regular Aurelia two-way data binding. In fact, I can reproduce this problem with the aurelia skeleton app.

The leak doesn't happen across different applications (i.e. my app and the skeleton app do not leak to each other).

**Comment by txels** [comment]
Investigating a bit further, the leak only happens between applications served by the same backend process (`gulp watch`) so it may have to do with how that server handles the live reload.

**Comment by JeroenVinke** [comment]
This is not a bug (or feature) of aurelia. This is because of the browsersync plugin (https://github.com/aurelia/skeleton-navigation/blob/master/build/tasks/serve.js#L8-L18). You can disable this by setting the ghostmode property of browsersync to false (http://www.browsersync.io/docs/options/#option-ghostMode).

**Comment by txels** [comment]
Oh gosh thanks, it was driving me crazy. It could be added to the tutorial documentation (or be a default setting in the skeleton app).

**Comment by paritoshmmmec** [comment]
Same here, I was not knowing this

**Comment by zewa666** [comment]
How bout this? https://github.com/aurelia/skeleton-navigation/pull/176

**Comment by txels** [comment]
Nice, thanks for the speedy responses.
