### ISSUE TITLE
Custom Element: Option to wait for aurelia-animator to complete

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/framework#220]
I'm running into an issue where a custom element is causing the aurelia-animator to fail. (In this cause, it's a Kendo plugin with jQuery animation that is causing the problem.)

I'm initializing my custom element in the `attached()` method in the lifecycle. However, I would like a way to initialize the element after the animation queue has finished without having to include an animator reference in the viewmodel.

I checked the `created` method in the custom element lifecycle, and it seems to return a View instance. Might it be possible to keep a reference to an animator promise in the View itself? Alternatively, might it be possible to pass this promise as an argument to the `attached()` method?

Edit: It turns out that this should be in the `templating` repository. Sorry about that.

Looking further, it seems that this is the relevant code, in `view-slot`:

```
  attached(): void {
    var i, ii, children, child;

    if(this.isAttached){
      return;
    }

    this.isAttached = true;

    children = this.children;
    for(i = 0, ii = children.length; i < ii; ++i){
      child = children[i];
      child.attached();

      var element = child.firstChild ? nextElementSibling(child.firstChild) : null;
      if(child.firstChild &&
        child.firstChild.nodeType === 8 &&
         element &&
         element.nodeType === 1 &&
         element.classList.contains('au-animate')) {
        this.animator.enter(element);
      }
    }
  }
```

We call `child.attached()` before the animation begins, and there's no part of the lifecycle that occurs after the animation. Passing the promise returned from `this.animator.enter(element)` isn't possible as that call occurs after the call to `child.attached()`. I could see this working if the animator interface was altered to include something like a "prepare" function, which would initialize the promise but not resolve it. Then, the `enter` function could resolve this promise on complete in addition to its own (or they could be chained, or whatever). Thus, this would end up looking like:

```
  attached(): void {
    var i, ii, children, child;

    if(this.isAttached){
      return;
    }

    this.isAttached = true;

    children = this.children;
    for(i = 0, ii = children.length; i < ii; ++i){
      var animationPromise = this.animator.prepare(); // Or something
      child = children[i];
      child.attached(animationPromise);

      var element = child.firstChild ? nextElementSibling(child.firstChild) : null;
      if(child.firstChild &&
        child.firstChild.nodeType === 8 &&
         element &&
         element.nodeType === 1 &&
         element.classList.contains('au-animate')) {
        this.animator.enter(element);
      }
    }
  }
```

Unfortunately, this specific solution might only help if the specific element has an animation involved. I don't know if this would help my use case (where I have a parent element with the animate class and the custom element can be anywhere inside that parent).

What do you guys think?

**Comment by EisenbergEffect** [comment]
Can't pass it to the attached method. There are other plans for that. Not sure if we can store the promise on the view or not. @zewa666 would have to comment on that.

**Comment by jedd-ahyoung** [comment]
I'm not sure if storing the promise on the view will work or not. You'd have to instantiate that promise very early on in the lifecycle. It would make more sense in attached, as that's where the animation happens. I suppose you could, however, pass an instance of the animator as part of the create lifecycle. This could help me a lot as I might want to check to see if all page animations in queue are finished. However, I don't know if this would be a general use case, and I'm not sure if you'd want to expose the animator object in that way. (Maybe it could be a good thing. I don't know.)

I'd have to look further at the codebase to see what other options there are (besides adding an additional lifecycle hook; which I think could overly complicate things). Perhaps there's a way to access the viewslot instance from a custom element? If so, I could get the animator instance and maybe work my way from there. The only problem that I see with that approach is that although the interface methods are standardized, the getters are not - so checking for an "isAnimating" property or something would bind me to the implementation of a certain animator.

**Comment by jedd-ahyoung** [comment]
Perhaps a better solution to this is for the animator to use Aurelia's event aggregator to publish events when it's finished animating (or, alternatively, publish an event from the `attached()` method upon `this.animator.enter` promise completion). Custom elements could simply import the event aggregator and listen for that event in the `attached()` method.

What do you guys think? Here are the pros, as I see it:

1. No extra lifecycle method.
2. Preserve the future arguments to `attached()`.
3. No need to change the order of the existing calls in the `attached()` method in view-slot.
4. Opt-in is purely optional from a user standpoint.
5. This doesn't necessarily go against any aurelia patterns, as the router exposes events like this as well.

Cons:
1. Adding a dependency to the event aggregator either in view-slot or in animator. Maybe not great.
2. If this is added to the animator, the interface would have to change - all implementations of the animator would have to publish a set of known events. (However, missing the event publishing wouldn't necessarily break existing functionality.)

@zewa666 and @EisenbergEffect , I'd love to know your thoughts on this. I don't want to bug you guys as I know you're busy with other things. I'd be willing to spearhead this if necessary.

**Comment by EisenbergEffect** [comment]
We can't create a dependency between the EA and the templating library. The EA library is an optional library, while the templating library is a core part of the framework. Also, the EA is global, so I'm not sure that publishing events on it for every single dom add/remove would be easy for you to interpret. It's also likely to cause a perf problem.

One of the reasons that the Animator is pluggable is so that you can change how that all works. I believe you could easily resolve `Animator` from the DI container and simply add the functionality that you need for your scenario.

I'd really like to know why the jQuery plugin is causing things to fail though.

**Comment by jedd-ahyoung** [comment]
Rob, I'll try to create a test case for you. This happens with a Kendo component, so I think I'll be able to recreate it in the Aurelia-Kendo-UI project. (I believe that it has to do with an introduction animation when a certain element is loaded.)
