### ISSUE TITLE
Binding issue on Firefox and IE

### ISSUE THREAD

**Issue by ostyn** [aurelia/framework#221]
From Rob:
>This may be a legitimate bug. Can you create an issue and please provide a simplest possible way for us to reproduct the problem, preferrably on the navigation skeleton? 

* Setup the skeleton-navigation app
* Add the following to welcome.js:
```javascript
constructor() {
	this.list = [];
	for (var index = 0; index < 3; index++)
	  this.list[index] = "-";
}
click(x) {
	this.list[x] = x;
}
```
* Add the following to welcome.html:
```html
<div class="column" repeat.for="item of list">
	<button class="cell" click.delegate="$parent.click($index)">${item}</button>
</div>
```
* gulp watch
* Open http://localhost:9000 in FF, IE, and Chrome
* Click the first of the 3 buttons in FF. Nothing will happen in FF but the button will change in Chrome.
* Do the same in each of the other browsers. Chrome will be the only browser that is affected correctly.

So changing the value after the initial bind is not functioning consistently across browsers. Maybe a difference in the bind mode selected(i.e. one-time vs. one-way)?

**Comment by jdanyow** [comment]
Aurelia's binding system will adapt to the browser features that are available.  It prefers to use Object.observe when it's available.  Chrome has Object.observe which is capable of detecting situations where items are replaced in array via the keyed assignment method you're using (`this.list[index] = "-"`).  For this to work in all browsers you'll need to use `this.list.splice(x, 1, x)`.  Basically stick to using the array instance's mutation methods and everything will work (`push`, `pop`. `slice`, `splice`, `shift`, `unshift`).

**Comment by ostyn** [comment]
Oooohhhh... That's perfect. Knowledge is power. Thank you kindly!
