### ISSUE TITLE
Default value converters for common input values

### ISSUE THREAD

**Issue by giovannicandido** [aurelia/framework#223]
Hi,
The feature of value converters is great, but what about default converters from the framework?
There are some behaviors that are just fine to make a default conversion.
By example if a template have a input with type number, the model should return a number and not a string

```
<input type="number" value.bind="model" />
```
The model value should be a int and not a string, without any intervention. This is the behavior of angularjs default directives, and is quite useful. Supose you need to convert a model to JSON and send to the server, if the server expects a number in some field of the model, then it will complain with bad requests when the string is passed.

Today we need:

```
<input type="number" value.bind="model | number" />
```
And write the proper `NumberValueConverter` class

Other inputs that could be on the list:

* Html5 Dates
* input type range
* checkbox
* radio

**Comment by EisenbergEffect** [comment]
@jdanyow I'm wondering if there's some way we could detect primitive types during binding and then somehow apply a conversion automatically on two-way bindings only to ensure that the value, when bound back from the input control, is transformed into the same time as the original input. There is a difficult of course in determining what to do if there is a parse error. So, I'm not sure if we should even do this or not. Needs some thought.

**Comment by giovannicandido** [comment]
@EisenbergEffect If the bind have access to the element object, in this case a input element, it could do a logic to check the conversion it should do. In the example it could check for the type="number" and do the parseInt conversion. In the case of failures it should flow the original text.
Or a way to attach the conversion by selector like the directives of angular, in this case the ValueConverter could declare a dom selector like ```input[type="number"] ``` and be attached to all input of type number. I think some sort of chain of resposability need to be done in this case, to apply multiple declared conversions, if some conversion fail, by default the value is passed as is to the next converter in the chain, until it hits the value. This is very powerful, but dificult to debug in some cases. I prefer that alternative because if very flexible. 
Other alternative is a converter with no chain, and the last applied converter takes place.

**Comment by jdanyow** [comment]
I think this would make a nice external plugin.  Here's why I don't think it's a good fit for the aurelia core:

Consider a date input: `<input type="date">`.  Adding an "automatic" value converter when data-binding to the input's value would require sophisticated parsing logic to handle different date formats, locales, invalid data entry, etc.  Parsing logic is already implemented in external libraries like MomentJS.  Aurelia can't take on external deps.  The other thing is an date input combined with a value converter isn't enough to make a useful date "control".  It won't do a good job of showing invalid data entry, etc.  A value-converter alone won't be able to control how a native datepicker formats the selected date in the input's textbox.

There are similar pitfalls for number inputs.  Aurelia already has handling for checkbox and radio inputs (these don't allow free-text entry so we're able to provide consistent data-binding capabilities in all browsers).

Thoughts?

**Comment by giovannicandido** [comment]
I think a plugin would be nice. The selector in valueConverter could be native, and the actual converters could be the plugin with the required dependencies for date parsing like moment.js
The number filed should not allow text inputs. But is not cross browser, firefox allow and chome doen'st allow, but I think is not a big deal in this case, the conveter could simple stop the parse on invalid input, and as a side effect the typing will not proced as expected

**Comment by EisenbergEffect** [comment]
Closing this as it's a better fit for a 3rd party plugin.
