### ISSUE TITLE
Compile errors under Node 4.x during install

### ISSUE THREAD

**Issue by eobeda** [aurelia/framework#224]
To make the next release an enjoyable event for everyone, I would recommend that the version of karma defined in the various projects be updated to at least the 0.13.11 level.

Currently for node 4.x users the Aurelia “install” throws a lot of errors because one of "karma": "^0.12.28" ‘s dependencies (specifically nan) is the wrong version for node 4.x. Updating karma to the 0.13.11 level would eliminate both the:

1) npm warning about the version range mismatch for karma itself:
karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.0.0","

2) and the actual compile error messages for  “nan\nan.h”.

I believe, newbies and early adopters would both be please by such a change.

**Comment by jimmywarting** [comment]
+1

**Comment by tomalec** [comment]
+1, I spend entire evening trying to get through first lines of [getting started](http://aurelia.io/get-started.html):
```
yo generator-aurelia
```
or just
```
npm install
```

with no luck at all :(

Is there any way in which I could run any kind of demo/example of Aurelia?
As I'm not even sure if it is the thing I'm looking for ;)

**Comment by EisenbergEffect** [comment]
Next week we will have a new release, with a new getting started guide which will allow you to try things out without installing anything. No node, no yo, no gulp, nothing. Please hang in there.

**Comment by tomalec** [comment]
That was quick response! :) thanks, sounds great.

**Comment by EisenbergEffect** [comment]
@tomalec Did you also see the problem as coming from Karma?

**Comment by tomalec** [comment]
`npm install > install.log` resulted in 
```log

WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.2","npm":"3.4.0"})
npm WARN install Couldn't install optional dependency: Unsupported

npm WARN prefer global marked@0.3.5 should be installed with -g
```
and 
install.log:
```log
d:\repos\PolymerPlayground\aurelia2\framework-0.18.0\node_modules\ws>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
d:\repos\PolymerPlayground\aurelia2\framework-0.18.0\node_modules\ws\build\bufferutil.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
d:\repos\PolymerPlayground\aurelia2\framework-0.18.0\node_modules\ws\build\validation.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
aurelia-framework@0.18.0 d:\repos\PolymerPlayground\aurelia2\framework-0.18.0
```

**Comment by EisenbergEffect** [comment]
Fixing as part of this release cycle.
