### ISSUE TITLE
router.navigate sometimes returns promise sometimes returns boolean

### ISSUE THREAD

**Issue by smoothblur** [aurelia/framework#226]
I added some code to my application to verify that the route change completed successfully. Using the following code...

``` javascript
var navigationStatus = this.router.navigate(view);
console.log(navigationStatus);
```

I can see that most of the time it returns a promise with a status object and if the target route is the current route it returns a plain boolean false. 

example return data logged to console:
false
Object {status: "completed", context: e, output: undefined, completed: true}

Is there some intended reason for this difference? It seems like it would be more ideal to always return a promise with a status for consistency.

I ended up wrapping the returned value with Promise.resolve, but It seems like it would be more elegant if I could l count on the data to always be a promise with a status.

``` javascript
this.router.navigate(view).then(response => {
    if(response.completed == true){
        //do something...
    }
});
```

Again just wondering if this is an oversight or intentional.

**Comment by atsu85** [comment]
just a note: based on return type 
https://github.com/aurelia/router/blob/master/src/router.js#L118
`router.navigate` must never return Promise

**Comment by smoothblur** [comment]
Interesting. I haven't updated to the latest version yet but 0.16.0 definitely returns a promise more often than not.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Didn't you have a simple way to address this by using even aggregator?

**Comment by EisenbergEffect** [comment]
I'd like it if this could be more consistent, but it's probably very difficult without breaking some things. This at least well-documents the return type so that there is no confusion.
