### ISSUE TITLE
Cannot capture scroll events

### ISSUE THREAD

**Issue by emcga** [aurelia/framework#228]
I have a piece of code that needs to run when the window scroll event is fired, but I cannot get it to work.

I have used the following code in the attached() function of my viewmodel without success...

I also dropped the code in the console after the page was loaded, but still a no go.

```javascript
window.addEventListener('scroll', function(){
     console.log("This is a test");
});

//and

$(window).scroll(function(){
     console.log("This is a test");
})

```

If I try the above code in a browser without Aurelia running, all is well and the console prints the "This is a test" message.

I did notice that the scroll event does not bubble; could this be the reason I'm having this issue? All of the other events I try to capture work fine using the above methods, but I really need to listen for the scroll event.

Thank you in advance for you help.

**Comment by jdanyow** [comment]
here's an example using scroll data-binding as well as scroll event binding
http://www.danyow.net/scroll-binding-with-aurelia/
