### ISSUE TITLE
Bootstrap Navbar Toggle Not Working

### ISSUE THREAD

**Issue by epzilla** [aurelia/framework#23]
After following the instructions to build the example app, I noticed that when I shrink my browser window, or open the app on my phone, when i click/tap the button to toggle the mobile nav menu, nothing happens. Is anyone else seeing this?

**Comment by mschoneman** [comment]
I see the same thing.

**Comment by EisenbergEffect** [comment]
We are tracking this and will get it fixed soon. Thanks!

**Comment by EisenbergEffect** [comment]
Commited fix. New skeleton releasing soon.

**Comment by tjyan** [comment]
I just downloaded the latest version of aurelia kit today, this toggle nav button still has the same issueas a year ago, when clicking on, nothing happen, can you confirm this has been fixed? thanks!

**Comment by doktordirk** [comment]
the kit? try the skeletons (though i don.t like the way it.s fixed there)

**Comment by EisenbergEffect** [comment]
There's an issue with bootstrap and jspm so the skeletons have some fixes for that. We're working on getting those update in the next week or so. We'll be removing the "beginner kits" soon and replacing them with a new simple script beginner kit, a new getting guide and a new first application tutorial.

**Comment by tjyan** [comment]
Great, thanks for the information. looking forward for the new tutorial.
