### ISSUE TITLE
new bindingEngine class / api

### ISSUE THREAD

**Issue by davismj** [aurelia/framework#232]
A quick note, I tried to
```
import { BindingEngine } from 'aurelia-framework';
```
which couldn't be found. The fix was to rename it to `bindingEngine`. However, as bindingEngine is a class, and not a method, the Aurelia style guide would recommend it be init capped, I believe.

This is a sort of breaking change, what do we want to do here?

**Comment by EisenbergEffect** [comment]
Before it was an object instance and was lower-cased, but we realized we wanted a class instead. We have made the change to a BindingEngine class for the next release.
