### ISSUE TITLE
Can repeat.for attribute support Iterable? 

### ISSUE THREAD

**Issue by hoangcuongvn** [aurelia/framework#233]
I see the repeat.for attribute actually only supports Array, Map, Number as its items source. Is it possible if you extend it to support Iterable too? So it would naturally suit with other js built-in collections like Set and any custom collections which implement iterable interface/protocol.

**Comment by StrahilKazlachev** [comment]
Check this [one](https://github.com/aurelia/templating-binding/issues/54#event-445640999).

**Comment by EisenbergEffect** [comment]
We have a plan to make it pluggable. Doing a performant repeater requires more than just the Iterable interface, unfortunately. So, we can't just go on that. But, we are currently implementing a pluggable strategy pattern. The PR is in..I just have to review it :)

**Comment by gingerik** [comment]
Any update on this?

**Comment by EisenbergEffect** [comment]
We made the repeat.for attribute pluggable so you can teach it how to handle different types of collections. If you have a question on how to do that @martingust can provide some details.

**Comment by gingerik** [comment]
Sounds great, thanks @EisenbergEffect.

**Comment by martingust** [comment]
@gingerik We recently added a [Set strategy](https://github.com/aurelia/templating-resources/blob/master/src/set-repeat-strategy.js) to the repeater. So today the repeater supports **Array**, **Map**, **Number** and **Set** out of the box. However as @EisenbergEffect said you can plug in your own strategies. 

What you would want to do is implement the [RepeatStrategy interface](https://github.com/aurelia/templating-resources/blob/master/src/repeat-strategy-locator.js#L10-L14) and then call the `addStrategy` method on [RepeatStrategyLocator](https://github.com/aurelia/templating-resources/blob/master/src/repeat-strategy-locator.js) which takes two parameters; `matcher` and `strategy` - where `matcher` is a function that takes the items to be iterated as parameter and returns true if the strategy is able handle the items, and `strategy` is an instance of the strategy.

Here is a simple example:

```html
<template>
    <div repeat.for="item of myIterator">
      ${$index} ${item}
    </div>
</template>
```

```javascript
import {RepeatStrategyLocator} from 'aurelia-templating-resources/repeat-strategy-locator';
import {createFullOverrideContext} from 'aurelia-templating-resources/repeat-utilities';

export class App {
  static inject = [RepeatStrategyLocator];

  myIterator = ['foo', 'bar', 'baz'][Symbol.iterator]();

  constructor(repeatStrategyLocator) {
    repeatStrategyLocator.addStrategy(items => typeof items[Symbol.iterator] === 'function', new IteratorStrategy());
  }
}

class IteratorStrategy {
  instanceChanged(repeat: Repeat, items: any): void {
    let index = 0;
    for(let item of items) {
      let overrideContext = createFullOverrideContext(repeat, item, index);
      let view = repeat.viewFactory.create();
      view.bind(overrideContext.bindingContext, overrideContext);
      repeat.viewSlot.add(view);
      ++index;
    }
  }
  instanceMutated(repeat: Repeat, items: any, changes: any): void {
  }
  getCollectionObserver(observerLocator: any, items: any): any {
  }
}
```

Let me know if that makes sense? Also you can have a look at the existing strategies in the `templating-resources` repo.

**Comment by gingerik** [comment]
That makes a lot of sense. Thanks for the quick reply!
I managed to integrate this example in my project and it works like a charm!

If I understand correctly, in order to fully use the capability of the repeater I should return a _IteratorObserver_ in `getCollectionObserver` to observe the iterable for changes and update the `viewSlot` within the `instanceMutated` method based on these changes, right?
