### ISSUE TITLE
require css as scoped not working

### ISSUE THREAD

**Issue by genadis** [aurelia/framework#234]
tried to test
```
<require from="my-view.css" as="scoped"></require>
```
as mentioned in [#50](https://github.com/aurelia/framework/issues/50) and [early-september-release-notes](http://blog.durandal.io/2015/09/05/aurelia-early-september-release-notes/)

tested with skeleton-navigation, welcome.html
Tried with ```@useShadowDom()``` on ```welcome.js``` and without.

Expected to see the ```<style>``` with ```scoped``` attribute.
With ShadowDom decoration, ```<style>``` is added under ```<router-view>```.
Without ShadowDom ```<style>``` is added in the header.

##### In both cases though, no ```scoped``` attribute.

My [Fork](https://github.com/genadis/skeleton-navigation) contains the test.

Please advise, what am I missing?

Using Chrome and latest skeleton-navigation.

#### About the test
In index.html I'm loading css. with one color set.
adding element(button) to nav-bar that uses the styling.

in welcome.html loading another css using scoped require with same classes but second color set.
adding element to welcome that uses the styling.

Expecting the element  in nav-bar to have color from first color set, and in welcome to have color from second set.

Result: after load both elements have same second color set.

**Comment by EisenbergEffect** [comment]
The scoped css only works if the browser supports it. Right now, that's only Firefox. The shadow dom only works inside custom elements, because we need a stable element to create the shadow root from. We can't create it on the router-view because different screens may or may not want shadow dom.

This feature is best used with real shadow dom inside a custom element. Right now, that's basically Chrome. So, it's most useful for electron, nwjs and phonegap apps. It's not as useful when targeting the browser because of missing support. Polyfilling this is not only difficult, but can hae serious performance implications. We are open to suggestions as always though.

**Comment by genadis** [comment]
Thank you for the detailed answer.
Indeed in Firefox scoped attribute is added and style is placed under the correct element.

I understand the compatibility issues, but it would be great if the behavior of aurelia would be consistent across browsers, so if a developer decides to use polyfilling or some other solution such as [jQuery plugin](https://github.com/thingsinjars/jQuery-Scoped-CSS-plugin) he would have the option to do so.

Currently for Chrome, IE, etc, the style is added to header (for non shadowDOM) and no ```scoped``` attribute is added.
For shadowDOM the style tag is added in the right element, but again no ```scoped``` attribute.
For Firefox the style tag is always in the right place and ```scoped``` is added.

**Comment by EisenbergEffect** [comment]
I'm not sure it makes sense to add a scoped attribute when the styles are
in the shadow dom, since that scopes them automatically. I don't know of a
sure fire way to pollyfill this. Recommendations are welcome.

On Wed, Oct 28, 2015 at 9:10 AM, Genadi <notifications@github.com> wrote:

> Thank you for the detailed answer.
> Indeed in Firefox scoped attribute is added and style is placed under the
> correct element.
>
> I understand the compatibility issues, but it would be great if the
> behavior of aurelia would be consistent across browsers, so if a developer
> decides to use polyfilling or some other solution such as jQuery plugin
> <https://github.com/thingsinjars/jQuery-Scoped-CSS-plugin> he would have
> the option to do so.
>
> Currently for Chrome, IE, etc, the style is added to header (for non
> shadowDOM) and no scoped attribute is added.
> For shadowDOM the style tag is added in the right element, but again no
> scoped attribute.
> For Firefox the style tag is always in the right place and scoped is
> added.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/framework/issues/234#issuecomment-151895555>.
>



-- 
Rob Eisenberg,
President - Blue Spire
aurelia.io

**Comment by genadis** [comment]
Thank you for your patience.

Regarding shadowDom I agree, lets put it aside.

Please consider non shadowDom use case.
What I'm experiencing is that:
* In Firefox, ```<style>``` tag is added under the scoped dom element and with ```scoped``` attribute .
* In all other browsers ```<style>``` tag in injected into ```<head>``` of the dom, without ```scoped``` attribute.

I'm using ```<require from="..." as="scoped"></require>```

It is clear that only Firefox will be able to interpret the ```scoped``` attribute and make use of it.
What I don't understand is why aurelia behaves differently for Firefox vs other browsers.

Why I believe consistency is imported:
If I wanted let's say to implement aurelia plugin that makes use of the ```scoped``` attribute, or use some third party solution such as:
[jQuery plugin](https://github.com/thingsinjars/jQuery-Scoped-CSS-plugin)
[scoped-polyfill](https://github.com/PM5544/scoped-polyfill)
[scoper](https://github.com/thomaspark/scoper)

I won't be able to, since the ```<style>``` is placed in the head and ```scoped``` attribute is missing when using non Firefox browser.

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/6747147/10803522/45418bae-7dcb-11e5-9f7f-e5189a863cf1.png)

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/6747147/10803528/4c3a94b4-7dcb-11e5-8100-9ba55defd70a.png)
