### ISSUE TITLE
Application boundaries (aurelia app as widget in third party web site)

### ISSUE THREAD

**Issue by genadis** [aurelia/framework#235]
Please consider use case where aurelia application is to be used as widget in third party website.
Website owner includes some javascript on their page, and get some widget which is based on aurelia framework.

I believe aurelia to be an amazing framework that can be used for widget development as well (without interfering with the third party website).

Please consider, that the website owner might be using aurelia for his website as well.
Meaning he has ```aurelia-app``` let's say on the ```<body>```.

As widget developer that wants to inject some dom elements into the body and make the integration easy with the website (one line javascript) as I understand it's an issue.

Once application root is set which in many cases would be ```body``` aurelia "takes over" the root element.
I don't see how another aurelia application can be run inside the other (nested).
* solution of providing widget app as aurelia plugin is not the best solution since there could be issues with dependencies and framework versions.

It could be great if we could set an attribute or custom html element that signals aurelia app: "don't go in there", so everything inside this element is not touchable by the framework.
That way, the widgets aurelia app root could be set inside that element which would be invisible to the websites aurelia application.

```
<body aurelia-app>  <!-- root of the third party website aurelia version 1.0.0 -->
  <!--........-->
  <div aurelia-dont-touch>
      <div aurelia-app  id="widget-app">    <!-- root of the widget aurelia version 1.10.0 -->
         <!-- custom aurelia bootstrap -->
          <!--- ..... -->
     </div>
  </div>
</body>
```
additional issue could be with bootstrap: while there is option for custom bootstrap setting the root element explicitly, I've noticed in bootstrapper the ```run();``` is called on script load. Which in turn looks for ```aurelia-app```. The widget's bootsrapper would find the ```<body>```.
Simple solution could be, to add attribute that will be used as flag indicating that this aurelia-app is already used (already bootstrapped by another application). 

Was this use case considered? Is there a solution? 

Thank you for great framework!

**Comment by smolinari** [comment]
This goes along the lines of https://github.com/aurelia/framework/issues/50.

Scott

**Comment by genadis** [comment]
I'm familiar with #50 <https://github.com/aurelia/framework/issues/50>.

Don't see the similarity/relevance.

**Comment by smolinari** [comment]
The relevance is about wanting to have components/ widgets, which '50 turned out to be more about. Look at Zoltu's comment a few posts down.

> the ability to build widgets/components that work in isolation is critical

Scott

**Comment by genadis** [comment]
I see your point,
But still '50 is more about isolating styles, and doesn't mention number of
aurelia applications
I wanted to focus on nested aurelia applications (not views/custom
elements), which has more to do with bootstrappint, templating, etc

Thanks,
Genadi

**Comment by EisenbergEffect** [comment]
To create an app boundary, simply create a custom element, using `@noView` and `@processContent(false)`. Wrap that around anything you want the compiler to ignore. If you want to have an Aurelia app inside another Aurelia app, that's no problem. You can just instantiate a new Aurelia, pass it the existing loader and a new container instance, and you are good to go. For an example of this, check out the app-documentation repo where we are building our documentation app. We have a custom element named "demo" that allows us to run Aurelia demos inline inside the doc. It creates an isolated Aurelia app for each demo.

**Comment by genadis** [comment]
@EisenbergEffect the [app-documentation](https://github.com/aurelia/app-documentation) repo is down.
Was it moved?
Thanks

**Comment by EisenbergEffect** [comment]
The source for the docs app is longer publicly available.

**Comment by BruceL33t** [comment]
I'd be interested to see an example on this. How to have an Aurelia app inside another Aurelia app.

**Comment by EisenbergEffect** [comment]
Something like this should create a custom element capable of creating child app instances.

child-app.js
```
import {Aurelia from 'aurelia-framework';
import {inject, Container} from 'aurelia-dependency-injection';
import {Loader} from 'aurelia-loader';

@inject(Loader)
export class ChildApp {
  @bindable main;
  
  constructor(loader) {
    this.app = new Aurelia(this.loader, new Container());
    this.app.use.standardConfiguration();
  }

  mainChanged() {
    this.app.start().then(a => a.setRoot(this.main, this.host));
  }
}
```

child-app.html
```
<template>
  <div ref="host">Loading...</div>
</template>
```

**Comment by BruceL33t** [comment]
Thanks a lot Rob.

It works somewhat, however if for example we take the aurelia navigation skeleton as the child application, whenever we click the routes in the navigation, it not only changes inside the  custom element - it also changes in the browser url (the main application). How would we contain actions and links clicked inside the custom element, so the main app won't react on it?

**Comment by EisenbergEffect** [comment]
That's going to be very complicated if possible to handle the routing in both cases.

**Comment by BruceL33t** [comment]
I guess iframes is the way to go the, for child applications then - which also seems to work fine! :-)

**Comment by millicandavid** [comment]
@BruceL33t Can you share your working example based on Rob's suggestion? I have need to do something like this and can't get my mind around how this would work. What I'm trying to do is setup a navigation shell app(or portal) that would display children apps in a content area. The goal is to enable separation of source for the children apps and to be able to deploy them independently. I have seen no examples of doing this but this seems like it would be a common scenario.  

Thanks.

**Comment by vedaantees** [comment]
Correcting typos in Rob's code
```

import { Aurelia, customElement, bindable} from "aurelia-framework";
import { inject, Container } from "aurelia-dependency-injection";
import { Loader } from "aurelia-loader";

@inject(Loader)
@customElement("portlet")
export class Portlet
{
    @bindable
    main;
    app: Aurelia;

    constructor(loader)
    {
        this.app = new Aurelia(loader, new Container());
        this.app.use.standardConfiguration();
    }

    mainChanged() 
    {
        this.app.start().then(a => a.setRoot(this.main, document.getElementById("portlet-host")));
    }
}
```

**Comment by vedaantees** [comment]
```
<template>
    <div id="portlet-host" ref="host">Loading...</div>
</template>
```

**Comment by sebb3** [comment]
@millicandavid I'm trying to achieve the same thing you described two years ago, "The goal is to enable separation of source for the children apps and to be able to deploy them independently."

Did you get that work?

**Comment by millicandavid** [comment]
I don't think I did. I think ended up having to compromise my design a bit IIRC but that was a long time ago now and I don't get to work on Aurelia professionally anymore. :(
