### ISSUE TITLE
Question: Will the removal of O.o have any impact on Aurelias roadmap?

### ISSUE THREAD

**Issue by pkkummermo** [aurelia/framework#237]
Ref: https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html

**Comment by EisenbergEffect** [comment]
No. We've always had a fallback implementation. It's what we used in all non-Chrome browsers. Believe it or not, our fallback actually performed better than native O.o. So, the only result of this is that we will remove some code from our binding engine in the future. Nothing will change for developers.

It is a shame this isn't being continued. I think the community champion just lost interest. We may pursue whether or not someone else can take it up and see it through.

**Comment by pkkummermo** [comment]
Thanks for the quick and concise answer :)

**Comment by EisenbergEffect** [comment]
You're welcome!

**Comment by nomack84** [comment]
@EisenbergEffect can't you be our champion? You are a recognized and famous developer and you'll have a lot of support from Aurelia's community developers.. I'd vote on you without hesitation. :v:

**Comment by StrahilKazlachev** [comment]
I thought that only a TC39 member can be a champion.

**Comment by EisenbergEffect** [comment]
Yes, "Champion" is somewhat of an official title and requires membership in TC39....which requires a bucket load of cash, last I checked.

**Comment by musicformellons** [comment]
There is currently a vacancy for Vice-Chairman.
