### ISSUE TITLE
Aurelia and computed properties

### ISSUE THREAD

**Issue by kjeske** [aurelia/framework#238]
I've just started looking at AureliaJS, so I created a sample app described here: http://aurelia.io/get-started.html. I've noticed a strange behavior.

In the example we have:

```js
get fullName(){
    return `${this.firstName} ${this.lastName}`;
}
```
But when I put a logging there:

```js
get fullName(){
    console.log('test');
    return `${this.firstName} ${this.lastName}`;
}
```
The app will start logging infinitely the 'test' value. Have you experienced the same results or this is just my machine and I'm doing something wrong here?

**Comment by atsu85** [comment]
Hi, see the sample in aurelia documentation:
http://aurelia.io/docs.html#adaptive-binding
```JavaScript
  @computedFrom('firstName', 'lastName')
  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }
```

Another alternative of adding `@computedFrom(..)` is to use aurelia-computed plugin:
http://eisenbergeffect.bluespire.com/aurelia-computed/ 
that works on AST analysis. But the down side with aurelia-computed is that it won't understand complex expressions so sometimes You still have to manually add `@computedFrom(..)`

**Comment by kjeske** [comment]
I see, so I experienced the dirty-checking here. Thank you for the explanation.
