### ISSUE TITLE
Plugin configuration

### ISSUE THREAD

**Issue by genadis** [aurelia/framework#239]
In the [documentation](http://aurelia.io/docs.html#plugins) mentioned that we can specify a function or object as the second argument to the configure function.
Meaning that if user does something like:
```
aurelia.use.plugin('plugin-name', config => { 
  /* configuration work on config: PluginConfigurationObject */
 });
```
The plugin receives the callback function in it's configure:
```
// index.js
export function configure(aurelia, configCallback) {
  /* .... */
   configCallback(PluginConfigurationObject);
}
```
In reference to @ahmedshuhel note on bundling best practice in [bundler #30](https://github.com/aurelia/bundler/issues/30),
What is the best practice to pass the PluginConfigurationObject to the plugin itself without importing it in index.js?

Should we export the PluginConfigurationObject?

Thanks in advance,

**Comment by EisenbergEffect** [comment]
You only need to export it if you want that type to be accessible directly by importing your module. The bundling config in the post will make sure the file is picked up with or without that.

**Comment by genadis** [comment]
The question wasn't related to bundling directly, just seemed relevant mentioning.

What is the best practice to pass the configuration to the plugin itself having `index.js` which has access through second configure() parameter:
```
export function configure(aurelia, configCallback) {
  /* .... */
   configCallback(PluginConfigurationObject);
   config.globalResources('./myplugin');
}
```
 and `myplugin.js` which is the actual plugin (customAttribute).

1. Export PluginConfigurationObject, and import in `myplugin.js` ?
2. Some other way supported by the framework ?

>**Note**: I'm aware of the ability to have multiple properties for customAttribute.

**Comment by genadis** [comment]
I've noticed that the `config:any` object eventually reaches `loadPlugin()` wrapped in `info` and passed to the plugins `configure`.
But that's it.

I would expect some way to inject it in the plugin resources (i.e. into `myplugin.js`), otherwise I'm not sure I see the point in having it in the first place.

**Comment by EisenbergEffect** [comment]
I'm not following you here. The config object or function allows the end-user of your plugin to pass your plugin configuration that it can use to set itself up.

**Comment by genadis** [comment]
As I understand usually the plugin has 2 parts:
1. index.js - contains the `configure()` and calls `globalResources()`.
2. the resources, which contain the plugin implementation itself.

The config object only reaches the first part: `index.js`, which usually doesn't contain any logic and does not has access to the second part, the resources (unless we import them or export config object from `index.js`). What usage of config object do we have in index.js?

Usually I would like to configure the second part: the resources (`myplugin.js`).

Consider the following:

```
// index.js

export function configure(aurelia, configObject) {
  /* .... */
   config.globalResources('./myplugin');
}
```
```
// myplugin.js

import {inject, customAttribute} from 'aurelia-framework';

@customAttribute('my-attribute')
export class MyAttribute{
  constructor()  {
     /********* Usually I would need the configObject here ************/
  }
}
```

Thanks again!

**Comment by EisenbergEffect** [comment]
If you want to pass the config object along to your behaviors, all you need to so is set that up in your plugin's configure method. Here's what you would do:

```
// index.js

export function configure(aurelia, configObject) {
   config.registerInstance(ConfigType, configObject);
   config.globalResources('./myplugin');
}

// myplugin.js

import {inject, customAttribute} from 'aurelia-framework';

@customAttribute('my-attribute')
@inject(ConfigType)
export class MyAttribute{
  constructor(configObject)  {
    //use the configObject as you see fit
  }
}

```

**Comment by genadis** [comment]
Thanks!

I've seen number of plugins, and the once that make use of the config object.
explicitly import the resource (`myplugin.js`) in `index.js` and pass it the config object, and export the resource.

I had the feeling that there had to be a better way...
