### ISSUE TITLE
Aurelia repeat.for throws exception on emptied list

### ISSUE THREAD

**Issue by asemahle** [aurelia/framework#240]
I've recently updated to the [Aurelia Pre-Beta Release](http://blog.durandal.io/2015/11/10/aurelia-pre-beta-release/) and have run into a problem with `repeat.for` on a list.

Essentially, if `repeat.for` is iterating a list, and that list is spliced down to an empty list, then Aurelia throws the following error:
```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
    getAnimatableElement @ aurelia-templating.js:1096
    removeAt @ aurelia-templating.js:1247
    handleChanges @ array-collection-strategy.js:50
    handleCollectionChanges @ repeat.js:172
    call @ repeat.js:62
    callSubscribers @ aurelia-binding.js:219
    call @ aurelia-binding.js:701
    flushMicroTaskQueue @ aurelia-task-queue.js:110
    (anonymous function) @ aurelia-task-queue.js:60
````

I've constructed a view-model that demonstrates this bug. Model Code (`test.ts`):
```javascript
export class Test {
    list: any = [];
    constructor(){  }
    add(){
        this.list.push("ITEM");
    }
    remove(){
        if (this.list.length > 0){
            this.list.splice(0, 1);
        }
    }
}
```
View Code (`test.html`):
```html
<template>
    <button click.delegate="add()">Add</button>
    <button click.delegate="remove()">Remove</button>
    <br>The list contains:
    <div repeat.for="element of list">---- ${element}</div>
</template>
```

The error does not occur if the list is popped down to empty (using `pop()`), or if it is reassigned to a new empty list.

**Comment by EisenbergEffect** [comment]
@martingust Is this the same issue you just PRed? I can get that release out in the next hour.

**Comment by spi-ap** [comment]
@EisenbergEffect @martingust I am pretty sure it is. I created the referenced issue ( aurlia/templating#147 ) with the exact same scenario)

**Comment by asemahle** [comment]
aurelia/templating#147 looks like the same scenario. It looks like martingust's change will fix it. Thanks for the quick response, you guys are great (and Aurelia is too)!

**Comment by EisenbergEffect** [comment]
Ok, will close this out. We will get the patch release with Martin's fix out with an hour or so.
