### ISSUE TITLE
Issue with core-js

### ISSUE THREAD

**Issue by glen-84** [aurelia/framework#241]
SystemJS tries to load `/core-js.js` for some reason.

Test repo: https://github.com/glen-84/aurelia-corejs-bug

Instructions are included for re-creating the project. Install with the usual npm install/jspm install.

The only reason that it usually works is because most people select babel as transpiler when initializing JSPM, which installs core-js.

core-js is loaded correctly initially, but then a request is made to `/core-js.js` which obviously 404s.

This should not happen, right?

**Comment by mattgaspar** [comment]
I've run into this too.  Using Visual Studio/Typescript.  core-js gets loading as a dependency of several packages but I always manually add an entry to the top level packages in config.js otherwise the url doesn't get resolved correctly as described above.

**Comment by rgripper** [comment]
I went with Typescript as transpiler, same thing - `/core-js.js` is 404.

**Comment by jdanyow** [comment]
closing- Aurelia no longer has a dependency on core-js

**Comment by glen-84** [comment]
Thanks Jeremy.
