### ISSUE TITLE
Router populated "late"

### ISSUE THREAD

**Issue by LivesleyWA** [aurelia/framework#247]
I have an application modeled on the introductory application - i.e. it has a router with an attached navbar custom element. This worked until the beta release. After that release, the navabar component ceased to populate the information derived from *router.navigation* object (although the rest of the HTML from the custom element was displayed) until I added a flag into the custom element html as shown below.

```
<ul class="nav navbar-nav" if.bind="router.isNavigating !== true">
        <li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
          <a href.bind="row.href">${row.title}</a>
        </li>
</ul>
```

This suggests to me that the navigation custom element is getting populated on the page before the router is fully populated. 

Here is my router code.

```
public configureRouter(configuration: RouterConfiguration, router: Router): Promise<RouterConfiguration> {
    this.router = router;

    return System.import("../../../../../package.json!").then((pckg: { version: string; }): Promise<any> => {
      configuration.title = `xxx [${pckg.version}]`;
      configuration.options = {
        shortTitle: "xxx"
      };
      configuration.map([{
        redirect: "reports",
        route: ""
      }, {
          moduleId: "./reports/reports-router",
          name: "reports",
          nav: true,
          route: "reports",
          title: "Reports"
        }, {
          moduleId: "./settings/settings-router",
          name: "settings",
          nav: true,
          route: "settings",
          title: "Settings"
        }]);
      return Promise.resolve();
    }).then((): Promise<IReportsPortalApplicationSession> => {
      return this.session.initializeSession("/source/json/web-applications/reports-portal/configuration.json");
    }).then((): Promise<RouterConfiguration> => {
      return Promise.resolve(configuration);
    });
  }
```

FWIW I have child routers which continue to work without any change. It appears to be the initial router which has this issue.

I haven't run through the latest introductory application so I assume it isn't showing this issue although I can't see any difference between my code and the introductory application code.

**Comment by EisenbergEffect** [comment]
Bear in mind, it cannot produce a nav model until after the router is configured. Since your configuraiton is async, it does need to wait until you provide the configuration.

**Comment by LivesleyWA** [comment]
Is the solution I am using what you would suggest or do you suggest an alternative?
