### ISSUE TITLE
HierarchyRequestError IE 10

### ISSUE THREAD

**Issue by ofuentes15** [aurelia/framework#248]
I have an error on IE 10, using the beta version.

It is when I have a repeat.for inside another repeat.for

Example:
li repeat.for="game of Games"
				div class='pattern'
					ul
						li repeat.for='pattern of game.Pattern' class="${pattern.Highlighted? 'Highlighted': ''}"

**Comment by jdanyow** [comment]
Not enough information.  Please try your question in the [main gitter](https://gitter.im/Aurelia/Discuss).  If you don't get a resolution create an issue here with the full exception details (message, stack trace, etc), along with your view and view-model code.
