### ISSUE TITLE
Gulp prepare-release task on windows uses first commit instead of last semver tag

### ISSUE THREAD

**Issue by MarcScheib** [aurelia/framework#249]
Executing the prepare-release on Windows adds up all commits from the first tag to HEAD for each prepare-release. This is an issue with how tags are fetched (see https://github.com/ajoslin/conventional-changelog/issues/25). 

Updating to 0.0.13 however does not solve this issue. At least version 0.0.15 is needed.

I was not able to test it on Linux by now. 

One remark: this version adds a `<a name="VERSION"/>`. This seems to be very common.

**Comment by doktordirk** [comment]
darn, took me some time to find that bug myself. please fix this before more people waste hours on that. 
(i guess last 0.0.x namely 0.0.17 would be recommended)

**Comment by RWOverdijk** [comment]
:+1:

**Comment by EisenbergEffect** [comment]
Fixes in progress across repos.
