### ISSUE TITLE
Map.set() and Map.delete() produce TypeError in aurelia-task-queue

### ISSUE THREAD

**Issue by nnscr** [aurelia/framework#251]
Hey,

first off: thanks for your great work, Aurelia is really lovely!

I think I've found a bug in the current beta regarding Maps throwing this error:
TypeError: Cannot read property 'firstChild' of undefined in aurelia-task-queue.js:40

If you bind a map like this:
```html
<li repeat.for="[k, v] of map">
  ${k}: ${v}
</li>
```
You can add elements using `set()`, which works the first time. If the key already exists, an error is thrown. The same error is thrown when you call `delete()`. `clear()` works as expected.

I have prepared a Plunker where you can see what I mean. The issue did not occur in earlier versions (tested on 0.19, don't know about others). Version `1.0.0-beta.1.0.1` and `1.0.0-beta.1.0.2` are both affected.

http://plnkr.co/edit/a3LGHJ0Llvh3e8JLdpRp?p=preview

**Comment by EisenbergEffect** [comment]
@martingust Do you have time to look into this? I've seen this issue reported a few times now I think.

**Comment by jdanyow** [comment]
These are the dupes:
https://github.com/aurelia/templating-binding/issues/70
https://github.com/aurelia/binding/issues/239

**Comment by martingust** [comment]
@EisenbergEffect Will do.

**Comment by martingust** [comment]
@jdanyow Already fixed this in https://github.com/aurelia/templating-resources/commit/7f245ce3b490fa82cae20103281b665a07cf3eb2. It's in master.

**Comment by RobertTheGrey** [comment]
Just ran into this same error myself (but only in IE10 - emulated) when removing a bound item from one array to another. Both collections bound in the view (basically drag and drop action). I have made the changes locally mentioned in  aurelia/templating-resources@7f245ce and debugged to confirm the change was there, but the line of code is never hit and the error still happens. In IE9 (emulated) the behavior is the same, but no console error. IE11 works fine. The error I'm seeing in IE10 looks like this:

![image](https://cloud.githubusercontent.com/assets/152037/11399899/0bf24c5e-9382-11e5-9658-ffce35f00b52.png)

**Comment by martingust** [comment]
@RobertTheGrey Ok, will check in IE9/10 what is going on. Thanks.

**Comment by martingust** [comment]
@RobertTheGrey 

I just tested in IE9/10 emulator mode. And it is working for me using this set up:

```javascript
export class Welcome {
  items = new Map([[1, 'Foo'], [2, 'Bar'], [3, 'Baz']]);

  delete(key) {
    this.items.delete(key);
  }

  set(){
    this.items.set(1, 'Martin2');
  }
}
```

```html
<template>
  <div repeat.for="[key, value] of items">
      ${key} ${value} <button click.delegate="delete(key)">Delete</button>
  </div>
  <button click.delegate="set()">Set</button>
</template>
```

**Comment by RobertTheGrey** [comment]
Ah ok, thanks @martingust - I've confirmed that this is works on `Map` for me as well. Apologies for the confusion, in my case it is happening when splicing and pushing to arrays. I will try to replicate the issue in a plunkr and raise a new issue from there
