### ISSUE TITLE
changing url with the same controller (module) not call unbind.

### ISSUE THREAD

**Issue by vanluke** [aurelia/framework#252]
i am reusing model-view to two different state and i need to reload data but unbind and other events are not called, so i am unable to reuse model-view if it is already loaded

**Comment by StrahilKazlachev** [comment]
Does you model have `determineActivationStrategy()`? If not check the [docs cheetsheet - Reusing an existing VM](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.2/doc/article/cheat-sheet).

**Comment by EisenbergEffect** [comment]
Please seek assistance in the Gitter channel if still needed.
