### ISSUE TITLE
globalResources fails when plugin output is concatenated

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/framework#255]
We are trying to enable dts-generation in [this plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin), which means it needs to concatenate the output on build. Fyi, we are calling globalResources in the `configure` method of the plugin. This works fine when the output is not concatenated into a single file, but when it is, we get 404 for these calls to globalResources.

![image](https://cloud.githubusercontent.com/assets/2189477/11456458/f3b9cf6c-9689-11e5-9c7b-13d39f3bd15d.png)

What is the best approach for this?

**Comment by JeroenVinke** [comment]
I believe you will have the same issue if you would try to implement dts generation in [ui-virtualization](https://github.com/aurelia/ui-virtualization/blob/master/src/index.js#L5-L8), [aurelia-validation](https://github.com/aurelia/validation/blob/master/src/index.js#L17), [aurelia-i18n](https://github.com/aurelia/i18n/blob/f279f0d8f343eb1ada346d7dcfb6ddeaaeb7a17c/src/aurelia-i18n.js#L23-L26)

**Comment by EisenbergEffect** [comment]
A plugin which contains view resources, should not be concatenated. The concatenation "destroys" the module ids that are referenced by the call to `globalResources`. A plugin like this should be distributed as "loose" module files which can then be bundled by the bundler, which will preserve the individual module ids.

**Comment by JeroenVinke** [comment]
That makes sense.

I have tried generating a d.ts file a plugin without concatenating before, and I ran into multiple errors. Is this a use-case you support?  If so, I would consider to try this again, reporting any problems I encounter in the process.

**Comment by jdanyow** [comment]
@JeroenVinke checkout the `templating-resources` repo- it's distributed the way @EisenbergEffect described above and has d.ts generation.

**Comment by JeroenVinke** [comment]
@jdanyow thanks for pointing me there! I will try this out :)
