### ISSUE TITLE
require'ing / importing self exectuting function scripts happening before template has loaded

### ISSUE THREAD

**Issue by davidbfrogman** [aurelia/framework#259]
Question:  I've 
```
jspm install smoothscroll
```
which is just some js code that will look through the document, find any anchor tags and add another click event to them to smooth scroll them.
then I require it in my vm like
```
import 'smoothscroll';
```
link to the actual code here: https://github.com/alicelieutier/smoothScroll/blob/master/smoothscroll.js

the problem is that this package, like many packages I can think of is expecting to be loaded at the bottom of the document.  Because it's a self executing anonymous function it's expecting to be loaded at the bottom of the html, and by then the things that it want to work on are there.  Problem is that in aurelia it's loading this script before it loads the template.

So I edited the code for smooth scroll with some console.logs to show that it is in fact loading, and executing it, it's happening before the view has been loaded, so it has nothing to operate on.  
![Chrome Dev](http://puu.sh/lErRw/3f88ba1dff.png)
(the view I want to use it in is contact.html)

So the question is, how can I require/import/load js like this that the bottom of my document?
As far as I can tell my options are:
1. Extract the code into a class 'smoothscroll', and call a method on that class from the attached method inside my view model.  Which seems pretty hacky and dumb
2. Do something like I already did for google maps, and gmaps integration
```javascript
    loadGoogleMap(){
        $.loadScript('https://maps.googleapis.com/maps/api/js', function () {
            $.loadScript('jspm_packages/npm/gmaps@0.4.21/gmaps.js', function () {
                var mapLocation = new google.maps.LatLng(39.703097, -105.137289, 878);

                var $mapis = $('#map');
```
Which also seems hacky and dumb

I'm really at a loss here, and any help would be greatly appreciated.

**Comment by PWKad** [comment]
Your document is dynamic which means you probably need to refresh the links.  I would move this in to a `CustomAttribute` and call the method mentioned here - 

```
window.smoothScroll(target, duration, callback, context)
```

from the docs with `target` being set to the `element` and the other options are optional.

Then you would just use the `smooth-scroll="true"` or w/e custom attribute on your DOM element and not have to worry about timing.

**Comment by davidbfrogman** [comment]
Is there no better way to include these styles of scripts?  For instance I know for sure I'm going to want to use masonry, and isotope in my app, and I know that those scripts are meant to be loaded when the document is ready.  It seems goofy to have to create custom attributes for all these styles of scripts.

Does aurelia not have a way to say you want this script included at the end of the template, or after the template has been rendered?

(also keep in mind, I only barely know what I'm doing when it comes to javascript)
(also thank you for helping I really appreciate it)

**Comment by PWKad** [comment]
Aurelia provides the `attached` method so you can initialize your scripts like Masonry mentions [here](http://masonry.desandro.com/#initialize-with-vanilla-javascript) 

Using a script that needs to be loaded after document ready doesn't make as much sense because the document changes dynamically via the router and user interaction in most apps, so you would have to continue to load or initialize the script, or add them in if you can't do that.

The library that you are referencing doesn't let you do this because it doesn't provide an API for initializing that I can tell from the README.md of it.

**Comment by davidbfrogman** [comment]
Super helpful answer.  That makes more sense. 

Given that... can you see a better way to load my google maps javascript? 

You can see the full code to what I'm doing currently here:
https://github.com/davidbfrogman/DBPAurelia/blob/master/src/contact.js

You can see that basically I'm loading the 2 scripts that I need to get my map to work in the attached method.  google-maps, and gmaps the second making it easier to work with google maps.

But that second one is again a self executing anonymous function that is looking for google to be loaded on the window.

**Comment by davidbfrogman** [comment]
https://www.npmjs.com/package/google-maps

https://www.npmjs.com/package/gmaps

**Comment by Thanood** [comment]
I've tried the following:
Import smoothScroll like this:

```javascript
import smoothScroll from 'smoothscroll';
```

In your contact.js attached() method, uncomment the event binding to linkHandler you already have. Then add linkHandler as a function.

It's not the most elegant solution but it works for me..

```javascript
attached() {
        function linkHandler(event) {
            event.preventDefault();
            let target = document.querySelector(event.target.getAttribute('href'));
            smoothScroll(target);
        }
    //    $('#contact-response').hide();   
        console.log('were inside the dom content loaded event');
        var internal = document.querySelectorAll('a[href^="#"]:not([href="#"])'), a;
        for (var i = internal.length; a = internal[--i];) {
            console.log('We have some links were going to smooth scroll');
            console.log(a);
            a.addEventListener("click", linkHandler, false);
        }
       
       this.loadGoogleMap(); 
    }
```

**Comment by PWKad** [comment]
@EisenbergEffect As this is about using a specific integration with another lib and a few good explanations of how to use have been given I think we can close this one out.

Please direct any other questions that aren't issues about the framework to our official gitter channel @ http://gitter.im/aurelia
