### ISSUE TITLE
Windows/NTFS - Path to long

### ISSUE THREAD

**Issue by Stoggy** [aurelia/framework#26]
Following the "Get Started" guide, using the example [package.json](https://raw.githubusercontent.com/aurelia/skeleton-navigation/master/package.json) file, npm creates a directory structure which seems to big for Windows/NTFS filesystem to handle.

Example:
>D:\aureliatest\node_modules\conventional-changelog\node_modules\lodash.assign\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\node_modules\lodash._basecreatewrapper\node_modules\lodash._basecreate\...

**Comment by mantzas** [comment]
+1 trying to delete the folder was a pain.

**Comment by EisenbergEffect** [comment]
This is related to how NodeJS handles packages and creates its directory structure. There's really nothing we can do about it. I would consider brining this issue up with the NodeJS/NPM teams.

**Comment by gep13** [comment]
We recently ran into the same problem with an un-related node project.  We had to use the rimraf node module (https://github.com/isaacs/rimraf) to help with the deletion of the node_modules folder.  We sometimes have to drill into the folder hierarchy and run rimraf a couple times, but you can get rid of the folders, eventually.

**Comment by Stoggy** [comment]
@EisenbergEffect Regardless if it's a NodeJS/NPM issue or not, it should be possible to finish the Get Started guide successfully, even for windows users.
As far as i can see, the current issue boils down to the package "conventional-changelog"
Maybe there's an alternative for this package?

**Comment by EisenbergEffect** [comment]
I'm not clear how working through the get-started tutorial involves deleting node packages. But regardless, this is not a bug in Aurelia or even the 3rd party gulp plugins. It's an issue with NodeJS on Windows and you will encounter it on various projects on Windows when trying to delete packages.

I'm open to alternatives for Windows users, in order to improve this, but I don't know of any at the moment. NodeJS is the de facto standard and really the only technology for doing this sort of work and Microsoft isn't building any alternatives...in fact they are embracing it with the next VS release. Maybe it's worth asking them to implement an advanced delete feature in VS?

**Comment by jedd-ahyoung** [comment]
This is a bug with the Windows API, not an NPM bug. Windows support
260-char-length paths, maximum, regardless of the underlying file system.
It hasn't changed for years.

If you need to remove files, you might try working from Windows Powershell
and using short paths.

**Comment by mantzas** [comment]
or you could shorten the length by copying a child higher up the hieracrchy in order to create shorter paths. that worked for me

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.assign@3.0.0
├─┬ lodash._baseassign@3.0.1
│ ├── lodash._basecopy@3.0.0
│ └─┬ lodash.keys@3.0.3
│   ├── lodash.isarguments@3.0.0
│   ├── lodash.isarray@3.0.0
│   └── lodash.isnative@3.0.0
└─┬ lodash._createassigner@3.0.0
  ├── lodash._bindcallback@3.0.0
  └── lodash._isiterateecall@3.0.1
```

There's even a simplified form:
```
lodash._baseassign@3.0.1
├── lodash._basecopy@3.0.0
└─┬ lodash.keys@3.0.3
  ├── lodash.isarguments@3.0.0
  ├── lodash.isarray@3.0.0
  └── lodash.isnative@3.0.0
```
