### ISSUE TITLE
ValueConverter is not notified if a property of its argument changes

### ISSUE THREAD

**Issue by Nepoxx** [aurelia/framework#260]
```html
<input type="text" value.bind="search.firstName">
<input type="text" value.bind="search.lastName">
<div repeat.for="user of users | filter: search"> <!-- never updates -->
<div repeat.for="user of users | filter: search.firstName"> <!-- updates whenever search.firstName changes, as expected -->
```

In the above example, the `filter` value converter will not be called if a property of the search object changes. Is this expected behaviour?

**Comment by jdanyow** [comment]
This is the expected behavior. Aurelia does not eagerly observe object properties. It would be quite expensive to do so, especially now that Object.observe is no longer being pursued in TC39.

**Comment by Nepoxx** [comment]
Thank you for the response.

Any viable workaround? I want to filter an array of objects on multiple properties.

**Comment by nomack84** [comment]
@Nepoxx you can use the `signable` behavior I think

**Comment by dpinart** [comment]
@Nepoxx I neve used signable behavior and don't know about it. There several options like using computedFrom behavior from binding plugin. You should have the properties defined in the view model and another property decorated with computedFrom like
</code>
``` javascript
firstName;
secondName
@computedFrom('firstName', 'secondName')
get search(){
 return {firstname: this.firstName, secondName: this.secondName}
}
````
</code>

**Comment by jdanyow** [comment]
@Nepoxx include the properties in the expression, even if the converter doesn't use the arguments directly:

```js
<div repeat.for="user of users | filter: search.firstName:search.lastName:search.ssn">
```

Consider using the [debounce](http://www.danyow.net/aurelia-binding-behaviors/) binding behavior to avoid searching on every keystroke.

```js
<div repeat.for="user of users | filter: search.firstName & debounce">
```

**Comment by Nepoxx** [comment]
Thanks for the suggestions!
