### ISSUE TITLE
processContent is called after <require> has been processed and removed

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/framework#262]
I made the following custom element: [au-code](https://github.com/JeroenVinke/aurelia-prism-plugin/blob/master/src/au-code.js), which highlights any type of code using PrismJS.

which is used like this:

```
  <au-code language="markup">
<require from="kendo-ui/styles/kendo.common.core.min.css"></require>
<require from="kendo-ui/styles/kendo.bootstrap.min.css"></require>
  </au-code>
```

however, I believe that `<require>` tags are evaluated and executed by Aurelia before @processContent is called. This is causing the [element.innerHTML](https://github.com/JeroenVinke/aurelia-prism-plugin/blob/master/src/au-code.js#L30) to be empty, which I need to highlight from. The custom element is working for any other HTML or javascript code, but it fails with `<require>` tags. We need this for the installation instructions for aurelia-kendoui-plugin

**Comment by EisenbergEffect** [comment]
`require` elements are processed before compilation. That cannot change because it's not possible to compile without the information/implementations provided by evaluating the view's requiremenets.

The code could be improved to only find require elements at the top of the view though. If you want to make a PR to improve that, see here: https://github.com/aurelia/loader/blob/master/src/template-registry-entry.js#L65

**Comment by JeroenVinke** [comment]
In some rather large views I have, I use <require> at different places, not necessarily at the top, for example just before I use a custom element. Would it be better to have a flag that tells <require> not do anything?

**Comment by EisenbergEffect** [comment]
The `require` element is synonymous to the `import` from ES6 in Aurelia. So, we can't just "not do anything". They *should* be placed at the top of the view, so the only thing we could do is enforce that.

**Comment by JeroenVinke** [comment]
Roger. Should I create an issue in the `loader` repository? I don't feel confident enough to create a PR myself, as this could break a lot of things. Also, since I needed this for only two lines of code, I decided not to have code highlighting for these lines. This issue can be closed.
