### ISSUE TITLE
Character encoding 

### ISSUE THREAD

**Issue by seiftie** [aurelia/framework#265]
When I'm trying to add a special character (ë) on my page, it'll show me the question-mark-error (encoding problem). The thing is, my page has the <meta charset="UTF-8">, but it doesn't seem to convert. 

Example: 'Pati�nt' should be 'Patiënt'
Meta in index page has charset="UTF-8" in it, so normally it should encode, but it doesn't. 

Could this perhaps have anything to do with Aurelia?

**Comment by zewa666** [comment]
check whether the file itself is saved in utf-8 format

**Comment by seiftie** [comment]
You're right. Visual Studio automatically saved the file as Western European instead of UTF-8. Thanks!
