### ISSUE TITLE
Suggestion: Check interpolation / binding in HTML templates with TypeScript

### ISSUE THREAD

**Issue by Gambero81** [aurelia/framework#268]
It will be a killer feature to use TypeScript in Aurelia to check the interpolation / binding in HTML templates.
There are no other framework with this feature!!

See same request for Angular: 
http://stackoverflow.com/questions/25140029/use-typescript-in-angularjs-to-check-the-interpolation-binding-in-html

**Comment by EisenbergEffect** [comment]
Yes, we've been thinking of this for a while. There are two things we would like to do:

* Add an optional build  step to check view/view-model pairs. We would probably have this work similar to a linter.
* Integrate with code editors to provide intellisense inside HTML for a view model. This has to be implemented for each code editor separately, so it's more complicated. But I would like to at least have it for VS Code and Atom.

Both of these are things we would like to have not only for TS but for EcmaScript as well. It's a lot of work so this probably won't make v1. But we aren't stopping with v1. We have lots of plans to enhance the framework and tooling continually.

**Comment by atsu85** [comment]
@EisenbergEffect 
> Integrate with code editors to provide intellisense inside HTML for a view model.

tern.js (and tern.java if writing plugin in java, for example for Eclipse or IDEA / WebStorm) might be worth looking into, to get content assist in html template for view model properties/methods. @angelozerr has used tern.java to implement Eclipse plugin for AngularJS that does the job quite well (see the screenshots https://github.com/angelozerr/angularjs-eclipse)

**Comment by EisenbergEffect** [comment]
We've got a community project that is already making progress in this space. Closing this issue since it's being tracked elsewhere.

**Comment by angelozerr** [comment]
@EisenbergEffect I'm waiting for this great feature for Angular2 to integrate it inside [Angular2 Eclipse](https://github.com/angelozerr/angular2-eclipse/wiki/Getting-Started)

If I have well understood, we need to wait for the issue https://github.com/Microsoft/TypeScript/issues/6508 to extend completion, validation, etc and develop plugin kind (for tsserver) to support any language like Angular2 interpolation.

Is it that? If you have some links about project which does that, could you tell me please, thanks!

**Comment by EisenbergEffect** [comment]
Why are you talking about Angular 2?

**Comment by arfilon** [comment]
> EisenbergEffect commented on Jul 4, 2016
> We've got a community project that is already making progress in this space. Closing this issue since it's being tracked elsewhere.

Hello
what is the project link?

thanks

**Comment by atsu85** [comment]
The project @EisenbergEffect referred to is https://github.com/MeirionHughes/aurelia-template-lint
