### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by Aaike** [aurelia/framework#27]
What browsers is Aurelia targeting ? is it IE9+ ?
couldn't seem to find anything on browser support in the docs

**Comment by miroslavpopovic** [comment]
From [Introducing Aurelia](http://blog.durandal.io/2015/01/26/introducing-aurelia/) post:

> Aurelia targets [Evergreen Browsers](http://eisenbergeffect.bluespire.com/evergreen-browsers/) only. However, some of our early adopters have reported that things appear to be working even on IE9...

Basically, this means any modern browser with automatic updates (Chrome, Firefox, Safari...), including IE10+.

P.S. A better place to ask this kind of question would be on [Aurelia's Gitter](https://gitter.im/Aurelia/Discuss#) channel.

**Comment by Aaike** [comment]
thank you, will try the gitter next time :)

**Comment by stevanuz** [comment]
I believe that Aurelia.io is developed with the framework. However, it does not work on IE11? If you got to this page http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start , the left panel will always be empty.
![aurelia_ie11](https://cloud.githubusercontent.com/assets/16387544/20622527/6ee1dba4-b357-11e6-9f22-b21222b56d30.png)

**Comment by atsu85** [comment]
Maybe missing polyfill? Maybe request animation frame?
![image](https://cloud.githubusercontent.com/assets/1206512/20631720/dd1f71e2-b340-11e6-939f-ca6e54ea6988.png)

**Comment by stevanuz** [comment]
Okay, so the Aurelia framework does not by default support IE11? Or at least the Aurelia hub should patch the polyfill if is required for IE11 so that it's browsable since IE11 is a pretty much modern browser.

**Comment by nenadvicentic** [comment]
Does not work indeed.

**Comment by paolocarrasco** [comment]
The Aurelia problem is with the navigation bar, the bad-styling in the notes section is not an Aurelia issue but CSS.

**Comment by AshleyGrant** [comment]
@paolocarrasco please create a new issue to report this display bug in our docs app. The issue you are responding to was a question of what browsers Aurelia supports. We support IE9+ and the current versions of all other browsers, as they are "Evergreen" (constantly kept updated).
