### ISSUE TITLE
Is Aurelia for mobile?

### ISSUE THREAD

**Issue by mikefills** [aurelia/framework#273]
Is Aurelia a good choice for mobile, I'm thinking for web-browsers which make sense based on market share (Safari 8+, Chrome for Android) ?
Compatibility and performance on these web-browsers are very important.
Is Aurelia team actively running tests on these web-browsers?
Thanks!

**Comment by EisenbergEffect** [comment]
Yes.
But, this isn't the place for questions. Ask those on gitter please.
