### ISSUE TITLE
Module 'aurelia-binding' has already exported a member named 'Callable'

### ISSUE THREAD

**Issue by glen-84** [aurelia/framework#275]
I get this error with TypeScript `1.8.0-dev.20151221`:

```
dist\jspm_packages\npm\aurelia-framework@1.0.0-beta.1.0.5\aurelia-framework.d.ts(209,3): error TS2308: Module 'aurelia-binding' has already exported a member named 'Callable'. Consider explicitly re-exporting to resolve the ambiguity.
```

**Comment by wforney** [comment]
I have this error as well:

`jspm\npm\aurelia-framework@1.0.0-beta.1.1.1\aurelia-framework.d.ts(209,3): error TS2308: Module 'aurelia-binding' has already exported a member named 'Callable'. Consider explicitly re-exporting to resolve the ambiguity.`

**Comment by EisenbergEffect** [comment]
TypeScript 1.8 is not released yet. If you are using a Beta, we can't guarantee support for that. If you understand the source of that error and why TS 1.8 would cause that, please let us know and we'll do our best to fix it on our end.

**Comment by wforney** [comment]
I found this: https://github.com/Microsoft/TypeScript/pull/5148/files

This may be the cause of the error...

**Comment by EisenbergEffect** [comment]
@jdanyow Looks like we might have to libraries exporting the same interface. We need to track that down and see if we can manage to not export one of them.

**Comment by glen-84** [comment]
Thanks Rob. =)
