### ISSUE TITLE
Router:: Inconsistent navigation states when activation interrupted.

### ISSUE THREAD

**Issue by nazariotpcbf** [aurelia/framework#276]
I've tested this on a Mac - Firefox and Chrome.
--
Having subscribed to the  **aurelia-router** events **router:navigation:processing** **router:navigation:success** and **router:navigation:complete**, and listening to it's states i understood that the flow into a Route goes like this.

RouterProcessing -> Page canActivate -> Page activate -> RouterSuccess -> RouterComplete.-> Page canDeactivate -> Page deactivate -> RouterProcessing -> SecondPage canActivate ... and so on.

Every event from the router receives a Param with the fragment that is in progress or completed except when pressing the back button in the browser during a delayed Promise in the **canActivate** of some page, in this case, there's no processing listed in the router events to the returning page, the returning page does show up though and the activation steps of it do happen, the Router events finish with a **router:navigation:complete** giving a fragment of the first page as parameter, not the one i returned to, and displaying the correct page.

Here i list the states i'm experiencing in both scenarios, the second showing the router avoiding the processing of the back flow, (both pages are plain pages).

## **Normal Flow - (Starting in Page0 and navigating to Page1)** ##
 
Router:: routerProcessing fragment /page1
Page0:: canDeactivate
Page1:: canActivate? takes 3 sec
Page0:: deactivate
Page1:: activate 
Router:: routerSuccess fragment /page1 Router.History.Fragment /page1
Router:: Complete fragment /page1
**(pressed back in the browser to page0)**
Router:: routerProcessing fragment /page0
Page1:: canDeactivate
Page0:: canActivate
Page1:: deactivate
Page0:: activate
Router:: routerSuccess fragment /page0 Router.Historty.Fragment /page0
Router:: Complete fragment /page0
**Page0 displays** 
 
## **Inconsistent Flow - (Starting in Page0 and navigating to Page1)**  
 
Router::  routerProcessing fragment /page1
Page0::  canDeactivate?
Page1::  canActivate? takes 3 sec **(pressed back in the browser to page0)**
Page0::  deactivate 
Page1::  activate
Page1::  canDeactivate
Page0:   canActivate
Page1::  deactivate
Page0:   activate
Router:: routerSuccess fragment /page1 Router.History.Fragment /page0
Router:: Complete fragment /page1
**Page0 displays**

**Comment by Vheissu** [comment]
This references an issue which has since been closed @EisenbergEffect
