### ISSUE TITLE
<require>

### ISSUE THREAD

**Issue by hubroot** [aurelia/framework#277]
Is there a feature or an implementation of this : 
I have : 
 one/index.html
 two/index.html

now if I do 
<reqiure fom="one/index.html></require>
<reqiure fom="two/index.html></require>

how can I differentiate / use from the 2 above ?

Is there something like 
<reqiure fom="one/index.html" as="index1"></require>
<reqiure fom="two/index.html" as="index2"></require>

**Comment by EisenbergEffect** [comment]
I think something got lost in your post. However, this isn't the place for general questions, only for bugs and features. Instead, please ask this in our gitter chat room.

**Comment by hubroot** [comment]
well, no one knows, So I fetched the source code and I've got what I looked for personally. Thans anyway ;)
