### ISSUE TITLE
Provide command line argument for gulp bump-version (or gulp prepare-release)

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/framework#28]
https://github.com/gulpjs/gulp/blob/master/docs/recipes/pass-arguments-from-cli.md

Using the recipe at the url, we should provide for the following:

`gulp prepare-release --type patch` 

Thoughts?

**Comment by EisenbergEffect** [comment]
I'd love to have that. Patch should be default, but should be overridable with the command line argument.

**Comment by AshleyGrant** [comment]
Give me the assignment and I'll make it happen.

**Comment by EisenbergEffect** [comment]
Done.
