### ISSUE TITLE
How to call a function outside custom element?

### ISSUE THREAD

**Issue by namcv** [aurelia/framework#280]
I have one custom element named custom-element and I put it inside template A (with controller A)

<img width="702" alt="screen shot 2015-12-28 at 3 39 38 pm" src="https://cloud.githubusercontent.com/assets/9289826/12016104/5fdac2cc-ad79-11e5-9c24-193bba8b0c85.png">

export class CustomElem {
	@bindable  onCompleted;
........
}
And updateDescription() is one function of controller A.

export class A {
	updateDescription(){
        ....
        }
}

How to call updateDescription() by using custom-element?

**Comment by EisenbergEffect** [comment]
`on-completed.call="updateDescription()"`
