### ISSUE TITLE
Pages not updating until I hit refresh

### ISSUE THREAD

**Issue by jleepietech** [aurelia/framework#285]
When I create or edit item, the webpage will not update until I hit refresh on the browser at least once.  

The webpages makes a web api call to retrieve the data when the page is activated.  I have tried both activation strategy - replace and invokeLifeCyle.  Note this only happens when the page is initially loaded.  If I hit refresh at anytime, the pages will start to update correctly.

**Comment by BrettMN** [comment]
When you create or edit an item do you update the collection on the client that you are using for the display?

**Comment by jleepietech** [comment]
Yes, I make a web api call to retrieve the data when I crud something.    

return this.data.get().then(response => this.list = response);

**Comment by EisenbergEffect** [comment]
Not reproducible.
