### ISSUE TITLE
[TypeScript] 'Singleton' decorator requires 'function call' to work

### ISSUE THREAD

**Issue by jhudler** [aurelia/framework#290]
Suppose the following ViewModel:

```typescript
    // MyViewModel.ts
    import * as Framework from 'aurelia-framework';

    @Framework.singleton
    export class Grid { }
```

Using the `@singleton` attribute/decorator will incur in the following error:

    ERROR [app-router] Error: Error invoking . Check the inner error for details.
    ------------------------------------------------
    inner error: TypeError: Cannot read property 'hasOwnProperty' of undefined
        at Object.Reflect.defineMetadata (http://localhost:9000/jspm_packages/npm/aurelia-metadata@1.0.0-beta.1/aurelia-metadata.js:32:37)

If I replace it like a function call, it works as expected:

```typescript
    @Framework.singleton()
    export class Grid { }
```

What made me stumble on this is that `@autoinject` works correcly the first way, as seen in the docs.

**Comment by EisenbergEffect** [comment]
Welcome to the beautifies of the ES2016 decorator design. Some decorators require the parens...and some don't.

**Comment by EisenbergEffect** [comment]
Not much we can do about it.

**Comment by jhudler** [comment]
Shouldn't then the docs samples adopt a convention of always use parenthesis instead?
Or this is not possible/safe?

I'm sorry if this is a basic/stupid question of mine, but googling some texts about this didn't made me feel clear about a rule of thumb for this...

**Comment by EisenbergEffect** [comment]
The unfortunate answer is that there isn't a rule of thumb. Some decorators require the parens. Some do not. We've tried to make any paren-less decorators also function correctly without them. But those that require them can't work without them. I think what we can do is try to indicate that in our API docs. If you would like to open a new issue about documenting this feature of decorators, that would help us to track the docs improvement.
