### ISSUE TITLE
configure isn't called after System.import('aurelia-bootstrapper')

### ISSUE THREAD

**Issue by Cedware** [aurelia/framework#291]
since the last update the configure method isn't called after running System.import('aurelia-bootstrapper'):

index.html:
```
<body aurelia-app="AureliaConfiguration" style="height: 100%">
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');
    </script>
  </body>
```

AureliaConfiguration.ts:
```
"use strict";
import {Aurelia, ViewLocator, Origin} from "aurelia-framework";
export function configure(aurelia: Aurelia){
    alert("not called");
	aurelia.use
	.standardConfiguration();
	
	ViewLocator.prototype.convertOriginToViewUrl = (origin: Origin)=>{
		var moduleId: string = origin.moduleId;
		var name = moduleId.split("/")[moduleId.split("/").length-1].replace("ViewModel","View").replace(".js","").replace(".ts","");
			return `Views/${name}.html`;
	}	
	aurelia.start().then(()=>aurelia.setRoot("ViewModels/MasterViewModel"));
}
```

**Comment by ChrisEbert** [comment]
I have the same issue with my project

**Comment by jsobell** [comment]
I can't reproduce this, and I'm using typescript with the same names with no problem.

Check that you have `/dist/AureliaConfiguration.js` generated with the expected content.

Also, in TypeScript beware of TSC build errors that still generate .js files.

**Comment by jdanyow** [comment]
@Cedware  / @ChrisEbert are you still hitting this issue?

**Comment by Cedware** [comment]
Currently i created a new project at work, I had no problem there, so I assume there must be an error in the project, in which i have this issue.

**Comment by ChrisEbert** [comment]
I'm still facing this issue. But after removing the configure method, my project wasn't running anyway. 
I will revert the updated packages to find out which causes the issue.

**Comment by ChrisEbert** [comment]
My app is running fine again with the latest updates. Thanks for your great work!
