### ISSUE TITLE
Docs: Alert-Box doesn't wrap text in IE

### ISSUE THREAD

**Issue by Manuel-S** [aurelia/framework#292]
If this is the wrong repo to post this issue I apologize, I couldn't find the repo containing the docs framework.

In the official [Docs](http://aurelia.io/docs.html), there is a css error in IE11:

The au-alert - box only has a single line for content, which will then overflow.
Simple fix:
.au-alert h4+p{
...
max-width:100%;
}

**Comment by EisenbergEffect** [comment]
@joelcoxokc Can you take a look into this.

**Comment by joelcoxokc** [comment]
@manuel-S thank you for the issue and solution. I'll get it taken care of.

**Comment by jdanyow** [comment]
@joelcoxokc can this be closed?

**Comment by joelcoxokc** [comment]
@jdanyow yes
