### ISSUE TITLE
Removal of corejs as a hard dependency

### ISSUE THREAD

**Issue by MrAndMrsK** [aurelia/framework#294]
Corejs is a shim for es6 features.  Some projects will target only browsers that are es6 native.  Also, other es6-compliant shims exist.  Also corejs npm package (current dependency version) causes issues with TFS and totally bloats the app source with 900 files.

I suggest that es6 features become a soft-dependency of Aurelia instead of a hard one.  This will allow for flexibility in the choice of shim (or none).  

With documentation guidance from Aurelia, or perhaps basic feature detection per module for descriptive errors (*Aurelia-whatever module requires ES6 Promises but this environment doesn't seem to support them.  We suggest adding a shim such as core-js's Promises module which can be added by ... see docs.aurelia.io/ailhibsdv for more information* in the browser console)

**Comment by EisenbergEffect** [comment]
Yes. I agree with you for the most part. We are working on a solution. In the mean time, you can update the map config in your config.js file such that the mapping for core-js points to an empty module. I believe that should work. It's not ideal, so we hope to have a better solution in the future.

**Comment by MrAndMrsK** [comment]
Ok, cool.  I do love what you guys are doing with the whole of it.  And I just wanted an up or down on this and if up, then now it can be tracked (if not a dup).  I only posted this after some discussion on gitter.

**Comment by atsu85** [comment]
One relatively easy option would be to include script that strips some functionality (from the sample app) - what do You think? I know that in long term @EisenbergEffect wants smth fancier, but as a start it might be good enough and wouldn't take too much effort (to create the script and to maintain several samples)

**Comment by atsu85** [comment]
(uups, my last comment was meant for another issue)

**Comment by EisenbergEffect** [comment]
Yes, it's good that you sumitted this issue. I was thinking about it again this week because I was frustrated by the size that core-js added to our library. I was wondering if we couldn't do something better to solve that.

**Comment by jdanyow** [comment]
Aurelia no longer depends on core-js

**Comment by MrAndMrsK** [comment]
:+1:
