### ISSUE TITLE
Most of code in get started not working

### ISSUE THREAD

**Issue by vinhtq** [aurelia/framework#295]
I tried to learn Aurelia through get started.

Most of the code not working.

First i ran on opera => not working at all.

Then i tried Firefox => i can see the menu bar but no links or content at all

I used Chrome and then it works but later when i write this code:
```
<ul class="nav navbar-nav">
    <li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
        <a href.bind="row.href">${row.title}</a>
    </li>
</ul>
```

row.href => undefined when i click on the link

One weirdest thing is although i restart server and refresh the page many times on Chrome.

The old content is still there. Huh, so i open private window i have new content.

I know it is just beta but for the first time use i already encountered so many problems

**Comment by EisenbergEffect** [comment]
Our apologies. Opera is not among our currently supported set of browsers, but we can look at adding it. We'll need some more information from you to track down the bugs. The same would go for the other issues, as those problems with firefox and Chrome have not been reported before.

**Comment by Gheoan** [comment]
> One weirdest thing is although i restart server and refresh the page many times on Chrome.

> The old content is still there. Huh, so i open private window i have new content.

Are you starting the webserver using `http-server`? `http-server` is caching the files so you have to clear the cache when you make a change. Use `CTRL+F5` to refreash and clear the cache or start `http-server` with 
```shell
http-server -c-1
```

**Comment by vinhtq** [comment]
@Gheoan Your solution helps me. Thank you!

As i know is opera now change to use webkit engine like chrome. I think maybe it is good if we can run on opera.

Since i began from get started, i have had many problems. If you can try out yourself the get started guide as a beginner like me you will see.

Thank your for your potential project. I really like it concept.

**Comment by CasiOo** [comment]
@vinhtq I've been using Opera with webkit, and I haven't noticed any problems that would not also occur in Chrome yet. There might be some differences though, but I myself haven't ran into them yet.
