### ISSUE TITLE
getting started nodejs webserver

### ISSUE THREAD

**Issue by Gheoan** [aurelia/framework#296]
The Getting Started article recommends starting a webserver on `nodejs` with the command `http-server -o`. However `http-server` defaults to [1 hour of cache time](https://github.com/indexzero/http-server/blob/master/README.md#available-options) which is [not good for a development server](https://github.com/aurelia/framework/issues/295#issuecomment-171885911).

I propose switching to `browser-sync` or disable caching for `http-server` with `-c-1`. I will submit a PR once a collaborator chooses one of the two.

**Comment by EisenbergEffect** [comment]
I think, let's stick with http-server for these scenarios. If you want to submit the PR for the docs instructions fix, I would be happy to accept that. This definitely causes an issue.
