### ISSUE TITLE
@computedFrom not working in TypeScript

### ISSUE THREAD

**Issue by jsobell** [aurelia/framework#300]
The `@computedFrom` appears to have no effect in TypeScript.
For example (based on the current TypeScript skeleton):
```
  firstName = 'John';
  _lastName:string = 'Doe';
  previousValue = this.fullName;

  @computedFrom('_lastName')
  get lastName()
    {
      console.log('Reading LastName', new Date());
      return this._lastName;
    }
  set lastName(val)
    {
      console.log('Lastname changed from ',this._lastName, 'to', val);
      this._lastName = val;
    }
```
The message shows polling every 120ms.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look into this?

**Comment by PWKad** [comment]
I just tested this on the skeleton and it works fine for me.  Polls only as expected.

**Comment by PWKad** [comment]
I just tested this on both typescript skeleton and es2016 skeleton and it works fine for me.

**Comment by jsobell** [comment]
Interesting.
I've tried it on two dev machines, and both exhibit the same polling issue.
I've attached the .js generated by inserting the snippet above into welcome.ts. Can you confirm it matches yours?
I'm happy to be proven wrong on this, but I undeniably have the issue on two different machines, both running from the skeleton TS project.
Neither have any compile errors, and the code execute without warnings or errors.

[welcome.js.txt](https://github.com/aurelia/framework/files/98382/welcome.js.txt)

**Comment by jsobell** [comment]
Ah, I've found why it occurs.
The following original code was still present:
```
  //@computedFrom('firstName', 'lastName')
  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
```
As such, *any* function without a computedFrom() will cause a poll of every property in the object.
I think we need to make this clear in the documentation, as `computedFrom` is an 'all or none' feature.

**Comment by EisenbergEffect** [comment]
It doesn't poll every property...just the fullName property. That just happens to be computed from firstName and lastName, so those get accessed too as part of the access of fullName.

**Comment by jsobell** [comment]
Oh bollocks. I see that now. D'oh.
Sorry for the timewaste.

**Comment by EisenbergEffect** [comment]
No need to apologize. We need more docs and we should make this clear.
