### ISSUE TITLE
oneTime binding behavior breaking in a changing collection

### ISSUE THREAD

**Issue by blkbltjns** [aurelia/framework#301]
This is not working as expected, the screen should show:
4 4
5 5
after clicking the button.

welcome.html
```
<template>
    <button click.trigger="clickme()">Click me!</button>
    <div repeat.for="item of items">${item.prop1 & oneTime} ${item.prop2 & oneTime}</div>
</template>
```

welcome.js
```
export class Welcome {
    items = [{prop1:1,prop2:1},{prop1:2,prop2:2},{prop1:3,prop2:3}];
    
    clickme() {
        this.items = [{prop1:4,prop2:4},{prop1:5,prop2:5}];
    }
}
```

**Comment by EisenbergEffect** [comment]
What does it show instead?

**Comment by blkbltjns** [comment]
It shows:
1 1
2 2

**Comment by Gheoan** [comment]
I think the excepted behaviour with `one-time` is 
1 1
2 2

**Comment by blkbltjns** [comment]
I don't understand this logic. I want a list of divs with each div binding oneTime to it's underlying data. If I replace the list of data, there should be brand new divs...the oneTime should only apply to that specific view-viewmodel, not to the index in the list.

**Comment by Gheoan** [comment]
http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/cheat-sheet/5 explains the 3 types of binding in Aurelia. What you want is probably `one-way`

**Comment by blkbltjns** [comment]
One-way gets dirty checked and removes a bunch of optimizations that one-time gets. One-time usually means the property you are binding to is immutable, which is the case I am talking about.

**Comment by blkbltjns** [comment]
And just to show what I mean, this -->does<-- work:

```
<template>
    <button click.trigger="clickme()">Click me!</button>
    <div repeat.for="item of items">${item.prop1 & oneTime}</div>
</template>
```

It just doesn't work if the div contains more than one item in the string template

**Comment by EisenbergEffect** [comment]
I think it's a legitimate bug. @jdanyow @martingust Can you guys look into this?

**Comment by blkbltjns** [comment]
Just checking to see if this is still being worked on...?

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look at this?

**Comment by jdanyow** [comment]
sorry guys- I assigned this to myself and then forgot all about it.  It seems to be specific to interpolation bindings, this template works as expected:
```html
<template>
  <button click.trigger="clickme()">Click me!</button>
  <div repeat.for="item of items">
    <span textcontent.one-time="item.prop1"></span>
    <span textcontent.one-time="item.prop2"></span>
  </div>
</template>
```

will get a fix in shortly.
