### ISSUE TITLE
The <content> element doesn't work for adding <option> to a <select>

### ISSUE THREAD

**Issue by egeland** [aurelia/framework#304]
The `<content>` element doesn't work for adding `<option>` to a `<select>`.

I have set up this test, based on the ES2016 skeleton:

ce.html
```
<template>
  <input type="text" placeholder="Some text to go here" />
  <ul>
    <content></content>
  </ul>
</template>
```

and adding this to `welcome.html`:
```
<require from="./ce"></require>
...
<ce>
  <li>option</li>
  <li>another option</li>
</ce>
```

This works perfectly:
![image](https://cloud.githubusercontent.com/assets/1281379/12501163/92378768-c0fd-11e5-8898-13ecb955cc77.png)

Change the `ul` to `select` and the `li` items to `option`, and you get an empty select dropdown.
![image](https://cloud.githubusercontent.com/assets/1281379/12501152/6d68417a-c0fd-11e5-8ae9-712a5ac149f9.png)

**Comment by EisenbergEffect** [comment]
The reason for this is that option elements are not valid inside of the ce element. They are only valid in select, datalist and optgroup. It's a matter of the html spec.

**Comment by egeland** [comment]
Darn.. so how should I make this functionality?
Use `<ul>` with a `click.delegate` and basically create my own version of a `<select>` ?

**Comment by EisenbergEffect** [comment]
Consider making a custom option element that you then use as a "data source" to create your real options internally. You can do this with the `children` decorator. Take a look in the cheat sheet and see if that helps you.

**Comment by egeland** [comment]
Thanks for your time - I'll see how I go! :+1:
