### ISSUE TITLE
How to use bootstrap-select or any other js control with Aurelia?

### ISSUE THREAD

**Issue by shivajiraot** [aurelia/framework#307]
Not sure what I am missing here, probably something silly, but I am unable to find anything regarding, let's say how to use bootstrap-select control in Aurelia views. Can someone point me to the right article please?
PS: I am not looking to create another custom control out of bootstrap-select but use as it as.
Request for your help.

**Comment by jdanyow** [comment]
Hi @shivajiraot, try your question in the [gitter channel](https://gitter.im/Aurelia/Discuss) or on stackoverflow with the tag `aurelia`. Include links to the specific library you want to integrate.
