### ISSUE TITLE
Window load callback never gets called from a view model

### ISSUE THREAD

**Issue by younesouhbi** [aurelia/framework#309]
First, awesome framework! I say that every time and I'll keep saying it.
That said, I'm trying to subscribe to the window load event through jQuery from a view model (in order to activate Masonry) but the callback never gets called. I'm practically sure this has nothing to do with Aurelia per say but with javascript modules and my knowledge about them or lack of it.

Masonry needs to operate after all images have been loaded, so is there anyway to subscribe to the window load from a view model? or may be some better way to achieve this?

Thank You

**Comment by Aniel** [comment]
you can use the `attached(){
 //your code
}` in your View Model see [Docs ](http://aurelia.io/docs#/aurelia/framework/1.0.0-beta.1.0.8/doc/article/cheat-sheet/2)

**Comment by younesouhbi** [comment]
attached doesn't work because it's not late enough, it might get called while images are still not loaded.

**Comment by Thanood** [comment]
Would it work from main.js?

**Comment by jdanyow** [comment]
by the time you're in a view model the window.load event has already fired.

**Comment by younesouhbi** [comment]
Does this mean that by the time I'm in a view model, all images in the corresponding view have been downloaded and available? How is this possible? Unless Aurelia loads the content of every view before starting which sounds inefficient. Can you please elaborate?

**Comment by jdanyow** [comment]
sorry- i meant document.ready.

if you're looking to this event:  https://developer.mozilla.org/en-US/docs/Web/Events/load
I don't think it's going to fire when the image elements are dynamically added via the templating system.

Maybe this will work for you:  http://imagesloaded.desandro.com/

**Comment by younesouhbi** [comment]
I was talking about images that are simply added to a view using the regular img html tag. There should be a way to get the window.load event into Aurelia...
That said, thank you! I'll try the plugin you mentioned.
