### ISSUE TITLE
Google Bot and others can't seem to render or speed test my site

### ISSUE THREAD

**Issue by davidbfrogman** [aurelia/framework#310]
So I'm starting to deploy my site ( just to test it out), and I've been looking through page speed insights, and pingdoms website speed tester.  It seems as though they don't wait for my aurelia app to finish loading before calling it good.  There also seems to be some pretty big delays between my main app, and the aurelia bundle actually loading.  I'm curious if anyone has seen behaviour like this before:
website: http://www.davebrownphotography.com/
repo: https://github.com/davidbfrogman/DBPAurelia

Google Bot Fetch as google bot:
http://puu.sh/mPMf6/f971057d95.png
![Image](http://puu.sh/mPMf6/f971057d95.png)
You can see it renders as a blank page

Pingdom Website Speed test:
http://puu.sh/mPMju/11712b35a5.png
![Image](http://puu.sh/mPMju/11712b35a5.png)
Here again.... the render is basically blank, and pingdom seems to think my website has finished loading.

Page Speed insights, again blank:
http://puu.sh/mPMpv/ec8caf9939.png
![Image](http://puu.sh/mPMpv/ec8caf9939.png)

There's a pretty big time gap between loading the aurelia framework bundle and my actual application bundle
http://puu.sh/mPMxX/3977a34be2.png
![Image](http://puu.sh/mPMxX/3977a34be2.png)

This is pretty disconcerting for a site that I certainly want to do some SEO optimization on.

Any help would be greatly appreciated

**Comment by davidbfrogman** [comment]
Apparently people are saying in the gitter channel that my bundle includes all of core-js, but I have no idea how to remove it. or only bundle the parts that I need.

**Comment by EisenbergEffect** [comment]
@davidbfrogman I recommend that you use an override so that instead of getting a million separate core-js moduels you just get one. That will mean less runtime module resolution processing. Take a look at the package.json file in our skeleton. You will see the override. Add that to your package and then re-install core-js.

**Comment by davidbfrogman** [comment]
huge difference:
[image](http://puu.sh/mPR6I/ede3d1fc6e.png)

Although still 
[image](http://puu.sh/mPReE/6c5034d952.png)

Which is pretty worrisome.

**Comment by davidbfrogman** [comment]
Well I made some progress. I'm adding notes here just in case anyone else tries this out, and starts to run into errors. 

It seems like google and others must be using something similar to phantom.js to fetch/render pages.  Which is interesting, because it seems like there are some polyfills that are needed in aurelia for these crawlers to be able to execute.  I worked through a lot of the problems, but I still have one open issue here: https://github.com/aurelia/pal/issues/6

Here's some notes on things I encountered:
1. Fetch polyfil is needed by these bots to properly access and render a page.  I was just using import ```{HttpClient} from 'aurelia-fetch-client';```
I needed to add:
```import 'fetch';```
for these headless browsers to work.

2.  Request animation frame isn't implemented by phantom.js.  So I added a poly fill for that, and included it in my bundles: https://github.com/davidbfrogman/DBPAurelia/blob/master/src/3rdParty/phantompolyfill.js

After doing these things, I'm getting much closer:

Pingdom 
http://puu.sh/mSz9g/81253249ad.png
![Image](http://puu.sh/mSz9g/81253249ad.png)

Page Speed Insights
http://puu.sh/mSzce/e1d464fd18.jpg
![Image](http://puu.sh/mSzce/e1d464fd18.jpg)

Google Bot
http://puu.sh/mSzfE/2f8b0d4d0a.jpg
![Image](http://puu.sh/mSzfE/2f8b0d4d0a.jpg)

**Comment by Gheoan** [comment]
@davidbfrogman very useful finding !

**Comment by Vheissu** [comment]
I think this one can be closed @EisenbergEffect I think the polyfills aspect is well documented in the Aurelia HUB.
