### ISSUE TITLE
Question: No way to replace default injector?

### ISSUE THREAD

**Issue by remojansen** [aurelia/framework#313]
Hi guys,

I'm working on my a IoC container and I would like to see how well would it work with Aurelia.

Do you guys provide some way to replace default IoC container with another IoC container with ease? Something like [`IDependencyResolver`](https://msdn.microsoft.com/en-us/library/system.web.http.dependencies.idependencyresolver(v=vs.118).aspx) resolver in ASP .net.

Thanks!

**Comment by EisenbergEffect** [comment]
Yes, you can do it, but you will need your own DI to implement a basic interface if you want Aurelia to work. To replace the default DI you need to write your own bootstrapper and supply the Aurelia object with your custom container instance.

So, it's all possible, but requires a bit of work and isn't really recommended. We could possibly make it so you don't have to write a custom bootstrapper...without too much work, but we don't want to encourage people to do this. The DI is critical to the system. If your DI is slower than ours, for example, you will slow down every aspect of Aurelia.

**Comment by remojansen** [comment]
Hi @EisenbergEffect thanks for answering. I asked this question because I've been working on http://inversify.io/ please take a look to [this comment](https://github.com/aurelia/dependency-injection/issues/73#issuecomment-196076010) you may find it interesting.

**Comment by EisenbergEffect** [comment]
To replace our Container, you would have to implement all the same methods that are expected. Then, you would have to manually bootstrap the Aurelia app, because that allows you to pass the root container in.

**Comment by remojansen** [comment]
I would like to try this without touching Aurelia code our touching it as little as possible. Replacing the injector should be more or less possible using the adapter pattern. Doing my own bootstrap sound more complex but I will try to give it a go at some point.

**Comment by EisenbergEffect** [comment]
You don't have to write your own bootstrapper. See the docs on manual bootstrapping. Just provide your container instance to Aurelia.
