### ISSUE TITLE
package.json within the published library

### ISSUE THREAD

**Issue by danfma** [aurelia/framework#314]
The current version of aurelia in jspm (1.0.0-beta.1.1.1) only has two files:

* a javascript file: aurelia-framework.js;
* a typescript definition file: aurelia-framework.d.ts.

If you put, with each repository a simple package file like bellow, it will allow the Typescript find the definitions automatically, when using 'node module resolution'.

```
{
  “name”: “aurelia-framework”,
  “main”: “aurelia-framework.js”,
  “typings”: “aurelia-framework.d.ts"
}
```

For example, if this `package.json` is on the `jspm_packages/aurelia-framework` directory, then I can create a symbolic link in the `node_modules/aurelia-framework` that points the to former directory. After that, the Typescript compiler will find the aurelia-framework.d.ts automatically, by just using the `import * from "aurelia-framework"` in the code.

**Comment by EisenbergEffect** [comment]
Are you saying that all we need to do is add our package.json file to the dist folders and then include the typings entry?

**Comment by atsu85** [comment]
@danfma, I'm curious, why You'd like to 
> create a symbolic link in the node_modules/aurelia-framework that points the to

> jspm_packages/aurelia-framework

? 
What (TypeScript code) would use aurelia-framework from node_modules folder instead of jspm_packages? My first thoughts were 
* Gulp (haven't figured out how it would be useful, maybe linting?)
* and attempt for server side rendering (i guess this still needs to wait some distant future)

so Your use-case is probably smth else, right?

**Comment by danfma** [comment]
@EisenbergEffect, yes. The new Typescript 1.9+ release will have a new module resolution that will allow to discover typings in a node package, if the package.json has a "typings" attribute that points to the definition file.

**Comment by danfma** [comment]
@atsu85, you are right. The only way to use that is if aurelia is installed on jspm and on node. But you can do some hacks like putting a symbolic link into the nodes folder that points to the jspm to overpass that. When I asked that I was trying to generate static bundles using the rollup, but that was not really a good option after all.

@EisenbergEffect, I don't think that you will lose anything by putting the property in the package.json, but in my atempt, I have failed, anyway. But if you, for some reason, distribute the aurelia by the npm, it could help who use it with the Typescript.

**Comment by EisenbergEffect** [comment]
We will be distributing by npm for Webpack and a future loader we are working on. We can easily start adding this property to our packages.

**Comment by danfma** [comment]
Thanks, @EisenbergEffect!! I think that will be of great help!
Just for curiosity, a new loader? Will JSPM be left apart?

**Comment by EisenbergEffect** [comment]
We will continue to support jspm, but I think, in order for us to provide a more stable platform, post v1, we are going to need to provide our own loader option.

**Comment by EisenbergEffect** [comment]
@danfma Can you provide me a reference to the documentation on this please?

**Comment by philmueller** [comment]
@EisenbergEffect Module resolution via "typings" field in `package.json` is described here: [Typings for NPM Packages.md](/Microsoft/TypeScript-Handbook/blob/master/pages/Typings%20for%20NPM%20Packages.md)

As @unional pointed out in the related issue #360, the `declare module "aurelia-framework" {...}` wrapping has to be removed for this mechanism to work.
I just did a quick test by adjusting all the pacakge.json and *.d.ts files locally and the automatic resolution works like a charm with the npm/webpack workflow. There is no need to add the package.json to the dist folders, just reference the typings with `"typings": "dist/aurelia-framework.d.ts". I'm sorry that I can't provide a PR for this as I'm not familiar how you generate your *.d.ts files.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham We need to look into this for the future... Can you take a look at what would be involved on our end? It would be nice to have this finally dealt with for v1.

**Comment by unional** [comment]
> The new Typescript 1.9+ release will have a new module resolution that will allow to discover typings in a node package, if the package.json has a "typings" attribute that points to the definition file

To clarify this a bit. Typings discovery for node package works in 1.8 (or prior) with `package.json/typings`. In 1.9+ it adds path mappings so that supporting `jspm` is possible without the symlink.

**Comment by atsu85** [comment]
@philmueller, @unional, @EisenbergEffect, @cmichaelgraham 
I think that following is incorrect:
> As @unional pointed out in the related issue #360, the declare module "aurelia-framework" {...} wrapping has to be removed for this mechanism to work.

I've written a longer [comment](https://github.com/aurelia/framework/issues/360#issuecomment-207843997) to the referenced issue.

*To be clear, I'm not stating anything about the required changes in package.json, just the format of TypeScript definitions for Aurelia*

**Comment by unional** [comment]
@atsu85 just responded. :smile:

**Comment by atsu85** [comment]
@unional, You are the man! Sorry for the confusion.

**Comment by EisenbergEffect** [comment]
Typings field and typings.json implemented.
