### ISSUE TITLE
CheckedObserver is not defined

### ISSUE THREAD

**Issue by xiaoweil** [aurelia/framework#317]
Hi there,

I'm trying out the latest skeleton-navigation 1.0.0-beta.1.1.3, when binding radio input button I got the following exception:

Unhandled promise rejection ReferenceError: CheckedObserver is not defined

at ObserverLocator.createPropertyObserver (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.1.0/aurelia-binding.js:4043:22)

Sample code:

welcome.ts:
`export class Welcome {
  colors = [{name: 'Red'}, {name: 'blue'}, {name: 'green'}];
  color = this.colors[1];
}`

welcome.html:
          `<label class="btn btn-default" repeat.for="c of colors">
            <input type="radio" name="color" model.bind="c" checked.bind="$parent.color"/>
            ${c.name}
          </label>`

Similar exception also happens in `<select>` input:

      `<select id="colors" type="text" class="form-control" value.bind="color">
        <option>Select A Color</option>
        <option repeat.for="c of colors" model.bind="c">${c.name}</option>
      </select>`

Unhandled promise rejection ReferenceError: SelectValueObserver is not defined
    at ObserverLocator.createPropertyObserver (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.1.0/aurelia-binding.js:4040:22)

Am I missing anything here? Thanks for your help.

**Comment by EisenbergEffect** [comment]
@jdanyow Was this fixed?

**Comment by EisenbergEffect** [comment]
Try running `jspm update` and see if that fixes it.

**Comment by xiaoweil** [comment]
Just ran the `jspm update` seems to fixed the issue, thanks for the quick response.
