### ISSUE TITLE
Slow load with Windows 10 Edge

### ISSUE THREAD

**Issue by DirkHagen** [aurelia/framework#318]
Are all Aurelia-Examples loading very slow with Windows 10 Edge?
Best regards
Dirk Hagen

**Comment by fopsdev** [comment]
could be related to "the promise" - issue
http://www.danyow.net/edge-promise-perf/

**Comment by EisenbergEffect** [comment]
@jdanyow What do you think, should we just include bluebird in all of our starter kits by default?

**Comment by jdanyow** [comment]
The Edge team is working on a fix- https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/11329845-improve-promise-implementation-performance

Maybe we should wait?

**Comment by EisenbergEffect** [comment]
Probably, maybe we should put a note about perf in the getting started and production setup docs just to let people know?

**Comment by RomainLanz** [comment]
@EisenbergEffect Thant would be very useful.
