### ISSUE TITLE
Interpolated value not updated when expression contains a function call

### ISSUE THREAD

**Issue by bekite** [aurelia/framework#32]
In this case the expression gets updated when the value of selected is changed in the view-model.
```${selected === selections[0]}```

If the expression contains a function call, then the expression is not updated:
```
${isSelected(selections[0])}

class SomeClass {
  isSelected(selection) {
    return this.selected === selection
  }
}
```

**Comment by EisenbergEffect** [comment]
The only thing that can trigger an update is a change to a property. There is no way to observe the return value of a function...other than to use dirty checking. We don't want to do that as it greatly complicates the binding library...and opens up the door to all the problems that Angular's implementation has.

So, it's best to try to use properties in your bindings and not functions. That said, we are planning some enhancements to the binding engine to allow triggering binding updates with "signals" as well as more control over computed properties in the future. We'll have that for v1 and maybe some other controls as well to make fine tuning these things nicer.
