### ISSUE TITLE
jspm install jquery breaks Aurelia demo app

### ISSUE THREAD

**Issue by djflex68** [aurelia/framework#320]
Hello,

I want to install jquery using jspm (jspm install jquery).
This breaks the demo app (Typescript kit).

What is causing this ? 

Thanks

**Comment by jdanyow** [comment]
need more info- what's broken? what's the error?

**Comment by atsu85** [comment]
i also encountered some problems with *typescript skeleton* after installing jquery - if i remember correctly, the problem was related to `$` that was being used by jQuery and by some lib for testing as well. (The problem was raised by typescript compiler). I solved it for myself by creating 2 different typescript compilation tasks that only included single definitions file that contained `$` - either one used for runtime (jQuery) or for tests.

**Comment by djflex68** [comment]
If I take the typescript kit, then run http-server -o -c-1 in the unzipped folder, it works fine (Aurelia Startup page is displaying correctly)
Then I run jspm install jquery into this folder because I need jquery. 
When I run Aurelia Again, I got a blank screen but no error in console.

**Comment by EisenbergEffect** [comment]
It's not an Aurelia issue but an issue with TypeScript. You have multiple d.ts files that are colliding with one another. You will need to resolve those to get the TS compiler to work correctly.

**Comment by atsu85** [comment]
> You will need to resolve those to get the TS compiler to work correctly.

That is exactly what i described above. 

To be able to reuse tsconfig.json configuration for both gulp build tasks (main & test sources) and for IDE as well (Atom), I did following:
1) extracted typescript build logic into separate file that reads configuration from tsconfig.json
2) when compiling main TypeScript sources, i excluded test sources and typescript declarations - see [testTsSourceFilesGlob](https://gist.github.com/atsu85/84c776a874f1c8e4fd84)
3) when compiling e2e-test sources, i excluded 
- main sources 
- unit test sources 
- jquery typescript declarations

(see [excludeTsSourceFilesGlobs ](https://gist.github.com/atsu85/84c776a874f1c8e4fd84))

I published relevant pices of code as GitHub gist: https://gist.github.com/atsu85/84c776a874f1c8e4fd84 - i hope You'll find them useful, they have served me very well so far :)

**Comment by djflex68** [comment]
The problem came from JSPM for me. When doing jspm install, the path to github and npm repositories is modified. Strange behaviour...
