### ISSUE TITLE
TS definitions error in TS 1.8

### ISSUE THREAD

**Issue by jods4** [aurelia/framework#322]
Apparently TS 1.8 performs additional checks and it doesn't like
```typescript
export * from 'aurelia-binding';
export * from 'aurelia-task-queue';
```
Because they both export `Callable`.

Not sure what proper resolution is, as this migth be a layering/code organization issue, or some renaming to avoid clashing is in order.

**Comment by EisenbergEffect** [comment]
I believe we've got this fixed in the latest release. Try running jspm update.
