### ISSUE TITLE
rendering http://aurelia.io/docs on dolphin browser not working

### ISSUE THREAD

**Issue by Gambero81** [aurelia/framework#323]
Hi, i can't load http://aurelia.io/docs from dolphin browser (both mobile android and desktop user agent) it remain with the loading image in progress without rendering

**Comment by Vheissu** [comment]
The Aurelia docs have changed a lot since you posted in terms of Aurelia updates. I haven't seen anyone else post any similar issue, maybe this one can be closed @EisenbergEffect ?

**Comment by EisenbergEffect** [comment]
I'm not sure. I haven't tried it on dolphin...I'll close and we can re-open if it's still a problem.

**Comment by Gambero81** [comment]
Still not working :-(

**Comment by Gambero81** [comment]
Still not working :-(
