### ISSUE TITLE
status of Polymer/WebComponents support

### ISSUE THREAD

**Issue by k2s** [aurelia/framework#329]
Aurelia documentation is stating that WebComponents technology is supported by Aurelia and also that Polymer is supported.

I am facing some issues with Polymer components in my application. I would like to know what are the plans to support Polymer and help to improve it.

1. Will [aurelia-polymer plugin](https://github.com/roguePanda/aurelia-polymer) be moved to Aurelia organization and maintained officially by Aurelia ? 

2. Bundling Polymer in [aurelia/bundler](https://github.com/aurelia/bundler) seams to be unsupported. Polymer imports and custom-style placed before `<template>` tag are not processed, there is no workflow to use Vulcanize. 

3. Are there plans to add for example `skeleton-es2016-webcomponents` to (skeleton-navigation](https://github.com/aurelia/skeleton-navigation) to make it easier to start with Aurelia+WebComponents (Polymer) ?

**Comment by bdenham** [comment]
I'm interested in support for we components as well. A clarification or update on this specific topic would be welcome. Thanks!

**Comment by EisenbergEffect** [comment]
What exactly isn't supported? I don't see any real issues here.

* The aureia-polymer plugin was created by a community member. It's possible that we could support it...but why? The community member who built it is actually using Polymer; we aren't. They are a better resource for doing it right than us.
* Polymer is based on HTML Imports, which aren't a standard technology at this point. However, we support HTML Import bundling with our current bundler. We could look into doing some further integration with Vulcanizer...but again that isn't a Web Component technology but a Polymer-specific bundling tech. My recommendation would be to contact the author of the aurelia-polymer plugin and see how he is handling bundling. Based on his experience we can incorporate specific improvements to our bundler.
* There aren't any plans to add a Polymer skeleton at this point. Polymer !== Web Components. Keep that in mind. Polymer is another framework altogether. This doesn't mean we couldn't have a skeleton in the future, but we would need community effort.

None of this has anything to do with standards-compliant web components. Those have been supported from day one. Most of this has to do with Polymer's non-standard HTML Import feature, which we have some support for already. Again, I would recommend you engage with the author of the aurelia-polymer plugin to see how he does things. Based on what he says we can consider *specific* technical improvements.

**Comment by bdenham** [comment]
Thanks for the explanation, Rob. I'm new to Aurelia, but it's the best framework I've seen in terms of standards, simplicity, and power. I'll contact you via email soon to tell you more. 

Best,
Bruce Denham

**Comment by ergo** [comment]
@EisenbergEffect I think many of us could take advantage of bundling google's material design elements among things. Aurelia ecosystem is still quite young,. I know polymer is not vanilla web components but currently is the best component ecosystem out there. So even if it's not standard - it would really make sense to maybe collaborate to make this happen.

**Comment by EisenbergEffect** [comment]
If it's something that you all want, please start by contacting the author of the  aurelia-polymer plugin and initiating conversations with him. He's the expert and the one most likely to know what the best solution is. We've worked with him in the past and addressed all his issues. He may know how to solve this problem already.
