### ISSUE TITLE
Add a way to modify the template inside an Attached Behaviour before element compilation

### ISSUE THREAD

**Issue by Aaike** [aurelia/framework#33]
Please add a way for us to change the template of an element before it is compiled in an Attached Behaviour.
This will allow us to attach more behaviours to an element simply by adding attributes.

much like the `static beforeCompile(template)` function for custom elements.

**Comment by Serhioromano** [comment]
Not clear what would be the `template`? Is it URL string, HTML string or ID of the element? Or it is template content? Can you add practical example in real world scenario?

**Comment by Aaike** [comment]
This issue started when i asked this this question :

is it possible to add a behaviour to an element that will include other behaviours ?

for example if i have a bunch of behaviours
```
<div focusable hoverable draggable droppable></div>
```
i want to be able to write one attribute that will activate all these behaviours , something like

```
<div ui></div>
```
adding the ui behaviour would in turn enable all the behaviours specified above

**Comment by Aaike** [comment]
there is currently already a way to do something like this, where you should inject the child behaviours into one parent behaviour and initialize the child behaviours like this
```
constructor(Element, BoldTextBehavior, YellowBehavior){
    this.element = Element;
    this.bold = BoldTextBehavior;
    this.yellow = YellowBehavior;

    this.bold.element = this.element;
    this.yellow.element = this.element;
}
```

But allowing us to simple change the template before it is compiled would allow us to simple add attributes to the dom element and let aurelia initialize all the child behaviours.

**Comment by Aaike** [comment]
Has there been any progress around this ?

**Comment by EisenbergEffect** [comment]
Hasn't been done yet.

**Comment by EisenbergEffect** [comment]
The new view resource pipeline steps allow you to create resources that can be imported into a view which modify the template before compliation.
