### ISSUE TITLE
Default value for <select> gets overwritten

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/framework#338]
The problem arises when I bind `<select>.value` to a property, not to a simple field. The default value set in the `promise.then` gets overwritten by a framework.

http://plnkr.co/edit/TIVrD2TcJH1VZUYETG9a demonstrates the issue.

Setting the value on a timeout solves the problem though...

**Comment by z-brooks** [comment]
Seems to _work_ if you put an `if.bind` on the select. https://gist.run/?id=05011ad1c28e303894f6

**Comment by MaximBalaganskiy** [comment]
It does... Looks hacky as well though :)

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?

**Comment by z-brooks** [comment]
Need to use `@computeFrom` on the getter or bind to the `_value` directly. https://gist.run/?id=a15e06e4495c25e25a0e

**Comment by jdanyow** [comment]
Agree- need to use computedFrom otherwise the select doesn't know it's value changed until the dirty-check fires, which is too late, this code will have already caused the model value to be overwritten: https://github.com/aurelia/binding/blob/master/src/select-value-observer.js#L127
