### ISSUE TITLE
CSS for view-model

### ISSUE THREAD

**Issue by Tinadim** [aurelia/framework#339]
I managed to include css files from my views using the `require` tag like described in #50. However once I require the file and navigate away from the view, the css file remain attached to the `head` of the HTML. I don't know, maybe this is the intended behavior, but I was wondering if there's a way for actually replacing the CSS file for each view model as sometimes the they conflict with each other.

**Comment by EisenbergEffect** [comment]
We''ve got another issue to track this as a possible new feature. It's not something we are doing right now though. I recommend that you avoid conflicts by using more strict css selectors.
