### ISSUE TITLE
Support jspm bundling

### ISSUE THREAD

**Issue by felixbuenemann** [aurelia/framework#34]
The navigation example clocks in at ~140 http requests to load all scripts, so it would be great if it was possible to bundle the framework dependencies using `jspm bundle`.

Currently this doesn't quite work, because many of the listed jspm dependencies are implicit (never imported by any source files), so those dependencies get skipped in the bundle. For example bundling aurelia-bootstrapper still leaves ~70 http requests for dependencies like core-js, aurelia-templating etc.

I'm not sure if this is an issue with how aurelia handles imports or how jspm bundle works, so feel free to direct me at jspm if that is the proper place to raise this issue.

**Comment by EisenbergEffect** [comment]
We're on it. We've been contributing back some improvements to jspm to allow glob-based bundling. Also, we're working on an aurelia cli that will enable easier bundling and other nice things. I'm going to close this for now, since I think we've got this tracked elsewhere. Hang in there!

**Comment by felixbuenemann** [comment]
Thanks for the clarification. I found the commit in jspm that added globbing support, but couldn't really figure out how to use it from the commit message or issue comments. I guess I'll just wait and see :smile:

Btw. coming from a ruby and rails background I love the uncluttered syntax that Aurelia uses. It allows me to understand what's going on immediately without knowing the framework internals!
