### ISSUE TITLE
click.delegate doesn't work with repeat.for

### ISSUE THREAD

**Issue by alexmahterian** [aurelia/framework#340]
I've got a list of items being pulled from my server that populates a list element. I need to be able to click on those items to add them to an array, but click.delegate doesn't work, nor does $parent.click.delegate. I've also tried to use JQuery via $("#myelement li).click(...) and [...].on('click', funciton(...)); none of these seem to work. Do you have any suggestions as to how I can get around this?

**Comment by atsu85** [comment]
@alexmahterian,
> nor does $parent.click.delegate

`$parent` is supposed to be used in the attribute value, smth like `click.delegate="$parent.save()"`

**Comment by alexmahterian** [comment]
Haha I'm sorry, that's what I meant.
I tried $parent.function(), not $parent.click.delegate.

**Comment by alexmahterian** [comment]
I don't know why I was trying to do that, but I was indeed trying to use $parent.click.delegate. Thanks for pointing that out, applying it to the function worked fine!

**Comment by atsu85** [comment]
I'm glad it got solved - Please close the issue :)
