### ISSUE TITLE
Documentation didn't work anymore

### ISSUE THREAD

**Issue by RomainLanz** [aurelia/framework#344]
Hey everyone.

**Link:** http://aurelia.io/docs.html
**Browser:** Chrome  48.0.2564.116 (64b)
**OS:** OS X El Capitan

I got a 404 in the main javascript file.

```
GET http://aurelia.io/dist/main.js 404 (Not Found)
```

<img width="1821" alt="screen shot 2016-03-02 at 09 44 50" src="https://cloud.githubusercontent.com/assets/2793951/13455071/867409ba-e05b-11e5-9dc5-4f0d00c70a8f.png">

**Comment by egeland** [comment]
Confirmed.

**Comment by abhilashsajeev** [comment]
+1

**Comment by Kaapelikala** [comment]
Was broken yesterday

**Comment by EisenbergEffect** [comment]
We are working on it. Appears something went wrong with the deploy...

**Comment by EisenbergEffect** [comment]
Fixed. Apologies.
