### ISSUE TITLE
"aurelia_framework_1.singleton is not a function" after bundeling

### ISSUE THREAD

**Issue by MaartenThomassen** [aurelia/framework#349]
Hello,

In my Aurelia app, I am using a Typescript development environment which transpiles to ES5 and in my code i use the @autoinject attribute and Aurelia's dependency injection framework.

When I build my app and run it locally, everything works fine. When I bundle my app (i made 2 bundles, one with all Aurelia deps i use and 1 with all my own code), i get the following error:

`system.js:41 Uncaught (in promise) Error: aurelia_framework_1.singleton is not a function`

This error in turn causes:

`Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?`

I did some debugging, and when running without bundles, the aurelia_framework_1 module contains both the .singleton() function definition and the .FrameworkConfiguration.singleton() . When I run with bundles, the aurelia_framework_1 module does NOT contain the .singleton() function definition but DOES contain the .FrameworkConfiguration.singleton().

I can't figure out what the difference between the unbundled and bundled versions are. I also can't figure out how, at runtime, the framework "copies" the .singleton() function directly in the aurelia_framework_1 module, since when i dove into the Aurelia code and Typescript definitions, the .singleton() function is only present in the FrameworkConfiguration whitin the aurelia-framework module.

The error happens when i try to do a custom registration into the DI container:

`aurelia.container.registerSingleton(UserManager_1.UserManager);` 

Where UserManager is a class in my own UserManager module.

NOTE: I use the latest version of Aurelia Beta 
`"aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.1.4",`

NOTE 2:

The error happens exactly at this line:
`UserManager = __decorate([aurelia_framework_1.singleton(), aurelia_framework_1.autoinject, __metadata('design:paramtypes', [IAuthentication_1.IAuthentication, ToCRUDConverter_1.ToCRUDValueConverter])], UserManager);`

At the bottom of  'System.register("src/libraries/UserManager.js",...' int he bundled file. there, both the aurelia_framework_1.singleton() and aurelia_framework_1.autoinject are undefined, causing the UserManager to not get defined, breaking the DI function call mentioned above.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/bundler #93](https://github.com/aurelia/bundler/issues/93) via [**ZenHub.io**](https://www.zenhub.io/)
