### ISSUE TITLE
log a warning when .html is used

### ISSUE THREAD

**Issue by opcodewriter** [aurelia/framework#350]
It looks like it's pretty common to include '.html' by mistake 
`<require from='./editor/controls-panel.html'></require>`
this makes the view-model not being loaded and bound.
it would be nice if a warning is given in console

**Comment by AshleyGrant** [comment]
This is actually an expected use case. This allows you to load an html file that doesn't have a js VM behind it. It's even used in our skeleton: https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-es2016/src/app.html#L2

**Comment by EisenbergEffect** [comment]
@AshleyGrant I think they would like there to be some meaningful error message when this is done by accident.

**Comment by mikefills** [comment]
yes, my point was writing a meaningful error message, which would be very helpful. 
It's very easy to include html by mistake, especially for all new people, I just heard others saying same thing

**Comment by Vheissu** [comment]
Is this going to be something that is being added into Aurelia @AshleyGrant @EisenbergEffect I feel as though Aurelia already does so much and that if a user makes this mistake, it is easy enough to fix without needing to incur any additional overhead of checking for a matching .js/.html file and throwing a warning.

**Comment by EisenbergEffect** [comment]
Since requiring an html file is a feature, we can't simply warn somebody that they are using a supported feature. We also can't check if there's a js file because that would entail additional http requests, potentially for no reason. That really wouldn't work in bundled apps or webpack-type setups at all I don't think.
