### ISSUE TITLE
[question] Is there a way to avoid putting model into dom

### ISSUE THREAD

**Issue by bigopon** [aurelia/framework#352]
currently we have result dom like this:
```html
<li au-menu-item="item.bind:tutorial; active.bind:tutorial.isSelected">...</li>
```
is there a way to have Aurelia work with only this:
```html
<li>...</li>
```

I tried to delete the property and the app still works fine, I don't know why we need it there

**Comment by jdanyow** [comment]
hi @bigopon- we're tracking this enhancement here:  https://github.com/aurelia/templating-binding/issues/81
