### ISSUE TITLE
Material design support. How to inject into view creation

### ISSUE THREAD

**Issue by mikefills** [aurelia/framework#354]
There's a aurelia-material library to add MD to an Aurelia app, author describes the implementation very well here http://blog.redpelicans.com/aurelia-material-design-lite/

The gist is it's using a 'mdl' custom attribute which calls MD's 'upgradeElement' on the element. The author does not maintain the library anymore.

I was wondering if instead of this, wouldn't be possible to inject into Aurelia's flow when it creates the view's HTML element. I could parse for MDL elements by their class name, and call upgradeElement on each.
Does Aurelia have a way for me to inject my logic into this flow?

**Comment by Thanood** [comment]
Please have a look here: https://github.com/genadis/aurelia-mdl
It's the same principle but genadis still maintains the repo.

IFAIK, you could subscribe to a router event and do ```componentHandler.upgradeDom()``` there when each view is injected. Personally I find the attribute solution more elegant, but that should work.

Basically it's the same as calling ```upgradeDom()``` in every ```attached()``` method of your views.

**Comment by mikefills** [comment]
thank you. 
the attribute is nice, but it requires you to put it everywhere in the HTML

**Comment by stoffeastrom** [comment]
There is also the possibility adding hooks like [here](https://github.com/aurelia/templating/issues/65). Maybe it would be possible to have a global resource for all your views that calls the `upgradeElement` ?

**Comment by Thanood** [comment]
Wow, hooks.. That definitely needs documentation. :smile:

**Comment by schatekar** [comment]
Sorry for a noob question, but why would you not simply use a material CSS framework like [Materialize CSS](materializecss.com)?

**Comment by mikefills** [comment]
the link to Materialize CSS is https://github.com/Dogfalo/materialize

**Comment by Thanood** [comment]
@schatekar Materialize does almost everything on ```$(document).ready()``` which also is too early for dynamic apps like Aurelia. You'd still have to initialize controls which do not only rely on CSS (e.g. most controls in the ["javascript"](http://materializecss.com/collapsible.html) category).

@mikefills Materialize is another implementation of MD. I'm not sure if it's lightweight, though. It weighs around 130k zipped.
We're are currently developing a [Materialize wrapper](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge) for Aurelia. If you're interested in that, have a look. :smile:

**Comment by mikefills** [comment]
not sure, but I wouldn't want to use anything but Material Design Lite, which is Google's official implementation of MD.

**Comment by EisenbergEffect** [comment]
It's possible to create a global behavior that will affect each view after it is created. However, I usually don't recommend that sort of hidden behavior. I would usually recommend creating some sort of custom attributes or elements to represent the widgets. This makes things more explicit. Something like this would be preferred: https://github.com/genadis/aurelia-mdl It also reduces the number of classes you have to write and shrinks the HTML, which is another bonus.

**Comment by mikefills** [comment]
@EisenbergEffect how would the "global behavior" work exactly ?  HTML pipeline hooks?
can you please shed some light since this issue is now closed

**Comment by EisenbergEffect** [comment]
To accomplish this, you need to plug into the view engine's resource pipeline. You do this be creating classes that have metadata which describe their "resource behavior". Things like custom attributes and custom elements, binding behaviors, etc. are all different resource types. Most of the time, the resource descriptor is assigned by convention, but when you apply an decorator such as `customElement` to a class, that is actually assigning the resource descriptor explicitly to the decorated class.

For this scenario, you need to create a custom resource descriptor. The descriptor tells the view engine how the resource classes will pug into the pipeline. Then, you need to create an actual resource (described by the descriptor).

Note, this is a pretty advanced topic, but it will show you how flexible and powerful Aurelia's templating engine is. Literally, almost everything that you know as Aurelia's templating engine is built out of these building blocks.

The descriptor class.
```
class ViewEngineHookResourceDescriptor {
  initialize(container: Container, target: Function): void {
    this.target = target;
  }

  register(registry: ViewResources, name?: string): void {
    registry.registerViewEngineHooks(this.target);
  }

  load(container: Container): Promise {
    //not needed fro this scenario; but allows resources to load dependencies
  }
}
```

A nice decorator to apply it
```
import {resource} from 'aurelia-templating';

export function viewEngineHooks() {
  return resource(ViewEngineHookResourceDescriptor())
}
```

Your resource class
```
@viewEngineHooks()
export class Materialize {
  afterCreate(view) {
    //view.fragment is the DocumentFragment for the view...apply the plugins to it
  }
}
```

There are four hooks for this type of resource: beforeCompile, afterCompile, beforeCreate and afterCreate.

To use this either require the module with the Materialize class into a view and the hooks will hook into that view or globalize the module and it will hook into every view.

**Comment by glen-84** [comment]
I needed to apply some jQuery plug-ins to elements after a view is loaded/created. I did this (in my configure function), which appears to work:

```ts
    const resources: ViewResources = aurelia.container.get(ViewResources);

    resources.registerViewEngineHooks({
        afterCreate: (view) => {
            $(".js-date-picker", view.fragment).datepicker();
        }
    });
```

Hopefully it's okay.

**Comment by EisenbergEffect** [comment]
Yes, that will apply the datepicker behavior to every view in your app after it is created.
