### ISSUE TITLE
1-2 second freeze after loading bundled app where mobile browsers become frozen.

### ISSUE THREAD

**Issue by ohjames** [aurelia/framework#356]
After the loading spinner vanishes the browser pauses for 1-2 seconds becoming completely unresponsive on mobile even with very tiny bundled apps. The more dependencies you add the longer this freeze is.

I assume this is due to the slower js JIT on mobile. I've seen this problem on many other frameworks in large projects though. One *great* way to work around this is via webpack's code splitting/lazy loading of chunks.

Essentially webpack scans all of your dependencies and determines which are loaded dynamically, then it spits out a number of bundled chunks automatically. This allows the browser to include the minimum possible code at any point without needing any manual configuration of bundles (as jspm currently requires).

You can read about webpack's code splitting functionality [here](https://webpack.github.io/docs/code-splitting.html) and there's a good explanation of the technique [in this github comment](https://github.com/sighjs/sigh/issues/18#issuecomment-174623992).

**Comment by Vheissu** [comment]
Given that the latest Webpack support allows bundles to be created and split bundling, tree shaking, etc. I think this one can be closed @EisenbergEffect

**Comment by ohjames** [comment]
@Vheissu you just think it can be closed or you have conclusive evidence the problem has gone away? Others are reporting the issue is still bad with webpack. If my team spends the time to port from JSPM to WebPack and finds the situation is still bad, we'll be very unimpressed :P

**Comment by ohjames** [comment]
Ah sorry I thought this was the bug relating to the delay on startup! Brexit and the ensuing lack of sleep has made me a bit crazy.
