### ISSUE TITLE
checkbox is not triggering a change event when updated through binding

### ISSUE THREAD

**Issue by Aaike** [aurelia/framework#36]
template:
```
<input type="checkbox" id="checkbox2" checked.bind="isChecked" ui-checkbox>
```
everything works correctly , the browsers checkbox is being updated when the VM property changes

The code in the behavior is simply listening to the checkbox element's onchange event like so :
```
this.element.addEventListener('change',function(){
      console.log("CHANGE");
});
```

that event does get triggered when i click the actual checkbox , so it is listening correctly.

i have a button below the checkbox that toggles the VM property and updates the checkbox , 
when that happens the change event is not triggered.

here is a repository that shows this setup:
https://github.com/Aaike/aurelia-test

template:
https://github.com/Aaike/aurelia-test/blob/master/src/welcome.html
behaviour:
https://github.com/Aaike/aurelia-test/blob/master/src/behaviors/ui-checkbox.js

**Comment by Aaike** [comment]
additional note : 
when Aurelia changes the checked property of a checkbox , does it simply change the checked property on the element or does it also dispatch a change when that happens ?

because i am listening to the onchange event on my checkbox , i am not detecting any changes if aurelia updates the binding ...

i'm just wondering because when i change the checked property of my checkbox in code, the change event is not triggered. i have to manually dispatch the change event right after property changes like so:
```
this.element.checked = !this.element.checked;
this.element.dispatchEvent(new Event("change"));
```

perhaps aurelia should dispatch a change event

**Comment by mvpspl619** [comment]
Same problem persists in a different issue. https://github.com/aurelia/framework/issues/30

@EisenbergEffect When someone binds to a property on the view-model from view, isn't it nice to have a listener on this property's changed event so Aurelia updates the DOM without waiting for the dirty checking to kick off ? 

I believe this would be how developers expect it to work. Better developer experience you see!

**Comment by Aaike** [comment]
I think this issue can be closed.
This seems to have been fixed somewhere along the way.

Here is [a plunkr that tests it](http://plnkr.co/edit/I7uJrI22OyoKyeHzO0Zf?p=preview).
