### ISSUE TITLE
make latest Docs app URL version indepedent

### ISSUE THREAD

**Issue by opcodewriter** [aurelia/framework#361]
With web-browser history it's very easy to go to an outdated Docs App, possibly missing features.
For example this example for "Declare Custom Element Without View-Model With Binding" is only in v1.1.4:    
```
<template bindable="name">
   Say Hello To ${name}
</template>
```
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/cheat-sheet
and it's missing in
`http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.3/doc/article/cheat-sheet`

Would be nice if the URL is something like 
http://aurelia.io/docs.html#/aurelia/framework/doc/article/cheat-sheet 
which always points to latest documentation.

**Comment by EisenbergEffect** [comment]
You can use `latest` in place of the version number to alway see the latest doc.
