### ISSUE TITLE
Slow loading on Edge and firefox

### ISSUE THREAD

**Issue by sidman1988** [aurelia/framework#362]
Playing with aurelia using the startup kit and the navigation skeletons, and one thing i seem to notice no matter how small the app is, how slow its loading on Edge and firefox. It works great for me on chrome but those other two browsers are having some performance problems on the initial startup. Ive seen other bugs related to this issue, was there any solution for this? Is there any way all aurelia modules can be loaded outside of jspm? Or just in fewer files? The System.js module loader seems to be the issue, and becuase aurelia loads so much files from jspm it may be causing that slowness.

**Comment by doktordirk** [comment]
@sidman1988 seems you didn't bundle http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/bundling-your-app-for-deploy

**Comment by martingust** [comment]
What @doktordirk said. Also if you are targeting Edge you should use `bluebird promises` instead of the native implementation, which is extremly slow on Edge. Microsoft is working on a fix for this but in meantime its recommended to use `bluebird`. 

http://bluebirdjs.com/docs/getting-started.html

**Comment by sidman1988** [comment]
Both solutions work especially the bluebird library it made a huge difference in edge, it loads in a second for me now.
