### ISSUE TITLE
npm-centric getting started?

### ISSUE THREAD

**Issue by silverbucket** [aurelia/framework#363]
It seems like the only efficient way to get started with aurelia is to download a `zip` file, which to me seems pretty cumbersome in this day and age when most frameworks can be installed with a simple `npm` command. From looking at the downloaded package.json there are 10s of packages which need to be installed to get the aurelia suite working properly. This is seems like quite a burden. Can we not have a meta package which users can `npm install` and begin using aurelia? Even if it's a command-line tool which then sets up the directory structure, it would be a better start than having to download a `zip` file.

Likewise, if this repository is the *front facing* repository (it's not exactly clear that it is, based on the rather ambiguous naming) it should have a getting started portion of the README for users to easily get up and running with a few steps. I'd submit a PR but I'm not sure what the preferred method of install is other than download the `zip` file.

**Comment by jedd-ahyoung** [comment]
@silverbucket While Aurelia can be installed using a zip file, it can also be installed using git. One can clone the skeleton-navigation repository and generate a clean installation from there (using either Typescript or ES2015).

If you would like to get set up without the skeleton-navigation repository, check out [this answer on StackOverflow](http://stackoverflow.com/a/32081822/677526) - this should help you get started without having to rely upon the skeleton-navigation repo.

Finally, if neither of those float your boat, there's alway Yeoman - the command-line generator for any project you want. Yeoman has an aurelia generator here: https://github.com/zewa666/generator-aurelia

**Comment by EisenbergEffect** [comment]
We are planning a metapackage, however, if you want to use npm, then using npm 3 or any npm package that flattens dependencies, you can simple `npm install aurelia-bootstrapper` and you will get everything you need to start with.

**Comment by atsu85** [comment]
@EisenbergEffect, what did You mean with "metapackage"? I guess http://wiki.ros.org/Metapackages is not what You meant? 

I haven't looked into @zewa666's Aurelia [project generator](https://github.com/zewa666/generator-aurelia) that is implemented with Yeoman, but i'm wondering what's wrong with that approach? I've seen great [presentation](https://www.youtube.com/watch?v=baVOGuFIe9M) about [Angular 1 Yeoman generator](https://github.com/yeoman/generator-angular) and i was very impressed. It also supports alternative languages for TypeScript and CoffeScript.

**Comment by astanciu** [comment]
I was looking for something similar. I cannot find any examples of how to setup an Aurelia project from scratch or outside of a pre-made kit. I tried the yo generator and all it did is generate the exact files from the starter kit with the getting started guide (nested router example).

Also, did you mean `**jspm** install aurelia-boostrapper`? This was the closes I could come to doing it from scratch.

**Comment by silverbucket** [comment]
@EisenbergEffect as this was focused on the fact that we are lacking /documentation/ on getting started, is it fair to close the issue?

We still don't have any documentation (that I can find) that provides any way to get started other than download the zip files, which I think can be problematic.

**Comment by silverbucket** [comment]
Essentially every way that you can get up and running with aurelia deserves making note of:

1. yeoman
2. manual jspm and/or npm set
3. zip file

**Comment by silverbucket** [comment]
@EisenbergEffect in response to your suggestion to just `npm install aurelia-bootstrapper` ... I tried that, and it leaves me in a completely different state than pretty much every example out there. The purpose of this issue was to bring light to the fact that there really doesn't seem to be much in the way of explaining the setup that exists in the zip files, so when you run into any issues, or want to update your packages, you have a lot of issues that could otherwise be avoided (or that could be learned from) with clear documentation on setting up your own aurelia environment.

**Comment by EisenbergEffect** [comment]
The zip files are present. We are also working on a CLI. Note that using `npm install aurelia-bootstrapper` requires NPM3 or the use of the `dedupe` package to ensure a flat package tree, which is required for client-side development. This is basically how Webpack works.

**Comment by silverbucket** [comment]
@EisenbergEffect yeah, I know we have the ZIP file, that's all we really have that's documented. All of the examples are based on the way this ZIP file is set up (systemJS & jspm). And doing an `npm install aurelia-bootstrapper` doesn't leave you in a similar place at all. Likewise, a `yo aurelia` command still gets you set up in a different way. Therefore, I would think more comprehensive documentation on the various ways of getting up and running with aurelia should be created. I'm willing to help with this, but right now it's still pretty obtuse because on one hand you have a "download everything already set up in a zip file and avoid running 'jspm install'" option, with nothing else documented, or what you say `npm install aurelia-bootstrapper` with no other details.

If you look at any other web framework, they have much more comprehensive/educational getting started or installation documentation. That's the reason I filed the issue in the first place.

I think onboarding is quite important, and in the case of aurelia, even though it's true you can get up and running quite quickly by downloading the ZIP file, it leaves the developer quite oblivious to the way things are set up, which can lead to frustration when they need to change something. Having documentation on manually getting yourself into the same layout as the ZIP file can help to reconcile this gap.
