### ISSUE TITLE
Cache busting and Navigation-Skeleton

### ISSUE THREAD

**Issue by joakimhallberg** [aurelia/framework#364]
When using SystemJS for cache-busting as suggested here https://github.com/aurelia/framework/issues/94, it breaks the navbar in the skeleton-navigation application. The navbar is no longer visible and doesn't get loaded into the view. There are no errors in dev-tools. The html gets loaded 
![image](https://cloud.githubusercontent.com/assets/7515153/13783751/35cd0638-ea92-11e5-891e-cb9b5ceb83e1.png)
but it never get loaded into the app/dom.
![image](https://cloud.githubusercontent.com/assets/7515153/13783809/799740fe-ea92-11e5-9692-d7d5f2087e0b.png)

Not sure if the problem is with SystemJS or with the Aurelia (I think). The problem might be with the double '?bust=x'
Requested url is http://localhost:9999/dist/nav-bar.html?bust=1457991836617?bust=1457991836617
I don't think the Framework is the correct place for issue, but not sure what subsystem it should go into.

If there is a new a new suggested and supported way to do Cache busting, I would love to hear it.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating-resources #203](https://github.com/aurelia/templating-resources/issues/203) via [**ZenHub.io**](https://www.zenhub.io/)
