### ISSUE TITLE
Templating/binding detaches incorrect nested component when splicing from a databound array

### ISSUE THREAD

**Issue by hiscodeness** [aurelia/framework#365]
When removing an item from an array bound to custom components with `repeat.for="..."`, it is possible that an incorrect nested component is detached. This occurs only if the nested component is contained within another component that doesn't implement `attached()` or `detached()`. The workaround is to add one of these methods.

I ran into this issue while developing an application and managed to reproduce it here:
https://gist.run/?id=e88ade5198924c5d2cf2

**Comment by hiscodeness** [comment]
Note that in the reproducable, when the alert is shown, the values remaining in the custom component are incorrect. After the alert is dismissed, correct data is bound to the custom component. Nevertheless, when `detached()` is called, it is called in the wrong viewmodel, so any custom logic in that method will be applied in an incorrect context.

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust I'm going to guess this has to do with some of the recent optimizations around lifecycle. Can you take a look?

**Comment by jdanyow** [comment]
reproducible in more recent build: https://gist.run/?id=173e62d9adfc6b776814

**Comment by mPisano** [comment]
got further after googling...

C:\Work2\Cifc\Spa>npm install glob

site looks up, but some errors below


npm WARN package.json concordia-freight-client@1.0.0 No license field.
glob@7.0.3 node_modules\glob
??? path-is-absolute@1.0.0
??? inherits@2.0.1
??? once@1.3.3 (wrappy@1.0.1)
??? inflight@1.0.4 (wrappy@1.0.1)
??? minimatch@3.0.0 (brace-expansion@1.1.3)

C:\Work2\Cifc\Spa>gulp watch
[23:11:45] Using gulpfile C:\Work2\Cifc\Spa\gulpfile.js
[23:11:45] Starting 'build'...
[23:11:45] Starting 'clean'...
[23:11:45] Finished 'clean' after 20 ms
[23:11:45] Starting 'build-system'...
[23:11:45] Starting 'build-html'...
[23:11:45] Starting 'build-css'...
[23:11:45] Finished 'build-css' after 67 ms
"C:/Work2/Cifc/Spa/src/resources/file-upload.ts(2,27): Module '\"dropzone\"' resolves to a non-module entity and cannot be imported using this construct."
"C:/Work2/Cifc/Spa/src/mawbs/mawb-toolbar.ts(78,22): Cannot use 'new' with an expression whose type lacks a call or construct signature."
"C:/Work2/Cifc/Spa/src/mawbs/mawb-toolbar.ts(94,5): Cannot use 'new' with an expression whose type lacks a call or construct signature."
"C:/Work2/Cifc/Spa/src/dashboard/edit-configuration.ts(63,36): Property 'findIndex' does not exist on type '{ Origin: string; Dest: string; }[]'."
"C:/Work2/Cifc/Spa/src/dashboard/edit-configuration.ts(72,41): Property 'findIndex' does not exist on type '{ Origin: string; Dest: string; }[]'."
"C:/Work2/Cifc/Spa/src/dashboard/dashboard-data.ts(98,44): Property 'findIndex' does not exist on type '{ Origin: string; Dest: string; }[]'."
"C:/Work2/Cifc/Spa/src/dashboard/dashboard-data.ts(130,7): Cannot invoke an expression whose type lacks a call signature."
"C:/Work2/Cifc/Spa/src/dashboard/dashboard-data.ts(136,7): Cannot invoke an expression whose type lacks a call signature."
"C:/Work2/Cifc/Spa/src/dashboard/configuration.ts(38,14): Property 'assign' does not exist on type 'ObjectConstructor'."
"C:/Work2/Cifc/Spa/src/dashboard/chart.ts(2,27): Cannot find module 'chartist'."
[23:11:48] Finished 'build-html' after 3.12 s
[23:11:48] Finished 'build-system' after 3.2 s
[23:11:48] Finished 'build' after 3.23 s
[23:11:48] Starting 'serve'...
[BS] Local URL: http://localhost:9000
[BS] Serving files from: .
[23:11:49] Finished 'serve' after 1.23 s
[23:11:49] Starting 'watch'...
[23:11:49] Finished 'watch' after 336 ms
