### ISSUE TITLE
E2E tests failing "asynchronous script timeout" for script in waitForRouterToComplete

### ISSUE THREAD

**Issue by bpierce88** [aurelia/framework#369]
Newbie here ...to both Web development and Aurelia. So far seems like it'll be fantastic to work with.

I'm playing with the aps.net5 skeleton, and it seems like issue #183 still isn't fully resolved. I added a new page to the nav that does nothing except set and render the heading, and I added an e2e test just to check the title (a copy/paste of the users page test that does the same). Running the e2e tests repeatedly, they will sporadically fail with an "asynchronous script timeout" error. If I copy/paste the e2e tests into another file (eg: demo2.spec.ts) such that they run twice ...then it almost always fails if I run the e2e tests even 2 or 3 times in a row. It is the script in "waitForRouterToComplete" that times out.

To confirm I wasn't doing anything too dumb, I tried instead modifying the users view to be just as simple (deleting the constructor and activate, simplifying the view to only show the header ...and deleting a unit test that then wouldn't compile) and the e2e tests sporadically failed in the same way. In both cases I confirmed that I could browse to those simple pages without issue in Chrome, so all was wired up alright.

This may not be a practical issue - maybe it won't fail as I add more functionality to my pages ...but wanted to let you know in case there is something going on that could impact more than just e2e tests. Btw, apologies if there are protocols I'm not following ...I don't think I've ever actually posted on a dev board like this.

Important note: I had manually updated the chromedriver to 2.21.371459, as the tests wouldn't run at all until I did that.

**Comment by EisenbergEffect** [comment]
Are you still experiencing this problem? I think we did some work around this recently so it may have gotten fixed as a side-effect of some other work.

**Comment by bpierce88** [comment]
Thanks for following-up. I regret to inform that, for my current project, I switched to Angular 2 a while back. That's not a knock on Aurelia. I'm a relative newbie to Web development, and I just found the Angular doc easier to work through as I was getting started (also it was a bit easier to find answers/examples online, as may be expected given the relatively large community of Angular users). I hope to give Aurelia another look on a future project when I won't need quite so much hand-holding.


________________________________

**Comment by trenneman** [comment]
@EisenbergEffect -- are you sure it has been fixed? Using the latest aurelia packages I get a `Failed: asynchronous script timeout: result was not received in 30 seconds` when testing the **bundled** app:

```
import {MyPageObject} from './pageobject/my.po.js';

describe('myPage', function() {
  let po;
  beforeEach(() => {
    po = new MyPageObject();
    browser.loadAndWaitForAureliaPage('/');
    $('.nav.nav-pills li:nth-of-type(1)').click(); // buttons route to subpages
    browser.waitForRouterComplete();
  });

  it('test', function() {
    ...
  });
});
```

When I run the same e2e test on the **unbundled** version, all tests are successful.

---

Leaving the `browser.waitForRouterComplete()` out of the `beforeAll` makes the tests pass for the **bundled** app, but failing for the **unbundled** app.

---

Now, when I add a timeout to the `waitForRouterComplete()` by changing it into
```
function waitForRouterComplete() {
  return Promise.race([ // add a race
    browser.executeAsyncScript(
      'var cb = arguments[arguments.length - 1];' +
      'document.querySelector("[aurelia-app]")' +
      '.aurelia.subscribeOnce("router:navigation:complete", function() {' +
      '  cb(true)' +
      '});'
    ),
    new Promise(resolve => setTimeout(() => resolve(false), 20000)) // add a timeout
  ])
  .then(function(result) {
    return result;
  });
}
```
both the bundled and unbundled app pass the tests.

Any idea what I could be doing wrong?
