### ISSUE TITLE
Could Aurelia "bootstrap" an html page from the server?

### ISSUE THREAD

**Issue by bradbarrow** [aurelia/framework#37]
In one of the apps I'm working on, we use Rails to handle routing. So:

`foo.com/bars` routes to `bars_controller#index` and renders `views/bars/index.html`

I'm using Angular at the moment which allows me to define `ng-app` on the body element of my Rails layout. This means Angular will bootstrap and parse everything inside the body tag. 

Thus, if I had a `<bars></bars>` element in `views/bars/index.html` that Rails serves, once Angular kicks in it'll do what's necessary to make that element function.

I know that's not the traditional way to use Angular, as it's more of a library approach rather than a framework (wherein Angular controls routing, views etc).

It works for me at the moment though.

I'm curious to know whether Aurelia could achieve something similar?

Given an index page as follows: 

```
<!doctype html>
<html>
  <head>
    <title>Example</title>
  </head>
  <body aurelia-app>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.baseUrl = 'dist';
      System.import('aurelia-bootstrapper');
    </script>

    This is content served by Rails for instance. I'd like to have aurelia-app act on
    this content as ng-app would.
    It'd mean I could render custom elements in my Rails templates

    <custom foo="bar"></custom>

    Aurelia would bootstrap and sort them out for me.
  </body>
</html>
```

The way Aurelia currently behaves, is that the app would bootstrap, and the contents of `<body>` would be replaced by the template from `app.html` (assuming "get started" setup).

My question, is can you apply the Aurelia `app.js` view model to the DOM that is already inside the body tag, rendered by Rails?

**Comment by EisenbergEffect** [comment]
I don't plan to change this behavior. However, that doesn't mean that you won't be able to accomplish something similar using an alternate technique. One thing we are looking into is improving our templating loading and location logic. So, we hope to support in-page templates in the future. The idea here is that you could include a `<template></template>` element in the page that you had rendered with Rails and then when we loaded up your app, we could located that template and use it as the view. We don't have this yet, but it's something we are working on. We need this to handle various bundling strategies as well, so it all plays together in the end.

**Comment by PWKad** [comment]
@bradbarrow Sorry I didn't see this until just now but you can use a `main.js` to set what to use as the root of your application as well with the second parameter - 

```
aurelia.start().then(a => a.setRoot('app', appHost));
```

**Comment by smolinari** [comment]
I'd be very interested in the in-page template loading technique too. I was under the impression Aurelia could do it too. Sad to hear it can't...yet.

Scott

**Comment by lneffa** [comment]
Any updates for in-page template loading? Would help re-architect some build pieces for a Rails app
