### ISSUE TITLE
Should bound values of dashed "attributes" be assigned to dashed properties or camelCase 

### ISSUE THREAD

**Issue by jpray** [aurelia/framework#370]
Hi!

I have a bunch of vanilla custom elements that I'm working on using within an Aurelia app.  A standard interface for custom elements are HTML attributes, so I was a bit surprised to see that something like
```
  <my-vanilla-custom-element
    bar=${aValueForBar}
  </my-vanilla-custom-element>
```
would assign the value of aValueForBar to the bar property and not set the attribute.  But after reading more I came to accept that this was probably done for performance reasons, though I do think it would still be nice to have an option to have it set the attribute without having to declare a custom attribute.  I assume this is technically feasible?  I wouldn't mind taking a stab at implementing it if you all think it makes sense and could provide some direction.  Maybe an alternative syntax to have templating behave this way?

Also, during this exercise I noticed that when doing something like this

```
  <my-vanilla-custom-element
    foo-bar=${aValueForFooBar} 
  </my-vanilla-custom-element>
```
this['foo-bar'] will contain the value.  Here's a [plunker](http://plnkr.co/edit/y3BRrPOelHejTrTJZmXn?p=preview) illustrating this.

For my own vanilla custom elements, I set them up so that dashed attributes are automatically bound to camelCase properties, similar to Polymer.

from https://www.polymer-project.org/1.0/docs/devguide/properties.html
> Attribute names with dashes are converted to camelCase property names by capitalizing the character following each dash, then removing the dashes. For example, the attribute first-name maps to firstName.
 
 Currently it seems there is no easy way for me to set the foo-bar attribute nor the fooBar property of the element.  I can do it by defining customAttributes but I don't want to have to define dozens of customAttributes simply to achieve this behavior. 

Thoughts? Thanks!

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating #300](https://github.com/aurelia/templating/issues/300) via [**ZenHub.io**](https://www.zenhub.io/)
