### ISSUE TITLE
ref binding to child object causes unbind failure

### ISSUE THREAD

**Issue by snortblt** [aurelia/framework#372]
Using the **ref** binding to a child object of a vm property as shown works until the view is destroyed. 

`  <li class="ex-choice-src" ref="option.element">
        <span class="ex-choice-drag">${option.text}</span>
   </li>`

When the view is being unbound, the context object in the following snippet from aurelia-binding.js (beta 1.2.2) is null.

`AccessScope.prototype.evaluate = function evaluate(scope, lookupFunctions) {
      var context = getContextFor(this.name, scope, this.ancestor);
      return context[this.name];
    };`

**Comment by EisenbergEffect** [comment]
I believe this has already been fixed. Run `jspm update` to get the latest and please try again. Thanks!

**Comment by snortblt** [comment]
Yeah, maybe not so much. I updated prior to posting this and again just now. Doesn't work over here. I will say that the parent object is transitive and part of the dependency tree itself. I suspect that may not be supported.

`@computedFrom('currentIndex','childVM', 'childVM.hasAnswer')`

**Comment by EisenbergEffect** [comment]
We will need a repro to see the actual problem so we can fix it.

**Comment by EisenbergEffect** [comment]
I don't think computedFrom supports property paths until after the upcoming release is out. So, there may be a problem with your decorator as well.

**Comment by snortblt** [comment]
Ugh. My bad. I was confusing the computedFrom issue with this other issue, but thanks for reporting status on that too. I need to get more sleep.

The unbinding issue continues to be a problem after updating.

**Comment by EisenbergEffect** [comment]
Can you provide us with a simple reproduction. I imagine @jdanyow could fix this pretty easily if we had this.

**Comment by snortblt** [comment]
Thanks. Let me see what I can do with the navigation skeleton app to repro.

**Comment by snortblt** [comment]
[Aurelia Bug 372 demo.zip](https://github.com/aurelia/framework/files/186534/Aurelia.Bug.372.demo.zip)

This exhibits the behavior. Just click the 'Next View' button, which will load a new child view. Every other view instantiation will throw the exception.

**Comment by jdanyow** [comment]
Thanks @snortblt, I've distilled your sample down to this:
https://gist.run/?id=de82773d5e8fd23c4ff7

Looks like we need to move [these lines](https://github.com/aurelia/templating/blob/master/src/view.js#L154-L155) to the end of the view's unbind method.
