### ISSUE TITLE
<content> doesn't work within if-bindings

### ISSUE THREAD

**Issue by genne** [aurelia/framework#375]
Using the content tag within an if-binding doesn't seem to work at all, the result becomes empty. Changing "if" into "show" makes it work fine.

For example:

**app.html:**
```
<template>
    <require from="./test.html"></require>
    <test>content</test>
</template>
```

**test.html:**
```
<template>
    <div if.bind="true"><content></content></div>
</template>
```

Expected result would be "content", but instead it's empty.

Tested in aurelia-framework 1.0.0-beta.1.1.4.

**Comment by EisenbergEffect** [comment]
No. That is a characteristic of the shadow dom. The content selection points have to be static. They cannot be added ore removed dynamically. If you want to hid them, then consider using `show.bind` instead.

**Comment by genne** [comment]
I would at least recommend adding some error message when this happens, since it's not obvious why it doesn't work (I spent at least one hour troubleshooting). Or some documentation covering it?

**Comment by EisenbergEffect** [comment]
@AshleyGrant Since you are working on the custom elements documentation. Can you include a note in those docs on the above, namely that content elements have to be statically defined and cannot exist inside template controllers like if, repeat, with, etc?

**Comment by AshleyGrant** [comment]
Will do.

**Comment by atsu85** [comment]
> I would at least recommend adding some error message when this happens

Having the error (either message or even thrown error) would also be nice.

**Comment by EisenbergEffect** [comment]
I'm actually not sure it's possible to reliably message or error in this case, especially if the browser is implementing native shadow dom.

**Comment by atsu85** [comment]
Yeah, actually i also had some doubts, if it is possible to do it at runtime. 

I'd really love to see a linter for Aurelia, that would detect problems at build-time (here i don't mean JS errors, that can be detected with TypeScript, other types of errors, for example wrong usages or missing methods/properties, etc.). Probably it is worth creating separate issue for that (in framework repo)?

**Comment by EisenbergEffect** [comment]
Yes, that is a great idea. I think...maybe create that on our tools repo?

**Comment by atsu85** [comment]
> I'd really love to see a linter for Aurelia, that would detect problems at build-time 

> Yes, that is a great idea. I think...maybe create that on our tools repo?

Done: https://github.com/aurelia/tools/issues/31
