### ISSUE TITLE
SystemJS.import should now be System.import in documentation

### ISSUE THREAD

**Issue by wshayes** [aurelia/framework#377]
In the docs - there are several references to SystemJS.import - should be System.import now.

**Comment by EisenbergEffect** [comment]
I talked to Guy about this. The newer versions of SystemJS have SystemJS as an api to shield you from breaking changes coming in the module loader spec. For example. System.import is going away. Unless he has changes something again...

**Comment by EisenbergEffect** [comment]
You may need to update your loader `jspm dl-loader --latest` will do that for you.

**Comment by wshayes** [comment]
Thanks!

**Comment by wshayes** [comment]
FYI - the latest Skeleton uses System.import.  I was using the latest Skeleton and cutting and pasting the documentation example for Progressive Enhancement (which uses SystemJS.import() and getting the SystemJS doesn’t exist error.

**Comment by EisenbergEffect** [comment]
This is so frustrating. Did you jspm install from scratch on that skeleton and have it not give you the latest loader? Or did the loader get in there some other way? I just want to try to determine how you got a non-up-to-date loader so I can try to fix the skeletons to prevent that from happening.

**Comment by EisenbergEffect** [comment]
To clarify, I'm not frustrated with you...but with jspm/system.js.

**Comment by wshayes** [comment]
Never worried about the direction of your frustration - though I’ve earned it on occasion :)

On a Mac:

skeleton-navigation-1.0.0-beta.1.1.6
npm@3.7.3
jspm v0.16.15

When I changed System.import to SystemJS.import: "Uncaught ReferenceError: SystemJS is not defined"
