### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by carlskii** [aurelia/framework#38]
I've been using Bluebird in some of my other projects to provide support for promises. I'm looking to build a new project using Aurelia and will need support for Promises. Since the whole ECMA6 and 6to5  thing is still so new, I'm struggling to understand the best way to add this to my Aurelia project. 

I have the navigation app up and running and wondered if you could provide an example within that app that maybe does something like this: 

```javascript
var Promise = require("bluebird");
var Request = Promise.promisify(require('request'));

function callhttp(host) {

    var cert = " ";

    var options = {
        url: 'https://' + host,
        method: "GET",
        headers: {
            'User-Agent': 'request'
        }
    };

    return Request(options).spread(function (response, body) {
        if (response.statusCode == 200) {
           // console.log(body)
            console.log(response.connection.getPeerCertificate().subject.CN)
            return {
                CN: response.connection.getPeerCertificate().subject.CN,
            };
        } else {
            // Just an example, 200 is not the only successful code
            throw new Error("HTTP Error: " + response.statusCode);
        }
    });
}


var join = Promise.join;
join(
    callhttp("www.google.com"),
    callhttp("www.microsoft.com"),
    callhttp("www.adobe.com"),
    function (first, second, third) {
        console.log([first, second, third]);
    });
```

**Comment by carlskii** [comment]
OK  - I probably should have read the documentation in more detail which mentions adding the 'bluebird' library to the beginning of my pages. I assume I add this to my html pages and not load them as modules using 'requirejs' ?

**Comment by EisenbergEffect** [comment]
Correct. Add it to your actual html page before the system.js script tag. That should do it for you.

**Comment by carlskii** [comment]
Thanks. I'll give that a try.
