### ISSUE TITLE
Question  - Sourcemaps from other libraries getting lost on aurelia startup

### ISSUE THREAD

**Issue by mgerwinn** [aurelia/framework#380]
As soon as we call aurelia.setRoot() our sourcemaps from other libraries getting lost. So debugging becomes a nightmare. I posted an image below about the exact source that is getting removed:
![image](https://cloud.githubusercontent.com/assets/836048/14021678/d953eb22-f1dc-11e5-9cee-9b5b5bb2b390.png)

Any help is highly appreciated!

**Comment by EisenbergEffect** [comment]
My guess is that it has to do with the script tags being in the body and the body content being replaced with you call setRoot. To avoid that, set the aurelia-app attribute on a child div of the body with no content or content that is safe to remove.

**Comment by npelletm** [comment]
Fun, I was face with exactly this this issue two days ago and I set the aurelia-app attribute on a child div :)

**Comment by mgerwinn** [comment]
@EisenbergEffect: Thanks for your fast response. Working fine now!
