### ISSUE TITLE
Binding break when an object attribute is deleted

### ISSUE THREAD

**Issue by hadrienl** [aurelia/framework#381]
If I bind an object attribute in a template and I delete one, then the view is no more updated. You can see [a demo in this plnkr](http://plnkr.co/edit/MiszbNYkrNBwLCLuYmnP?p=preview). The first button set value to null, the second button delete the value.

**Comment by jdanyow** [comment]
Deleting properties that are being observed is not supported. The binding system rewrites properties it's observing with a getter and setter.  This enabled the binding system to intercept property assignments and handle the property change.  Deleting the property will put things in a bad state.

**Comment by EisenbergEffect** [comment]
Also, you don't want to delete properites, usually for performance sake, because that changes the runtime's "shape" understanding of the object, which is costly. It's better to simply set the property's value to undefined or null.
