### ISSUE TITLE
unit test custom element

### ISSUE THREAD

**Issue by ariovistus** [aurelia/framework#382]
I am trying to unit test a custom element here: https://github.com/ariovistus/aurelia-mask/tree/dev
I am injecting Element and the test fails with 

```
Error: Error invoking Element. Check the inner error for details.
------------------------------------------------
inner error: TypeError: Illegal constructor
...
```

**Comment by EisenbergEffect** [comment]
You will need to use Element as the DI key but not as the actual constructor since it's a base class that cannot be directly instantiated. So, if you want a spy, for your test, you could do someting like this

```
container.registerInstance(Element, createElementSpy());
```

**Comment by ariovistus** [comment]
ah, thank you

**Comment by silbinarywolf** [comment]
For those who stumble upon this in the future, my solution was:
```
aurelia.container.registerInstance(Element, document.createElement);
```
