### ISSUE TITLE
Error loading Custom Element without View-Model

### ISSUE THREAD

**Issue by 5ebastianMeier** [aurelia/framework#385]
When trying to register a Custom Element without a View-Model by using globalResources JSPM seems to attach ".js" to the file path. The .html file gets correctly copied into the /dist folder.
Could this be caused by the recent JSPM update?

This is what the error looks like:
```
system.src.js:4597 GET http://localhost:9000/templatename.html.js 404 (Not Found)
```
```
system.js:4 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:9000/templatename.html.js
	Error loading http://localhost:9001/templatename.html.js
    at o (http://localhost:9001/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:9001/jspm_packages/system.js:4:13219)
```
I looked it up in the cheatsheet and followed the exact same pattern.
My configuration looks like this:
```
import 'bootstrap';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .globalResources('./templatename.html');


  aurelia.start().then(() => aurelia.setRoot());
}
```

**Comment by EisenbergEffect** [comment]
This was a regression. We've got a fix and it's going out tonight or tomorrow morning. Hang in there.

**Comment by 5ebastianMeier** [comment]
Glad to hear that. Thanks for the info!

**Comment by 5ebastianMeier** [comment]
@EisenbergEffect I updated jspm and got it running again. But the dist folder is no longer the base path for referencing relative file paths - I have to include it in the path. 

Is this by accident or by design?

**Comment by EisenbergEffect** [comment]
Hmm. That's unexpected. @ahmedshuhel Can you look into this?

**Comment by ahmedshuhel** [comment]
@5ebastianMeier Could you show me what is the change you had to make it work with the following information? 
- The previous path and current path. .
- JSPM version
- SystemJS version

Thanks

**Comment by 5ebastianMeier** [comment]
Before I expected this configuration to work:
```
    .globalResources('./templatename.html');
```
Now I have to specifiy the dist folder as well (so the base path seems to be the project root folder)
```
    .globalResources('./dist/templatename.html');
```
My example file templatename.html is located in the same folder as the main.js in the skeleton project.
The path is: 
```
    [ project-folder ] /src/templatename.html
```
I guess my phrase above may have been misleading in terms of JSPM - I didn't update jspm for my example to work, but I updated its dependencies via jspm update since Rob mentioned he had the fix in the pipe.

Anyways my JSPM version is 0.16.15 and it uses SystemJS v0.19.6.
