### ISSUE TITLE
Inheriting a class having autoinject causes weird behavior

### ISSUE THREAD

**Issue by Zenorbi** [aurelia/framework#387]
See https://github.com/Zenorbi/aurelia-autoinject-bug for the example.

This example shows, how `@autoinject` on a base class causes aurelia to only render the first custom element inherited from that base class and also swizzle its content.

To test the weird behavior:

1. See how both of the custom element's render below.
2. Open `base-class.ts` and remove the comment from `@autoinject`
3. See how not only one of the custom element renders, but also the content of it is wrong (First one containing the second one's content)

**Comment by Zenorbi** [comment]
I updated the repo showing the behavior. Removed the skeleton-navigation example, removed gulp, just a simple `jspm install` and you can open up the `index.html`.

**Comment by EisenbergEffect** [comment]
Inheritance of custom elements is not supported.
We have also made some improvements in how DI handles inheritance.
