### ISSUE TITLE
Contributions of Durandal

### ISSUE THREAD

**Issue by ZoolWay** [aurelia/framework#389]
Hello,

I got a small question about the contributions to Aurelia from Durandal Inc. 
Over 70% of the commits are done by Rob. Does he merge the work of other Durandal contributors so these are not visible on GitHub themselves or does really 70% of the work rely on sole Rob Eisenberg?

This is no offense, I just would like to get a feeling how much Aurelia really relies on Rob alone.

Best regards,
Ricky

**Comment by EisenbergEffect** [comment]
Hello Ricky,


A couple of notes for you:


* All the original code was contributed by Rob in early 2015, so the remnants of that original large commit are still around. However, most development is no longer done by Rob.
* It’s important to realize that Aurelia is split across 40+ repositories. So, if you are looking at only the “framework” repository, you aren’t seeing the majority of the work being done. Various members of the Aurelia team manage and do almost all development on certain repositories.
* For the most part Rob manages the pull requests that come in. So, the artifacts of that also disproportionally affect things.
* Durandal Inc. has three founders, of which Rob is one. 
* There are about 20 developers as part of the core team: contributors, trainers, authors, etc.


Rob

**Comment by ZoolWay** [comment]
Hello Rob!

Thanks for your fast response!

The size of the whole ecosystem with all those repositories has slipped my attention, sorry.
That makes sense and gives me a better overview of the project. So my first impression that this relies on a very large scale on you Rob was mislead.Thanks for pointing out!

Best regards,
Ricky

**Comment by EisenbergEffect** [comment]
Ricky,


Thanks for checking out the platform!


Rob
