### ISSUE TITLE
3rd party plugins have stopped working

### ISSUE THREAD

**Issue by bhatnagar-ankur** [aurelia/framework#397]
Hi,

Last night I have updated the jspm packages for aurelia framework. After the update all my 3rd party plugins like material.spinner, twitterTypeahead, bootstrap-datepicker and many more have stopped working.
Every plugin is throwing error 'Unhandled promise rejection' and respective function is a not a function.

I have attached the image showing error for of the plugin.

![unhandled_promise_rejection_error](https://cloud.githubusercontent.com/assets/2298169/14462135/4f7801d4-00e3-11e6-9ab7-55f21b71a901.PNG)

Curernt Version for the framework:
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.1",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.0",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.1",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.1",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0",

**Comment by EisenbergEffect** [comment]
I'm not sure this is an Aurelia issue. I built an app with plugins just fine yesterday. It could be related to system.js somehow. Make sure you run `jspm update` to ensure you have the latest and also check that you don't have any forks. @ahmedshuhel can you look into this further? @bhatnagar-ankur We will need a specific set of instructions or a sample that reproduces the problem.

**Comment by cdennig** [comment]
I bet this has nothing to do with Aurelia. Check if jQuery is imported (as dependency in your 3rd party plugins) multiple times. There should be just one „source“, NPM or GitHub. If you have Github **and** NPM, jQuery is pulled into your browser several times…overwriting the previous instance.

I had the same issue some time ago and just manually updated the dependencies to pull in the „NPM Version“.

Cheers,
Chris

**Comment by bhatnagar-ankur** [comment]
@EisenbergEffect thanks for the quick reply.

@cdennig last night even I tried the same thing, and it has started working.
and you are correct two different versions of jQuery were getting downloaded, one from npm and other from github. Thanks for sharing your experience.

Ankur
