### ISSUE TITLE
useView doesn't load views relative to the view model?

### ISSUE THREAD

**Issue by glen-84** [aurelia/framework#398]
I have a structure like this:

```
/src
    /app
        /view-models
            app.ts
            index.ts
        /views
            app.html
            index.html
    /events
        /matches
            /view-models
                view.ts
            /views
                view.html
    index.html
    main.ts
```

For the `index` module, I load the view using `@useView("../views/index.html")`.

For the `view` module, if I try to do the same thing, it tries to load the view from `/assets/app/views/view.html` instead of `/assets/events/matches/views/view.html` – shouldn't it load the view relative to the view model?

Note: `assets` is the folder that the files are built into.

**Comment by EisenbergEffect** [comment]
It should indeed. Please create a simple production using the es2016 nav skeleton and attach it here. That will help us locate the bug and fix it. Thank you.

**Comment by glen-84** [comment]
Here we go: https://github.com/glen-84/skeleton-navigation/commit/354ee8a6fed929f32dadb7bec702a58de170fe0b
