### ISSUE TITLE
Font-Awesome and Bootstrap won't load or are outdated?

### ISSUE THREAD

**Issue by SamuelCaudenberg** [aurelia/framework#403]
Hi guys,
I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/10906724/14711302/1f878b82-07d9-11e6-8d81-7ad74053bee8.png)
I'm sure its an easy fix, I just don't know how to fix it.
The error popped up after the node_modules downloaded a new version and I decided to use an older folder of node_modules.

Thanks in advance.

**Comment by wshayes** [comment]
Make sure that the libraries are actually available and that your versions are correct (e.g. you do have npm/font-awesome@4.5.0 not something else like 4.4.0).

**Comment by EisenbergEffect** [comment]
Check in your config.js. As @wshayes says, your version numbers are probably off.

**Comment by SamuelCaudenberg** [comment]
I have font-awesome@4.6.1 but everywhere I am looking in the project the version is correct, except when I run it the app is asking for a 4.5.0 version

**Comment by SamuelCaudenberg** [comment]
Status update, I was indeed missing something and the font-awesome errors are gone.
The Bootstrap errors are still here, I tried the same approach as with font-awesome but no succes :/

**Comment by doktordirk** [comment]
jspm i github:twbs/bootstrap@^3.3.6
