### ISSUE TITLE
The browser combine styles importing in different views 

### ISSUE THREAD

**Issue by svzosorio** [aurelia/framework#404]
I have two templates' types, one type use materialize.css to create some design aspects and another type use material-design-lite. But, if I stay in a page usign materialize and go to material-design-lite based the browser combine the two css styles so if I reload the page the browser don't combine two css styles

login.html `<template> <require from="some.css"> </require </template>`

nav.html  `<template> <require from="another.css"> </require> </template>`

**Comment by EisenbergEffect** [comment]
All that the require element does is ensure that the referenced .css is loaded before the view renders. It does not remove css. We have an issue to track this as a potential future improvement.
