### ISSUE TITLE
Trigger bootstrap after 3rd-party re-render

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/framework#405]
I'm working on a Java Server Faces application, gradually replacing parts of it with Aurelia. The problem is that when JSF re-renders parts of the page with custom Aurelia elements in it, they aren't bootstrapped. Is there some way I can signal Aurelia to bootstrap the re-rendered piece of HTML? I tried:

```js
System.import('aurelia-bootstrapper').then(function(im) {
  im.bootstrap(function(aurelia) {
    aurelia.enhance({}, document.getElementById("re-rendered"));
  });
});
```

but I got

```
Uncaught (in promise) Error: A BindingLanguage must implement inspectAttribute(...)
    at a.BindingLanguage.a.inspectAttribute (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:4:31189)
    at a.ViewCompiler.a._compileElement (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:5:15943)
    at a.ViewCompiler.a._compileNode (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:5:13513)
    at a.TemplatingEngine.a.enhance (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:6:7652)
    at eval (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:2:22418)
    at a.Aurelia.a.enhance (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:2:22336)
    at <anonymous>:4:13
    at eval (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:1:26287)
    at eval (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:1:24116)
    at d (http://localhost:8080/myvevida/frontend/bundles/aurelia.js:1:24086)
```

**Comment by EisenbergEffect** [comment]
Yes. You would use enhance for this, but the framework configuration still needs to happen before calling it. Look here for an explanation: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.2/doc/article/app-configuration-and-startup/8

**Comment by RomkeVdMeulen** [comment]
I may have been unclear: I've already bootstrapped Aurelia once at page load. Now, because of some user interaction, new HTML has been placed in the page which contains Aurelia elements I want to pick up. Do I reuse the `Aurelia` instance I used during my first bootstrap? Something like:

```ts
let globalAurelia: Aurelia;

bootstrap((aurelia: Aurelia) => {
	aurelia.use
		.defaultBindingLanguage()
		.defaultResources()
		.globalResources(myCustomElements);

	aurelia.start().then(() => {
		aurelia.enhance({}, document.body);
		globalAurelia = aurelia;
	});
});
```

and then at some point:

```js
globalAurelia.enhance({}, document.getElementById("re-rendered"));
```

Or should I start a completely new Aurelia instance every time the HTML changes?

**Comment by RomkeVdMeulen** [comment]
After going through the source files, I've tried this:

```js
import {Aurelia, TemplatingEngine} from "aurelia-framework";

let templatingEngine: TemplatingEngine;

bootstrap((aurelia: Aurelia) => {
	aurelia.use
		.defaultBindingLanguage()
		.defaultResources()
		.globalResources(myComponents);

	aurelia.start().then(() => {
		aurelia.enhance({}, document.body);
		templatingEngine = aurelia.container.get(TemplatingEngine);
	});
});
```

and then when HTML changes:

```js
templatingEngine.enhance(document.getElementById("re-rendered"));
```

which seems to work like I want.

Is this a good approach to use? Or could it lead to side-effects?

**Comment by EisenbergEffect** [comment]
Yes, you got it :) That's exactly the API to use. It doesn't return an "element". It returns a View instance. You can use that to automate the UI that you just enhanced. If you ever need to dispose things, you'll want to call  `unbind` to unbind the view.
