### ISSUE TITLE
Binding not working

### ISSUE THREAD

**Issue by dstroyrofworlds** [aurelia/framework#407]
My test project [https://github.com/dstroyrofworlds/ntui](Github).

I have a custom element called cs-modal in the widgets directory.
I a have a parent view that has a property. This property must be two way binded with cs-modal element.

The cs-modal is a semantic ui modal.
The property will be a boolean that if set to true will show the modal.

I have a property changed method on cs-modal that prints out the value when changed.

If the value is initially false in the parent view, nothing happens in cs-modal.
If it is true, it is printed as true in cs-modal.

Scenario:
In parent view the property is false.
The parent view has a button to set the property to true.
I click the button nothing happens, cs-modal does not get the change.

If the property name on cs-modal, i.e. the bindable property is named "show", it does not work at all, even if the property is initially true.

If I name the property "showModal" it at least gets the initial true value change of the property, but nothing else.

**Comment by jdanyow** [comment]
If you setup a small reproduction [here](https://gist.run/?id=7542e061bc940cde506b) we can try to help

**Comment by dstroyrofworlds** [comment]
I made a gist, [here](https://gist.run/?id=53ce02fb5b71c349efdb4935d5583489)

The click  function sets the variable xxx, but is not the variable I declare in the app.js.

Passing the click function onto a child element seems to run it in its own context, recreating the xxx variable.

I put on console.logs to show what is happening.

Is Aurelia working as expected or have I not read the docs thoroughly enough ?

I would expect the click function to run in the context of the app object.

**Comment by dstroyrofworlds** [comment]
(Doh). Found solution.

To pass a function to a child use click.call="click()" and not click.bind="click".
