### ISSUE TITLE
valueChanged callback in custom attribute is triggered when used in repeat.for attribute and repeated array is unshifted

### ISSUE THREAD

**Issue by micnil** [aurelia/framework#408]
## Overview of the Issue
Issue occurs when iterating a list of objects with the `repeat.for` attribute in the view, and you create a `<div>` element with a custom attribute each iteration and bind a value from the current object of the list to that attribute. If a new object is inserted to the beginning of the list (with the `unshift()` function), then all of the valueChanged callbacks are called, instead of just the first one.

# How to reproduce 

The program below repeats through a list of objects with IDs. And for each object, the redSquareCustomAttribute adds a red square when id changes. after 2.5 seconds app.js adds another id to the beginning of the objects list, and all the idChanged callbacks are called, adding a second square to the view. I would expect only the idChanged callback for the added object to be called. 

app.js:

	export class App {
		message = 'hello world';
		objects = [
			{'id': 2},
			{'id': 3},
			{'id': 4},
			{'id': 5}
		]
		constructor(){
			setTimeout(()=>{ this.objects.unshift( {'id': 1} ); }, 2500);
		}
	}

app.html:

	<template>
		<require from="./red-square"></require>
		<div repeat.for="obj of objects">
			<div red-square="id.bind: obj.id"> ${obj.id} </div>
		</div>
	</template>

red-square.js

	import {bindable, inject} from 'aurelia-framework';

	@inject(Element)
	export class RedSquareCustomAttribute {
		@bindable id;

		constructor(element){
			this.element = element;
		}

		idChanged(newValue, oldValue){

			console.log(`new value: ${newValue} old value: ${oldValue}`)
			// new value: 2 old value: null
			// new value: 3 old value: null
			// new value: 4 old value: null
			// new value: 5 old value: null
			// new value: 5 old value: null
			// 
			// After 2.5 seconds:
			// new value: 1 old value: 2
			// new value: 2 old value: 3
			// new value: 3 old value: 4
			// new value: 4 old value: 5

			let redSquare = document.createElement("div");
			redSquare.style.width = redSquare.style.height = '30px';
			redSquare.style.margin = '3px';
			redSquare.style.backgroundColor = 'red';

			this.element.appendChild(redSquare);
		}
	}

The same behaviour occurs if I concat to the list `this.objects = [{'id': 1}].concat(this.objects);`, if i use splice `this.objects.splice(0, 0, {'id': 1});` or if i first `push({'id': 1})`and then `sort((obj1, obj2) => obj1.id - obj2.id)`.

What I have to do to get my expected behaviour (I learned after several hours of messing around) is to reference the array with the `$index`:

	<div repeat.for="obj of objects">
		<div red-square="id.bind: objects[$index]"> ${obj.id} </div>
	</div>

Then everything workes fine! 

It seems like you are not binding to the object itself when using the `id.bind: obj.id` binding, but rather to the index in the repeated array?

Maybe this is expected behaviour, but it seemed strange to me so I though i'd let you know.

I use Chrome on Windows.

**Comment by EisenbergEffect** [comment]
I'm not surprised by this happening with concat because you are creating a new arrya and returning it. However, I am surprised that it's happening in the other cases. @martingust @jdanyow Do you have any idea about this? I haven't seen this before.

**Comment by jdanyow** [comment]
The repeat is using the optimized "in-place process items" array strategy because the repeated template does not have any html behaviors that use bind/unbind/attached/detached. This strategy never moves elements and only adds or removes elements from the end.  Existing element's binding context's are updated which is why the valuechanged method is being called.  Adding an `unbind` to the custom attribute method forces the repeat to use the standard logic:
https://gist.run/?id=96c81cd187c0636befb1de48533c10f4

I wonder if we should only use the "in-place process items" array strategy when the array instance changes (make it more specific to dbmonster like scenarios) and not use it for array mutation.  This may have already changed with some of the recent repeat refactoring.

**Comment by jdanyow** [comment]
confirmed latest refactoring won't change this behavior.  Maybe we should always use the standard logic for array mutations:

```diff
  instanceMutated(repeat, array, splices) {
-    if (repeat.viewsRequireLifecycle) {
      this._standardProcessInstanceMutated(repeat, array, splices);
-      return;
-    }
-    this._inPlaceProcessItems(repeat, array);
  }
```
https://github.com/aurelia/templating-resources/blob/master/src/array-repeat-strategy.js#L172

**Comment by martingust** [comment]
Yes, agree on always `_standardProcessInstanceMutated` on changes. And then we might be able optimize that to have the logic to detect moved views in similar way as instance changes is handled with the recent changes.

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust Can you give me a status on this? Has this been fixed?

**Comment by jdanyow** [comment]
not yet
