### ISSUE TITLE
Suggestion: Typings tool support

### ISSUE THREAD

**Issue by WorldMaker** [aurelia/framework#409]
I wasn't sure which repository to add this issue at it applies to most of them. Hopefully this is a fair place to put this suggestion.

[Typings](https://github.com/typings/typings) is a package management approach to typing information; it inherits from `tsd` but adds better support for typings packages to be installed from elsewhere on GitHub (beyond just DT), from npm, etc. It's very similar to JSPM, but for typing definitions.

To support `typings` it should just be a matter of adding the appropriate `typings.json` files to the repositories.

**Comment by cecilphillip** [comment]
@WorldMaker looks like the skeleton-navigation repo does https://goo.gl/0JshD0

**Comment by EisenbergEffect** [comment]
Yes, all our TS skeletons now use Typings.

**Comment by WorldMaker** [comment]
What I was suggesting was non-ambient package installation for the Aurelia libraries themselves.  The skeletons don't exclude the jspm_packages directory from the tsconfig.js, but in my experience I have many reasons to exclude jspm_packages, particularly as it grows, and I want to install Aurelia typings and dependencies directly with typings, as non-ambient preferably so I can remap if needed, similarly to some of the mapping support with jspm.

Essentially, I'd like appropriate typings.json in the Aurelia libraries to install them as typings packages.

**Comment by EisenbergEffect** [comment]
If you would like to put together a pull request to get it all working, we would certainly welcome that :)

**Comment by StrahilKazlachev** [comment]
Wouldn't continuing the conversation here #360 be more appropriate?
