### ISSUE TITLE
kit-es2016 -> http://localhost//127.0.0.1:8080

### ISSUE THREAD

**Issue by jkleiser** [aurelia/framework#410]
This may not be an Aurelia bug, maybe just something in kit-es2016. I just followed the "Getting Started" instructions, and when I do the `http-server -o -c-1`, my Safari (9.1) opens a new tab on "http://localhost//127.0.0.1:8080", which Safari fails to handle. That URL of course is bad, but it took me a little while to spot it.
I'm using Mac OS X 10.10.5.

**Comment by jkleiser** [comment]
I now tested this using Mac OS X 10.8.5, and I got the same bad URL. When I correct the URL, it works.

**Comment by jkleiser** [comment]
I now tested this using Mac OS X 10.11.4, and I got the same bad URL. When I correct the URL, it works.

**Comment by EisenbergEffect** [comment]
This seems like an issue with the http-server module rather than Aurelia itself. If possible, please report the issue to that project so they can help find a fix.

**Comment by jkleiser** [comment]
Done: https://github.com/indexzero/http-server/issues/271
