### ISSUE TITLE
How to clean aurelia resources manually?

### ISSUE THREAD

**Issue by padzikm** [aurelia/framework#414]
Hi, how can I unbind and detached main aurelia page manually? Aurelia app is used as a part of a webpage, so when navigating to other pages I want to close and clean all aurelia resources. I managed to unbind from history via router.history.deactivate() and this one left. I'd like to trigger these events in main page level, so it would recursively trigger nested view-models events

**Comment by EisenbergEffect** [comment]
If you refresh or fully navigate to another page, there's no need to tear down aurelia.

**Comment by padzikm** [comment]
Yes, but I can't navigate to or refresh a page - it's a spa application, where only part of a page (say content of <div id="content"></div> on main page) is dynamically loaded. As a result I'd like to write that dynamic part in aurelia, but when dynamic content on main page is changed and different part is loaded into <div id="content"></div> I must close and clean all aurelia's resources - how can I manage that? I tried to manually invoke lifecycle events on controller instance, such as unbind and detached, but still not whole html created by aurelia is unbind, so there may be also some event listeners left unbind.

**Comment by EisenbergEffect** [comment]
I'm a bit confused...you are writing a SPA but you aren't using Aurelia's capabilities to help with the multi-page aspect of the app? 

There's no api to explicitly do what you want currently. However, if you get a reference to the Aurelia object, you can get the root component. From there you can detach and unbind the root component. That should tear down most of it.
