### ISSUE TITLE
Allow global viewStrategy and viewLocator configuration during framework configuration

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/framework#415]
Currently, in order to change the ViewLocator strategy, it's necessary to change the prototype method of the ViewLocator inside of the framework configuration block. I propose a solution that would allow us to hook into the aurelia configuration block - something like this, perhaps:

```
import {MyViewStrategy} from 'myViewStrategy';
import {MyOtherViewStrategy} from 'myOtherViewStrategy';

export function configure (aurelia) {
    aurelia.useDefaultViewStrategy(MyViewStrategy);
    aurelia.registerViewStrategy(myOtherViewStrategy);

    // useViewResolver, or some other name
    aurelia.useViewResolver((origin: Origin) => {
        var moduleId: string = origin.moduleId;
        var name = moduleId.split("/")[moduleId.split("/").length-1]
            .replace("ViewModel","View").replace(".js","").replace(".ts","");

        return `Views/${name}.html`;
    });

    ...
}
```

This would also require changes here: https://github.com/aurelia/templating/blob/master/src/view-locator.js

I think this would be a nicer API - easier for people to find and use. Further, I think it would insulate users from any future API changes. Thoughts are welcome.

**Comment by EisenbergEffect** [comment]
If you can do it without breaking changes, submit a PR and I'll review.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Any chance to submit a PR for this? We are wrapping things up for RC....

**Comment by EisenbergEffect** [comment]
Ok, this missed the RC, so we can only add it if you can do it in a non-breaking way. Also, it needs to get done in the next week or two. @jedd-ahyoung

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : 4weeks } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```
