### ISSUE TITLE
'host' does not exist on type Aurelia

### ISSUE THREAD

**Issue by cecilphillip** [aurelia/framework#417]
the host property is missing off of the d.ts file for the Aurelia object which causes build errors when compiling typescript code.

I'm accessing the attribute in a similar way to how it's shown in [this post](http://patrickwalters.net/creating-multipage-apps-using-aurelia-2/)

I don't know if this was intentional or not, but figured I'd ask

**Comment by EisenbergEffect** [comment]
It looks like it's not declared in the API. Would you like to submit a PR to add it?

**Comment by cecilphillip** [comment]
Sure. That should be a quick fix
