### ISSUE TITLE
Application loaded event

### ISSUE THREAD

**Issue by ejsmith** [aurelia/framework#419]
Not sure what the right repo is for this, but I would like to have aurelia send out a event aggregator event when the app is completely loaded and the main view has rendered.

**Comment by EisenbergEffect** [comment]
There's a DOM event that is raised called `aurelia-composed`. Try registering for that. We can't use the EventAggregator because that is technically a plugin and may not be installed. But, you can simply add an event listener for `aurelia-composed` and that should give you what you want.

**Comment by ejsmith** [comment]
Thanks @EisenbergEffect !
