### ISSUE TITLE
jspm issue installing the nav-demo

### ISSUE THREAD

**Issue by gizmoboy** [aurelia/framework#42]
Hi, I was able to get the basic onstallation on the demo completed through npm install, but when I try the jspm command, I get the following (I noticed skonn had this issue in #6, but it was partway down the thread, and not specifically addressed):

C:\Users\jeff\WebstormProjects\AureliaDemo>jspm install -y
     Creating registry cache...

err  Error locating jspm:aurelia-bootstrapper
     ReferenceError: ui is not defined

warn Installation changes not saved.

C:\Users\jeff\WebstormProjects\AureliaDemo>

**Comment by gizmoboy** [comment]
Windows 7, running in WebStorm 9 terminal (but same problem happens in DOS command prompt)

**Comment by EisenbergEffect** [comment]
I have no idea what this is. It sounds like a jspm issue. Make sure you have the latest version of node and jspm. Make sure you have git installed. Try doing a clean jspm install of the project and see if that changes anything.

**Comment by cmichaelgraham** [comment]
also try running jspm from `git bash` shell.

Useful Git Links
Install GitHub for Windows: https://windows.github.com/ 
Install Git for Windows  http://git-scm.com/download/win

**Comment by gizmoboy** [comment]
Wow... works fine from the git bash shell, but fails from powershell, CMD, and WebStorm terminal.

Thanks, Michael!

**Comment by cmichaelgraham** [comment]
Awesome !! :)

**Comment by hdale** [comment]
Had the same problem using CMD. Thanks Michael, git bash shell worked fine.
