### ISSUE TITLE
Use gulp as minify

### ISSUE THREAD

**Issue by jaroslawziolkowski** [aurelia/framework#423]
Hi,
does exists some manner to preload libraries which I load always as one file?

I mean that I can minify some aurelia modules to one file (only one request) and load by system.js only parts of my applications.

Of course I know, how I can add libraries to one file by gulp but I don't know how I can force auelia to use preloaded libraries?

I'm using aurelia in php laravel framework and this is very helpful to limit requests.

Thanks in advance.

**Comment by EisenbergEffect** [comment]
You can use our bundler. Have a look at this article: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/bundling-your-app-for-deploy
