### ISSUE TITLE
Templating-Router required in app without router

### ISSUE THREAD

**Issue by thelgevold** [aurelia/framework#428]
I have used the navigation skeleton as a baseline for my application. I removed all the sample code and replaced it with my own application code.

My app works well, but I have started experiencing with the bundling strategy and want to reduce the size of the aurelia bundle to an absolute minimum. I started removing items like aurelia-router, bootstrap, jquery etc from the include array in bundles.js. This works well and helps reduce the size. However, when I try to remove templating-router and history-browser I am getting errors since the bundle tries to load those at runtime. 

Why do we need those in an app where there is no router? I though these were part of the router dependencies? 

Also, would it make sense to add a "tree shaking" feature like we have in systemjs builder? The motivation would be to get the bundler to shed any unreferenced code to further optimize the bundle.

**Comment by thelgevold** [comment]
Another observation is that even though the router is omitted from the include in bundles.js, I still see references to aurelia-router in aurelia.js

**Comment by EisenbergEffect** [comment]
You need to configure the app so as not to use these features. If you have `use.standardConfiguration()` in your `main.js` or don't have a main (which causes the framework to use the standard configuration), then all the history and route modules will be included. See the section here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/app-configuration-and-startup/1 on "Manual Configuration" You will need to not call the router or history apis.

**Comment by thelgevold** [comment]
Yes, that makes sense.
 I was calling standardConfiguration. 
Switched to a more minimal configuration like you suggested

```
 aurelia.use.defaultBindingLanguage().defaultResources();
        aurelia.start().then(function () {
          return aurelia.setRoot();
        });
```

This is tandem with 
```
"dist/aurelia": {
      "includes": [
        "aurelia-framework",
        "aurelia-bootstrapper",
        "aurelia-fetch-client",
        "aurelia-templating-binding",
        "aurelia-polyfills",
        "aurelia-templating-resources",
        "aurelia-loader-default",
      ],
      "options": {
        "inject": true,
        "minify": true,
        "depCache": false,
        "rev": false
      }
    }
  }
```

Seems to be the most minimal configuration I can achieve.  I ended up with aurelia.js weighing in at 85k after gzip, which is pretty good. 

Thanks for your help.
