### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by pravin-d** [aurelia/framework#429]
The API Documentation does not seem to be complete. Any idea when will it be completed ? I'm trying to read on pipelines, etc. Docs give only a very brief idea. No Idea how to proceed

**Comment by EisenbergEffect** [comment]
Did you look here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/cheat-sheet/7

**Comment by pravin-d** [comment]
Hi Rob,

let me check it out.. thanks for the info
