### ISSUE TITLE
aurelia-http-client example

### ISSUE THREAD

**Issue by carlskii** [aurelia/framework#43]
Hi,

I'm looking for a decent SPA framework for small internal project. I've wasted hours trying to get my head around Ember.js, Angular.js. Being new to SPA's both of these frameworks seem like a massive overkill for me, not to mention the complexity especially with Ember. They both seem like their trying to be all things to all men. 

So Aurelia looks very interesting, except for the dependancy injection bit, which I'm struggling to get my head around. 

```javascript
import {HttpClient} from 'aurelia-http-client';

export class WebAPI {
    static inject() { return [HttpClient]; }
    constructor(http){
        this.http = http;
    }

    return getAllContacts(){
        return this.http.get('uri goes here');
    }
}
```

Would you mind providing a simple working example of this (just a simple HTTP GET) in the "getting started" navigation-app to help me understand how to splice things together? 

Ultimately my app will need to make multiple HTTP requests and then correlate the returned data in order so I'll need to include the ability to deal with promises too.

Thanks for what could be a productivity game changer.

**Comment by EisenbergEffect** [comment]
Did you have a look at the flickr view model on the skeleton-navigation?

**Comment by carlskii** [comment]
Arh no not in detail but I will do. I'll do that next.

**Comment by carlskii** [comment]
I just had a look at the Flickr example. It sort of makes sense. I don't quite get how the URL gets passed into to library though. Looks a bit like magic. :)

**Comment by EisenbergEffect** [comment]
The url is just passed into the jsonp call.
