### ISSUE TITLE
aurelia-babel-ie11-loading-problem

### ISSUE THREAD

**Issue by cizmiak** [aurelia/framework#433]
We are experiencing aurelia loading problem in IE11(versions: 11.306.10586.0 or 11.0.9600.18321) (IIS 8.5 or 10 used). Application freezes on index.html until you move mouse over the content a while or open developer tools. Using es6-promise or bluebird does not solve the issue. We have found workaround that you can enable by uncommenting css link and span dummies in index.html. You can find reproducible example here: https://github.com/cizmiak/aurelia-babel-ie11-loading-problem or create minimal aurelia environment to reproduce the problem like this:

npm init /// all defaults
npm install jspm --save-dev
jspm init /// baseUrl: "./", transpiler: "babel"
jspm install aurelia-framework aurelia-bootstrapper

````
index.html:
<!DOCTYPE html>
<html>
	<head>
		<title>Aurelia</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- <link rel="stylesheet" href="dummy.css"> -->
	</head>
	<body aurelia-app>
		<!-- <span class="dummy"></span> -->
		
		<script src="jspm_packages/system.js"></script>
		<script src="config.js"></script>
		<script>
			System.import('aurelia-bootstrapper');
		</script>
	</body>
</html>

app.html:
<template>
	<h1>${heading}</h1>
	<button click.delegate="exclaim()">Exclaim!</button>
</template>

app.js:
export class App {
	constructor() {
		this.heading = 'nothing';
	}
	
	exclaim() {
		this.heading = this.heading.replace(".", "");
		this.heading += '!';
	}
	
	activate() {
		this.heading = 'Aurelia activated...'
	}
}

dummy.css:
.dummy {
    animation-name: dummy;
    animation-duration: 1s;
    animation-iteration-count: 1;
}

@keyframes dummy {
  0% {
    background-color: transparent;
  }
}
````

**Comment by EisenbergEffect** [comment]
This is a known issue with system.js. We recommend that you use RequireJS or Webpack to work around the issue. We are working on other alternatives as well.
