### ISSUE TITLE
globalResource paths must be prefixed with ./

### ISSUE THREAD

**Issue by forestmarie** [aurelia/framework#434]
On the latest non-breaking-changes bits.  Reference below: 

```
import { Aurelia } from "aurelia-framework"; //eslint-disable-line no-unused-vars

export function configure(aurelia) {
    let resources = [
        "./nav-menu",
        "./footer",
        "./active-state",
        "./pagination",
        "./../recruiter/recruiter-transfer-popup", 
        "./../queues/queue-timer",
        "./../recruiter/recruiter-online-offline",
    ];
    aurelia.globalResources(resources);
}
```
I don't feel I should need to use ```"./../recruiter/recruiter-online-offline"```  Before updating, ```../recruiter/recruiter-online-offline``` worked just fine. 

Thanks.

**Comment by EisenbergEffect** [comment]
@ahmedshuhel This seems like a breaking change in the code you added in FrameworkConfiguration. Can we fix this?

**Comment by EisenbergEffect** [comment]
@forestmarie I'm diving into this now. What's the easiest way to reproduce this? Do I just create a plugin with `../` as part of a resource path?
