### ISSUE TITLE
Strange IE11 issue - Activate Does not trigger every time the view is loaded. (But works fine when the F12 tools is open)

### ISSUE THREAD

**Issue by theodarsundeep** [aurelia/framework#435]
First thing first, Awesome framework! Thanks for all your efforts in building this. Have been using this for quite sometime and really like the way this framework is built and its simplicity for developing applications.

Have been facing this issue with "activate" life cycle event, as shown in the sudo code below I am making a data service call on the server to get some data to load it in my UI view. This code works fine , makes the service call and get the data in chrome and Firefox every time I go to the view. But in case of IE11 I have this strange issue, the "activate" event gets called only the first time I visit the view and subsequent visits doesn't trigger the event and I keep seeing the old cached view and doesn't get refreshed. Strangely everything works fine as expected when I have the F12 developer tools console window open. Can some one please look into this and let me know what is going wrong here ? and suggest accordingly.

Note : I am using the "aurelia-http-client" to make the server REST API calls. I have also tried removing all the console.log messages & disabling developmentLogging from my application source , but still the issues exists.

``````javascript
import {MyDataService} from "./DataService/MyDataService";
import {inject} from 'aurelia-framework';

@inject(Element,MyDataService)
export class Welcome {
    heading = 'Simple Welcome Page for Aurelia';
    
    constructor(el,dataservice) {
        this.elem = el;
        this.dataService = dataservice;
    }

    
    activate()
    {
        //console.log('activate called');
        return this.dataService.getVizualizationData()
                                 .then(vizData => {
                                     this.vizData = vizData;
                                 });
    }
}
```

**Comment by fabioluz** [comment]
It seems that another thing is breaking your app after the first time it's loaded. Probably, it happens when you set `this.vizData`. Show the html code of your view.

**Comment by theodarsundeep** [comment]
Apology wasn't able to reply back earlier. Thanks for you response.

I am still facing this issue , I have nothing much great on the HTML, below is the code. Have a JQGrid component that binds the vizData.
``````html
<template>
    <require from='./Components/jqgrid'></require>
    <jqgrid id="gridContainer" uidata.bind="vizData"></jqgrid>
</template>
```
Please note : I have this issue only in IE & everything works fine when I have the F12 developer tools is open.

**Comment by Vheissu** [comment]
@theodarsundeep If you pull down the skeleton and test it out in IE, are you able to replicate the issue? Seems to me that maybe something else is at play here, as I personally haven't run into such an issue myself in IE11.

**Comment by theodarsundeep** [comment]
I was planing to do that. I will create a new application from the skeleton and try to replicate the issue and share the code, so that we can narrow down the issue and investigate further. Thank you!

**Comment by theodarsundeep** [comment]
@Vheissu I have create the sample application using the latest released Aurelia RC and I am able to reproduce this issue on IE. You can access the code from my repo [here](https://github.com/theodarsundeep/Theo.RnD.Aurelia.IEIssue) 

Have created this using the Aurelia CLI using the ASP.NET Core options. You can verify that application has two views "Welcome" & "Users". In the Activate event of the users view-model I make a data service call "getAllUsersData" which just calls the back-end ASP.NET REST WebApi implemented in the same application. The Response from this API is displayed on the view.

When you run and browse this from IE , you will notice that the each time we visits the "users" page the api is only called for the first time and subsequent visits the REST API is not called. When you have the F12 developer tools open in IE , then every time you click on "Users" the API is getting called. 

I was suspecting that the issue would be with the activate not getting triggered in IE, hence to verify that I added a counter in the welcome view model to verify if activate gets called and there the counter works fine (Just Stored the Counter in the sessionStore for testing). Which confirms that activate does get triggered fine in IE, Now I am suspecting that this behaviour has something to do with aurelia-http-client which I am using in the "Data Service" to make the service call. Please verify and let me know whats going wrong here and if I am missing anything.

Thank you!

**Comment by EisenbergEffect** [comment]
This wouldn't be a problem with the http client. It's just a thin layer on the browser's abstraction. To me, this sounds like a caching issue. The browser may not be making the request and instead sending cached data.

**Comment by theodarsundeep** [comment]
@EisenbergEffect Thanks for commenting on the issue. Can you please let me know if there is any possible fix for this ?

**Comment by coder8keyboard** [comment]
Has anyone find a solution to this? I'm having he same problem. Only works in Developer Mode on IE11. 
Works fine on Chrome.
I'm using Edge.

**Comment by coder8keyboard** [comment]
ok, I've added the following to main.ts and it started working on IE:
(<any>Promise).config({
  warnings: {
    wForgottenReturn: false
  }
});
