### ISSUE TITLE
TS hints use @type and not @param (at least in Atom)

### ISSUE THREAD

**Issue by doktordirk** [aurelia/framework#436]
All those nice parameter descriptions in the doc blocks aren't displayed in the Typescript hints as TS (at least with Atom) uses @type and not @param. 

Since Typescript has some importance i suggest to switch to @type and tell your api documentation builder to recognize @type as well. That seems easier than to tell the typescript guys to switch to @param.

**Comment by doktordirk** [comment]
@cmichaelgraham thoughts?

**Comment by niieani** [comment]
It works in Visual Studio Code, maybe it's a problem with Atom?:

<img width="746" alt="screen shot 2016-06-04 at 21 07 20" src="https://cloud.githubusercontent.com/assets/563469/15801533/6770d160-2a98-11e6-829a-b5ce3a14bdf3.png">

**Comment by niieani** [comment]
In fact, when I change `@param` to `@type` it stops working.

**Comment by doktordirk** [comment]
In your picture it doesn't actually. All the Text behind the @param is missing

**Comment by niieani** [comment]
No it's not. "The container to resolve from." is the text from `@param`.

**Comment by doktordirk** [comment]
your right. though i meant the hover hints which don't display that info. code completion works better. so, it's definitely param.
