### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andreujuanc** [aurelia/framework#437]
Hello,
I was really interested in this framework. But i just tried the typescript skeleton, and doesnt work. Fixed it (with help of a post on gh unreplied issue there) and now framework does not compile (i know its probably about the skeleton).

Im not creating an issue or need help or anything. I just wanted to know whats exactly the status of the project? Can i safely continue my endeavour to checkout aurelia? Is it production ready?

Thanks !

PS: project looks good.

**Comment by EisenbergEffect** [comment]
What exactly didn't work?

**Comment by andreujuanc** [comment]
I know it is a small issue, but these https://github.com/aurelia/skeleton-navigation/issues should be getting some priority, since some people use them when checking out the project.

I will check the js version of skeleton to see if it works, but I can say the typescript one has some entries already in the project's issues.

Cheers and thanks for the feedback.!
