### ISSUE TITLE
${0} not interpolated as number

### ISSUE THREAD

**Issue by bekite** [aurelia/framework#44]
When using variables that contain the value of 0, the content is not displayed in the view.
${0} should interpolate to the number 0 and not a falsy value.

**Comment by martingust** [comment]
What version of templating-binding are you running? This should have been fixed in the latest release: https://github.com/aurelia/templating-binding/releases/tag/0.8.4

**Comment by bekite** [comment]
You are right. I had version 0.8.3 installed. Should have updated my dependencies first before posting an issue.
