### ISSUE TITLE
Very long startup time on mobile devices

### ISSUE THREAD

**Issue by dpinart** [aurelia/framework#443]
Hi
I'm observing very long startup time on mobile devices, even when the app is locally deployed as an apache cordova app.

I have 3 aurelia middle/large apps, 2 of them using jspm + systemjs and the other one using webpack. All application need about 15 seconds to launch on a Samsung Galaxy Tab 10.1, even if deployed locally as cordova application.

**Comment by m-j** [comment]
I'm researching similar topic. Could you dive deeper into this using chrome dev tools timeline? I'm guessing that's more problem with system.js/jspm than Aurelia itself.

**Comment by atsu85** [comment]
Have You bundled the application? Are You using core-js (not aruelia polyfills)? Are You using bluebird? How big is the application in KB?

**Comment by dpinart** [comment]
I'm bundling all js,html and css in a single bundle.js, once minified is 2418 KB. Not using core-js amd,  I'm using bluebird. This app uses jspm + systemjs.

I was including bable-polyfill cause I did use async/await pattern, I thought that might be the proble but after getting rid of async/await and babel-polyfile and getting back to regular promises I couldn't see any siginificative improvement.

I have another larger app using webpack, the size is bigger, about 6MB, I think webpack bundles fonts, images,...). Startup time in mobile devices i very long too

**Comment by EisenbergEffect** [comment]
Wow. That certainly explains things. Don't do that :)
You need to break your app down into multiple bundles.

**Comment by Cheater912** [comment]
How does splitting up the bundles increase local loading performance?  Will the browser compile 2 or more separate bundles at the same time? Do you have any recommendations for the number of bundles or maximum size of one? Thanks, Rob

**Comment by EisenbergEffect** [comment]
Splitting the bundles means the browser doesn't have to download, parse and compile all the code upfront. Usually, I recommend that you look at how the app is used and take that information as a guide to how to break up the bundles. Usually, if your app is organized by feature area, that will also form a nice guideline. Other guidelines are things like user role.

**Comment by EisenbergEffect** [comment]
If your app has a login screen, you can bundle only the login screen and the core app together, for example. Then, as soon as the login screen loads (not waiting for the login even) you can trigger a download of the main app bundle.

**Comment by Cheater912** [comment]
Gotcha. Makes sense. I didn't think that would have such a big impact on local Cordova apps. Thanks for the speedy rely.

**Comment by EisenbergEffect** [comment]
If you have a lot of JS, the browser has to parse all of it up front. So, if you can delay that and only feed it what is necessary, that will help.

**Comment by Vheissu** [comment]
Seems to me this issue can now be closed @EisenbergEffect . The slowness issues have diagnosed as being caused by the inclusion of a massive polyfill and having a bundle size of well over 2mb.
