### ISSUE TITLE
Problem with content select

### ISSUE THREAD

**Issue by atticushome** [aurelia/framework#444]
Hey!

In the latest version I am having trouble with content select.
I have a custom element "modal", before I added custom content like this:
<modal><modal-content>THIS IS CONTENT</modal-content></modal>
<template><content select="modal-content"></content></template>

But now it is not working, am I missing something?

Thanks in advance.

**Comment by EisenbergEffect** [comment]
It's hard to say for sure without a more in depth example, but likely it's because our latest versions use shadow dom v1. You would need to update your custom elements to use that. For simple cases, that just means changing `<content>` elements into `<slot>` elements.

**Comment by atticushome** [comment]
That worked, thanks!

**Comment by javadbat** [comment]
please update this:
http://patrickwalters.net/enhance-an-existing-page-with-aurelia/
there is no comment in site to say
