### ISSUE TITLE
Typescript Kit not working when installing node packages

### ISSUE THREAD

**Issue by ptraceur** [aurelia/framework#446]
Hello,
its my first time using Aurelia and I wanted to use it with typescript, so I've download the kit from this page:

http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started

but when I try to install node packages with `sudo npm install` on my MacOS(and windows 10 too), it fails and returns the following warnings:

```shell
npm WARN package.json aurelia-beginner-kit-typescript@1.0.0-beta.1.0.1 No repository field.
npm WARN package.json aurelia-beginner-kit-typescript@1.0.0-beta.1.0.1 No README data
```

Could you help me with this, please?
Thanks.

**Comment by EisenbergEffect** [comment]
The beginner kit actually isn't designed to be installed. It's a standalone dist only for use with the tutorials. We are actually going to be removing them soon and replacing it with something else. In the mean time, please try out our CLI which should let you quickly create a new project and install everything.

**Comment by ptraceur** [comment]
Thanks for your quick answer, 
with your CLI can I use Aurelia with Typescript?
