### ISSUE TITLE
select multiple doesn't bind the selected options to the value in the view

### ISSUE THREAD

**Issue by elefantino** [aurelia/framework#447]
I tried to see the selected options in select multiple element in the view with the following code
View-model:
```
things = [
      {value: 0, name: 'aaa'},
      {value: 1, name: 'bbb'},
      {value: 2, name: 'ccc'}];
  selectedThing = [];
activate(info) {
  this.selectedThing = [1,2];
}
changeCallback(event) {
    console.log("change callback", JSON.stringify(this.selectedThing));
  }
revertTest() {
    this.selectedThing = [1,2];
    console.log("revert", JSON.stringify(this.selectedThing));
  }
```
View:
```
<select multiple class="form-control input-sm" id="th" value.bind="selectedThing"
          change.delegate="changeCallback($event)" style="width: 100%">
    <option repeat.for="thing of things" model.bind="thing.value">${thing.name}</option>
  </select>
  Selected: ${selectedThing}
  <button type="submit" class="btn btn-primary btn-sm" click.delegate="revertTest()">revert</button>
```
Only after I push revert button, it starts showing correct values in the view in Selected: ${selectedThing}
However console always shows the right value. It also works correctly with single select elements.
This is a link to gist:
https://gist.run/?id=0fc9051c8c266c89d15c60b1abda030b

**Comment by fabioluz** [comment]
The docs say to use model.bind for select multiple. Therefore, the select should be like this:

```
<select multiple='multiple' value.two-way="selectedThings" style="width: 100%">
   <option repeat.for="thing of things" model.bind="thing">${thing.name}</option>
</select>
```

However, the changes in `selectedThings ` don't seem to be reflected on the view. I believe that's because of the way aurelia sets the value. Perhaps @jdanyow can explain to us why this happen and if it's really the expected behaviour.

In the mean time, I could solve this using the a getter property that dirty-checks selectedThings. Like this:

```
get myThings() {
   return this.selectedThings.map(thing => thing.name).join(',');
   //or just return this.selectedThings
}
```

Running example: https://gist.run/?id=5a9c5cda449bfe3789a58122372a0a20

I also answered your question on SO. I hope this helps!

**Comment by csrow** [comment]
If you change from 'activate' to 'attached', it seems to work except for a strange behavior on selecting index 0 option.
The highlight does not show up until the second select click on the first option even though the element has been selected.  Other option select seems to work fine.  It's just the very first option select that is funky.

-------------------------------
Chi Sung Row


Date: Thu, 23 Jun 2016 23:49:32 -0700

**Comment by elefantino** [comment]
Both solutions are viable though I prefer select multiple to work properly without extra requirements (like dirty checking of each element or assigning data to variables the second time in attached() once the page is loaded) **as a singe select works**. I want to combine this select multiple element with a custom attribute (most likely select2)

**Comment by fabioluz** [comment]
I have edited my answer! Please, take a look

**Comment by jdanyow** [comment]
@elefantino check out [this](http://jdanyow.github.io/aurelia-examples/#/select-test) set of examples- it's an old version of aurelia, not bundled but all the code select element binding examples are up to date.
