### ISSUE TITLE
Please review my validation plugin

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/framework#45]
I've written [a small validation plugin for aurelia] (https://github.com/janvanderhaegen/aurelia-validation).
If you have some time, please do check it out. 
Code comments are welcomed on the aurelia integration (highly WOP though ).

Thank you

**Comment by EisenbergEffect** [comment]
@janvanderhaegen Haven't had time to review just yet. Quick question though...what is the general status? Is it working? What is done? What still needs work? What scenarios are supported?

**Comment by EisenbergEffect** [comment]
Ok, that was more than one question...to be fair.

**Comment by jdanyow** [comment]
@janvanderhaegen nice plugin- followed the guide in the readme, worked without any issues for me.

Created a pull request to reduce the dependencies:  https://github.com/janvanderhaegen/aurelia-validation/pull/23

**Comment by EisenbergEffect** [comment]
A cursory look.......looks good. @janvanderhaegen Are you interested in possibly making this an official aurelia library then? I've got some ideas about how we can make it a bit more extensible. We might also be able to do some things in the framework to make it more easy for you to match elements with validation rules. I'll need to think about that.

**Comment by janvanderhaegen** [comment]
Hey @jdanyow @EisenbergEffect 
Sorry about the non-response earlier, had some family issues that needed my full attention.
I'd love to make this part of the official aurelia bundle! Please give me one more weekend to do a bit of cleanup, need to make some stuff more extendible, refactor some, add a couple of minor features and add multi-language. I'll post back here after the weekend with the status!

Thanks

**Comment by BalassaMarton** [comment]
Awesome, I was looking for a validation style just like this. My biggest problem with validation libraries like the jQuery Validation plugin is that they expect the template author to define validation rules. In large business applications, any validation rules should be declared in the view model, and the template author should just lay out the fields, and make room for validation error messages. So I definitely vote for this plugin to be the official Aurelia validation logic. Maybe there could be a config value defining the name of the attribute that holds the validation result (I prefer prefixing framework properties with '$', so my choice would be `$validation`).

**Comment by janvanderhaegen** [comment]
Hey @BalassaMarton 
Thanks for the support and cheers!
I'm not 100% sure I completely understand your last sentence, could you perhaps drop a line or code of how you'd like your code to look?
I'll open an issue to follow up then :)

Thanks

jan

**Comment by BalassaMarton** [comment]
@janvanderhaegen: My bad, for some reason I misread the sample code, and thought that the `validation` property was created for the viewmodel by the plugin. So it's perfect after all :)
