### ISSUE TITLE
canDeactivate returns true but does not navigate to route

### ISSUE THREAD

**Issue by sjbthfc2** [aurelia/framework#450]
Hi,

Just starting to learn and understand Aurelia and currently working with routing, and I seem to have an issue with the `canDeactivate` hook. I have hardcoded it to return true to see if I could force it to work, and although the hook is getting called and returning true, the Router does not navigate to the intended route.

My route config is:
`
configureRouter(config: RouterConfiguration, router: Router) {
        config.title = 'MyApp';
        config.options.pushState = true;
        config.map([
            { route: '', name: 'home', moduleId: './home/home', nav: true, title: config.title },
            { route: 'search/:postcode', name: 'search', moduleId: './searchresults/searchresults', title: 'Restaurant search' }
        ]);
    }
`

I have a button click on my Home view which navigates to the Search component:
` this._router.navigateToRoute('search', { 'postcode': this.searchPostcode });`

And the Home component ViewModel has the canDeactivate hook which gets called and just returns true:
`canDeactivate() {        
        return true;
  }`

However, the Router does not navigate to the Search component. If I remove the canDeactivate hook from Home, the routing works fine.

I am using the RC1. Is this a bug or am I doing something silly?

Many thanks for your help and a fantastic framework.

**Comment by EisenbergEffect** [comment]
This is highly unexpected...considering we have a demo of this in the skeleton which I tested last night ;) I'll try to reproduce this. If you can zip up a repro and attach it here, that would help us in case it's something specific to your solution. Also, make sure to check the console to see if the framework is giving you any errors or info about what is going on. If you have a route error, that would stop navigation.

**Comment by sjbthfc2** [comment]
Hi Rob,

I have zipped up my solution, it is an ASP.NET Core RC 1 project however. On the Home View is a Find button, if you enter anything into the Postcode textbox and click 'Find a takeaway' you can hopefully see the issue. The HTML views are in the wwwroot folders, with TypeScript code copied from Appdev folder.

Many thanks.
[CanDeactivateReproAurelia.zip](https://github.com/aurelia/framework/files/331948/CanDeactivateReproAurelia.zip)

**Comment by EisenbergEffect** [comment]
We can't reproduce this problem and we would need a simple repro, based on the nav skeleton or gist that reproduces the issue. Most likely, it's not an issue with canDeactivate (since that has been working since day one as part of all our skeletons). I've used it constantly and tested it again in another project, but it works as expected. It could be that your new destination route is erroring out and thus the router is "recovering" by keeping the current route in place. Check the console and investigate your code to see if there's an issue like that.

**Comment by Senseye** [comment]
Could also be that you are calling "this.canDeactivate()" from within the ViewModel.
