### ISSUE TITLE
Docs section

### ISSUE THREAD

**Issue by Pablo-Ivan** [aurelia/framework#453]
See the [Docs](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/getting-started/1), right? It says "Based on your selection, you'll want to configure this documentation to show the appropriate language for all samples. Look at the top of this page. You will see a language selector. Be sure to select the language that matches the package that you downloaded." But wih the new HUB, that language selector dissapears.

**Comment by EisenbergEffect** [comment]
Ooops. We will need to correct that. We'll get it done soon. You can still select your language. It just directly next to the code sample.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/documentation #228](https://github.com/aurelia/documentation/issues/228) via [**ZenHub**](https://www.zenhub.com/)
