### ISSUE TITLE
Aurelia constantly update property with getter

### ISSUE THREAD

**Issue by bigopon** [aurelia/framework#456]
```javascript
export class App {
  constructor() {
    this.message = 'Hello World!';
  }

    get fullMessage() {
        return 'Halo ' + Math.random()
    }
}
```
```html
<template>
    <h1>${message}</h1>
    <p>${fullMessage}</p>
</template>
```
Above is the code I started for fun and I notice that Aurelia constantly update `<p>` textContent. I'm not sure if it's the right behavior

**Comment by EisenbergEffect** [comment]
If you use a `getter`, there's no way for Aurelia to know when it will change. It's impossible to observer that. So, it has to fall back to dirty checking instead of observation. As a result, it polls that property to see if it has changed and updates the UI if it has.

To avoid this you can either use a one-time binding or use signals to tell the binding system when to update.

**Comment by EisenbergEffect** [comment]
@jdanyow Please include some information about this scenario in the binding docs you are working on. Thanks!

**Comment by AshleyGrant** [comment]
To expand on @EisenbergEffect's comment: Typically, you can utilize our `computedFrom` decorator to explicitly tell Aurelia which class properties your getter depends on. An example of this is included in the `welcome` page of the Skeleton. However, for your example, using `Math.random()`, there's no way to avoid dirty checking other than using the `oneTime` binding behavior.
```html
<p>${fullMessage & oneTime}</p>
```

This may or may not accomplish what you want, in this specific instance. Granted, this is a bit of a contrived example to explicitly show the dirty checking. That being said, it is something that could likely happen in certain cases in a real app where you have, for example, a "x seconds|minutes|days ago" string. In a case like that, a good choice would be to use a signal as Rob suggested to tell Aurelia when to update the binding. An example of this is included in our docs [here](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-binding-behaviors/5).

**Comment by bigopon** [comment]
Thanks for clarifying. :+1:
