### ISSUE TITLE
In Edge, page will not load until I move the mouse over it

### ISSUE THREAD

**Issue by dkent600** [aurelia/framework#458]
In the Edge browser, Typescript transpiled for ES6, the page will not load until the mouse is moved.  If I watch in the javascript console, the "DEBUG [aurelia] Loading" messages pause until I move the mouse, then stop again when I stop moving the mouse.

Using JSPM/SystemJs.

Relevent code:  [Index.zip](https://github.com/aurelia/framework/files/344225/Index.zip)

**Comment by EisenbergEffect** [comment]
I believe this is an issue of Edge where it tries to optimize by not running certain code if the browser isn't active.
