### ISSUE TITLE
constructor in custom attributes receives {} as element if used with Polymer and Webpack

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/framework#459]
When I use Polymer with Webpack, the constructer of a custom element is passed {} as the element parameter.

```
@customAttribute('editable')
@autoinject
export class EditableCustomAttribute {
	
  constructor(element: Element){
```

The same code works well with Polymer and JSPM.

**Comment by EisenbergEffect** [comment]
I believe this is solved in the latest webpack setup. The pal-browser has to be loaded before the other modules are evaluated.
