### ISSUE TITLE
bindable change and typescript

### ISSUE THREAD

**Issue by rekna1** [aurelia/framework#460]
I have a decorated a field in my typescript class with the bindable attribute

`@bindable searcharg:string=''`

If a write my change function like this in typescript (so 'this' is explicitly the instance of the class)

`searchargChanged=(newValue:string)=>{ ... }`

it is not called, but if I write it using function syntax it is called:

`searchargChanged(newValue:string) { ... }`

Is this intended that the first syntax does not work ?

**Comment by EisenbergEffect** [comment]
Yes. Aurelia uses reflection to inspect your class prototype. By doing that it is able to optimize bindable behavior. If you have a property instead of a method, it won't find the change handler.
