### ISSUE TITLE
mutationobserver.js 404

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/framework#461]
![image](https://cloud.githubusercontent.com/assets/5897525/16623100/f75e43a0-4372-11e6-8574-604ee53023e3.png)

Hi @EisenbergEffect ,

From time to time I am getting that error?

Do you know what could be the reason?

If I reset VS it works. That is weird.

Regards.

**Comment by EisenbergEffect** [comment]
What is your system.js version?

**Comment by hmarcelodn** [comment]
@EisenbergEffect it is SystemJS v0.19.29

**Comment by EisenbergEffect** [comment]
I'm not sure what is going on there. It seems like a jspm or system.js issue though. Could it be that you don't have the correct system.js configuration?
