### ISSUE TITLE
Tree-shaking and bundling

### ISSUE THREAD

**Issue by ppn2** [aurelia/framework#462]
Recently I read an [article](http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/) on angular2 where they managed to redeuce the size of the library from 1.6 MB to 50KB using techniques like minification, compression and Tree-shaking with rollup.js. The tree-shaking is technique where bundler statistically analyze the javascript code and exclude the unused modules from the final bundle.

When I bundle aurelia (modules listed below) the size comes to 693 KB. After minification the size goes down to 343 KB. The Gzip compression take the size further down to 110 KB. To be fair without doing much Aurelia size is already so much smaller than angular 2 and it is remarkable. My question is, is it is possible to push the envelop even further and use tree-shaking and reduce the size of the bundle even more??

Here is the aurelia modules I used (all modules are rc except for those modules which has not gone into rc).
aurelia-animator-css
aurelia-bootstrapper
aurelia-dependency-injection
aurelia-dialog
aurelia-fetch-client
aurelia-framework
aurelia-history-browser
aurelia-loader-default
aurelia-logging-console
aurelia-metadata
aurelia-pal
aurelia-pal-browser
aurelia-polyfills
aurelia-router
aurelia-task-queue
aurelia-templating
aurelia-templating-binding
aurelia-templating-resources
aurelia-templating-router

**Comment by MarkHerhold** [comment]
I'm not sure how relevant this is, but Webpack 2 (in beta) builds in support for tree-shaking. http://www.2ality.com/2015/12/webpack-tree-shaking.html

**Comment by EisenbergEffect** [comment]
This really isn't a feature related to any particular framework. It's a build optimization enabled by several build/bundling libraries. We are looking into enabling it for you, but some people have already used tree shaking with Aurelia themselves. It's completely possible. We even support a new module type "native-modules" for all of our libraries which is designed to be consumed by some of these build systems. So, from a framework perspective, you've got what you need :)

One final note on the size of Angular 2. Bear in mind that tree shaking can only shake what you do not use in your application. The 50k size of Angular 2 is based on a "Hello World" application with uses *almost none* of the framework. A real application would never be able to get Angular's size that small. With Aurelia, the core framework, without tree-shaking can be minified and gzipped down to 64k. That's without any tree shaking.
