### ISSUE TITLE
Aurelia HUB mobile layout issue

### ISSUE THREAD

**Issue by Pablo-Ivan** [aurelia/framework#465]
When I go to the Hub, the layout is not structured. Here is a screenshot
![screenshot_2016-07-08-21-58-37](https://cloud.githubusercontent.com/assets/10409758/16705696/17986cc8-4557-11e6-889e-ad366d4c245f.png)

**Comment by EisenbergEffect** [comment]
We've got it tracked and are preparing an update for mobile and tablet.

**Comment by bigopon** [comment]
I also have an issue woth scrolling horizontally for code block on my mobile.

Model: Google Nexus 6P
Brower: Chrome 52.0.2743.98
