### ISSUE TITLE
plugins that use plugins do not respect jspm mappings

### ISSUE THREAD

**Issue by davismj** [aurelia/framework#466]
I've written a little module designed to throw all kinds of frustrating spam and pop-ups in order to generate as much ad revenue as possible. It depends on the `aurelia-dialog` plugin.

**spamModule/src/index.ts**
```typescript
export function configure(config) {
  config.plugin('aurelia-dialog');
}
```

Now, I've installed it in my main application, a questionable site where you can watch your favorite movies for free somehow. It does _not_ depend on the `aurelia-dialog` plugin.

**freeMovies/src/main.ts**
```typescript
export function configure(aurelia: Aurelia) {
    aurelia.use
        .standardConfiguration()
        .plugin('spam-module')
}
```

I'm using systemjs, and everything installs correctly, giving me the following mapping in my `config.js`.

**freeMovies/config.js**
```json
map: {
  "spam-module": "github:legitimate/spam-module@0.9.1",
  "github:legitimate/spam-module@0.9.1": {
    "aurelia-dialog": "npm:aurelia-dialog@1.0.0-beta.1.1.0"
  }
}
```

The problem is that systemjs is now throwing errors when looking for `aurelia-dialog`. Even though there's a mapping in the `config.js` that tells it where to find it, systemjs is unable to find the mapping and looks for a local file instead:

> system.src.js:5123 GET http://localhost/freeMovies/dist/aurelia-dialog.js 404 (Not Found)

It seems that this is actually an Aurelia issue, as the `configure(config)` function in `spamModule/src/index.ts` is getting passed the _local_ aurelia object, and so loading the plugin takes place not in the `spam-module` module but in the `free-movies` module.

**Comment by davismj** [comment]
May be of interest to @guybedford.

**Comment by EisenbergEffect** [comment]
We have an iterator tracking this elsewhere already. Closing this as a dupe.

**Comment by davismj** [comment]
I searched for it but couldn't find it. What's the link?

**Comment by EisenbergEffect** [comment]
https://github.com/aurelia/framework/issues/376
https://github.com/aurelia/framework/issues/193
