### ISSUE TITLE
[Question/Help Wanted] Using RequireJS

### ISSUE THREAD

**Issue by AStoker** [aurelia/framework#468]
Edge has failed to load in our project for quite some time. We've about exhausted our resources trying different things and trying to nail down the issue. We've looked extensively at the issue here: https://github.com/aurelia/framework/issues/227  
Currently, I am in the mindset that it's something wrong in Aurelia's code, as it only occurs when I'm pulling down plugins and other resources (doesn't happen if I just use the standard configuration). I've been trying to find the source of this particular issue mentioned: https://github.com/aurelia/framework/issues/227#issuecomment-191061035
and currently believe it might be related to how template resources are loaded up when using SystemJS and adding the plugin for `template-registry-entry`, as it finally fails here when trying to load up the `app.html!template-registry-entry` file via aurelia-loader-default
``` javascript
DefaultLoader.prototype.loadTemplate = function loadTemplate(url) {
      return this._import(this.applyPluginToUrl(url, 'template-registry-entry'));
    };
```

__All these details aside, we're beginning to look into alternatives to SystemJS.__ The AureliaCLI isn't in a place where we can use it on existing projects yet, so we're looking into how it uses RequireJS now, and what we'd have to do to configure Aurelia to use RequireJS instead of SystemJS. Is this documented somewhere? Any help is appreciated. I'm going to include the other details I mentioned above in the issue for Edge.

**Comment by EisenbergEffect** [comment]
Make sure you have the latest system.js first.
Personally, I recommend choosing an alternative such as RequireJS or Webpack.

Using RequireJS isn't really that hard. Just npm install the libraries you want and then set up the path and package config. You can see what the CLI generates and use that as a guide. Depending on your needs, you may also want to investigate Webpack.

**Comment by AStoker** [comment]
We have the latest of pretty much everything.
The benefit we had with JSPM/SystemJS was that we didn't have to worry about managing our dependency versions. When we last used require, we had to. Is there a way to automatically manage the RequireJS Config like JSPM did?

**Comment by AStoker** [comment]
Additionally, how would you do an update process on libraries with RequireJS? For example, when Aurelia gets to v.1, how would you update all the aurelia packages with their dependencies? With JSPM, it would have just been `jspm update`.

**Comment by EisenbergEffect** [comment]
Not yet, no. We're working on something like that but it isn't ready yet.
It's not really that hard though...

**Comment by EisenbergEffect** [comment]
For updates, you just use `npm`. It's really easy.
