### ISSUE TITLE
global-behavior is not case sensitive

### ISSUE THREAD

**Issue by Kennethtruyers** [aurelia/framework#47]
I tried invoking a jQuery plugin through a global-behavior attribute:

    <div jquery.nanoScroller="someProperty: true">Content here</div>

Unfortunately, the DOM returns the attributes in lowercase, so Aurelia tries to execute `jQuery.nanoscroller`, instead of `jQuery.nanoScroller`.

**Comment by EisenbergEffect** [comment]
Yes. That's an unfortunately aspect of how the DOM works. To get around this issue, you can register the plugin with the global behavior.

Here's the code to do that:

```
GlobalBehavior.jQueryPlugins['nanoscroller'] = 'nanoScroller';
```

**Comment by Kennethtruyers** [comment]
This not really obvious. Also this means that the automatic behavior won't work with any jQuery plugin that has a capital in its method call (which is about every plugin due to camelCasing).

I can see two possible workarounds:

1. allow for a special property so you can override the method-call:
    <div jquery.nanoscroller="someProperty: true; pluginName: nanoScroller">Content</div>
2. When a method is not found with that name in lowercase, iterate over all jquery methods and check if there's a lowercase match. In that case, call the lowercase match. Obviously this is not optimal and you could output a warning to the console to say that it should add the line to GlobalBehavior.jQueryPlugins.

If you want, I could provide a pull-request for this, just let me know if you would want this and if so, which approach you prefer (or a combination of both).

**Comment by EisenbergEffect** [comment]
I agree. This is a bit of an experimental feature. It should be possible to implement #2 in the jQuery handler. If you want to send a PR for that, I'd be happy to accept it. Just make sure to sign the CLA and follow the contrib guide.
