### ISSUE TITLE
unhandled exception in "detached()" causes uncaught promise & not logged

### ISSUE THREAD

**Issue by smax48** [aurelia/framework#470]
**I'm submitting a bug report**
- **aurelia-framework version:**
  1.0.0-rc.1.0.2

**Please tell us about your environment:**
- **Operating System:**
  Windows 8.1
- **Node Version:**
  4.4.5
- **NPM Version:**
  3.9.3
- **JSPM OR Webpack AND Version**
  JSPM 0.16.15
- **Browser:**
  Chrome 51
- **Language:**
  TypeScript 1.8

**Current behavior:**
Unhandled exception (e.g. trying to call a method of undefined object) in the viewmodel's detached() method causes the "uncaught promise" error and error message is not logged by aurelia (so it is displayed only by the browser)
Call stack just before the failing line of code (`Tree` is my viewmodel component):

```
Tree.detached (tree.ts:50)
detached (aurelia-templating.js:3433)
detached (aurelia-templating.js:1557)
removeAction (aurelia-templating.js:1850)
removeAll (aurelia-templating.js:1869)
after (router-view.js:85)
work (router-view.js:184)
(anonymous function) (router-view.js:214)
```

**Expected/desired behavior:**
handle promise rejection in aurelia and log the error
- **What is the motivation / use case for changing the behavior?**
  Impossible to log & display errors like this without opening debug console

**Comment by EisenbergEffect** [comment]
Closing old questions. Lots of error improvements made over the last year as well.
