### ISSUE TITLE
Custom element is not loading

### ISSUE THREAD

**Issue by cizmiak** [aurelia/framework#473]
**I'm submitting a bug report**

* **aurelia-framework version:**
1.0.0-rc.1.0.2

**Please tell us about your environment:** 
* **Operating System:**
Windows 8.1

* **Node Version:**
4.4.5

* **NPM Version:**
3.9.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.39 

* **Browser:**
Chrome 51 | Firefox 47 | IE 11

* **Language:**
TypeScript 1.8

**Current behavior:**
I have a simple example with two custom elements: clock and banner. Both view models inherit from one base class.  This base class has bindable property and inject decorator.
The app.html displays only one of the custom elements. Sometimes Banner and sometimes only Clock element.
If I comment inject decorator and bindable property in the base class, the app.html displays both custom elements as expected.

app.html
```
<template>
    <require from="./clock"></require>
    <require from="./banner"></require>

    <clock baseTopic="Clock:1"></clock>
    <banner baseTopic="Banner:1"></banner>
</template>
```

banner.html
```
<template>
    <div style="background-color: red">Banner</div>
</template>
```

banner.ts
```
import {customElement, useView} from 'aurelia-framework';
import {Base} from './base';

@customElement('banner')
@useView('./banner.html')
export class Banner extends Base {
}

```

clock.html
```
<template>
    <div style="background-color: azure">Clock</div>
</template>

```

clock.ts
```
import {customElement, useView} from 'aurelia-framework';
import {Base} from './base';

@customElement('clock')
@useView('./clock.html')
export class Clock extends Base {
}
```

base.ts

```
import {EventAggregator} from 'aurelia-event-aggregator';
import {inject, bindable} from 'aurelia-framework';

@inject(EventAggregator)
export abstract class Base {
               @bindable baseTopic: string;
}
```

**Expected/desired behavior:**

* **What is the expected behavior?**
I would expect that both custom elements would be loaded, even if the base class has bindable property or inject decorator.

**Comment by Thanood** [comment]
AFAIK, `bindables` cannot be inherited. You would have to declare them again in the inherited classes.

**Comment by EisenbergEffect** [comment]
We are tracking this issue already elsewhere as a possible enhancement in the future. Current, bindables on base classes are not supported. We generally recommend that you avoid inheritance as it caused unnecessary strong coupling. In modern JS you have other options available to you. Take a look at using a Decorator. You can create a custom decorator that can added shared behavior, bindables, etc to classes.
