### ISSUE TITLE
Cannot bind checked attribute

### ISSUE THREAD

**Issue by hadrienl** [aurelia/framework#474]
Hi,

I can't bind checked attribute of an input. You can see exemple here : https://gist.run/?id=2ef7f03f7ccd8ea7b21620b63ccf42b2

Without the checked.bind, the radio works well, but I want to set the initial checked radio on view attaching.

**Comment by EisenbergEffect** [comment]
@hadrienl We set up issue templates on every repo. We can't accept bug reports without filling out that template. It's critical to our workflow.

**Comment by AshleyGrant** [comment]
@hadrienl see here: https://gist.run/?id=1d91fc2ad07ab63fe69a42a0017bdafd

**Comment by hadrienl** [comment]
Ok ! checked.bind must match the input value… I think it's not very easy to get that.
