### ISSUE TITLE
Bug report: Unexpected token import

### ISSUE THREAD

**Issue by jestntime** [aurelia/framework#476]
* **Library Version:**
1.0.0-rc.1.0.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu Linux 14.04

* **Node Version:**
5.11.1

* **NPM Version:**
3.8.6

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When running:

`au run --env dev --watch`

I get an error:

`Unexpected token import`

on line 1 of main.js

I'm using the Aurelia CLI and the build/tracing steps complete successfully, but the application won't run once in the browser.

**Comment by EisenbergEffect** [comment]
We're going to need more information. How can I reproduce this error?

**Comment by AshleyGrant** [comment]
Node 5.11.1 is an unsupported version of Node. Please upgrade to a Node 6.x build. The latest version is `6.3.0`.

**Comment by alsoicode** [comment]
HI guys. I'm working with @jestntime on this project. It was started on Windows 10, and runs as expected. When we moved it to an Ubuntu environment, it started acting up. All dependencies will install, and the app will build and trace without errors, but once it hits the browser, we get the token error. We tried moving it to OSX and got the same error.

@AshleyGrant we get the same error on Node 6.3. This is a very small app with a few custom components. Everything else is out of the box.

**Comment by AshleyGrant** [comment]
@alsoicode does this happen with a brand new aurelia cli based project created on or copied over to Ubuntu (no custom code added)?

**Comment by alsoicode** [comment]
@AshleyGrant A new project created via the CLI works just fine. It's very odd. Aside from a couple of jQuery plugins, this is a super simple project.

**Comment by AshleyGrant** [comment]
If you can give us a minimal repro it'd be awesome.

**Comment by alsoicode** [comment]
@AshleyGrant Where can I PM you a link to the codebase?

**Comment by AshleyGrant** [comment]
Hit me up on Gitter or on twitter. I'm @ashleymgrant on twitter

**Comment by EisenbergEffect** [comment]
Make sure the Ubuntu project contains all the "dot" files. In particular, the .babelrc file. It sounds like that is missing and Babel isn't transpiling the import statements. We've seen this happen before. It may be that the dot files weren't added to source control.
