### ISSUE TITLE
Is there any possibility to render view from MVC partial view

### ISSUE THREAD

**Issue by riyasat** [aurelia/framework#479]
Hi,

I am evaluating Angular 2 and Aurelia for my app with new Asp net Core. By far I have successfully tested Angular 2 with mvc partial views which is nicely done. e.g.
@Component({
	selector: 'my-app',
	templateUrl: '/Home/Angular'
})
A typical use case for this is support for globalization with resx or json language files.

Now I am working on Aurelia by far it's much better framework then Angular 2 but I am not able to render view like Angular 2 did that. 

Can you point me out a right direction to do that ? or is there any other way I can use Aurelia with globalization e.g.

http://www.mysite.com/sv/start 

where SV = Swedish and change the language of whole site as long as sv is in the url.
Thanks.

//Riy

**Comment by EisenbergEffect** [comment]
This isn't really the place for questions, but I may be able to help you. If you want to be explicit for each view, you can decorate your component like this:

```
imoport {useView} from 'aurelia-framework';

@useView('/Home/Aurelia')
export class MyApp {
  ...
}
```

Something like that should work. If you want to automatically use server generated views for every component, you can use the `ViewLocator` and configure a convention. See the docs here on how to do that: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/9

**Comment by riyasat** [comment]
Thanks for quick response.

I tried that but that doesn't work for me it gives error Cannot find module 'aurelia-framework'.

Can you point me where should I ask this question ?

**Comment by EisenbergEffect** [comment]
Cannot find the module? This sounds like your project isn't setup correctly. Are you using jspm? If so, run `jspm install aurelia-framework`.

**Comment by riyasat** [comment]
yes, indeed I am running jspm and had installed aurelia-framework. I had uploaded my sample test project on following link http://s000.tinyupload.com/?file_id=68847668664124928878.

If you have time can you please look at it and point me where am I doing wrong. 

Thanks

**Comment by AshleyGrant** [comment]
@riyasat I'll try to figure out what's going on with your issue. In the meantime, would you mind transferring this to a StackOverflow question tagged aurelia, please?

**Comment by AshleyGrant** [comment]
Also, I downloaded your project, ran `dotnet restore` and `dotnet run`. It failed at first, but then I added 
```
@{
    Layout = null;
 }
```
to the top of `Aurelia.cshtml` and now it works fine.
