### ISSUE TITLE
String not interpolated for HTML input attributes maxlength and style

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/framework#48]
In this markup

 ```html
<tr repeat.for="searchParam of searchParams">
  <td>
    <input type="text" class="form-control input-sm form-fixer"
        id="${searchParam.FIELDNAME}_low"
        size="${searchParam.LENG}"
        maxlength="${searchParam.LENG}"
        style="width:${searchParam.STYLE.width}px;"
        value.bind='searchParam.LOW'/>
  </td>
</tr>
```
after the interpolation, the size attribute is processed, the maxlength and style not:

`<input type="text" class="form-control input-sm form-fixer au-target" id="VKORG_low" size="4" maxlength="${searchParam.LENG}" style="width:${searchParam.STYLE.width}px;" value.bind="searchParam.LOW">`

Tried to change the sequence of attributes, no effect. The LENG type is string.

**Comment by EisenbergEffect** [comment]
Thanks for tracking this issue. We haven't implemented style bindings yet. We'll track that here. We'll also look into what's going on with maxlength.

**Comment by jdanyow** [comment]
looks like I duplicated this issue when I opened https://github.com/aurelia/binding/issues/38 
sorry!
