### ISSUE TITLE
Shouldn't Aurelia.enhance resolve at some point?

### ISSUE THREAD

**Issue by tkhyn** [aurelia/framework#480]
Not sure if it's a bug, if it's intentional or if there was no other option.

From what I understand from the [source code](https://github.com/aurelia/framework/blob/master/src/aurelia.js#L102), the Promise returned by ``Aurelia.enhance`` never resolves.

As a consequence, there is no way to execute something only when the enhancement is completed.

I'm asking that because I'm trying to test a relatively complex component (using a slightly altered version of ``aurelia-testing`` but that works similarly, calling ``aurelia.enhance`` the same way), and the component is not rendered when the actual test starts (I said it was a relatively complex one!). I can't ``await`` the enhancement as it never resolves, so the only option for now is to use an appropriate timeout, which is not ideal.

Would there be a way to make this promise resolve at some point, or would the fact that all the gears it puts in motion behind the scenes prevent this?

Thanks in advance

**Comment by EisenbergEffect** [comment]
It looks like a bug, this line: https://github.com/aurelia/framework/blob/master/src/aurelia.js#L110 should resolve `this` instead of return it. Would you be willing to submit a PR to fix that?

**Comment by tkhyn** [comment]
Yes, that would make the promise resolve ... but it does not resolve the issue as there is no guarantee that when the returned promise resolves, the ``engine.enhance(...)`` and ``this.root.attached()`` have been completed as they are triggering async actions (and then a related issue would be that they do not return promises themselves).

That's what I was meaning when I was mentioning the 'gears it puts in motion behind the scenes'. Making the promise resolve is easy enough, making it resolve only after ``engine.enhance(...)`` and ``this.root.attached()`` may be quite tricky.

**Comment by tkhyn** [comment]
I took some time to look at the 'gears', and it seems that what would be needed to achieve the above mentioned behavior would involve a possibly important refactor of [aurelia/templating](http://github.com/aurelia/templating) to make every ``bind``, ``attached``, ``detached``, ``unbind`` method return a Promise made of all the promises returned by the nested calls to other ``bind``, etc. methods on children controllers, view-models, etc. I'm unsure if this is what you'd want, and I'm even less sure my understanding of Aurelia's internals is good enough to assume this would work without creating other problems ...

**Comment by EisenbergEffect** [comment]
The component lifecycle methods are always synchronous. Changing that would ruin the framework probably ;)

**Comment by tkhyn** [comment]
Ok. Just seen #367.

I'll submit the PR to fix the return value for enhance then and will investigate what can be done about my particular use case.
