### ISSUE TITLE
canActivate/Activate method parameters

### ISSUE THREAD

**Issue by hay12396** [aurelia/framework#484]
Hello guys!

So i am trying to understand the method parameters that this methods have.
I was lookin in the docs but i couldn't find anything about it.

I have a few questions:
1:

Activate(params, routeConfig, navigationInstruction).
This methods receive params, routeConfig and navigationInstruction parameters.
But i am not sure what can i get from each of this parameters? what are their interfaces?

2:

We can give our ViewModel reference to objects using model.bind{ key: value, key2:value..}, this key-value pairs will be available via the "params".
But where can we find the parameters that are received from the url? (say that our route have :id parameter, how can we catch that parameter in our ViewModel?).

While askin in Gitter, someone pointed me to this link:
https://github.com/aurelia/router/blob/master/src/interfaces.js
But according to this link, there is no way to get a reference to the router from the routeConfig, however i do get reference to the router via the routeConfig in my project, is that interface outdated?

By the way, you guys made a great framework! i am only using it for a few days but i already fall in love with it. :)

With regards,
Hay.

**Comment by atsu85** [comment]
@hay12396, take a look at https://github.com/aurelia/router/pull/376 - We are working with @StrahilKazlachev on PR to clarify the signatures. Let me know if that answers Your questions.

**Comment by StrahilKazlachev** [comment]
**1** - you can't get the router from `RouteConfig`, if you are referring to the `RouteConfig.navModel`, that's something else.
**2** - I think you've mixed the `activate` on a VM you are navigating to and the VM you pass to the `compose` element, they're different things. You do get the url parameters and query string from `params`.

**Comment by hay12396** [comment]
Hey @StrahilKazlachev and @atsu85 
My project have the following build:

I have an app.js | html which defines the router, it is also the entry point of my application.

from there, i have a Navbar VM which i call like this(in the app.html):
<compose view-model="./Navbar" model.bind="{router: router}">
The Navbar class:
`export class NavBar {
    private router;
    constructor() { }
    activate(data) {
        this.router = data.router;
    }
}`

than the navbar calls the NavbarRight ViewModel like this(in Navbar.html):
<compose view-model="./NavbarRight"></compose>

and i can get a reference to the router from the activate method in the NavbarRight.js:
activate(data, route, navigationInstruction) {
        this.router = route.router;
}
and i can use this router to navigate to the defined routes in app.js.

Now what i don't understand, is first what type are this (data, route, navigationInstruction) parameters? what data do they hold?

If i would call the NavbarRight like this:
<compose view-model="./NavbarRight" model.bind={key1: val1, key2: val2}> and i would like to get a reference to both this value-pairs, and to the route parameters (say i have a :id parameter in the route), how would i access this values in the inner ViewModel?

**Comment by StrahilKazlachev** [comment]
I don't see any html, but I do think you are using the `compose` element and as I said, the `activate` method on a VM passed to a `compose` is different from the signature you are asking about `activate(params, routeConfig, navigationInstruction)`. This signature is for the activate method of a VM whose `moduleId` you have associated with a route pattern, when you configured the router - `configureRouter`. Also you can check the API docs: [RouteConfig](http://aurelia.io/hub.html#/doc/api/aurelia/router/1.0.0-rc.1.0.0/interface/RouteConfig), [NavigationInstruction](http://aurelia.io/hub.html#/doc/api/aurelia/router/1.0.0-rc.1.0.0/class/NavigationInstruction)

**Comment by hay12396** [comment]
Hey @StrahilKazlachev , that indeed was my problem, i mixed up between this two method.
Thank you for the help :)
