### ISSUE TITLE
The click.delegate on th element does not find the function

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/framework#49]
The **click.delegate** in **th** element does not find the function (Uncaught Error: headerClick is not a function ast.js:58)

    <table id="header" class="table">
    	<thead>
        	<tr>
            	<th repeat.for="header of Headers" click.delegate="headerClick(1)>${header[1]}</th>
            </tr>
        </thead>
    </table>

while it works on **tr** element

    <table id="header" class="table">
    	<thead>
        	<tr click.delegate="headerClick(1)>
            	<th repeat.for="header of Headers">${header[1]}</th>
            </tr>
        </thead>
    </table>

**Comment by EisenbergEffect** [comment]
If the function is on `header` then it needs to be `header.headerClick(1)`. If the function is on the parent view model, then it needs to be `$parent.headerClick(1)`

**Comment by bsrdjan** [comment]
It was $parent, thanks!
