### ISSUE TITLE
MS Edge Fails to Load

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/framework#490]
Up until the release candidate everything worked fine in Edge, once i upgraded our application not longer loads in Edge and just hangs. If i have developer tools opened than it does load.  I will dig into this  more but want to know if there's been any reports or information off hand.

**Comment by EisenbergEffect** [comment]
No reports that we are aware of. Our hub is built with Aurelia and works in Edge. If you are using SystemJS still, that could be related. The description you are giving related to the developers tools, I believe, stemmed from that.

**Comment by devteamexpress** [comment]
Seems to be related to the system.js loader, including bluebird.js doesn't solve the issue, and it literally just hangs and never loads. Do you personally prefer webpack over jspm , where would you say aurelia is moving more towards?

**Comment by AshleyGrant** [comment]
Aurelia itself is moving towards the Aurelia CLI, but Webpack is most definitely a first class citizen. @niieani has made our Webpack skeletons top-notch. They're blazing fast.

**Comment by EisenbergEffect** [comment]
Our CLI uses RequireJS and we'll probably enable SystemJS support on that as well. We've also got solid Webpack support with tomorrow's release, that closes the gap with other solutions. My first choice would be to either use the CLI or Webpack. That's what we'll be pushing going forward. We'll still support JSPM-based workflows as best as we can, but it has been very painful for us and many community members so we're not sure we want to make that the default anymore.
