### ISSUE TITLE
Clearing arrays with length=0 no longer working

### ISSUE THREAD

**Issue by ZoolWay** [aurelia/framework#491]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework 1.0.0-rc.1.0.13

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.39

* **Browser:**
Chrome 51.0.2704.103 m

* **Language:**
all

**Current behavior:**
When I reset an array by setting its `length` to `0` its items in a `repeat.for` are no longer removed.

This example shows three possibilities to clear:
https://gist.run/?id=4caf35a8abc1cedfc8487df1ea997548

Splice and replace still work, setting length not. When you try to clear with setting length to 0 a splice after that call will also **not** work (while replacing still would)!

*Note*: I have experimented using the TaskQueue because at first I though it was a problem with that.

**Expected/desired behavior:**
This was working in aurelia-framework 1.0.0-rc.1.0.0. When setting the length to zero and adding new items, the list was cleared and rebuild as expected.

**Comment by jdanyow** [comment]
Issue moved to [aurelia/binding #465](https://github.com/aurelia/binding/issues/465) via [**ZenHub**](https://www.zenhub.com/)
