### ISSUE TITLE
Blur.Trigger not working with Safari

### ISSUE THREAD

**Issue by eblancperso** [aurelia/framework#498]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.1.2.5

**Please tell us about your environment:**
- **Operating System:**
  MacOSX 10.11.4
- **Node Version:**
  6.3.1
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  JSPM 0.16.35
- **Browser:**
  Safari 9.1
- **Language:**
  TypeScript 1.7.3

**Current behavior:**
The property "blur.trigger" doesn't seem to work on links (<a href...) with Safari.

**Expected/desired behavior:**
https://gist.run/?id=ba2132a1211c7ba2468fc65f47b80aef
1 - Click on the link
2 - Click on any white space under the link
3 - An alert should show

This does work on major browsers but not with Safari. It should call the given function.

**Comment by jdanyow** [comment]
is this a mobile safari issue or desktop safari?

http://stackoverflow.com/a/13492999/725866

**Comment by eblancperso** [comment]
Desktop Safari!

**Comment by jdanyow** [comment]
The issue report says windows 10- is that a typo? There's no safari for windows anymore.

**Comment by eblancperso** [comment]
Yep, that was I typo! Sorry

**Comment by EisenbergEffect** [comment]
@jdanyow putting this back on your radar.

**Comment by jdanyow** [comment]
Doesn't seem to be an issue with Aurelia. I can reproduce with vanilla js in Safari 10 on a MacBook Pro:

https://plnkr.co/edit/kZBOlb51nxj9dAGjMqzG?p=preview

```html
<!DOCTYPE html>
<html>
  <head></head>

  <body>
    <a id="theAnchor" href="#">Blur Me</a>
    <script>
      theAnchor.addEventListener('blur', function() { alert('yes!'); });
    </script>
  </body>
</html>
```
