### ISSUE TITLE
Click.Delegate() Not Working Properly?

### ISSUE THREAD

**Issue by allencoded** [aurelia/framework#499]
**I'm submitting a bug report**

* **Library Version:**
1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.5

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I have a click.delegate `child()`. When I click on it, it fires the `child()` but also the `parent()` click.delegate. Not sure why this is occurring as it use to not.

**app.html**
```
<div click.delegate="parent()">
         <custom-test></custom-test>
</div>
```
**app.js:**
```
parent() {
    console.log('parent');
}
```
**custom-test.html**
```
<template>
  <button click.delegate="child()">inside</button>
</template>
```
**custom-test.js**
```
  child() {
    console.log('Child Fires');
  }
```
Result of code in console when click on child():
```
-> "Child Fires"
-> "parent"
```

I would expect:
`-> "Child Fires"
`

When I click on the button in the child element `custom-test` it also fires the parent click found on app.html. It seemed to have started this in version 1.0.

**Expected/desired behavior:**
When clicking a click.delegate inside another click.delegate it shouldn't fire the parent one.

**Comment by CasiOo** [comment]
There has been a bug fix, so events now properly bubble, just as you would expect DOM events to behave. You'll have to call `stopPropagation` to stop it from bubbling.

Also see https://github.com/aurelia/binding/issues/467 for `stopPropagation` bug. It has just now been merged.

**Comment by CasiOo** [comment]
Found the original issue about the bubbling: https://github.com/aurelia/binding/issues/460

**Comment by AshleyGrant** [comment]
@CasiOo we did some testing and matched the behavior to both how the browser and jQuery handle event bubbling. It was a (minor, but necessary) breaking change in the 1.0.0 release.

**Comment by allencoded** [comment]
So even if I use event.stopPropagation() it wont stop the bubble?

**Comment by CasiOo** [comment]
@allencoded It should work if you update aurelia-binding to 1.0.1. See the release notes, they mention `stopPropagation` https://github.com/aurelia/binding/releases/tag/1.0.1
