### ISSUE TITLE
Issue in quick start doc

### ISSUE THREAD

**Issue by jnm2** [aurelia/framework#500]
In the [quick start](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/6), the rendered text looks like this in one spot:

> Second, did you notice the ` ` syntax?

The [markdown source](https://github.com/aurelia/framework/edit/master/doc/article/en-US/quick-start.md) has ``Second, did you notice the `\${heading}` syntax?``

Firefox 47.0.1, Windows 10 x64.

**Comment by EisenbergEffect** [comment]
We've got it fixed, it's just not yet released.

**Comment by jnm2** [comment]
Should I submit a PR for the typo in the next sentence, or is that fixed as well?

**Comment by atsu85** [comment]
When starting to change the text, you'll see if it is fixed (unless it isn't merged)

**Comment by jnm2** [comment]
Got it, thanks. Didn't understand the mechanisms involved and thought that meant it needed to be escaped twice when I went to edit, but that makes sense.
