### ISSUE TITLE
Aurelia App crashes at startup

### ISSUE THREAD

**Issue by code-chris** [aurelia/framework#505]
Hi,

I updated the Aurelia libraries of my app today. After that, the app crashes with exceptions at startup.

**First exception:**
`Unhandled rejection TypeError: m.ConsoleAppender is not a constructor
    at http://localhost:8080/assets/bundle.js:20210:38
From previous event:
    at http://localhost:8080/assets/bundle.js:20209:56
From previous event:
    at http://localhost:8080/assets/bundle.js:20208:99
    at next (http://localhost:8080/assets/bundle.js:19957:31)
From previous event:
    at next (http://localhost:8080/assets/bundle.js:19957:48)
    at runTasks (http://localhost:8080/assets/bundle.js:19963:11)
    at FrameworkConfiguration.apply (http://localhost:8080/assets/bundle.js:20226:13)
    at Aurelia.start (http://localhost:8080/assets/bundle.js:19843:22)
    at http://localhost:8080/assets/bundle.js:143:22
From previous event:
    at http://localhost:8080/assets/bundle.js:107:24
    at http://localhost:8080/assets/bundle.js:19417:13
    at Array.<anonymous> (http://localhost:8080/assets/bundle.js:19347:20)
    at http://localhost:8080/assets/bundle.js:19407:28
From previous event:
    at http://localhost:8080/assets/bundle.js:19399:45
From previous event:
    at run (http://localhost:8080/assets/bundle.js:19396:25)
    at Object.<anonymous> (http://localhost:8080/assets/bundle.js:19421:2)
    at Object.aurelia-bootstrapper-webpack (http://localhost:8080/assets/bundle.js:19422:31)
    at __webpack_require__ (http://localhost:8080/assets/bundle.js:52:38)
    at Object.0 (http://localhost:8080/assets/bundle.js:101:172)
    at __webpack_require__ (http://localhost:8080/assets/bundle.js:52:38)
    at 0 (http://localhost:8080/assets/bundle.js:93:18)
    at http://localhost:8080/assets/bundle.js:96:10`

This exception occurs in the framework during `app.start()` is called. I fixed this with disabling the "**developmentLogging**" feature. After that, I received this exception:

`Unhandled rejection Error: BindingLanguage must implement inspectTextContent().
    at u (http://localhost:8080/assets/bundle.js:30:26272)
    at e.t.BindingLanguage.e.inspectTextContent (http://localhost:8080/assets/bundle.js:31:15053)
    at e.t.ViewCompiler.e._compileNode (http://localhost:8080/assets/bundle.js:32:4117)
    at e.t.ViewCompiler.e._compileNode (http://localhost:8080/assets/bundle.js:32:4510)
    at e.t.ViewCompiler.e.compile (http://localhost:8080/assets/bundle.js:32:3562)
    at http://localhost:8080/assets/bundle.js:32:12044
From previous event:
    at http://localhost:8080/assets/bundle.js:32:11949
From previous event:
    at t.ViewEngine.t.loadViewFactory (http://localhost:8080/assets/bundle.js:32:11745)
    at t.InlineViewStrategy.t.loadViewFactory (http://localhost:8080/assets/bundle.js:31:13776)
    at t.HtmlBehaviorResource.t.load (http://localhost:8080/assets/bundle.js:32:22392)
    at e.t.ResourceDescription.e.load (http://localhost:8080/assets/bundle.js:32:9492)
    at t.ResourceModule.t.load (http://localhost:8080/assets/bundle.js:32:8685)
    at http://localhost:8080/assets/bundle.js:32:13658
From previous event:
    at t.ViewEngine.t.importViewResources (http://localhost:8080/assets/bundle.js:32:13291)
    at http://localhost:8080/assets/bundle.js:38:25311
From previous event:
    at a (http://localhost:8080/assets/bundle.js:38:25213)
    at http://localhost:8080/assets/bundle.js:38:29946
    at o (http://localhost:8080/assets/bundle.js:38:24223)
    at o (http://localhost:8080/assets/bundle.js:38:24257)
    at http://localhost:8080/assets/bundle.js:39:801
From previous event:
    at http://localhost:8080/assets/bundle.js:39:778
From previous event:
    at t.apply (http://localhost:8080/assets/bundle.js:39:628)
    at t.Aurelia.t.start (http://localhost:8080/assets/bundle.js:38:27466)
    at http://localhost:8080/assets/bundle.js:1:1835
From previous event:
    at http://localhost:8080/assets/bundle.js:1:1194
    at http://localhost:8080/assets/bundle.js:33:5603
    at Array.<anonymous> (http://localhost:8080/assets/bundle.js:33:4637)
    at http://localhost:8080/assets/bundle.js:33:5532
From previous event:
    at http://localhost:8080/assets/bundle.js:33:5385
From previous event:
    at a (http://localhost:8080/assets/bundle.js:33:5270)
    at Object.<anonymous> (http://localhost:8080/assets/bundle.js:33:5741)
    at Object.aurelia-bootstrapper-webpack (http://localhost:8080/assets/bundle.js:33:5747)
    at t (http://localhost:8080/assets/bundle.js:1:180)
    at Object.0 (http://localhost:8080/assets/bundle.js:1:826)
    at t (http://localhost:8080/assets/bundle.js:1:180)
    at e.0 (http://localhost:8080/assets/bundle.js:1:763)
    at http://localhost:8080/assets/bundle.js:1:768`

This occours at the same time.

Both errors occur in the current versions of **Chrome and Firefox**.

My app is based on
- TypeScript 1.8.10 (compilation to AMD style)
- Webpack 1.13.1

NPM is used as package manager instead of JSPM.

This Aurelia versions were used **before** the update:
aurelia-binding@1.0.0-rc.1.0.3
aurelia-bootstrapper-webpack@1.0.0-rc.1.0.0
aurelia-bootstrapper@1.0.0-rc.1.0.1
aurelia-dependency-injection@1.0.0-rc.1.0.1
aurelia-dialog@1.0.0-beta.2.0.0
aurelia-event-aggregator@1.0.0-rc.1.0.0
aurelia-fetch-client@1.0.0-rc.1.0.1
aurelia-framework@1.0.0-rc.1.0.2
aurelia-history-browser@1.0.0-rc.1.0.0
aurelia-history@1.0.0-rc.1.0.0
aurelia-i18n@1.0.0-rc.1.0.0
aurelia-loader-default@1.0.0-rc.1.0.0
aurelia-loader-webpack@1.0.0-rc.1.0.0
aurelia-loader@1.0.0-rc.1.0.0
aurelia-logging-console@1.0.0-rc.1.0.0
aurelia-logging@1.0.0-rc.1.0.1
aurelia-metadata@1.0.0-rc.1.0.1
aurelia-pal-browser@1.0.0-rc.1.0.1
aurelia-pal@1.0.0-rc.1.0.0
aurelia-path@1.0.0-rc.1.0.0
aurelia-polyfills@1.0.0-rc.1.0.0
aurelia-route-recognizer@1.0.0-rc.1.0.1
aurelia-router@1.0.0-rc.1.0.1
aurelia-task-queue@1.0.0-rc.1.0.0
aurelia-templating-binding@1.0.0-rc.1.0.1
aurelia-templating-resources@1.0.0-rc.1.0.1
aurelia-templating-router@1.0.0-rc.1.0.1
aurelia-templating@1.0.0-rc.1.0.1
aurelia-webpack-plugin@1.0.0-beta.4.0.1

This versions were used **after** the update:
aurelia-binding@1.0.1 
aurelia-bootstrapper-webpack@1.0.0 
aurelia-bootstrapper@1.0.0 
aurelia-dependency-injection@1.0.0 
aurelia-dialog@1.0.0-beta.3.0.0 
aurelia-event-aggregator@1.0.0 
aurelia-fetch-client@1.0.0 
aurelia-framework@1.0.1 
aurelia-history-browser@1.0.0 
aurelia-history@1.0.0 
aurelia-i18n@1.0.0 
aurelia-loader-default@1.0.0 
aurelia-loader-webpack@1.0.2 
aurelia-loader@1.0.0 
aurelia-logging-console@1.0.0 
aurelia-logging@1.0.0
aurelia-metadata@1.0.0 
aurelia-pal-browser@1.0.0 
aurelia-pal@1.0.0 
aurelia-path@1.0.0 
aurelia-polyfills@1.0.0 
aurelia-route-recognizer@1.0.0 
aurelia-router@1.0.2 
aurelia-task-queue@1.0.0 
aurelia-templating-binding@1.0.0 
aurelia-templating-resources@1.0.0 
aurelia-templating-router@1.0.0 
aurelia-templating@1.0.0 
aurelia-webpack-plugin@1.1.0 

Does anybody know were the problem is here?
Thanks!

**Comment by waxenegger** [comment]
Seems like I have a similar, if not the same issue. 

I'm by no means and expert but I could kind of locate the problem in my case although I'm not happy with the "resolution". 

I suspect that you like myself use webpack configuration prior to easywebpack (and no offense but I cannot see anything easy in that). Having the desire to keep it more simple and "webpack standard/mainstream" I also upgraded just the individual aurelia compenents in package.json.

Not surprisingly something must have changed and I can only guess it has to do with the loading of modules, the loggers in the context of my problem because if I leave "aurelia-webpack-plugin": "1.0.0-beta.4.0.0" all works well. I might be wrong but I think it's the version before easywebpack and skeletons based on the latter. Now, if that helps you, I don't know. Maybe it does, maybe not.

It would be great to know if there is an easy way to fix this, and by that I mean without going easywebpack.

I really like aurelia but its easy in terms of use/coding does not extend into building. It's true that there are the skeletons but the newer easywebpack is too "heavy/much" and requires too much looking into it to dissect it to keep it minimal and tailored to what one needs. For the old way I just handled the dependencies in package.json and had a webpack config that was easy to understand and looked pretty much like any other project out there.

**Comment by code-chris** [comment]
It seems that this bug does not relate to the aurelia updates directly. Only the update from "aurelia-webpack-plugin 1.0.0-beta.4.0.1" to "1.0.0" and above breaks the whole app...

Are there any breaking changes in 1.0.0 of the webpack plugin?

**Comment by miguelzakharia** [comment]
I've just run into what seems to be the same issue. I also recently upgraded to aurelia-webpack-plugin 1.1.0. I'm probably going to try going the easywebpack route to see if things get resolved. I'll report back if I find anything useful.

**Comment by bigopon** [comment]
> and no offense but I cannot see anything easy in that
> pretty much like any other project out there

I would second this. I don't think webpack is easy, and easy webpack just introduces another layer of complexity on top of it. Making it harder to know where exactly to modify, other than just add another argument to `generateConfig`

**Comment by thesmallbang** [comment]
When i upgraded from beta4 to 1.0.0 it broke for me also but updating to 1.1.0 and setting 
nameExternalModules to false fixed it for me. You could try setting

 nameExternalModules  and/or nameLocalModules to false 

example:
`
new AureliaWebpackPlugin(
             {
                 nameExternalModules: false
             })
`

**Comment by waxenegger** [comment]
aaaah. beautiful @thesmallbang! that makes it go away for me as well.

**Comment by code-chris** [comment]
@niieani I think the usage of this flag (corresponding to this discussion) should be documented in the readme of the aurelia-webpack-plugin. What do you think?

**Comment by niieani** [comment]
I can't recommend disabling `nameExternalModules` unless you know what you are doing, that's partially why it's not documented yet. I'll provide a non-easy-webpack config at some point for all those that don't want to use it; also the Aurelia CLI will support Webpack too.

**Comment by MarkHerhold** [comment]
I am also running into the same issues when using normal webpack. I was surprised [when easy-webpack was introduced](https://github.com/aurelia/skeleton-navigation/pull/534) and I just hope that it is not going become mandatory tooling to use Webpack with Aurelia.

Although I appreciate the effort @niieani has put into easy-webpack, I still do not see the value in yet another wrapper, _especially_ when there is not much of a community around it. Usually these things do not get maintained as readily as ones where the community has a significant backing. This hasn't been the case so far, but is still a valid concern. Sorry. :worried:

**Comment by code-chris** [comment]
Closed, because the original issue can be resolved right now with the "nameExternalModules" flag in the webpack configuration.

Further discussions regarding easy-webpack should probably be done in a separate thread in the corresponding repositories ;-)

**Comment by niieani** [comment]
@MarkHerhold easy-webpack is and will be entirely optional. It's just a wrapper with configuration presets, nothing less, nothing more.
