### ISSUE TITLE
consider adding cla-assistant integration

### ISSUE THREAD

**Issue by jdanyow** [aurelia/framework#510]
https://cla-assistant.io/

# PROs

* Contributors will get instant feedback on PRs when they haven't yet signed the CLA.
* Maintainers will know which PRs are safe to merge.
* CLA assistant can be pre-seeded with GitHub users that have already committed code to the Aurelia repositories. I have a script that can pull this list using GitHub's "pulls" API.
    ![import](http://i.imgur.com/grbX3uy.png)

# CONs

* Contributors would need to sign the CLA when they commit to a repository they hadn't previously commited to: https://github.com/cla-assistant/cla-assistant/issues/66 (if they weren't part of the initial seeding work we do)
* Contributors that have signed the old CLA with their email, but have never opened an accepted PR will need to sign the CLA next time they commit.

**Comment by EisenbergEffect** [comment]
Can we have a single CLA for all our repos? Or do they need to sign per repo?

**Comment by EisenbergEffect** [comment]
I see that this still requires signing per repository. I really don't want to do that. Perhaps there is another technology that is competitive with cla-assistant that can handle this requirement? The two main things I'm looking for:

* Sign once for our project; not once per repo
* Import a list of our existing signatories

**Comment by EisenbergEffect** [comment]
@AshleyGrant Didn't you do some research on this? Were there some other options?
