### ISSUE TITLE
Router doesn't work anymore after switching active shell when using configureRouter

### ISSUE THREAD

**Issue by suamikim** [aurelia/framework#519]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.16 but right now I work with npm only...

* **Browser:**
Chrome 52

* **Language:**
ESNext

**Current behavior:**
I have multiple shells in my app (`login` & `app`) and initialize the router in the main app via `configureRouter`. The app initially loads the `login` shell from `main.js`.  

When I go from the `login` shell to the `app`, everything is fine. `configureRouter` is executed and the correct views for my current route are shown. Once I go back to the `login` shell and then again to the `app`, routing doesn't work anymore. I guess that's because `configureRouter` is not called anymore...

If I initialize the router using the "old" way by injecting the router into the app and calling it's `configure` method from within the app's `activate` method everything is working as expected...

**Comment by EisenbergEffect** [comment]
Closing this since we are tracking this issue already.

**Comment by suamikim** [comment]
Ok, is there any place where I can track the progress/updates on this?

**Comment by EisenbergEffect** [comment]
https://github.com/aurelia/framework/issues/400

**Comment by suamikim** [comment]
Thks!
