### ISSUE TITLE
for.bind instead of repeat.for

### ISSUE THREAD

**Issue by robrich** [aurelia/framework#521]
**I'm submitting a feature request**

I realize it's probably waaaaaay too late to make this change, but this surprised me.  Everything else in Aurelia is `something.bind="..."` but the repeater -- the for-loop -- is not `for.bind`, it's `repeater.for`.  This confused me.  Consider renaming `repeater.for` to `for.bind` or aliasing it this way.

**Comment by AshleyGrant** [comment]
`for` is an attribute that is already available on some standard elements such s `label`, so this wouldn't work.

**Comment by robrich** [comment]
Buggers.  :D

**Comment by EisenbergEffect** [comment]
You can do `repeat.bind="items"` though :) The `.for` simply adds the `for..of` syntax on top of any attribute.
