### ISSUE TITLE
when using multiple viewports routes must specify module for each viewport

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/framework#522]
I think this might be a bug, I've stepped through the code, it worked without webpack, for the life of me I can't figure out why the one viewport won't render.

http://stackoverflow.com/q/38807210/206466
[rpf-ui.tar.gz](https://github.com/aurelia/framework/files/405255/rpf-ui.tar.gz)

```
uname -a && node -v && npm -v && google-chrome-stable --version && au --version && npm list aurelia-framework
Linux slave-vi 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
v6.3.1
3.10.3
Google Chrome 52.0.2743.82
0.17.0
aurelia-skeleton-navigation-webpack@1.0.0 /home/xenoterracide/IdeaProjects/rpf-ui
├── aurelia-framework@1.0.1
```
**I'm submitting a bug report**

* **Language:**
TypeScript 2.0

**Current behavior:**

if you start the app, you click sign in (it doesn't do any validation right now, just navigates, and on the left side you will not see the nav populated. do a manual refreshof the page, the left side will have nav.
This same template/route worked before I extracted to a webpack skeleton. The logs make it obvious that it's not trying load the nav, but I can't figure out why.

**Expected/desired behavior:**

nav viewport should render like content and logout viewports.

**update**
further analysis suggests this is caused by not always populating the viewports, but I'm not sure why it behaved differently without webpack. This doesn't work

            {
                route: [ '', 'home' ],
                name: 'home',
                nav: false,
                viewPorts: {
                    content: { moduleId: 'main/home' },
                    authn: { moduleId: 'authn/login' },
                }
            },
            {
                route: Route.MANAGE_CONTENT,
                name: Route.MANAGE_CONTENT,
                title: 'Manage Content',
                nav: true,
                viewPorts: {
                    nav: { moduleId: 'main/nav' },
                    content: { moduleId: 'main/home' },
                    authn: { moduleId: 'authn/logout' },
                }
            },

this does

            {
                route: [ '', 'home' ],
                name: 'home',
                nav: false,
                viewPorts: {
                    content: { moduleId: 'main/home' },
                    authn: { moduleId: 'authn/login' },
                    nav: { moduleId: 'main/test' }
                }
            },
            {
                route: Route.MANAGE_CONTENT,
                name: Route.MANAGE_CONTENT,
                title: 'Manage Content',
                nav: true,
                viewPorts: {
                    nav: { moduleId: 'main/nav' },
                    content: { moduleId: 'main/home' },
                    authn: { moduleId: 'authn/logout' },
                }
            },

I personally think both should work that said if the former isn't going to work an error should be logged that a viewport supplied isn't populated.

**Comment by jdanyow** [comment]
need to add this to the router documentation:  when using multiple viewports, each route must specify a module for each of the viewports.

**Comment by jdanyow** [comment]
Issue moved to [aurelia/router #413](https://github.com/aurelia/router/issues/413) via [**ZenHub**](https://www.zenhub.com/)
