### ISSUE TITLE
creating objections that don't match the type pre erasure

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/framework#526]
**I'm submitting a bug report**

```
ame -a && node -v && npm -v && google-chrome-stable --version && au --version && npm list typescript aurelia-framework
Linux slave-vi 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
v6.3.1
3.10.3
Google Chrome 52.0.2743.82
0.17.0
aurelia-skeleton-navigation-webpack@1.0.0 /home/xenoterracide/IdeaProjects/rpf-ui
├── aurelia-framework@1.0.1
├── typescript@2.0.0
└── UNMET PEER DEPENDENCY webpack@2.1.0-beta.20
```

**Current behavior:**

databinding at runtime can create an object that doesn't map the type pre-erasure, full details on SO

http://stackoverflow.com/q/38818883/206466 

**Expected/desired behavior:**

this is probably a hard issue to fix, the simplest fix though is not to create the object, require objects to be created by the view model. Simply calling new, in typescript or user = {}, in js would be enough.

**Comment by jdanyow** [comment]
closing, SO post was answered.

**Comment by xenoterracide** [comment]
I believe I answered it before creating this ticket, it simply includes the sample code/process leading up to this. So that really doesn't resolve the issue of parameter binding being willing to create an object for the view model, thus possibly instantiating an improper type.

**Comment by jdanyow** [comment]
@xenoterracide please put together a reproduction of the issue using the aurelia gist and we'll look into it: https://gist.run/?id=7542e061bc940cde506b

**Comment by xenoterracide** [comment]
So the problem is super obvious in Javascript, is there a way to make the gist in typescript?

I mean the issue is that the view will create an object for you, and so if you have methods on your object, they will not be available if you don't instantiate your object yourself. With Typescript, the compiler is "You have a type it has method" in the debugger "you have an object, in the spot where there should be X type" no methods.

when writing a sample in javascript, it's duh, nothing is going to call `new Message()` how would it know to do that... but in Typescript, maybe it can reflect on autoinject? either way you'll get an object that is not what you're expecting. The bug is that the view creates an object for you, thus possibly creating one of the wrong type. Since Javascript isn't strictly typed... there's no such thing as the wrong type.
