### ISSUE TITLE
use in tag html dom 

### ISSUE THREAD

**Issue by javadbat** [aurelia/framework#530]
before this i was a pro angular1.x Developer and im try to test and try aurelia in test project.
anyway , i try to build a controller in your farmework and findout its called component with different concept but the problem is i dont want to pull external HTML file for my component and i want to render my inner tag HTML and dom and render it automatically like what we have in angularjs before .
see below example:
`<div class="wrapper"><div aurelia-app="src/main">${myVariable}</div></div>`
can you guid me how to do it i search too much but i cant find any solution

**Comment by ricbermo** [comment]
I think the noView option would do the trick for you.

http://aurelia.io/hub.html#/doc/api/aurelia/templating/1.0.0/overview
http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-elements/7

**Comment by javadbat** [comment]
i found @noView before but when i try to use it it throw error and dont work 
star.js:
```
'import {inject,noView} from 'aurelia-framework';'
@noView
 export class star{
     constructor() {
        this.ss = "hi";
         debugger;
    }
}
```

Uncaught (in promise) Error: (SystemJS) SyntaxError: http://localhost:63488/Scripts/Aurelia/MainPage/star.js: Unexpected token (2:0)(…)t @ system.js:4p @ system.js:4(anonymous function) @ system.js:4

i dont know what is the problem i search and found it is becuase my bable dont support es7 but i follow every step in toutorial to avoid this problem

**Comment by javadbat** [comment]
Thank you Thanhood for gist Example.
as you ask what im looking for is put app.html tags directly into the body in index.html like below:
```
<!doctype html>
<html>
  <head>
    <title>Aurelia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  </head>
  <body aurelia-app="main">
      <ul>
    <li repeat.for="row of router.navigation">
      <a href.bind="row.href">${row.title}</a>
    </li>
    <!--<li><a href="#/second/sub/">second sub route</a></li>-->
  </ul>
    
    <script src="https://jdanyow.github.io/rjs-bundle/node_modules/requirejs/require.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/config.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/bundles/babel.js"></script>
    <script>
      require(['aurelia-bootstrapper']);
    </script>
  </body>
</html>

```

**Comment by javadbat** [comment]
any advice?

**Comment by javadbat** [comment]
i fix my problem with install jspm in default way by CMD and init it without the way aurelia Getting started Document said and use jspm init and etc ...
after that add ES7 support to it by change config.js file to:
```
babelOptions: {
      stage: 0,
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  }, 
```
by adding stage:0 ;
and prev problem solved but still some problem exist about @noView() and its really a bug
