### ISSUE TITLE
compose view.bind not working

### ISSUE THREAD

**Issue by JurgenDJ** [aurelia/framework#537]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 

* **Browser:**
All 

* **Language:**
all 

**Current behavior:**
contrary to the documentation (templating>basics>composition) this does not work:
\<compose view-model="myvm" view**.bind**="myvm-variation.html" model="mymodel">

but this does:
\<compose view-model="myvm" view="myvm-variation.html" model="mymodel"> 

**Expected/desired behavior:**
of course documentation and behaviour should be "in sync". In this case I assume the doc's should be updated, since **.bind** usage would refer to a value of the parent model.

**Comment by jdanyow** [comment]
This is working: https://gist.run/?id=3cd5f3bc07dda58e058f5b64f57f1ffd
