### ISSUE TITLE
Custom elements attached method not working when it is placed inside layout slot

### ISSUE THREAD

**Issue by ricbermo** [aurelia/framework#556]
**I'm submitting a bug report**
- **Library Version:**
  I'm not sure about it but on my package.json I found 1.0.0-rc.1.0.0
- **Operating System:**
  OSX 10.11.6
- **Node Version:**
  6.2.2
- **NPM Version:**
  3.9.5
- **Aurelia-CLI**
  0.17.0
- **Browser:**
  Chrome 52.0 | Firefox 48.0 | Not tested in others
- **Language:**
  ES2015

**Current behavior:**
When placing a custom element inside one of a layout slots the attached method is never called, but is I place the same element outside the layout the method does get called. I must add that the element is created and is functional but that callback, than in this specific case I am needing, is not called.
I created [this](https://gist.run/?id=277f8775e729ca87387f5913ce6fd201) gist to show the issue. Notice I used the custom element twice. One inside the layout and the other outside it.

I found this issue while playing a little with Aurelia.
This is the repository link: https://github.com/ricbermo/super-gym-client-aurelia
Feel free to fork it and use it for debugging or w/e.

**Expected/desired behavior:**
I expect the attached callback get called when a custom element is used/placed inside a layout.

**Comment by Alexander-Taran** [comment]
https://github.com/aurelia/templating-router/issues/34
same issue, I think.

**Comment by AshleyGrant** [comment]
@jdanyow would you mind looking at this and the linked issue above? @ricbermo contacted me from reddit about this issue.

**Comment by EisenbergEffect** [comment]
@charlespockert We've had a couple of people report this issue. Since you did the original work to enable the layouts, would you be willing to look into this bug and attempt to fix it?

**Comment by ksm2** [comment]
What is the status regarding this issue? Is there any progress so it'll be possible to use layouts in future versions of Aurelia?

**Comment by EisenbergEffect** [comment]
It should be fixed.
