### ISSUE TITLE
Ability to disable bundling

### ISSUE THREAD

**Issue by fracz** [aurelia/framework#561]
**I'm submitting a feature request**

By default, Aurelia bundles all files so they do not cause to many requests. However, it is really hard to track for errors if we don't know immediately in which file the errorneous code is (the console log always says that error is `at new Something (.../app-bundle.js:18:11)`).

The [doc](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-jspm/1) does not say how to disable it. It only says how to configure more bundles.

It also says that 

>Before deploying your app to production, you'll want to bundle the assets for efficient use of the network.

Actually, I do not want to bundle anything in production. It's [HTTP/2 times already](http://caniuse.com/#feat=http2). Dispatching many requests is not an issue anymore. Moreover, concatenating files [can be considered an antipattern](https://www.smashingmagazine.com/2016/02/getting-ready-for-http2/#concatenating-css-and-javascript) now because it forces you to download the code (JS/CSS) you are not about to use.

**Comment by EisenbergEffect** [comment]
To disable bundling, just go into the js, html and css classes and change the "dest" call to output to a folder instead of into the bundling system. That's all there is to it.
