### ISSUE TITLE
@noView bug

### ISSUE THREAD

**Issue by javadbat** [aurelia/framework#565]
BUGS: 
**I'm submitting a bug report**
* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
windows10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9
<!--

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
 Chrome 53

* **Language:**
ESNext

**Current behavior:**
when we use @noView aurelia throw error in following file:
/jspm_packages/npm/aurelia-templating@1.0.0/aurelia-templating.js
in line 3361 :
`this.view.bindingContext = this.viewModel;`
this.View is null and js cant set a property of null 
please fix it :)

**Expected/desired behavior:**

aurelia-templating.js do not throw exception and render inner tag HTML with data binding

**Comment by EisenbergEffect** [comment]
Can you provide an example that reproduces the problem? We have demos and samples that use this attribute with no errors. So, there's something specific about your scenario that's causing the problem. We'll need some more information to be able to track that down.

**Comment by javadbat** [comment]
https://github.com/javadbat/PersonalSite1

**Comment by javadbat** [comment]
there is no special thing its just a simple app with one varaible

**Comment by EisenbergEffect** [comment]
What exactly would you expect to happen if you declare that your application's root component has no view?

**Comment by javadbat** [comment]
use extenal view file cost Extra traffic and seo problem for me and make my app complex as you see in home.cshtml i just want Aurelia to render dom in main html and dont use extenal file , like what we have in Angular controller . after that complete i just want to try to return my dom from function to write dynamic plugin or directive  
for example in angular directive  i made something like this:
```
TradingSystemApp.directive('bigfont', function () {
    return {
        restrict: 'E',
        replace: 'false',
        transclude: false,
        template: function (element, $scope) {
            $scope.innerContent = angular.element(element);
		return '<h1>'+$scope.innerContent+'</h1>'
}}});
```

**Comment by EisenbergEffect** [comment]
Ok, well you just aren't using the framework correctly. First, there's no penalty for the external file if you use bundling like all our skeletons and the cli are setup to do. Also, you can use inline views if you just want to put your markup inside the same file for some reason. If, instead, you have markup in the dom that you just want to enhance with Aurelia, you can use the enhance api instead of setRoot. Please have a read through the documentation.
