### ISSUE TITLE
cant call function in constructor

### ISSUE THREAD

**Issue by javadbat** [aurelia/framework#572]
BUGS: Please use this template.

**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.2.0
* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
Chrome XX 

* **Language:**
ESNext

**Current behavior:**
easy and simple i want call func1() in constructor but it is undifined :|
my original purpose is : when template loaded i can get red box width and height then make some array randomly in that box i try to use attached() event but it dont recognize func1 too .
https://github.com/javadbat/PersonalSite1/blob/master/src/PersonalSite/wwwroot/Scripts/Aurelia/MainPage/Home.js:
```
import {bindable,inject} from 'aurelia-framework';
export class Home{
    constructor(Element) {
       this.List1 = func1();
        debugger;
    }
    func1(){
        debugger;
return[1,2,4]
    }
}
```

**Comment by devanp92** [comment]
Change  ``` this.List1 = func1();``` to ``` this.List1 = this.func1();```. You need to refer to the current object with _this_.

**Comment by javadbat** [comment]
th
