### ISSUE TITLE
Aurelia fails to render or report an error if template uses self-closing tags

### ISSUE THREAD

**Issue by MNGoldenEagle** [aurelia/framework#583]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7 SP1 (6.1.7601)

* **Node Version:**
5.7.0

* **NPM Version:**
3.6.0

* **JSPM OR Webpack AND Version**
none

* **Browser:**
Firefox 48.0.2 | Chrome 52.0.2743.116

* **Language:**
all

**Current behavior:**
When following the Contact Manager example application, creating the app.html template file with the following content:
```html
<template>
   <require from="bootstrap/css/bootstrap.css"/>
   <require from="./styles.css"/>

   <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="navbar-header">
         <a class="navbar-brand" href="#">
            <i class="fa fa-user"/>
            <span>Contacts</span>
         </a>
      </div>
   </nav>

   <div class="container">
      <div class="row">
         <span>Contact list placeholder</span>
         <router-view class="col-md-8"/>
      </div>
   </div>
</template>
```

Expecting this template to behave like other standard XML/XHTML documents, I ran the application (which built without reporting any issues) and a blank screen was displayed.  The contents of the CSS files were inlined into the resulting HTML, but nothing further than that.

**Expected/desired behavior:**

* **What is the expected behavior?**
The expected behavior is that it would properly render if the tag is self-closed rather than using an explicit close tag.  Alternatively, it would be expected that Aurelia would display an error or warning message on the console if the template was malformed.

* **What is the motivation / use case for changing the behavior?**
It is difficult to diagnose the underlying issue to this problem without examining the framework code or trying to make blind guesses.  With a small sample application this isn't so big of a deal, but with a larger application it would be more problematic.  Even more of an issue is that those who are used to working with XML/XHTML will expect to be able to use this kind of syntax (and can with the standard HTML tags), so having inconsistent requirements within the same document becomes even more difficult to work with.

**Comment by EisenbergEffect** [comment]
This is an issue with HTML itself, not with Aurelia. HTML only allows for a certain, small set of tags, to be self-closing. The HTML parser literally doesn't support it.

@MeirionHughes Is this something that is or could be handled by your template linter?

**Comment by MeirionHughes** [comment]
Yes, this this was the reason I wrote the [lint](https://github.com/MeirionHughes/aurelia-template-lint). :)

XHTML is technically different though. right? If you use the xhtml doc type it will decode with xml schema instead.
