### ISSUE TITLE
Cannot use 2 components which inherit the same base class

### ISSUE THREAD

**Issue by len-ro** [aurelia/framework#584]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.42

* **Browser:**
Chrome 52

* **Language:**
TypeScript

**Expected/desired behavior:**
I have 2 components which VM inherits the same base class. M1 inherits M and M2 inherits M. Cannot use the 2 components in the same template:

```
<template>
    <require from="m2"></require>
    <require from="m1"></require>
    
    <m1></m1>
    <div style="border:2px solid red">&nbsp;</div>
    <m2></m2>
</template>
```

Can be replicated using the following gist: https://gist.run/?id=84226c914f3a8ff2a6afa41ccdeef9e3

Only one component is shown (the one with the last require). Change the order of the require in app.html to see or remove the `extends M` from any vm (M1.js or M2.js) and both components will show.

**Comment by EisenbergEffect** [comment]
We have this tracked already, but it's not a priority for us to fix because we want to discourage inheritance. Instead, consider using decorators to enable composition.
