### ISSUE TITLE
Aurelia can't resolve the root View Model when Redux is imported

### ISSUE THREAD

**Issue by Zensavona** [aurelia/framework#587]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.4

* **Node Version:**
5.6.0

* **NPM Version:**
3.6.0

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When I import a particular file (see `src/app.js` in the repository), Aurelia is producing errors like `Unhandled rejection Error: No view model found in module "app".`.

To make the error go away, comment out line 1 from `src/app.js` 

The particularly interesting thing about this is that it occurs in (latest versions of) Chrome and Safari on BrowserStack, Safari locally on my Mac, but *not* Chrome locally (exactly the same Chrome version, 52.0.2743.116 (64-bit)).

Some screenshots:

Safari locally:
![Safari locally](http://i.imgur.com/z9Qrysk.jpg)

Chrome locally:
![Chrome locally](http://i.imgur.com/faiXXWa.jpg)

Chrome on BrowserStack:
![Chrome BrowserStack](http://i.imgur.com/ILBE2YJ.jpg)

**Steps to reproduce:**
- clone `https://github.com/Zensavona/aurelia-redux-bug-repro`
- `npm install && npm run build`
- view the resulting files in your browser

Note: You'll see in the screenshots that the app is served at `/web-admin/`, this is just to do with our dev server, I've removed this baseUrl from `webpack.config.json` and this will effect the `<base>` tag in `index.html` also. 

**Expected/desired behavior:**
To behave as it does in Chrome locally on my machine (second screenshot) and display the text "Hello, Zen"

* **What is the expected behavior?**
The above mentioned error occurs and Aurelia can't find the view-model.

I've spent a fair amount of time trying to debug this without success, if you guys have any ideas about what could be going on here I would much appreciate.

**Comment by EisenbergEffect** [comment]
If something is setting the base, that's going to change the module resolution probably. What is causing that?

**Comment by Zensavona** [comment]
The `<base>` tag is set by webpack, exactly as it is in the official webpack navigation skeleton project. All I meant is that because on my dev machine it's served at `http://somewhere/web-admin/`, my `baseUrl` in `webpack.config.json` reflects that, if you're running the reproduction project on some javascript dev server locally at `http://somewhere/`, the `baseUrl` will work (it's set to `/`, as in the skeleton nav project).

**Comment by Zensavona** [comment]
Hey @EisenbergEffect any ideas about what could be causing this?

**Comment by EisenbergEffect** [comment]
I have no idea to be honest. I'm not sure how they could be related. Can you attache me a zip with the most basic example so I can take a look?

**Comment by forest** [comment]
@Zensavona any progress on this. I am having the same issue. I found that if I comment out the `applyMiddleware` code it works fine. I can call `createStore` with a basic reducer, but when I try to `applyMiddleware` I get the `No view model found in module` error.

**Comment by forest** [comment]
@Zensavona this isn't redux specific. I think it has something to do with webpack. I removed the `applyMiddleware` and then ran into the same issue with some firebase initialization code.

**Comment by Zensavona** [comment]
@forest my issue was to do with Redux Devtools, if you check line 38 of `configureStore.js` in my repro repo you'll see `window.devToolsExtension ? window.devToolsExtension() : null`.

In fact it should have been `window.devToolsExtension ? window.devToolsExtension() : f => f`. Aurelia was just swallowing the error.

I guess this can be closed, swallowing errors like these is far from ideal behaviour but I suppose that's a different issue.

**Comment by forest** [comment]
Thanks for the update.

**Comment by EisenbergEffect** [comment]
@Zensavona I'll close this for now. If you can locate a place where we can put some error handling code in Aurelia itself to report the error, let us know.
