### ISSUE TITLE
ES6 arrow functions are not generated with the correct function context

### ISSUE THREAD

**Issue by sunjay** [aurelia/framework#59]
One of the major benefits of ES6 arrow functions is that they inherit the `this` context of whatever function they are being called from. 

This expected behaviour is further clarified on the [MDN Arrow functions page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this):
> Arrow functions capture the this value of the enclosing context

Currently, if you define a function like this:

    (test) => this.a + this.b;

It is transpiled into this:

    (function (test) {
        return this.a + this.b;
    });

This does not correctly bind/capture the outer context and results in incorrect code.

**Comment by EisenbergEffect** [comment]
This is not an Aurelia issue. You should take that up with Babel.

**Comment by xjamundx** [comment]
.... it's not a babel issue ;-)

**Comment by xjamundx** [comment]
https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=true&spec=false&code=%0Afunction%20a()%20%7B%0A%20%20var%20x%20%3D%20(car)%20%3D%3E%20this.wash%0A%7D%0A

babel correctly handles `this` in arrow functions

**Comment by xjamundx** [comment]
I think the code is wrong basically.

try this:
`(test) =>{  this.a + this.b; }`

**Comment by sunjay** [comment]
Yes. Sorry about that. It turns out that because of the way source maps work, the ES 6 code shown in Chrome's inspector displays Window as the this context for the function. That is technically correct because babel generates a `_this` variable and replaces `this` throughout the function. When Chrome looks up `this` when I set a breakpoint, it does not find the correct value.

Disabling source maps in chrome's inspector and debugging the raw generated code helped me find my bug.

**Comment by EisenbergEffect** [comment]
Glad it got worked out and thanks for the explanation!
