### ISSUE TITLE
Please provide guidance and documentation for switching the root and correctly handling navigation

### ISSUE THREAD

**Issue by glen-84** [aurelia/framework#590]
There doesn't appear to be any documentation for the common case of switching the root VM for a login (or similar) VM, and back again.

Surprisingly, there's also what appears to be a very critical [bug](https://github.com/aurelia/framework/issues/400) which was not addressed before the 1.0 release.

What I need to do is similar to what is described in these SO topics: [one](http://stackoverflow.com/questions/33458274/how-to-switch-between-login-page-and-app-with-aurelia), [two](http://stackoverflow.com/questions/38120388/aurelia-switching-between-app-roots-with-different-route-configurations)

I tried to implement the suggestion [here](http://stackoverflow.com/a/38121060/221528), but it doesn't seem to work well and feels a lot like a hack (messing with `mapUnknownRoutes`, etc.).

The problem is that if you're currently on `/a`, and then call `setRoot("x")`, the `x` root VM will try to load `/a` again instead of the route that you actually want.

Would it be possible to have something like `setRoot("x", null, "/route/in/x")` where the last param is either a "fragment" or a route name? This would then load the `x` root and navigate to the specified fragment/route instead of trying to reload the current route.

This is really quite important/urgent.

**Comment by EisenbergEffect** [comment]
We already have this tracked as an issue. Also, we don't use github for questions....

That said, if it were me, I would just use the router to change the history to what you want it to be:

```
this.router.navigate('route/in/x', { replace: true, trigger: false});
this.router.reset();
this.router.deactivate();
this.aurelia.setRoot('x');
```

**Comment by glen-84** [comment]
@EisenbergEffect,

> We already have this tracked as an issue

Where? This is not the same as #400. This is a request for guidance and documentation on how to do something *very* common that is currently extremely awkward.

> Also, we don't use github for questions

This is not a question. This is a request for either documentation or new API. I have done my research (as shown by the SO links), and I was not able to find a satisfactory solution.

> I would just use the router to change the history to what you want it to be

I'll try this, and I appreciate the suggestion, but:

1. It's more involved than it should be for something so trivial.
2. How will hundreds if not thousands of other developers find this information?

With 1.0 out, does this mean that we have to live with work-arounds and funky solutions now? :disappointed:

**Comment by EisenbergEffect** [comment]
If you are reporting an issue, you need to use the issue template. We don't accept issues that don't follow that template.

That said, there is nothing "funky" about the solution I provide. It uses standard apis which were designed for the specific purposes. When used in combination, they accomplish your specific use case. Not everyone that is using setRoot needs to do what you are doing. Some people use a router but don't want to change the history. Some people don't use a router at all. In your case, you want to change the history and reset the router when you set root again. That's a particular combination which isn't always the same for everyone.

We can add a "recipe" for something like this in the future. Please create an issue on the documentation repo. That's where we track requests for docs.

**Comment by glen-84** [comment]
@EisenbergEffect,

My apologies for not using the template. When I read `BUGS: Please use this template` I thought that it was only for bugs. I didn't realize that you needed all the version numbers etc. for a feature/enhancement.

It looks like your solution might work from VMs, but I'm not sure how to use it from the main/configure file (I tried by getting the router with `aurelia.container.get(Router)`, but it doesn't seem to work) – should I ask about this on StackOverflow rather?

Thanks.

**Comment by EisenbergEffect** [comment]
I think doing that from main.js is going to be problematic because there isn't really a navigation system up and running at that time. You could also consider setting up some configuration in main.js, storing that in the container and then having the app.js component inject that and use it to dynamically configure the router. I don't know if that fits your scenario though.

**Comment by glen-84** [comment]
I'm not sure exactly what you mean. I'm getting desperate so I hacked together a new `useRoot` decorator, LOL.

```ts
function useRoot(root: string, rootPath: string) {
    return (target) => {
        const activate = target.prototype.activate;

        target.prototype.activate = async (params, routeConfig, navigationInstruction: NavigationInstruction) => {
            const container: Container = navigationInstruction.router.container;
            const aurelia: Aurelia = container.get(Aurelia);

            if (container.root.viewModel.constructor.name !== root) {
                await aurelia.setRoot(rootPath);
            }

            activate();
        };

        return target;
    }
}

@autoinject
@useRoot("AppGuest", "/assets/app/view-models/app-guest.js")
@useView("../views/login.html")
export class Login extends Base {
    // ...
}
```

... I think it works but it scares me too much. :laughing:

**Comment by EisenbergEffect** [comment]
constructor.name won't work if you minify the code.

**Comment by glen-84** [comment]
GitHub needs a sad face reaction. =)

I'm wondering now if it would make sense to put a view selection strategy on the `App` VM, that maps routes to a specific enclosing view/"layout".

It's getting late so I'm probably forgetting something obvious that would prevent this from working. I'll take a look tomorrow.

Anyway, thanks for your help.

**Comment by johot** [comment]
Just wanted to say thanks and that Robs suggestions work! It's important to note that without the:
`... { replace: true, trigger: false });`

part it didn't work properly and I would get errors during the second app root switch (for some reason?).

Also the deactivate method does not exist on the router, should it still be called?
