### ISSUE TITLE
Handling null/undefined values when binding to HTML attributes

### ISSUE THREAD

**Issue by landofjoe** [aurelia/framework#599]
**I'm submitting a bug report**

* **Library Version:**
Aurelia-cli 0.18.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.9.0

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
n/a

* **Browser:**
all

* **Language:**
all

**Current behavior:**

When populating HTML attributes using a binding command, such as `one-way`, the values `null` and `undefined` are rendered as literal strings, `"null"` and `"undefined"`, respectively.

When using string interpolation to populate HTML attributes, the values `null` and `undefined` are rendered as empty string, as stated in the documentation:
http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-basics/6

This is somewhat confusing, since `value.bind` does seem to automatically convert null/undefined values to empty string.

**Expected/desired behavior:**

I would like for data-bound HTML attributes to always render `undefined` and `null` the same as an empty string.  I worked on a very large Durandal/Knockout project, and this default behavior was almost always the correct one.  Providing an opt-out of this behavior should handle any edge cases where the string-version of these values is needed.

Alternatively, an explanation as to when string interpolation should be used and why, instead of the `.bind` function and why the values are deliberately rendered differently between the two.

* **What is the motivation / use case for changing the behavior?**

It is difficult to predict when/where the values will show up as `"undefined"` instead of empty string.

**Comment by jdanyow** [comment]
String interpolation binding always converts the result of a binding expression to a string. In this context, developers always want `null` or `undefined` to be presented as empty-string.

Attribute binding can be used for all sorts of types: objects, numbers, strings, dates, etc.  It would be very confusing if the binding system coerced values to strings. It's already confusing enough for developers that don't realize the `<input>` element coerces anything assigned to it's value property/attribute to a string, even in `type="number"`, `type="range"`, etc inputs.

**Comment by rockResolve** [comment]
See closely related #288 and #308.
