### ISSUE TITLE
Testing with bluebird

### ISSUE THREAD

**Issue by hadrienl** [aurelia/framework#60]
Hi,

Thank you for your great job, you made an excellent framework.

I can't find the way to include bluebird in my jasmine tests. I've added its path in karma.conf like this :

`files: ['jspm_packages/github/petkaantonov/bluebird@2.9.12/js/browser/bluebird.js'],`

but it's never loaded and I don't have a .finally method.

**Comment by EisenbergEffect** [comment]
You probably need to import it through the module system.

**Comment by hadrienl** [comment]
How ? The only doc I can found about bluebird is here http://aurelia.io/docs.html#promises :
"By default, Aurelia uses ES6 native Promises or a polyfill. However, you can replace this with the excellent Bluebird Promise library. Simply include it in your page before you reference the other scripts. It will provide its own standards-compliant Promise implementation which is currently faster than native and has better debugging support. Additionally, when used in combination with the 6to5 transpiler, you can use coroutines for improved async code.'

**Comment by EisenbergEffect** [comment]
At the top of your test `import 'bluebird'` should be all you need I think.

**Comment by hadrienl** [comment]
"Uncaught Error loading "bluebird" at projectpath/bluebird.js"

**Comment by hadrienl** [comment]
I don't understand why I should have to load the file differently in browser mode and in test mode. If I have to load it before System in browser mode, I though I should have the same in test mode. But why karma doesn't load files set in its `files` attribute ?

**Comment by hadrienl** [comment]
If I believe in karma debug log, it would be because all files in jspm_packages are ignored…

**Comment by hadrienl** [comment]
I'ev duplicated bluebird.js file in another folder, and now it works… not very nice…

`files: ['tests/mocks/bluebird.js'],`
