### ISSUE TITLE
$index should be a number, not a string

### ISSUE THREAD

**Issue by geleto** [aurelia/framework#604]
* **Library Version:**
1.0.3

It seems that when I do value.bind("$index") the value is bound to a string of the index.
Which can sometimes cause confusion, for example, see this gist:
**https://gist.run?id=4bf7ef1466a13a03b9966114f17cacf2**

For the first drop-down I have a number property which is bound to a `<select>` value, and each `<option>` value is bound to `$index`. I think this does not work because the select value is bound to a number and the option value is bound to `$index`, which is a string.

For this to work I have to explicitly convert the property to string, like I did for the second drop-down.

**Comment by jdanyow** [comment]
An HTMLOptionElement's value attribute will coerce anything it's assigned to a string (as will an HTMLInputElement's value attribute).

A string interpolation binding (`${.....}`) will also coerce values to a string, replacing null and undefined with empty-string.

Check out the binding docs for the `<select>` element. There a bunch of samples demonstrating data-binding to various data-types.
