### ISSUE TITLE
Properties defined in app.js are not always visible for second level child views

### ISSUE THREAD

**Issue by ah1508** [aurelia/framework#610]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Linux Unbuntu

* **Node Version:**
6.2.2

* **NPM Version:**
3.6.5

* **JSPM Version**
JSPM 0.16.45

* **Browser:**
Chrome 49, Firefox 47

* **Language:**
ESNext

* **Other:**
local server : browserSync + connect-history-api-fallback

**Current behavior:**
With a child router, the second level view cannot access the properties defined in the app.js if the user tries to access directly to the child view (if he bookmarked the url of if he refresh the page).

A property "myProperty" defined in app.js appears well in the first level view (${myProperty}) but not in the second level view. Of course it works if the users starts his navigation from the index page. It only concerns the first access (after a refresh for instance), if the user navigate (to a sibling second level view and come back to the second level view he requested initially) it works.

**Expected/desired behavior:**
Second level views should always have access to the property defined in the app.js

**Comment by EisenbergEffect** [comment]
2nd level views don't have access to their parent view model. That is by design in order to encapsulate views and prevent unnecessary structural coupling. If you need access to the App class, you can have it injected into the child component. That makes the relationship explicit and is considered a better practice.
