### ISSUE TITLE
Todo MVC Example

### ISSUE THREAD

**Issue by joezimjs** [aurelia/framework#62]
I was just curious if you or anyone planned on making a TodoMVC demo with it. Maybe I'll take a look into it when I get time, but I'm partially just wondering because of an article on performance: http://www.filamentgroup.com/lab/mv-initial-load-times.html

It'd be nice to be able to compare it to others performance-wise and also have the baseline app to use for comparing performance between releases, though the skeleton app could work for the latter.

**Comment by miroslavpopovic** [comment]
There are already few implementations:
- https://github.com/sonnylazuardi/todomvc-aurelia
- https://github.com/mhoyer/todomvc-aurelia

As for performance, it's not yet relevant, since bundling and minification story aren't completed. They are focus of the next iteration - http://eisenbergeffect.bluespire.com/aurelia-status-march-2015/.

**Comment by mPisano** [comment]
Also Check out:

https://github.com/cmichaelgraham
https://github.com/AshleyGrant

For some TypeScript and Visual Studio projects

**Comment by EisenbergEffect** [comment]
We've got one built by the community which was submitted to Todo MVC. I'm going to review it and if it looks good, or good enough with a few modifications, then we'll bring it in as an official sample. In the meant time, definitely check out this: https://github.com/mhoyer/todomvc-aurelia

**Comment by omidkrad** [comment]
Should list it at [TodoMVC.com](http://TodoMVC.com/)

**Comment by jdanyow** [comment]
Breeze flavored todo app:  [code](https://github.com/jdanyow/todo-aurelia-breeze), [live](https://jdanyow.github.io/todo-aurelia-breeze)
