### ISSUE TITLE
Where is the best place to wedge in remote resource loading for modules?

### ISSUE THREAD

**Issue by ngib** [aurelia/framework#63]
I started with the "Get Started" project and am working from there to get to understand the framework. I'm new to JSPM and System JS as well, so this has been a learning experience! So far, great framework to develop with!

Due to some limitations of the platform I'm developing for, HTML and JS resources have to all be stored in some remote bucket (e.g. CDN, S3). Using System JS and setting the paths property allows me to remap the view models, but the views/templates are still being pulled from the local server. Where should I look to get this working?

**Comment by ngib** [comment]
To clarify, I can only have one HTML resource (the index page) and no javascript resources on the server. The rest have to be remote.

**Comment by EisenbergEffect** [comment]
This will be solved in the next release which will correctly use the system.js loader to resolve all paths, including views.

**Comment by EisenbergEffect** [comment]
In master. Going out in next release.
