### ISSUE TITLE
"css" attribute seems to be ignored on <textarea>

### ISSUE THREAD

**Issue by sousekd** [aurelia/framework#633]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

**Current behavior:**
"css" attribute seems to be ignored on `<textarea>`

**Expected/desired behavior:**

1) add `<textarea css="color: blue">` and `<textarea style="color: blue">` to a template
2) open in browser - the one with "style" attribute "works", the one with "css" attribute not

* **What is the expected behavior?**
I would expect "css" attribute to work on `<textarea>` element in the same way as it works on `<input>` elements

**Comment by EisenbergEffect** [comment]
@jdanyow Can you check this out?

**Comment by jdanyow** [comment]
this is https://github.com/aurelia/templating-resources/issues/237

need to use `css.bind` or the `style` attribute directly if there's no data-binding in the attribute.
