### ISSUE TITLE
@observable does not work when used with reflect-metadata polyfill and TypeScript

### ISSUE THREAD

**Issue by geleto** [aurelia/framework#637]
- **Library Version:**
  1.0.7
- **Browser:**
  Chrome
- **Language:**
  TypeScript

When using the [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) polyfill in a TypeScript project - the @observable decorator does not work, the callback is never called. If I use @bindable instead, or use an ЕSNext project - everything works properly. 
While there looks to be a reflect polyfill in Aurelia, it is incomplete and is not working with the [class-transformer](https://github.com/pleerock/class-transformer) library.
### Steps to reproduce the problem:
- Create a new TypeScript aurelia-cli project
- Install reflect-metadata:
  `npm install reflect-metadata --save-dev`
- Add reflect-metadata to `prepend` in aurelia.json:

```
"prepend": [
  "node_modules/bluebird/js/browser/bluebird.core.js",
  "scripts/require.js",
  "node_modules/reflect-metadata/Reflect.js"
]
```
- Use this code in `app.ts`:

``` typescript
import { observable } from 'aurelia-framework';

export class App {
  @observable message = 'Hello World!';
  attached() {
    setTimeout(() => {
      this.message = 'Bye bye!';
    }, 5000);
  }
  messageChanged(newValue, oldValue) {
    console.log(oldValue, newValue);
  }
}
```

**Comment by timfish** [comment]
I spent ages trying to debug this. It should be fixed or at least documented somewhere!

**Comment by EisenbergEffect** [comment]
@PWKad Can you look into this? Maybe @jdanyow Something is going on there.

**Comment by timfish** [comment]
This might have been fixed by some recent bug fixes. I've updated all my dependencies and no longer have this issue. @geleto is it fixed for you if you do the same?

I'm on:

```
    "aurelia-binding": "npm:aurelia-binding@1.1.1",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@2.0.1",
    "aurelia-framework": "npm:aurelia-framework@1.0.8",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.1.0",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.1.1",
    "aurelia-router": "npm:aurelia-router@1.1.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.2.0",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.2.0",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.1",
    "reflect-metadata": "npm:reflect-metadata@0.1.9",
```

**Comment by geleto** [comment]
Yes, this bug seems to be fixed in the latest release.
