### ISSUE TITLE
default export module

### ISSUE THREAD

**Issue by Kabe0** [aurelia/framework#639]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
Linux (distro)

* **Node Version:**
6.2.0

* **NPM Version:**
3.5.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
Chrome 54

* **Language:**
TypeScript X.X

**Current behavior:**
Module loads but aurelia ignores the component and does not display it.

**Expected/desired behavior:**
If defined export default class ClassName
and included as `<require from="ModuleName"></require>`

it should be able to load the module and display the component without a problem.

* **What is the expected behavior?**
To display the component if the same as filename requested.

* **What is the motivation / use case for changing the behavior?**
the Default module is useful in development when wanting to define the main class (or object) that should be returned when loading the module.

**Comment by AshleyGrant** [comment]
@Kabe0 would you mind updating the description with some information? We need you to fill out the issue template or we cannot help you.

Thanks!

**Comment by Kabe0** [comment]
Haha, Sorry accidentally submitted before being able to writing anything! thanks!

**Comment by EisenbergEffect** [comment]
It's a feature request to support default exports. We have that tracked already elsewhere.
