### ISSUE TITLE
Object literal as view-model

### ISSUE THREAD

**Issue by honkskillet** [aurelia/framework#64]
Sorry if this question is a little basic.  In the getting start doc I saw this...
> You can use AtScript, TypeScript, CoffeeScript...or today's browser language: ES5. All you have to do is follow the language's standard pattern for creating classes and everything will work fine.

Can you use an object literal to represent an aurelia view-model instead of a class?  If yes, what would it look like?

**Comment by EisenbergEffect** [comment]
It's not set up to enable that currently. Mainly the use of classes helps memory management and performance (particularly when they are native an constructed statically). So, we are favoring that approach. However, we could add support for literals I suppose. Bare in mind that literals can't benefit from dependency injection, so there might be limited practical use.

**Comment by honkskillet** [comment]
Yeah, without DI there really would not be any point.  What's the limitation of literals that precludes DI?

**Comment by bastienJS** [comment]
You can not instantiate an object literal but a class you can. Thus you can inject something.
