### ISSUE TITLE
Use npm @types for TypeScript definition file acquisition 

### ISSUE THREAD

**Issue by eamodio** [aurelia/framework#643]
**I'm submitting a bug report**
Acquiring TypeScript definition files for Aurelia is very difficult. If they were published on npm under @types it would be drastically improved (as TypeScript 2 automatically looks for types there and no need for another tool like typings).
- **Library Version:**
  1.0.7

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.12.1
- **Node Version:**
  6.9.1
  
  
- **NPM Version:**
  3.10.8
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.47
  
  
- **Browser:**
  all
- **Language:**
  TypeScript 2.0.6

**Current behavior:**
Requires another tool `typings`, requires edits to `tsconfig.json` to look in the typings folder, etc.

**Expected/desired behavior:**

`npm install @types/aurelia` :)
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
  Improve the use of Aurelia and TypeScript

**Comment by StrahilKazlachev** [comment]
I'm not using the `typings` tool and have not problems whatsoever. The aurelia packages have the `typings` property set. The TS [docs](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) say:

> If you control the npm package you are publishing declarations for, then the first approach is favored. That way, your declarations and JavaScript always travel together.

> Note that the "typings" field is synonymous with "types", and could be used as well.

**Comment by eamodio** [comment]
@StrahilKazlachev it must be JSPM that is borking things for me then -- since I'm using jspm rather than npm to install the Aurelia packages

**Comment by StrahilKazlachev** [comment]
Aaaah, yes, I have npm packages for dev/compilation, jspm for runtime deps.

**Comment by eamodio** [comment]
So you duplicate all the packages? once in devDependencies and once in jspm?

**Comment by StrahilKazlachev** [comment]
Yes. Also we do have our own packages, so we have some of them in peer.

**Comment by eamodio** [comment]
@StrahilKazlachev thanks - I'll have to give that a try!

**Comment by jdanyow** [comment]
closing - @StrahilKazlachev is correct, Aurelia packages provides the `typings` property in their package.json which is the preferred way to tell the typescript compiler where the defs are.

**Comment by vegarringdal** [comment]
Any edits on this part ?

Got this during npm install:
`npm WARN deprecated typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information`
