### ISSUE TITLE
View-specific css isn't unloaded after navigation to another view

### ISSUE THREAD

**Issue by sysanin** [aurelia/framework#645]
Hi,
I use bootstrap for admin part of my site and it conflicts with public site css, so I want to load bootstrap only for the admin part. I used `<require from="bootstrap/dist/css/bootstrap.css"></require>` in admin template, so Aurelia loads it only in admin part.
The problem is that this css isn't unloaded after navigating back to public site, it stays in head.

I use the latest aurelia with webpack from skeleton.

**Comment by AshleyGrant** [comment]
Hi @sysanin this is a known issue. We are currently exploring the correct way to fix this.

**Comment by jdanyow** [comment]
@AshleyGrant are there plans to remove css once it's been loaded. Wondering if this would be an unnecessary perf tax in most people's use cases.

**Comment by EisenbergEffect** [comment]
I wasn't planning to change this actually.
However, the new styles coming in AureliaXP might be a nice alternative. That's what I would use.

**Comment by AshleyGrant** [comment]
I was speaking of the styles stuff that @EisenbergEffect is mentioning.
