### ISSUE TITLE
doc: quickstart - basic-aurelia-project.zip should be with ES Next by default

### ISSUE THREAD

**Issue by Nasicus** [aurelia/framework#649]
Hi

This is more like a PR instead of an issue, but since I would need to change the content inside the download package (and I don't know how to do this), I'm trying it here.

It's a minor thing, but since everything (especially all code samples) are by default set to "Es Next" the basic package should also reference the ES Next file instead of the TS file.

Basically this would mean to change 

`<script src="scripts/config-typescript.js"></script>` 
to 
`<script src="scripts/config-esnext.js"></script>`.

Obviously the text on the quick start page would also need minor adjustments.

What do you guys think?

Greetings
Patrick

**Comment by EisenbergEffect** [comment]
Feel free to submit PRs for that.
