### ISSUE TITLE
RouterView with Layout Causes "attached" Not Called on Custom Elements

### ISSUE THREAD

**Issue by michaelsg** [aurelia/framework#650]
**I'm submitting a bug report**
* **Library Version:**
1.0.7

* **Operating System:**
Windows 10

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **Browser:**
all 

* **Language:**
TypeScript 2.0

**Current behavior:**
If a layout-view is used on a RouterView or a layout is specified for a route, the composed view's used custom elements' "attached" functions are never called.
This happens whether a layoutView is used without a viewmodel or a layoutViewModel is used.
If a layoutViewModel is used, its "attached" is called, but not those of the custom elements contained.
If the layout is specified only on certain routes, only those pages demonstrate the bug.
"detached" is not called either.

**Expected/desired behavior:**

Custom Element callback events function whether composed into a router-view with a layout or without one.

gist of broken example - with layout: 
https://gist.run/?id=523320b2686bf2044f723b91fab608d5

gist of working example - without layout: 
https://gist.run/?id=ad7492d73fbac902860e599fe384b796

**Comment by aegenet** [comment]
Unfortunately same issue : #https://github.com/aurelia/templating-router/issues/34 .

**Comment by EisenbergEffect** [comment]
Closing as duplicate.
