### ISSUE TITLE
Broken JSON structure in official doc.

### ISSUE THREAD

**Issue by gustawdaniel** [aurelia/framework#659]
**I'm submitting a bug report in official docs about routing on the bottom of website**

![](http://i.imgur.com/Ss1Ev2B.png)

In `app.js` in `config.map` there should be ":" instead of "=" after layout view, because of json structure is broken.

**Comment by EisenbergEffect** [comment]
This document is located in the docs folder of the router repository. Would you be interested in sending a PR to fix the typo?

**Comment by gustawdaniel** [comment]
I would be interested. I love this project, but I don't know how. In documentation on [github](https://github.com/aurelia/router/blob/master/doc/article/en-US/router-configuration.md) there is everything ok!

[![github.png](https://s21.postimg.org/5mp5stvuf/github.png)](https://postimg.org/image/8gsb69y0j/)

**Comment by EisenbergEffect** [comment]
Oh! It was probably already fixed then. We just need to release the update to the docs. The docs update release will go out early next week. Sorry for the confusion!
