### ISSUE TITLE
should add a TodoMVC example

### ISSUE THREAD

**Issue by chovy** [aurelia/framework#66]
https://github.com/tastejs/todomvc/tree/master/examples

**Comment by Nevraeka** [comment]
Great idea @chovy . The more examples the project has the more developers will be apt to try it out and play around

**Comment by miroslavpopovic** [comment]
Check out #62.

**Comment by Nevraeka** [comment]
@miroslavpopovic thank you...asked, received....BOOM! lol

**Comment by EisenbergEffect** [comment]
Closing this since it was done a while back...
