### ISSUE TITLE
Contact Manager Tutorial (Step 2) does not seem to work in Edge

### ISSUE THREAD

**Issue by halllo** [aurelia/framework#668]
**I'm submitting a bug report**

* **Library Version:**
1.0.7

* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
I dont know.

* **Browser:**
Edge 38

* **Language:**
TypeScript 2.0

**Current behavior:**
I wanted to do the Contact Manager Tutorial (http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial) and created a new aurelia project with au new and then au run. In Chrome it shows "Hello World" and no errors in the Console. In Edge it does not show "Hello World" and there are errors in the Console.

![Screenshot](https://pbs.twimg.com/media/CzD5HEJWIAAWWuZ.jpg)

I committed it https://github.com/halllo/AureliaTutorial/tree/master/contact-manager.

**Expected/desired behavior:**
What do I need to do in order to have it working on Edge?

**Comment by AshleyGrant** [comment]
What version of the CLI are you running? Please make sure it is `0.23.0` You can check using `au -v`. If you are using an older version, please upgrade and start over. There was a bug in earlier versions of the CLI that might be causing this issue. If you still have the issue after upgrading your CLI, please let us know.

Thanks!

**Comment by halllo** [comment]
Yes, it already is version 0.23.0.

**Comment by AshleyGrant** [comment]
Please comment out the following lines in `main.js`:
```javascript
Promise.config({
  longStackTraces: environment.debug,
  warnings: {
    wForgottenReturn: false
  }
});
```
Then refresh Edge. It'll work then.

There's open issue regarding this on the CLI repo. @EisenbergEffect this issue can be closed here.

**Comment by halllo** [comment]
Yes, it works now. Thanks :)

**Comment by EisenbergEffect** [comment]
@AshleyGrant Do we have a PR to fix this up?
