### ISSUE TITLE
Trying to use string interpolation within attributes silently fails

### ISSUE THREAD

**Issue by grofit** [aurelia/framework#669]
**I'm submitting a bug report**

* **Library Version:**
major

**Please tell us about your environment:**
* **Operating System:**
N/A

* **Node Version:**
N/A

* **NPM Version:**
N/A

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
all

* **Language:**
all

**Current behavior:**
If you attempt to put a string interpolated value inside an attribute in your markup the attribute is omitted from the generated outputl

**Expected/desired behavior:**
The textual output should contain the interpolated string, here is an example of the problem:
https://gist.run/?id=c3d618546a0fef10a266109465eed94c
(ray is never outputted nor is there an error as to why its been omitted)

Here is a SO question which started this:
http://stackoverflow.com/questions/41021661/aurelia-not-outputting-attribute-with-string-interpolation-in-repeat

* **What is the motivation / use case for changing the behavior?**
Because 3rd party libs outside of aurelia may use attributes as a means for hinting intent, but you may want to use some of your data in the view model within the attribute.

**Comment by EisenbergEffect** [comment]
We can't leave the attribute as is because that would contain the interpolation syntax. So, we remove the attribute. If you want the attribute to be updated with the final value that comes from the binding engine, you can use the `attr` binding behavior. The reason for this is that Aurelia's binding system works against properties, not attributes. Some properties are automatically reflected to attributes by the DOM. Others aren't. Most of the time this doesn't matter, but as you mention it does in some cases, especially when the attrs are important to libraries. So, we provide the binding behavior to let you opt into that.

**Comment by grofit** [comment]
Is there any documentation on this `attr` approach? as I expected there was some more "official" attribute related binding much like knockout has `attr` but I couldnt find anything on a precursory look through the docs (hence why I went on SO and posted here).

**Comment by MeirionHughes** [comment]
try this: https://gist.run/?id=c3d618546a0fef10a266109465eed94c

using an intermediary template: 
```html
<template bindable="bar">
  <div something.bind="bar & attr">${bar}</div>
</template>
```

```html
<template>
  <require from="foo.html"></require>
  <foo repeat.for="item of items" bar="[${$index}]"></foo>
</template>
```

but for some odd reason `some-thing.bind="bar & attr"` is added as `something="[0]"` :S

**Comment by grofit** [comment]
Thanks for the example @MeirionHughes, it does seem quite verbose just to get a value into an attribute and although your above approach *does* provide me a value into the attribute it malforms the name so @EisenbergEffect is there any docs around best practice to do this sort of thing or any official docs on the subject of attr binding behaviours?

Ideally I need to be able to stipulate what the attribute name should be i.e `some-attribute-name` and the value of it `something[0]` with `0` being derived from a value within the aurelia lifecycle, i.e `$index` or something.

**Comment by cirelli94** [comment]
My array is in the view model, so I simply passed the index and get the object by the array, and the parameter by the object.

However, this would be wonderful to have interpolation within attributes.
