### ISSUE TITLE
Add step in build process for custom processing

### ISSUE THREAD

**Issue by Svish** [aurelia/framework#67]
Would be good with a hook/switch/step in the Aurelia gulp/build process where you could add your own processing. This should be done in such a way that one wouldn't have to touch the Aurelia build files at all (to prevent messing them up or having your stuff overwritten every framework update). The hook/switch/step should probably be as late in the build process as possible so you could in theory even act on the files built by Aurelia.

**Example usages**

* Compiling Less/Sass/Stylus files
* Minifying CSS
* Generate thumbnails for images
* Run database migration scripts
* ... etc?

---

:information_source: [Start of related Gitter conversation](https://gitter.im/Aurelia/Discuss?at=5502d1ebff6ec3eb42fa4368)

**Comment by EisenbergEffect** [comment]
Can you provide some additional thoughts on what you think this would look like ideally?

**Comment by Svish** [comment]
Don't know enough about Gulp and such to say much on how I'd want things to look really. Chatted a bit more with @AshleyGrant after I created this issue and got some things clarified. For example that Aurelia will actually be built already and pulled down through jspm (or was it npm?) and that the build tasks and everything we get in the skeleton app is only meant as a starting point which you from that point own and maintain.

As a newb coming from PHP and not really used to any sort of building other than pressing a button in Visual Studio and that kind, what I would appreciate is I guess a good set of tools, like the current build tasks that comes with the skeleton app, that just works and works well in most cases. What I'd also like is if these tools are kept up to date and made better over time as Aurelia itself is also updated.

Basically I want "everything" outside `src` and `styles` to be maintained by smarter people than I, and with easy hooks for adding for example Less/Sass/Stylus support or minifying CSS without touching Aurelia code that which should keep itself updated and fantastic :)

>**AshleyGrant March 13 2015**
>See, the things that can be updated easily are dependencies
>Dependencies are handled by npm or jspm
>The build files are actually part of the project you are writing
>**Svish March 13 2015**
>would it be possible to maybe pull it out into an option package so newbs like me could say "I want >the awesome Aurelia Magic Build Tool", and just do npm/jspm update to update it?
>**AshleyGrant March 13 2015**
>It's something we can research
>And there's stuff we've already done along those lines

Maybe my "dream" is touching on Project X mentioned on durandal.io? :P

**Comment by AshleyGrant** [comment]
I still think this is outside the scope of Aurelia. Everything that is mentioned can be done by modifying the gulpfiles, which is something that is bound to happen on any sufficiently large project.

Maybe we could create a UI that would assist users with editing gulp files? I'll have to do some research to see if something like that already exists.

That being said, we do have the two aurelia specific gulp tasks in aurelia-tools, so maybe there's some other tools we can add to enhance developer happiness.

**Comment by EisenbergEffect** [comment]
It's much better now that we've broken out the tasks. Here's what I would do:

* add new tasks to the build folder for your own stuff
* create a new custom-build task that aggregates our original build task along with your other stuff

In this way you can make additions without changing any of our build tasks and you can easily keep them in sync with our updates.
