### ISSUE TITLE
About the main files

### ISSUE THREAD

**Issue by kennynaoh** [aurelia/framework#671]
Hello @EisenbergEffect , I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project. We want to host this library, but there is a question want to ask. Could you help me mention the files on git repo are necessary to add on cdnjs? Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/9166

**Comment by EisenbergEffect** [comment]
Are you apposed to us hosting on more than one CDN?

**Comment by kennynaoh** [comment]
What you mean is that you keep this library on another CDN?

**Comment by paolocarrasco** [comment]
According to this [issue](https://github.com/aurelia/bundler/issues/133), there was a plan to do so, but no updates so far.
There is a project for that: https://github.com/aurelia/aurelia
Before that, Jeremy Danyow created this gist with CDN-able files (they are similar to those on the aurelia/aurelia project) that can be seen here: https://gist.run/?id=7542e061bc940cde506b&sha=663ada1535eb7ff8eb094bb6c4b920a2b75808c4

**Comment by gheoan** [comment]
I think the files that should be on the CDN are:
- https://github.com/aurelia/aurelia/blob/master/scripts/aurelia-core.js
- https://github.com/aurelia/aurelia/blob/master/scripts/aurelia-core.min.js
- https://github.com/aurelia/aurelia/blob/master/scripts/aurelia-routing.js
- https://github.com/aurelia/aurelia/blob/master/scripts/aurelia-routing.min.js

**Comment by paolocarrasco** [comment]
It sounds good! I agree those are the files. @kennynaoh, what else do you need?

**Comment by Alexander-Taran** [comment]
can be closed?

**Comment by EisenbergEffect** [comment]
For vNext, I'm keeping this scenario in mind much more. I think we'll have a better way of handling this in the future.
