### ISSUE TITLE
Issues with npm update, versioning

### ISSUE THREAD

**Issue by jdanyow** [aurelia/framework#676]
It seems like we've been having more issues with npm update lately, now that several of the low-level dependencies have had minor version bumps. Here's an example I recently saw:

*package.json*
```json
{
  "dependencies": {
    "aurelia-bootstrapper": "^1.0.1",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-fetch-client": "^1.0.1",
    "aurelia-framework": "^1.0.7",
    "aurelia-pal": "^1.0.0",
    "aurelia-templating-binding": "^1.0.0",
  }
```

*execute `npm update`*
```shell
C:\repos\cfc [master ≡]> npm update
+-- aurelia-event-aggregator@1.0.1
+-- aurelia-fetch-client@1.1.0
+-- aurelia-framework@1.0.8
+-- aurelia-pal@1.2.0
+-- aurelia-templating-binding@1.1.0
+-- moment@2.17.1
+-- numeral@1.5.6
+-- typescript@2.1.4
`-- whatwg-fetch@1.1.1

C:\repos\cfc [master ≡]>
```

aurelia-binding remains at 1.0.9, causing runtime errors. 

**Questions**

* Do we need to update the deps in top-level packages like aurelia-framework and aurelia-bootstrapper?
* If yes, should those packages also receive minor version bumps?

**Comment by EisenbergEffect** [comment]
What was the cause of the errors coming from aurelia-binding? Maybe it's just one other library that needed to have the version dependency updated but didn't. If there's a new feature in one lib that another one is dependent on then we need to update the dependent so that it has the minimal version of the new library to match. It's quite possible I wasn't aware of something like this. I usually don't update dependent version numbers unless I know this is the case.

**Comment by jdanyow** [comment]
The error had to do with the new `capture` binding command. There were changes in `templating-binding` and `binding`. Maybe all we need to do is update templating-binding's binding dependency?

**Comment by EisenbergEffect** [comment]
I believe that's all that is needed. Do you want to do that? I can make a new release immediately. Just let me know.

**Comment by jdanyow** [comment]
Strange- templating-binding's dependency on binding has already been updated to aurelia-binding@1.1.0:

https://github.com/aurelia/templating-binding/blob/master/package.json#L53

https://github.com/aurelia/binding/releases

**Comment by jdanyow** [comment]
💤 😴 

>As of npm@2.6.1, the npm update will only inspect top-level packages. Prior versions of npm would also recursively inspect all dependencies. To get the old behavior, use npm --depth Infinity update, but be warned that simultaneous asynchronous update of all packages, including npm itself and packages that npm depends on, often causes problems up to and including the uninstallation of npm itself.

https://docs.npmjs.com/cli/update

**Comment by EisenbergEffect** [comment]
Doh. So, the problem is happening because we don't have top level dependencies for everything?

**Comment by lmj0011** [comment]
per @jdanyow in gitter:
https://gitter.im/aurelia/Discuss/archives/2016/12/15

running:
`npm install --save aurelia-logging@latest aurelia-logging-console@latest aurelia-metadata@latest aurelia-pal@latest aurelia-pal-browser@latest aurelia-path@latest aurelia-polyfills@latest aurelia-router@latest aurelia-route-recognizer@latest aurelia-task-queue@latest aurelia-templating@latest aurelia-templating-binding@latest aurelia-templating-resources@latest aurelia-templating-router@latest aurelia-binding@latest aurelia-bootstrapper@latest aurelia-bundler@latest aurelia-dependency-injection@latest aurelia-event-aggregator@latest aurelia-fetch-client@latest aurelia-framework@latest aurelia-history@latest aurelia-history-browser@latest aurelia-loader@latest aurelia-loader-default@latest`

should update the framework
