### ISSUE TITLE
Anchor points are considered part of route parameters instead of being ignored.

### ISSUE THREAD

**Issue by tbnovaes** [aurelia/framework#677]
**I'm submitting a bug report**

* **Library Version:**
"aurelia-router@^1.0.1"

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.2.2

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
aurelia-cli 0.23.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
using anchor point (#) after a route parameter (:id) anchor point is interpreted as part of the parameter.

E.g.: contacts/:id#phones

**Expected/desired behavior:**
https://gist.run/?id=641e40f34acbb1ad329f13123f1e0c3c

* **What is the expected behavior?**
The anchor point should not be considered as part of the parameter

* **What is the motivation / use case for changing the behavior?**
Using params and anchor points can cause some unexpected bugs when the parameter passed is used in API or as parameters to other functions.

**Comment by EisenbergEffect** [comment]
Closing as duplicate: https://github.com/aurelia/router/issues/225
Contributions are welcome to add this.
