### ISSUE TITLE
globalResources does not seem to work

### ISSUE THREAD

**Issue by halllo** [aurelia/framework#678]
**I'm submitting a bug report**

* **Library Version:**
1.0.8

**Please tell us about your environment:**
* **Operating System:**
Windows  10

* **Node Version:**
v6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
Chrome 55 | Edge 38

* **Language:**
TypeScript 2.1.4

**Current behavior:**
I have a custom element (loading-indicator from the contact manager tutorial).
If I require it in the views I want to use it in, it works.
If I dont require it in the views I want to use it in, but register it with invoking globalResources in main, it does not seem to get found.

**Expected/desired behavior:**
I expected registering a custom element with globalResources makes it available in all my views without having to require it there.
I commited my project to https://github.com/halllo/AureliaTutorial/tree/master/tutorial_contact-manager where the effect is reproducible.

I am not sure if I did everything correctly, because it worked when I did the contact manager tutorial with the CLI. In this project I particularly did not want to use the CLI to get a feel for what is needed for what.

**Comment by jdanyow** [comment]
Change [this line](https://github.com/halllo/AureliaTutorial/blob/master/tutorial_contact-manager/index.html#L6) from `aurelia-app` to `aurelia-app="main"` to ensure your main.js is used.
