### ISSUE TITLE
Multiselect values are not updated

### ISSUE THREAD

**Issue by MayGo** [aurelia/framework#679]
**I'm submitting a bug report**

**Current behavior:**
Events are not updating multi select bindings(1.0.0-beta.1.0.8):
http://plnkr.co/edit/7yzNHKumHeCxwzdJdHKH?p=preview
There is error, in background:
Uncaught RangeError: Maximum call stack size exceeded.
This is prevented by using:
if (e.originalEvent) {
    return;
}

**Expected/desired behavior:**
In older version(at least 0.18.0) multi select worked properly:
http://plnkr.co/edit/mEpr8E?p=preview

**Comment by StrahilKazlachev** [comment]
If you do `<pre repeat.for="thing of selectedThing"><code>${thing | stringify}</code></pre>` it will work.
When you select/unselect items only the content of the array is changed, not the array value.
When doing `${selectedThing2 | stringify}`, or similar, it is monitored whether the value assigned to `selectedThing2` has changed(not the contents of the value) so it does not pick up the changes. There were some changes around the arrays when `Object.observe` was dropped.

**Comment by jdanyow** [comment]
http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects
