### ISSUE TITLE
Array.from() is undefined during jasmine tests

### ISSUE THREAD

**Issue by michael1976** [aurelia/framework#68]
If I use Array.from() in my view-model this will be undefined when running unit tests.

**how to recreate:**
using navigation-app example: add a method in App.js that executes Array.from()
```
  myMethod() {
    return Array.from([1,2]);
  }
```
in app.spec.js add a test
```
  it('defines a result', () => {
    expect(sut.myMethod().toBeDefined());
  })
```
then run
```
karma start
```

**Comment by zewa666** [comment]
Well it seems you have some typos in your unit test. Given that `sut` is a instance of a class it should look like this:

```
var sut = new YOURDEMOCLASS();
it('defines a result', () => {
    expect(sut.myMethod).toBeDefined();
})
```

which works as expected

**Comment by michael1976** [comment]
Alright, sorry about the typo but the issue is that Array.from is undefined. Try this instead:
```
it('defines a result', () => {
    var result = sut.myMethod()
    expect(result).toBeDefined());
  })
```

**Comment by zewa666** [comment]
tried so as well. Works for me. `console.log(result)` returns `LOG: [1, 2]`.
Just curious could you try to get a fresh new copy of the Skeleton with the latest updates and check it in there as well?

**Comment by michael1976** [comment]
Ok, will try this again from home later. Having issues with jspm behind corporate proxy. It might just be that everything is not installed
