### ISSUE TITLE
templateEngine.enhance not working on safari

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/framework#680]
I am using templateEngine.enhance to initialize aurelia on dynamically created UI.
All the bindings works on chrome and firefox but not on safari, it also does not work on mobile browsers. 

I have tried using aurelia-polifills but that did not help.

Project reference
https://github.com/caperavensoftware/pragma-screengen

Source for initializing aurelia is in 
https://github.com/caperavensoftware/pragma-screengen/blob/master/src/components/widget-base.js

see function initializeAurelia

**Comment by jdanyow** [comment]
@caperavensoftware any errors in the console?

**Comment by caperavensoftware** [comment]
no sorry no a single error.

**Comment by caperavensoftware** [comment]
I uploaded a screenshot to show off the difference.

https://github.com/caperavensoftware/pragma-screengen/blob/master/screenshots/screenshot.png

**Comment by caperavensoftware** [comment]
This is a bug as far as I can see not a question.
It works in chrome and does not in safari.
See the repository from the post.
I am hoping that this issue will be resolved soon ?

**Comment by caperavensoftware** [comment]
If this is not a bug please come back to me as to how I can make this work on both chrome and safari please.

**Comment by caperavensoftware** [comment]
I am disappointed that no one actually took this issues seriously enough to provide some feedback, but you can close this issue. I found a work around.
