### ISSUE TITLE
aurelia-binding uses babel loose mode

### ISSUE THREAD

**Issue by rviscomi** [aurelia/framework#684]
Why is the default babel preset to use loose mode?

I encountered this issue with ES6 code and traced it back to that mode, which appears to be set by aurelia-binding. See http://stackoverflow.com/questions/41358744/how-should-array-spread-notation-work-with-nodelists-in-babel/ for the original issue.

To summarize, `[...document.querySelectorAll(selector)]` transpiles with a bug: `[].concat(document.querySelectorAll(selector))` which is not the same thing.

Is there a way to overwrite Aurelia's default babel presets to not use loose mode? Or would it be possible to revisit why loose mode is used?

**Comment by EisenbergEffect** [comment]
Is this a bug inside of Aurelia or in your own code? If it's your own code, then you can just change the build configuration for your project. It's in the babelrc file or the build options file depending on which setup you are using.

**Comment by rviscomi** [comment]
I'd categorize this as a bug in Babel, which is enabled by Aurelia: http://blog.aurelia.io/2016/03/23/aurelia-babel-6-and-jspm-update/. My project doesn't have any explicit build configurations to use Babel presets.

**Comment by EisenbergEffect** [comment]
You just need to change the configuration inside the babelrc file.

**Comment by rviscomi** [comment]
Sorry but that still leaves my original question unanswered: why does Aurelia use loose mode? It seems to enable pitfalls for your users.

**Comment by EisenbergEffect** [comment]
Loose Mode performs way better and generates much smaller code. Believe it or not, you are the first person I've heard that has hit a problem related to it.
