### ISSUE TITLE
please consider incorporating npm shrinkwrap into the various build processes

### ISSUE THREAD

**Issue by ajoslin103** [aurelia/framework#685]
I have always used the skeleton/esnext/webpack for the basis of all my projects

I have several times found my projects suddenly won't build anymore, having been affected by changes & upgrades to the bits and pieces that support webpack

Of late I have started using npm shrinkwrap and that problem has gone away entirely 

I get a fresh skeleton running and then use npm shrinkwrap which freezes all those files -- then I am free to install and add modules that I need without suffering unexpected upgrades that break my project

I have helped several folks on the Gitter with this suggestion, not all of whom use the same skeleton/esnext/webpack as I do, so it appears to help other combinations as well

It occurred to me that if I suggested this here, that perhaps it may become part of the distributed toolset and everyone would then automatically benefit from it

Please accept my warmest wishes for a happier new year and my profound thanks for all your work on Aurelia, 

Al;

**Comment by jods4** [comment]
Aside: recent developments like `aurelia-loader-webpack` have used `yarn` and include `yarn.lock`, which is basically the same thing as npm shrinkwrap except it's always on.

**Comment by ajoslin103** [comment]
yes, I just tried yarn again for the 1st time in a few months - it was a lot smoother!  I'm starting up w/Electron apps and have read a few things here and there that say yarn is iffy there, but I don't imagine that will remain so for long (those might have even been old notes.)

so I'm fine with yarn or npm+shrinkwrap -- as long as it's one or the other, not just lonely npm :)

**Comment by jods4** [comment]
BTW I'm not sure the lock files deployed inside dependencies count, do they? I think it's only the one created at the root where you `npm install` (or `yarn install`).

So including `yarn.lock` (or a shrinkwrap) is great for people who work on Aurelia, but I am really not sure it will change anything for people who consume the library?

**Comment by chabou-san** [comment]
> So including yarn.lock (or a shrinkwrap) is great for people who work on Aurelia, but I am really not sure it will change anything for people who consume the library?

I can confirm this, based on [yarn documentation](https://yarnpkg.com/en/docs/yarn-lock#toc-current-package-only). The `yarn.lock` is only for the current package, so it won't change a thing whether Aurelia libraries include their own `yarn.lock` file or not.
I don't know about npm's `shrinkwrap` but I wouldn't be surprised that it'd behave the same way.

**Comment by Alexander-Taran** [comment]
shrinkwrap is gone
and package.lock.json they say is not stable.

vscode developers (electron app) moved to yarn with explicit post about it

Can be closed

**Comment by jods4** [comment]
I don't quite agree that this can be closed on the basis that shrinkwrap is gone and `package.lock.json` is not stable. Solutions are gone but the problem remains.

If NPM is still unable to lock (transitive) dependencies to specific versions, then I suggest that we should use `yarn` instead.

**Comment by Alexander-Taran** [comment]
https://github.com/npm/npm/issues/18613
frustrating read
