### ISSUE TITLE
web-api.js: Unexpected token

### ISSUE THREAD

**Issue by mark-hahn** [aurelia/framework#688]
I am trying to go through the contact manager tutorial and ran into a problem.  After doing the `au new --watch` command and specifying all the defaults,  I get this error ...

```
Starting 'buildJavaScript'...
[15:52:55] gulp-notify: [Error running Gulp] Error: /root/dev/p2/contacts/src/web-api.js: Unexpected token (47:15)
[15:52:55] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
Finished 'buildJavaScript'
```

It appears the file has a variable property in a class which I thought was illegal ...

```
export class WebAPI {
  isRequesting = false;
  
  getContactList(){
    this.isRequesting = true;      // THIS FAILS ON THE = TOKEN
    return new Promise(resolve => {
      setTimeout(() => {
...
```

So there is apparently some language support confusion going on.  I entered all defaults doing `au new` which specified ESNext.

Some help?

**Comment by AshleyGrant** [comment]
`isRequesting = false;` is part of the Public Class Fields proposal: https://tc39.github.io/proposal-class-public-fields/

As to why this is failing, I'm not sure. What version of the CLI are you running? (Run `au -v` in the project folder)

**Comment by mark-hahn** [comment]
Thx. That was fast.

I'm wiping the folder and starting over.  I'll let you know how it goes and
what the au version is.

**Comment by mark-hahn** [comment]
I went through the setup again carefully and this time I had no problem.  I don't know what I could have done wrong.  I'm now trying to run the contacts app the first time and I'm getting a blank page but I'll work on that.

Closing now, sorry for the trouble...

**Comment by ThomasWeiss** [comment]
I just ran into the exact same issue while going through that tutorial (created in Typescript mode); for anyone getting that error, renaming `web-api.js` to `web-api.ts` solved the issue.

**Comment by Genfood** [comment]
Also make sure to change the name in the include section in the `tsconfig.json` file form `web-api.js `to `web-api.ts`, after renaming it.

**Comment by rcmosher** [comment]
I'm hitting this issue as well. the rename fix addressed it. I didn't need to make any changes to tsconfig.json. But it seems like this is still an open issue for anyone trying to do the tutorial with typescript.
