### ISSUE TITLE
injection of inline styles should be prevented

### ISSUE THREAD

**Issue by peterver** [aurelia/framework#689]
**I'm submitting a bug report**

* **Library Version:**
1.0.7

**Please tell us about your environment:**
OSX 10.12.3

* **Node Version:**
7.2.0

* **NPM Version:**
3.10.9

* **Webpack**
Webpack 2.1.0-beta.27

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Bundling an aurelia application and executing it triggers unsafe-inline styles being injected.

**Expected/desired behavior:**
Allow the option to bundle aurelia-defined styles into an aurelia css file which can then be added as a style source

* **What is the motivation / use case for changing the behavior?**
Injecting inline styles opens the door for possible xss attacks. On systems ( such as mine ) where a csp prohibits the usage of inline-styles this becomes an issue.

**Comment by peterver** [comment]
For more information on how xss can occur with inline style injection : https://mikewest.org/2013/09/xss-no-the-other-s-cssconfeu-2013

**Comment by peterver** [comment]
This is the exact piece of code that is troublesome in my eyes : 

![screen shot 2017-01-13 at 19 40 50](https://cloud.githubusercontent.com/assets/821415/21941275/42ccfe44-d9c8-11e6-87ce-f453147115d3.png)

**Comment by EisenbergEffect** [comment]
I don't think this is a problem since the styles being injected are safe. It's also not always possible to put these into a CSS file since, if you are using shadow dom, they have to be injected into the shadow dom root and cannot be elsewhere.

**Comment by peterver** [comment]
Fact of the matter is that aurelia is most likely not the only package that's going to be used in most enterprise grade applications. I run a tight ship when it comes to security, but fair enough, i'll look into declaring a nonce for the aurelia bundle on my projects, cause enabling unsafe-inline projectwide is definitely something i don't want :].
