### ISSUE TITLE
Nested repeater

### ISSUE THREAD

**Issue by michalstepien** [aurelia/framework#69]
Hello,
first I'm newbie. I wanted add element to array (addRow()) but when add I get error:
Cannot read property 'length' of undefined  - repeat.js:50 

Without nested repeat.for, everything is ok.

```html
        <div class="row" repeat.for="rowq of rows_hoq">
          <div class="col-md-3">
            <input type="text" value.bind="rowq.name" class="form-control" id="fn" placeholder="name of functionality">
          </div>
          <div class="col-md-1" repeat.for="col of $parent.columns_hoq">
            <input type="text" value.bind="col.name" class="form-control" placeholder="name of ability">
          </div>
        </div>
        <button type="button" class="btn btn-default" click.delegate="addRow()">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      </button>
```

```javascript
export class New_hoq{
  constructor(){
    this.rows_hoq = [];
    this.columns_hoq = [];

    this.rows_hoq.push({  name: 'row1'});
    this.rows_hoq.push({  name: 'row2'});

    this.columns_hoq.push({name: 'column1'});
    this.columns_hoq.push({name: 'column2'});
  }

  addRow(){
    this.rows_hoq.push({ name: 'nazwa'});
  }
}
```

**Comment by zewa666** [comment]
Hello there,

I've tried your given example, just added the `<template>` tag for the View. It works without any problems. Tested on IE11, Chrome and Firefox. Could you try to get the latest version of the Skeleton App and verify whether the problem still exists?

**Comment by michalstepien** [comment]
I've tried on latest Skeleton App. Problem still exists. Tested on Chrome 41.0.2272.89 m . When I change this:

```javascript
  addRow(){
    this.rows_hoq.push({ name: 'nazwa'});
  }
```
to this:

```javascript
  addRow(){
    this.rows_hoq = this.rows_hoq.slice();
    this.rows_hoq.push({ name: 'nazwa'});
  }
```
It`s working.

**Comment by zewa666** [comment]
Thats really strange. Could you publish that example via github so we can check it out?

**Comment by michalstepien** [comment]
Sorry my mistake. I downloaded one more time all dependencies and everything is ok.
