### ISSUE TITLE
Is there an extension point where I can intercept all errors globally?

### ISSUE THREAD

**Issue by cluka** [aurelia/framework#690]
**I'm submitting a feature request**

* **Library Version:**
*

**Please tell us about your environment:**
* **Operating System:**
All

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.28

* **Browser:**
all 
* **Language:**
TypeScript 2.1

**Current behavior:**
I have to write try/catch block to intercept errors and display the dialog to the user.

**Expected/desired behavior:**

I would like a place where I can globally intercept any error that happens on the client. Then I could properly handle them.

* **What is the expected behavior?**
A place for infrastructural logic.

* **What is the motivation / use case for changing the behavior?**
To not repeat infrastructure code all over the app.

**Comment by AshleyGrant** [comment]
There's no need for Aurelia to have one as the browser already has this built in: `window.onerror`

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by cluka** [comment]
Oh, ok. This is fine. :-)
