### ISSUE TITLE
How to know if, and how, to create new Aruelia modules

### ISSUE THREAD

**Issue by jwx** [aurelia/framework#693]
I'm working on my second PR and unlike the first one this spans over several modules (aurelia/router and aurelia/browser-history) and it might even warrant a new one: aurelia/storage. My question is how I go about to know whether to make a new module out of storage and if so how to create that new module. 

I'm going to be working with Aurelia for a while and think I've got at least one more "framework core functionality" module that'd be useful so information on how to create and submit Aurelia modules would be great.

**Comment by EisenbergEffect** [comment]
For now, create the repo in your own library and then after we review your initial PR, we can make an official repo and move the code over.
