### ISSUE TITLE
Add supporting interfaces (e.g. RouterApp)

### ISSUE THREAD

**Issue by unional** [aurelia/framework#700]
* **Library Version:**
1.0.0

It may be beneficial to add supporting interfaces (e.g. RouterApp) interface into typings to help user implementing the function they need.

```ts
import {Router, RouterConfiguration, RouterApp} from 'aurelia-router'

export class App implements RouterApp {
  // IDE will show error and let user know they need to implement `configureRouter()`
}
```

The same idea can apply to other components. 🌷

**Comment by CasiOo** [comment]
The interfaces are there, but they aren't grouped into one single interface.
http://aurelia.io/hub.html#/doc/api/aurelia/router/1.1.0/overview
`ConfiguresRouter` `RoutableComponentActivate` ... `RoutableComponentCanDeactivate`

**Comment by EisenbergEffect** [comment]
They are there for both cases.
