### ISSUE TITLE
[Bug] Unable to run the default app created by aurelia-cli

### ISSUE THREAD

**Issue by WendySanarwanto** [aurelia/framework#702]
**I'm submitting a bug report**

* **Library Version:**
![image](https://cloud.githubusercontent.com/assets/18456618/22278356/c6cc27b8-e2fd-11e6-99ba-4abc73634d4f.png)

**Please tell us about your environment:**
* **Operating System:**
![image](https://cloud.githubusercontent.com/assets/18456618/22278368/e28bc210-e2fd-11e6-83a6-12a65882d126.png)

* **Node Version:**

![image](https://cloud.githubusercontent.com/assets/18456618/22278379/fcbaa0fc-e2fd-11e6-8541-f798524d5ccb.png)

* **NPM Version:**
![image](https://cloud.githubusercontent.com/assets/18456618/22278381/098e7772-e2fe-11e6-980f-3c9b76d0fe4f.png)

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.23

* **Language:**
ESNext

**Current behavior:**
When I run the app that I created ( using `au new`) through running the `au run --watch` CLI command, I got error on my CLI terminal as follow: 

![image](https://cloud.githubusercontent.com/assets/18456618/22278444/93e7a150-e2fe-11e6-9543-505356a7860b.png)

**Expected/desired behavior:**
* **What is the expected behavior?**
I should not get this error, the command is running and I should be able to browse the simple app created by aurelia-cli 

* **What is the motivation / use case for changing the behavior?**
I just want to get the default aurelia app running

**Comment by EisenbergEffect** [comment]
This looks like you have an environmental flag set on your machine that is getting picked up by the watch command (making it look for development.js). Try using this commend instead:

```
au run --watch --env dev
```
