### ISSUE TITLE
Example global-behaviors in Doc not working

### ISSUE THREAD

**Issue by KoenLuyten** [aurelia/framework#71]
In the docs this example is given:
`<div jquery.modal="show: true; keyboard.bind: allowKeyboard">...</div>`

when you change it to:
`<div jquery.modal="show: false; keyboard.bind: allowKeyboard">...</div>`
it still opens the modal on start.

It seems as if the options are ignored

**Comment by EisenbergEffect** [comment]
I'm going to guess that it's because the value "false" is actually true. So, this is probably a strong case for some property type info to be added. Do you have a chance to confirm if that is in fact what is happening?

**Comment by KoenLuyten** [comment]
Rob,

Like you said: "false" is true:

![image](https://cloud.githubusercontent.com/assets/8046654/6764908/edb2a41a-cfc7-11e4-9f46-f0436bb889b5.png)

**Comment by EisenbergEffect** [comment]
Global behaviors are being deprecated.
