### ISSUE TITLE
Basic Project Template on Aurelia-Hub is not updated

### ISSUE THREAD

**Issue by hajs** [aurelia/framework#711]
**I'm submitting a bug report**

The idea to use Aurelia without node, npm&friends for smal private or in-house projects is very appealing. Unfortunately the archive only contains an Aurelia release from seven months ago:

http://aurelia.io/downloads/basic-aurelia-project.zip
(via http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/1)

* **What is the expected behavior?**

The archive should be automatically updated whenever there is a new release. Otherwise some text should mention that this example project might be out of date.

Alternatively it would be ok if updated files would be available in a github project template. Even better would be instructions how I could generate the files myself.

* **What is the motivation / use case for changing the behavior?**

I am aware that you cannot create a complete scalable single-page-application with this approach. But it is great to try out new things, to quickly create demos and to debug problems (e.g. on JS-Fiddle/JS Bin).

**Comment by hajs** [comment]
Ah I guess that I found the corresponding github repository: https://github.com/aurelia/aurelia
But no updates, either :(

**Comment by Alexander-Taran** [comment]
https://github.com/jdanyow/rjs-bundle
will help you

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondAYearLater()
 let response = await getResponseFromOP( { timeout : 3weeks } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by EisenbergEffect** [comment]
Moving to a different approach for the getting started article and for vNext.
