### ISSUE TITLE
Reorganize packages under `@aurelia` npm scope.

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/framework#712]
Probably too large of a change this late in the game, but it would be very welcome to group Aurelia core packages under `@aurelia` in a similiar manner to Angular.

Docs: https://docs.npmjs.com/getting-started/scoped-packages
Examples: https://www.npmjs.com/~angular

**Comment by EisenbergEffect** [comment]
Unfortunately, when we started our work, that feature wasn't yet supported on NPM. I think it's too late for that for v1. We can look to doing something like this in the future.

**Comment by RichiCoder1** [comment]
Yup! Food for though for a future major release :)

**Comment by AshleyGrant** [comment]
We should go ahead and claim the namespace though, @eisenbergeffect

**Comment by Alexander-Taran** [comment]
namespace claimed.. 
and vNext is heading that way.

Can be closed, I guess
