### ISSUE TITLE
Checkbox binding not working as written in documentation

### ISSUE THREAD

**Issue by cluka** [aurelia/framework#715]
**I'm submitting a bug report**

* **Library Version:**
1.0.7

**Please tell us about your environment:**
* **Operating System:**
Windows Server 2016

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
all

* **Language:**
TypeScript 2.1

**Current behavior:**
Currently selecting any checkbox, selects them all.
I have created a Gist: https://gist.run/?id=8eae4ed8ddefbef803664b22bd5123f7

**Expected/desired behavior:**

As stated in the documentation: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/5. I expect that the selected items are in my array.
So if i have an array of roles and i bind to this array in a repeat.for loop, and set the checked attribute to bind to an array, i would expect it to have all the selected (checked) items in it, instead I get "true".
If this is not the case then it would be good to update/fix the documentation as there is not clearly explained how does the checkbox binding work.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by jdanyow** [comment]
check the console- there's an error that explains the issue. The user class's `roles` property is undefined. Change from `roles: [];` to `roles = [];` and the gist will start working.

**Comment by cluka** [comment]
Thanks, that solves it
