### ISSUE TITLE
'webkitIndexedDB' is deprecated and will be removed in M57, around March 2017. Please use 'indexedDB' instead.

### ISSUE THREAD

**Issue by te-je** [aurelia/framework#718]
I get this warning in aurelia-bootstrapper. I tried updating to the latest version of aurelia and webpack and it does not go away.

**Comment by EisenbergEffect** [comment]
We don't use indexDB anywhere, as far as I know.

**Comment by npelletm** [comment]
I experiment the same "issue".
Module loader : requirejs
Browser : Chrome 56.0.2924.87
module location : `define("aurelia-metadata", ["exports", "aurelia-pal"], function(n, t) {`
![image](https://cloud.githubusercontent.com/assets/1608892/23204612/9322926c-f8e7-11e6-9233-0baea7beb7bd.png)
