### ISSUE TITLE
General question - Can Aurelia support Ramda?

### ISSUE THREAD

**Issue by philmein23** [aurelia/framework#720]
#Just out of curiosity - anyone here using Ramda in conjunction with Aurelia, and if not, are the two compatible? I have been immersing myself in the arts of functional programming but with through my experience of using Aurelia (for work) I was not sure if the two support each other. Can someone confirm? I apologize for this ridiculous question, but as a junior developer, I would love to know. 

Thanks again!

**Comment by AshleyGrant** [comment]
Ramda could work within an MVVM framework like Aurelia, but it isn't a natural fit, I'd say. ViewModels, by design, are stateful.

You could use it in the levels below the UI though, no problem. Aurelia apps are just JavaScript apps.
