### ISSUE TITLE
HOW to put META TAG DESCRIPTION

### ISSUE THREAD

**Issue by ptmagalhaes** [aurelia/framework#722]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

How to put meta tag description per page ???

* **What is the motivation / use case for changing the behavior?**

**Comment by jdanyow** [comment]
please ask these types of questions on stackoverflow
