### ISSUE TITLE
Event Listeners not working on Mobile Devices

### ISSUE THREAD

**Issue by camdebuck** [aurelia/framework#723]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
Android - Chrome

* **Node Version:**
6.8.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.47

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
ESNext

**Current behavior:**
Doesn't filter out alpha characters.  Works fine on desktop (all browswers), but not on mobile devices

**Expected/desired behavior:**
I've provided a GIST.  Simply run it on a mobile device.  Try entering in an alpha character.  It should not allow this, but it does.

* **What is the expected behavior?**
It should only allow numeric and decimal characters.

* **What is the motivation / use case for changing the behavior?**
Propert functionality.  It would appear that the Event Listener is not working properly on mobile devices.

https://gist.run/?id=5d41be0ff408e71c92618c4a5ba74512

**Comment by camdebuck** [comment]
It also fails on iPhone using their default browser.

I entered the operating system incorrectly:
 Operating System:  macOS Sierra 10.12.3

Hope that helps.

**Comment by stoffeastrom** [comment]
I don't understand. What do you mean that the event listener is not working? Is it fired and your code that tries to filter out numeric/decimal characters doesn't work? Or is it not fired? Also, I'm not sure your code will work since there are quite a lot of browser inconsistency in this area.

**Comment by camdebuck** [comment]
Unfortunately, I do not know the exact details (and don't know how to debug it).  All I know is that it works fine when using a browser on the computer, but it does not work on a mobile device.

I can only assume that event listener is not being fired properly.

I'm more than willing to help where I can, I will just need some guidance to help you.  Thank you.

**Comment by stoffeastrom** [comment]
@camdebuck First thing would be to figure out if the event listener is working which I think it does. Next thing would be to use more cross browser friendly code to ensure it works as you want. If you google this you will get a lot of results. What I would have tested is

* Use `keypress` event instead so you don't have to check for modifiers etz
* Use `event.which` or `event.keyCode` or check how for example jQuery is normalising the `event.which`

**Comment by jdanyow** [comment]
@stoffeastrom thanks for jumping in here.

@camdebuck please move this over to stackoverflow if you have further issues.

Some good reading:
http://www.quirksmode.org/dom/events/keys.html
http://www.quirksmode.org/js/keys.html
