### ISSUE TITLE
Normalize imports with configuration

### ISSUE THREAD

**Issue by estaylorco** [aurelia/framework#725]
**I'm submitting a feature request**

* **Library Version:**
1.0.6

**Please tell us about your environment:**
* **Operating System:**
MacOS 10.12.3

* **Node Version:**
7.3.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.52

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Import statements take on many forms: strings, curly brackets, an asterisk, etc.  Also, no distinction is made between something that is imported for framework support and something that is imported as a dependency.

**Expected/desired behavior:**
Import statements should simply have the form of `import 'something'` or `import dep 'something'`, where the former imports something that will not be injected into the constructor, and the latter imports something that must be.

Consider this code from an actual custom element that I have written to wrap a DevExpress DevExtreme component:

```
import {inject} from 'aurelia-dependency-injection';
import {bindable, bindingMode, noView } from 'aurelia-framework';
import postal from 'postal';
import 'devextreme/ui/switch';
```

This, to me, introduces the same problem we have with the `new` operator and call-site dependency: if any of the vendors represented in these imports change their exports, we have to update our code all over the place.

It would be nice if we could push configuration of the imports to the bootstrapping workflow (much like we did with require under Durandal), we could normalize usage at the import sites.  Consider this revision:

```
import 'inject'
import 'bindable', 'bindingMode', 'noView'
import 'dxSwitch'

import dep 'Element'
import dep 'postal'

@inject(Element, postal)
@noView()
export class AudxSwitchCustomElement {
    constructor(el, postal) {
    }
}
```

Anything imported with the `dep` keyword _must_ be injected.  Now, elsewhere, using some format, we might have:

```
importsConfig {
    inject: { name: 'inject', type: 'member', source: 'aurelia-dependency-injection' },
    framework: [ 
        { name: 'bindable', type: 'member', source: 'aurelia-framework' },
        { name: 'bindingMode', type: 'member', source: 'aurelia-framework' },
        { name: 'noView', type: 'member', source: 'aurelia-framework' }
    ],
    element: { name: 'Element', type: 'global' },
    postal: { name: 'postal', type: 'defaultMember', source: 'postal' },
    switch: { name: 'dxSwitch', type: 'moduleName', source: 'devextreme/ui/switch' }
    ....
}
```

We could even distinguish between two different modules with the same name from two different authors, or two different versions from the same author:

```
importsConfig {
    postal1: { name: 'postal-v1', type: 'defaultMember', 'v1/postal' },
    postal2: { name: 'postal-v2', type: 'defaultMember', 'v2/postal' }
    ....
}
```

* **What is the motivation / use case for changing the behavior?**
The benefits are manifold:

- Puts developer in touch with the nuances of import formats.  In the `importsConfig` example, the `type` property requires calling out the import type, right out of the documentation;
- DRY: From where, exactly, a module is imported and the names of its features can be configured one time, in one location.  If the authors change any of those details, we can make the change in one place;
- Provides a way to normalize version differences or different modules with the same name from two different authors;
- The `dep` keyword does two things: a) It provides clarity of intention and, b) it can assist in static analysis by making sure that all `deps` are actually injected and that non-`deps` are not;
- Static analysis can be performed to make sure that we're not importing anything that hasn't been configured in the `importsConfig`;
- Could move us closer to automatic imports: If our IDE detects, say, `postal.subscribe(...)`, an import could more easily be inserted automatically by checking `importsConfig` only once for the presence of 'postal', and then simply adding `import 'postal'` at the top of the file;
- In the example that I gave above, the `source` could be a function, a url, or a string: For example, a function could be called over a source string to look up a module alias and return the full name (great in cases like, say, 'aurelia-framework').

Thank you for your consideration.

Eric

**Comment by AshleyGrant** [comment]
The `import` statement isn't part of Aurelia. It is part of the language.

```javascript
import 'inject'
import 'bindable', 'bindingMode', 'noView'
import 'dxSwitch'

import dep 'Element'
import dep 'postal'
``` 

is not valid JavaScript, and thus we would not be able to support this.

**Comment by AshleyGrant** [comment]
Also, a lot of the stuff you're looking for can already be done by utilizing TypeScript and Visual Studio Code.

**Comment by estaylorco** [comment]
The keyword `import` isn't really a part of the language yet, either.  But we could improve what's there with transpilation, no?  We're already improving the language itself.

**Comment by AshleyGrant** [comment]
`import` has been part of the language for nearly two years now. It's part of ES2015. 

That being said, Aurelia doesn't currently do anything on the transpilation front. This would have to be a plugin for Babel or something. Given our stance on "Aurelia is *just JavaScript*," I highly doubt we would consider extending the language in any way. 

This doesn't mean I don't like parts of your proposal, I just don't think we at Aurelia are looking to extend JavaScript, as we currently feel that not utilizing non-standard language features is a feature of the Framework. Do we support and encourage certain "experimental" features, specifically decorators? Yes. But decorators are a Stage 2 feature proposal in front of the TC-39.

**Comment by EisenbergEffect** [comment]
We are constrained by the language and don't have any desire to do something that is non-standard. Having said that, as @AshleyGrant mentions, some of this can be done by VS Code, some of it could be done as a transpiler plugin (specific to the transpiler you use) and some of it could be done as an extension to the module loader or bundling solution. To achieve what you have above, would likely be a very complicated combination of all of these things.

**Comment by estaylorco** [comment]
I wonder if I could write a gulp task that could simply look to a configuration file and replace the import statements with ES6-compliant statements.  In other words, simply handle this pre-transpilation.

Perhaps that would be more practical?

**Comment by EisenbergEffect** [comment]
That's definitely possible as part of a build step. It's not something we want to do with the Aurelia Team. We've got so much on our plates just keeping up with web standards and the general integration with popular tools.

**Comment by estaylorco** [comment]
Oh, I understand:  Once it falls within the realm of gulp, it makes sense to me that it would be outside the roadmap of the Team.  I mean, that's the beauty of a task-runner.  

I just hadn't thought of gulp until the prodding of your comment.

**Comment by jedd-ahyoung** [comment]
@estaylorco For what it's worth, you can technically do this already by setting up your dependency injection container at startup. All you have to do is call `aurelia.container.register` with the key and the value you want, and then you can remove the import statements from your module code if you do want to do that. Basically, this is already possible.

**Comment by estaylorco** [comment]
Jedd,


I didn't realize that.  Thanks for the advice!


Eric S. Taylor
CEO
TierSoft, Inc.
________________________________

**Comment by AshleyGrant** [comment]
Great point @jedd-ahyoung. I knew there was a reason we kept you around. :-)
