### ISSUE TITLE
attached and methods used in template are not called when navigating to the same view

### ISSUE THREAD

**Issue by vit3k** [aurelia/framework#726]
**I'm submitting a bug report**

* **Library Version:**
1.0.8

* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.51 

* **Browser:**
Chrome 56 | Firefox 51 

* **Language:**
ESNext

**Current behavior:**
Attached method and methods that are used in template are not called when navigating to the same view but with different data (for example different id). Activate is called, data in model is updated, bound fields are updated. It works when view is changing.

**Expected/desired behavior:**
Attached method and all methods used in template are called every time as it could potentially do some initialization work specific for current data.

* **What is the motivation / use case for changing the behavior?**
Template is the same but data is updated so in fact this is different "view". Initialization should be consistent. Currently I don't know when visible elements are updated (for example height is changed) and can be safely manipulated.

Please let me know if there's a workaround available now, especially for attached method as I use it to move some stuff around on page.

**Comment by stoffeastrom** [comment]
Does [this](http://stackoverflow.com/questions/39999969/how-to-set-default-activationstrategy-in-aurelia) help you? E.g you have to set `activationStrategy` either by implementing the `determineActivationStrategy` on the view model or setting it for the router config
```
{ 
  route: ['', 'foo'],       
  name: 'foo',       
  moduleId: 'foo', 
  activationStrategy: 'replace'
}
```

**Comment by vit3k** [comment]
Yes that helps. So it's not a bug it's a feature :) Thank you
