### ISSUE TITLE
svg class bind not work after refresh page

### ISSUE THREAD

**Issue by javadbat** [aurelia/framework#728]
i use last virsion of aurelia and this is rare problem:

in my html template i have a svg like this:
`
<svg data-map="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid meet" version="1.1" x="0" y="0" viewBox="0 0 204.2 184.5" enable-background="new 0 0 204.181 184.548" xml:space="preserve"> 
            <g  repeat.for="state of stateList" name="${state.name}" title="${state.name}" id="${state.id}" click.delegate="selectState(state)" innerhtml.bind="state.svg" class="${state.saleValue < saleIndex.lvl1 ? 'color-level-1':''} ${(state.saleValue > saleIndex.lvl3) ? 'color-level-4':''} ${(state.saleValue > saleIndex.lvl1 && state.saleValue < saleIndex.lvl2) < saleIndex.lvl2?'color-level-2':''}  ${(SaleIndex.lvl2 < state.saleValue && state.saleValue < saleIndex.lvl3) ? 'color-level-3':''} ${state.active ? 'active':''}">
            </g>
        </svg>
`
it suppose to change color of the map of state list base on sale value in 4 diffrent color 
after i write code it work fine and good but when i refresh page it stop working and even clear cash not work 
but when i change code and refresh again it work!
something really wrong here with babel i guess

**Comment by AshleyGrant** [comment]
Please use the issue template. Also, please format your code better using Github Markdown: https://guides.github.com/features/mastering-markdown/

**Comment by jdanyow** [comment]
stackoverflow for questions please
