### ISSUE TITLE
Errors during app configuration provide no stack trace

### ISSUE THREAD

**Issue by axefrog** [aurelia/framework#73]
In Chrome (41) I inadvertantly misconfigured my application, causing an error to be thrown. In the dev tools however, I only received the raw underlying JavaScript runtime error message and no accompanying stack trace, which meant it took a little while to figure out where my error was.

Any runtime error in the configuration file should presumably reproduce this error, though in my case the code was the following accidentally-saved change:

```js
export function configure(aurelia) {
	aurelia.use
		.defaultBindingLanguage()
		.defaultResources()
		.router()
		.eventAggregator()
//	aurelia
		.start()
		.then(a => a.setRoot('main', document.body));
}
```

**Comment by PWKad** [comment]
If you have a chance, when you get errors that are thrown from somewhere that you think could be more descriptive, could you comment on that code specifically identifying what causes the issue to raise and what the expected message is?  It helps the team to add better error handling without having to reproduce a bunch of scenarios and figure out which you ran in to

**Comment by Aaike** [comment]
i have the same issue : 
there is something very wrong with the error logging, something is catching the exceptions and just making things fail silently in my attached behaviours , this could be happening in other places too , but for now i've detected this is an attached behaviour.

I don't even get an error in the console , or line number when i do something like
`callUnknownMethod();`

it's completely silent.. impossible to debug

**Comment by Aaike** [comment]
another one of these is happening in the main.js 
if there is a bug there , you will see it in the console and there will be a line number
but no stack trace ...

if i remove this catch block in the bootstrapper then i do get the stack trace :
https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L186

note: this does not help with the completely silent errors in attached behaviours.

**Comment by Aaike** [comment]
ok i've been able to solve my problem by removing aurelia and reinstalling from scratch with jspm ...
it was just very hard to figure out that i had to do that :) everything was working except for the exceptions ... weirdest thing... anyway i'm glad it is resolved.

**Comment by axefrog** [comment]
@PWKad I generally try to provide enough relevant information in an issue so that I'm not wasting anyone's time. The last sentence explains my error in particular, and the code snippet shows my erroneous configure function. Seeing as this only gets called once in the application, and that location is dictated by the value of `aurelia-app="..."`, I'm not sure what additional information I could provide that would be helpful?

**Comment by EisenbergEffect** [comment]
Fixed this in the bootstrapper. Going out next week in the next set of releases.
