### ISSUE TITLE
Bundle aurelia apps with a transparent webpack- or rollup-configuration

### ISSUE THREAD

**Issue by martinoppitz** [aurelia/framework#733]
Hello @EisenbergEffect,

is there any way to use Aurelia with a transparent build process? Like webpack or rollup.

I feel there is a lot of magic, if you use the cli.

There is Aurelia, but nowhere I import it.

Thank you for your answer.

Best regards

PS: greetings to @jedd-ahyoung

**Comment by EisenbergEffect** [comment]
Yes, we have a Webpack setup as well. In fact, we're about ready to release a fully updated Webpack solution.

**Comment by martinoppitz** [comment]
://github.com/aurelia/framework/issues/642

**Comment by martinoppitz** [comment]
See http://github.com/aurelia/framework/issues/642
