### ISSUE TITLE
Use `files` in package.json

### ISSUE THREAD

**Issue by jods4** [aurelia/framework#735]
We should set `files: ['dist']` in `package.json` for all Aurelia libs.

This config key defines which files (or folders)  are included in a published NPM package. 
To consume an Aurelia library, `dist` folder is all we need.
`LICENSE`, `README` and `package.json` are always included.

Note that `package.json` contains the links to source code, issues tracker, etc. on github.

What difference does it make?
Let's take `aurelia-framework` as an example:

`aurelia-framework`| # files | Total size
---|---:|---:
Current NPM package | 79 | 1 222 Ko
`files: ['dist']` | 16 | 114 Ko

10 times smaller is a _huge_ difference.

The core set of Aurelia libraries (no extra like dialog, validation, etc.) takes 15.6 Mo on my disk for each project I have, in more than 2000 files and 477 folders!

This is of course not unique to Aurelia, but a plague to NPM. For me a relatively bare bones `node_modules` is 80 Mo and 10K files :(

By doing this trivial change we are being good NPM citizens and we help speed up packages installation and reduce disk usage.

**Comment by StrahilKazlachev** [comment]
In general you want to exclude src, build, etc.? If so I'm OK with that, but just a question. We are starting to use the npm scripts for the build so is it OK to have *broken* scripts in the npm package?

**Comment by jods4** [comment]
That is an interesting consideration!
For me the answer is yes.

From the official purpose of NPM `scripts`: if you had a `prepublish` script it would run before your package is published. Its purpose can be to compile your sources, so users don't have to. By virtue of compilers being `devDependencies`, `npm run prepublish` is broken in installed package, since they are not installed.

Given this is the official purpose and documentation -- and since I don't think people should compile stuff inside their `node_modules` anyway -- I would have no problem with `npm run aurelia-framework build` being broken.

**Comment by EisenbergEffect** [comment]
This sounds like a reasonable improvement. We'd need to make sure we aren't breaking our JSPM configuration with that as well.

Funny enough I had lunch today with John-David Dalton (lodash). He mentioned that he's working on gzip support for lodash that would integrate into Node.js and Webpack. His goal is to shrink package sizes on disk and enable the gzips to be directly supported by the module systems.

**Comment by jods4** [comment]
I don't use JSPM but I think everything it needs is inside `package.json`? Or is there another file we'd need to include?

**Comment by jdanyow** [comment]
Using the files attribute would slim things down a little. To fully shrink our install footprint I propose we create a publish task that does the following:

1. creates a "publish" folder
2. copies the "dist" into the folder
3. copies the package.json into the folder, *minus all the dev dependencies*
4. does the npm publish from this folder

Or something along these lines. There may be an existing tool that will do this sort of minimal publish.

My thinking here is our src files are a drop in the bucket in comparison to what gets pulled down with the dev deps.

**Comment by jods4** [comment]
dev deps are only installed when your restore your project, not for your transitive dependencies, are they?

**Comment by Alexander-Taran** [comment]
seems stale packages still include src etc

**Comment by Alexander-Taran** [comment]
@bigopon this is an interesting one (-:

**Comment by bigopon** [comment]
All repo dists are bundled into a single file by now, and `files` are used. Src is still delivered for sourcemap purposes. I think it'll be better than where it was in this thread.
