### ISSUE TITLE
directive binded string value cant be updated

### ISSUE THREAD

**Issue by javadbat** [aurelia/framework#736]
BUGS: Please use this template.

**I'm submitting a bug report**
* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10]

* **Node Version:**
6.2.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
 Chrome XX 
* **Language:**
 ESNext

**Current behavior:**
hi 
i create a calendar directive in my project and i use `value.bind="'@DateTime.Today'"`
so my value variable in directive get '3/11/2017 12:00:00 AM' 
and id bind it 2 way:
`@bindable({ name: 'dateValue', attribute: 'data', defaultBindingMode: bindingMode.twoWay })`
in unfocus when i try to change the "value" variable i set it like below:
`this.dateValue = outputValue;` 
output value is just simple date string but aurelia give me an error 
  `Uncaught Error: Binding expression "'3/11/2017 12:00:00 AM'" cannot be assigned to.
    at LiteralString.assign (aurelia-binding.js:1180)
    at Binding.updateSource (aurelia-binding.js:4833)
    at Binding.call (aurelia-binding.js:4855)
    at BehaviorPropertyObserver.callSubscribers (aurelia-binding.js:373)
    at BehaviorPropertyObserver.call (aurelia-templating.js:3562)
    at TaskQueue.flushMicroTaskQueue (aurelia-task-queue.js:126)
    at MutationObserver.eval (aurelia-task-queue.js:66)`
seems that aurelia try to bind a value to string and it make a problem is any way to update the inputed string in this way without set it to a variable
**Expected/desired behavior:**

seems that aurelia try to bind a value to string and it make a problem is any way to update the inputed string in this way without set it to a variable

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
I'm having a hard time understand the scenario fully. Can you create a simple reproduction of the problem and attach or link it here?

**Comment by jdanyow** [comment]
closing, abandoned
