### ISSUE TITLE
Doc Hub - Content Projection section is broken

### ISSUE THREAD

**Issue by piet-v** [aurelia/framework#741]
* **I'm submitting a bug report**

* **Browser:**
all

**Current behavior:**
Going to http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-content-projection results in non-responsive page when arriving there through tree-navigation. Or an infinite loading indicator manifests when opening this section through the supplied link.

**Expected/desired behavior:**

The documentation page should be readable.

**Comment by EisenbergEffect** [comment]
We have this tracked already.

**Comment by Gheoan** [comment]
Duplicate of https://github.com/aurelia/documentation/issues/330, https://github.com/aurelia/templating/issues/536.

**Comment by metamaker** [comment]
Still broken :( .
