### ISSUE TITLE
computed property function keep calling repeatedly

### ISSUE THREAD

**Issue by AlexanderChen1989** [aurelia/framework#745]
**I'm submitting a bug report**

* **Library Version:**

```
 "dependencies": {
    "aurelia-bootstrapper": "^2.1.0",
    "aurelia-animator-css": "^1.0.1",
    "bluebird": "^3.4.1",
    "requirejs": "^2.3.2",
    "text": "github:requirejs/text#latest"
  },
  "devDependencies": {
    "aurelia-cli": "^0.26.1",
    "aurelia-testing": "^1.0.0-beta.2.0.1",
    "aurelia-tools": "^1.0.0",
    "browser-sync": "^2.13.0",
    "connect-history-api-fallback": "^1.2.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-changed-in-place": "^2.0.3",
    "gulp-plumber": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.0.0-alpha",
    "gulp-notify": "^2.2.0",
    "minimatch": "^3.0.2",
    "through2": "^2.0.1",
    "uglify-js": "^2.6.3",
    "vinyl-fs": "^2.4.3",
    "babel-eslint": "^6.0.4",
    "babel-plugin-syntax-flow": "^6.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-amd": "^6.8.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.10.3",
    "babel-plugin-transform-flow-strip-types": "^6.8.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-1": "^6.5.0",
    "babel-polyfill": "^6.9.1",
    "babel-register": "^6.9.0",
    "gulp-babel": "^6.1.2",
    "gulp-eslint": "^2.0.0",
    "gulp-htmlmin": "^3.0.0",
    "html-minifier": "^3.2.3",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-babel-preprocessor": "^6.0.1"
  }
```

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3 (16D32)

* **Node Version:**
v7.7.3

* **NPM Version:**
4.1.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
Chrome 56.0.2924.87 (64-bit)
* **Language:**
ESNext

**Current behavior:**

```
au new hello
cd hello
```
![image](https://cloud.githubusercontent.com/assets/2957936/24188799/ae0189c0-0f1d-11e7-89b0-a3b1985e6c79.png)

![image](https://cloud.githubusercontent.com/assets/2957936/24188809/b5b9f6c0-0f1d-11e7-99bc-13061b6e580b.png)

computed property function keep call again and again 
![image](https://cloud.githubusercontent.com/assets/2957936/24188751/8fb41546-0f1d-11e7-99cf-0a0066046629.png)

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by bigopon** [comment]
I reported exactly the same stuff before so ill try to help the Aurelia team.
The result you see is because Aurelia cant put the observer on your getter, so it has to fallbavk to dirty checking (120ms interval).

Theres a way for you to deal with this case thouhg, its the `computedFrom` decorator. Basically you use it to tell Aurelia what the dependencies of your getter are, then Aurelia will observe those deps instead of dirty check.

**Comment by AlexanderChen1989** [comment]
so it's right behavior?

**Comment by bigopon** [comment]
Yup. And expect the samething when you point to getter properties, e.g html elements `clientWidth` ..., Array length

**Comment by Gheoan** [comment]
Similar question: https://github.com/aurelia/framework/issues/238.

**Comment by atsu85** [comment]
@AlexanderChen1989, I'm using [aurelia-computed](https://github.com/jdanyow/aurelia-computed/) plugin, so I don't have to add `@computedFrom(...)` everywhere. My approach is to add `@computedFrom(...)` decorators only to the places, where it is absolutely needed. To figure them out (and notice them) during development, I've overwritten the method that by default just writes warning to the console:
```TypeScript
        .plugin('aurelia-computed', { // install the plugin
            enableLogging: true, // enable debug logging to see aurelia-computed's observability messages.
            writeLog: (propertyName, reason) => {
                const originalMsg = `Unable to observe '${propertyName}'.  ${reason}`;
                const msg = "Potential performance issue: " + originalMsg;
                console.warn(msg);
                ...
                if(notProductionEnvironment) {
                    alert(msg);
                }
            }
        })
```
That is over-simplification of my solution, but it is more than enough to get started :)

**Comment by bigopon** [comment]
Just to clarify, I think Aurelia deals with array length by a special observer, so binding to it can be used without dirty checking. I'm not 100% sure though.

**Comment by EisenbergEffect** [comment]
You are correct.
