### ISSUE TITLE
Wrapping if statement is evaluated _after_ data binding?

### ISSUE THREAD

**Issue by powerbuoy** [aurelia/framework#747]
I'm not sure this is a bug in Aurelia, but I have no idea what I can change in my code to make it work.

I have an array of objects representing form fields, each with a different type. Each field has a `value` property and sometimes an `options` property (if the field type is `select`). The `value` will be `null` for most fields, but for `select` fields the value is `[]`.

In my view I render different HTML depending on the field type, but when I go from one field without options to one with options Aurelia throws an error at me saying that "Only null or Array instances can be bound to a multi-select".

I've managed to reduce the code to a minimal test case here: https://gist.run/?id=5424b1e2dca61aa64b65a44aad9dec15

Note that at first no errors are thrown, then click next, again no error, next again is error free but then when going from a text field (with no options) to a select field (with options) I get the error.

To me it seems that my data binding `<select value.bind="field.value" multiple="multiple">` runs _before_ the wrapping if statement: `<div if.bind="field.type == 'select'">`?

If I add `activationStrategy: 'replace'` to my route (in app.js) it works, but I don't want to have to do that.

I actually get a similar error by just looping the value array in a `<ul>` in my real world app, but was for some reason unable to reproduce it in GistRun.

If this isn't an Aurelia bug then what am I doing wrong?

**Comment by AshleyGrant** [comment]
@jdanyow any thoughts?

**Comment by powerbuoy** [comment]
@AshleyGrant @jdanyow any updates on this? I really don't know what I'm doing wrong here...

**Comment by jdanyow** [comment]
@powerbuoy where did you find the gist? Reason I ask it's using a really old version of Aurelia and I'd like to get it updated. Here's the current https://gist.run/?id=7542e061bc940cde506b

**Comment by powerbuoy** [comment]
Oh, that's my bad. I found it on SO I believe but didn't pay attention to the version. This happens with the latest version of Aurelia in my app however.

And I've now updated my Gist to use the same index.html as yours, and I still get the same error: https://gist.run/?id=bf10295418a18bbe0d601b0098ad5f3e

**Comment by jdanyow** [comment]
putting the select part of the template after the input part of the template will resolve the issue:

https://gist.run/?id=658e04d3ae2fa13c487a5651f92a2fc8

When Form.field changes, the bindings subscribing to that property's changes evaluate sequentially. Which means there's a period of time when the select AND the input are both on the page. The html input element coaleses null values to empty string which in turn causes field.value to be empty string, which makes the multi-select throw.

We really need a "data template selector" for cases like this:

```html
<template-selector value.bind="field.type">
  <template value="select">
     <select ...... </select>
  </template>
  <template value="input">
     <select ...... </select>
  </template>
  ...
</template-selector>
```

**Comment by jdanyow** [comment]
keep an eye on https://github.com/aurelia/templating-resources/pull/280 - it looks like it will help in situations where you need a more atomic swap out of two templates.

**Comment by powerbuoy** [comment]
Oh ok I see, that's a bit strange imo, but I guess it sort of falls under the same category of issues as putting `value.bind` before `min` and `max` in a range input.

In my real app I actually use `<compose>` instead of if statements but I still get the same issue. Will try to move things around to solve it. Thanks for clearing this up!
