### ISSUE TITLE
Add a "Submit an Issue" Button to Docs pages

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/framework#748]
**I'm submitting a feature request**

**Current behavior:**
There is no built-in way for a user to submit an issue or comment on a specific article in our documentation.

**Expected/desired behavior:**
It'd be great to add some type of "Submit an Issue/Comment" button to the docs page so users can give feedback on the docs. Maybe we could have a separate repo that is just for these comments. 

**What is the motivation / use case for changing the behavior?**

Community members have mentioned a desire for some way to provide docs feedback.

**Comment by EisenbergEffect** [comment]
Once the new dev hub is released, it will be easier to customize and do new things.

**Comment by lazaridis-com** [comment]
@AshleyGrant , if I understand you right, you want to provide kind of `[Submit an Issue]` (in addition to the existent `[Edit]`) on each doc page. This sounds like a nice and logical extension, but there is one issue here:

* the github PR workflow is already too much for typo corrections
* the github issue-tracking (and repo-hosting in general) does not work well with large-subsystem-count projects (like Aurelia is). The effort to get/keep project-wide overview is excessive.

So, possibly your (rational) feature-request should go hand-in-hand with an overall evaluation of the project-resources.

As for a docs repo, what about this one?

https://github.com/aurelia/documentation

**Comment by Alexander-Taran** [comment]
And also "edit this page" link

**Comment by Alexander-Taran** [comment]
@bigopon should definitely be done to v2 docs (-:
How can I help?

**Comment by bigopon** [comment]
We'll need to check Gitbook documentation for this. If it doesn't support it we may need to do something (add some button at the end of the markdown ourselves, via a plugin) or use another product.
