### ISSUE TITLE
Small discrepancy in the getting started docs.

### ISSUE THREAD

**Issue by smolinari** [aurelia/framework#75]
Hi,

I am having fun playing with Aurelia. As a beginner with the framework, I figured I'd go through the [Get Started page](http://aurelia.io/get-started.html). However, when I added the flickr page by cutting and pasting `app.js(updated)`, the whole thing died (no formatting, no bootstrap, no jQuery and no error).

Simple fix though. The updated app.js is missing the second line to load bootstrap.

```js
import bootstrap from 'bootstrap';
```

That's it!

Now to see how to get my IDE to show ES6 without errors.....LOL!

Scott

**Comment by EisenbergEffect** [comment]
Thanks! I think this was submitted as a fix just the other day. It will go out in the next docs release.

**Comment by smolinari** [comment]
Hey Rob. A little off topic, but is there a way to cache bust the dist files and also replace smartly the calls to the files with the proper file names too? I've added gulp-rev to the build.js file, but it also breaks Aurelia, because the framework is looking for "app.js" and not "app-01123c47.js".

Scott
