### ISSUE TITLE
doc: Use Term "Defaults" instead of "Conventions"

### ISSUE THREAD

**Issue by lazaridis-com** [aurelia/framework#750]
`Conventions` are usually understood to be `as-is`.

In contrast, the (natural, since early IT) concept of `defaults` is understood as `can be reconfigured`.

I understand that Aurelia provides the flexibility to override the `defaults`. See this excerpt from the docs:

>In this case, we have a very simple convention. The root, by default, is app.js, relative to the main.js file. If you don't like that, as with all Aurelia conventions, you can override it with explicit configuration. For now, let's stick to the conventions.

Notice the use of the word "default" in the flowing text ("The root, by default, ...)

Switching to the term "default" would result in this doc:

> The root, by default, is app.js, relative to the main.js file. If you don't like that, as with all Aurelia defaults, you can override it with explicit configuration. For now, let's stick to the defaults.

This would be an overall change, which affect all communication around Aurelia. It must become clear, that Aurelia uses (reconfigurable, naturally) `Defaults` and not `Conventions`.

**Comment by YardGnomeNinja** [comment]
+1

**Comment by AshleyGrant** [comment]
I disagree. The term "convention" is well understood in the developer world, specifically in regards to how Aurelia uses it as "convention over configuration."

Examples:
* https://en.wikipedia.org/wiki/Convention_over_configuration
* http://rubyonrails.org/doctrine/#convention-over-configuration

**Comment by lazaridis-com** [comment]
( @cluka & @Serabe, having fun playing "Julius Caesar" ? )

The links you provide are of no relevance.

You may want to reread my initial message with precision, and reflect on this for a few hours or days.

**Comment by MeirionHughes** [comment]
You may find a few cases where the words "default" and "convention" are interchangeable; but generally they are not. 

For instance, if I have "foo-bar-ray.js" there is no "default" view-model file for it. There is however a  _default_ **convention** to replace the extension with `.html`. This contrasts with having to _configure_ the system to map "foo-bar-ray.js" -> "foo-bar-ray.html" explicitly.

**Comment by EisenbergEffect** [comment]
"Convention over Configuration" is the standard industry term that describes this scenario, particularly when it pertains to frameworks.

**Comment by lazaridis-com** [comment]
@EisenbergEffect, "standard industry term"? This sounds strong! Was it the IEEE? The W3C? Which standard-organization was it?

Aurelia uses `Defaults`, which is a **stronger** concept, a "natural" one, which has not much to do with this "Convention over Configuration" (which no standards-organization would ratify, simply because its totally fuzzy). Marketing does wonders, in thousands adopting concepts, without verifying the validity (or the existence of and identical, differently named concept).

But hey, who am I?

Your Product, Your Project, Your Decision.

And possibly exactly this, is Aurelias weakest point.
