### ISSUE TITLE
doc: "http-server -o -c -1" not working correct on "127.0.0.1:8080"

### ISSUE THREAD

**Issue by lazaridis-com** [aurelia/framework#751]
`"http-server -o -c -1"` besides beeing really a bit ugly, does not serve the todo correctly.

When I apply changes and stop/start the server, the changes do not appear.

next thing I know, they appear, then again not.

My workaround is to use firefox, which display things correct, and I was able to finish the tutorial.

then I realized that I went to http://127.0.0.1:8080/, as mentioned by the server:

```shell
P:\sand\aurelia>http-server -o -c -1
Starting up http-server, serving ./
Available on:
  http://192.168.56.1:8080
  http://192.168.1.2:8080
  http://127.0.0.1:8080
```

going to localhost:8080 or the other ip's => things work fine.

(Note that I am in the role of a newcomer, so don't tell me things about IP's, loopback-interfaces etc. - things did not work as described, on a standard win10 machine. )

**Comment by AshleyGrant** [comment]
When filing issues, please use the issue template. It is utilized to help us gather information that will help us triage the issue you have filed.

For example, you have not mentioned which document you are referring to, which meant I had to spend time figuring out which specific document needs to be reviewed.

@EisenbergEffect I'll fix this document issue after I finish the meeting I have with a client in a few minutes.

**Comment by lazaridis-com** [comment]
> When filing issues, please use the issue template.

Use imagination: possibly I saw the template, and refused to use it?

(an issue-template cannot replace a decent issue-tracker, which the github one simply don't is)

>  which meant I had to spend time figuring out

Sounds fair, and I really hope it took you long.

See, I spent (or better: lost) time whilst struggling with your instructions.

Then I spend time to file this issue (instead of simply going on).

And now I'll spend (again) time to explain something to you:

I tried to copy the URL of the tutorial I was on, yet something went wrong, and this URL showed some different location (this happened before). This was again a fault on your (Aurelia) side, but I was really too tired to look it up.

Bad boy I am, did not my homework.

**Comment by AshleyGrant** [comment]
Actually, after further testing, this command works fine on my Windows 10 machine.

![image](https://cloud.githubusercontent.com/assets/9885322/24257794/2b64fc86-0fc2-11e7-84bc-4478158badc2.png)

**Comment by lazaridis-com** [comment]
>  AshleyGrant commented a minute from now 

Github went nuts!

@AshleyGrant , now change the code (add something to the title) and restart. See if the change comes up.

**Comment by AshleyGrant** [comment]
Please refer to the Aurelia project's code of conduct before posting further. 

> Code of Conduct

>As contributors and maintainers of Blue Spire projects, we pledge to respect everyone who contributes by posting issues, updating documentation, submitting pull requests, providing feedback in comments, and any other activities.

>Communication through any Blue Spire channels (GitHub, Gitter, mailing lists, Google+, Twitter, etc.) must be constructive and never resort to personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

>We promise to extend courtesy and respect to everyone involved in this project regardless of gender, gender identity, sexual orientation, disability, age, race, ethnicity, religion, or level of experience. We expect anyone contributing to Blue Spire projects to do the same.

>If any member of the community violates this code of conduct, the maintainers of the Blue Spire projects may take action, removing issues, comments, and PRs or blocking accounts as deemed appropriate.

The Code of Conduct can be read here: https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md

**Comment by lazaridis-com** [comment]
(you are aware about the logical/ethical errors in your CoC? Anyway, can you please focus at the issue at hand?

If you change the code (add something to the title) and restart, does the change come up?
