### ISSUE TITLE
Blank screen when running in IE10, when using view-template from server

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/framework#753]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework 1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
aurelia-cli 0.27.0 (requirejs 2.3.3)

* **Browser:**
IE 10

* **Language:**
TypeScript 

**Current behavior:**

When accessing page which has child component defined with `@useView("/templates/my-view")`, where view-template is not bundled, but instead downloaded from server, navigation to the page fails. If this child component is part of the initial application page, complete window will remain blank, without showing any JavaScript errors.

Feature works in other browsers (Chrome, FF, Edge)

**Expected/desired behavior:**

Page should load normally in IE 10, like in any other browser, regardless if it uses external (non-bundled) view-template or not.

**Comment by EisenbergEffect** [comment]
Please ask question on how to accomplish this in the Gitter channel.

**Comment by nenadvicentic** [comment]
@EisenbergEffect can you just confirm that we did not misunderstand each other?

I have this working in production and it works on any other browser but IE10 (did not check IE9). Also, other pages, not having this remote view work normally on IE10,

I have to ask for browser specific solution/workaround on Gitter?

**Comment by EisenbergEffect** [comment]
I'm sorry. This was my misunderstanding. I missed that rather important detail...

**Comment by nenadvicentic** [comment]
@EisenbergEffect I think it's my bad. I checked application in debug mode with IE 10. I'm getting:

> TypeError: Object doesn't support this action at createMutationObserver

Accidentally, this happens only on view-template loaded form the server. Maybe this error should be thrown in production build too?

**Comment by Gheoan** [comment]
Please provide the full error.

I suspect Mutation Observer is not polyfilled. See http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/3.

**Comment by Alexander-Taran** [comment]
similar behavior mentioned in gitter
deap82 @deap82:
If anyone is curious; My conclusion for now is that my issue from earlier today is isolated to my use of `<template>` elements within asp.net core .cshtml files (where markup is later aurelia enhanced [http://aurelia.io/docs/fundamentals/app-configuration-and-startup#leveraging-progressive-enhancement]).
Using this polyfill (http://jsfiddle.net/brianblakely/h3EmY/) fixes my issues in most cases, I just had to change a `<template if.bind="foo">...` and move the if.bind to the element(s) instead. Any `<template>` elements within actual aurelia custom elements are not affected.
I'm still not sure why IE gives this xmlns related error message... (thanks for input from @bigopon and @Alexander-Taran!)

> I've found that my issue from before (below) is not related to compose+template, but rather when we use template as a holder for repeat.for instead of adding repeat.for directly on the repeated element. This is possible to refactor in most cases, but I have one flexbox layout where the rendered elements in each loop differs based on value of $index so there I will have a problem with not being able to do a "containerless" repeat.for... hm... Still no idea about the root of the issue, this xmlns thing...

> For some reuse reasons I've been using `<compose view="path/to/some/markup.html"></compose>`. The html file obviously has a `<template>` element as its root element. Now when I'm testing in IE11 I get an error message saying `Potentially unhandled rejection [1] Error: You cannot place a template element within http://www.w3.org/1999/xhtml namespace` and the page is not rendered as intended. Without success I've been trying to google this issue, I have confirmed that Aurelia should support IE9+ etc (and I only need IE11+). Does anyone here have any idea of what might be going on?

**Comment by Alexander-Taran** [comment]
can be closed
