### ISSUE TITLE
Error TS2322: Type 'Response' is not assignable to type 'string[]'

### ISSUE THREAD

**Issue by rajeeshmenoth** [aurelia/framework#760]
Hi,

I'm facing problem while compiling Aurelia app in command prompt. 
When I add "tsc" in cmd then I get the following error.

**_"wwwroot/src/views/values.ts(13,17): error TS2322: Type 'Response' is not assignable to type 'string[]'.
wwwroot/src/views/values.ts(13,17): error TS2322: Type 'Response' is not assignable to type 'string[]'.
  Property 'length' is missing in type 'Response'."_**

I done all the configuration through this article [click here](http://tutaurelia.net/2016/07/02/getting-started-with-aurelia-and-typescript-in-visual-studio-2015-update-3/). But it's not working!!.

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **JSPM**
0.16.53

* **Browser:**
Chrome

* **Language:**
TypeScript ( Compiler Version : 2.2.2 )

**Comment by cluka** [comment]
I don't think that this is a bug,. It's probably error in your code. Please post this question in StackOverflow.
Anyway I can't be sure (you have not shared any code), but to me this seems you are not doing response.json().
