### ISSUE TITLE
New instance of view model is created before every activation

### ISSUE THREAD

**Issue by suamikim** [aurelia/framework#763]
**I'm submitting a bug report**

* **Library Version:**
CLI `0.28.0`
Framework `1.1.2`

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Chrome 57 but I guess it happens in other browsers as well

* **Language:**
TypeScript 2.2.1

**Current behavior:**
Since one of the last updates (I guess it was from framework version `1.1.0` to `1.1.2`) my view models which are bound to routes are instantiated afresh every time they are activated.

**Expected/desired behavior:**
The view model should act as a singleton and should only be instantiated the first time it is activated.

Is this change intentional, a bug, or am I doing something weird in my code which triggers it? I'm pretty sure that it worked the way I've expected it before the update (I can reevaluate this if it'd be of any help).

**Comment by suamikim** [comment]
I've just created a fresh app using the CLI which shows the same behavior:

```ts
// app.ts
import {RouterConfiguration, Router} from 'aurelia-router';

export class App {
	configureRouter(config: RouterConfiguration, router: Router): void {
		this.router = router;
		config.title = 'Aurelia';
		config.map([
			{ route: '',      name: 'home',  moduleId: 'home/index' },
			{ route: 'users', name: 'users', moduleId: 'users/index' }
		]);
	}
}
```

```ts
// home/index.ts
// Users view model looks the same...
export class Home {
	constructor() { console.log('Home view model constructed...'); }
	activate() { console.log('Home view model activated...'); }
}
```

Here's a short screen recording of how this behaves:

![2017-04-12_12h13_11](https://cloud.githubusercontent.com/assets/2870365/24952921/abc12514-1f79-11e7-881c-502211a08fa8.gif)

**Comment by AshleyGrant** [comment]
Yes, this is the default, and expected behavior. If you need to override this behavior for a page, you can use the `@singleton()` decorator.

```javascript
@singleton()
export class Home {
}
```

@EisenbergEffect this issue can be closed.

**Comment by suamikim** [comment]
It seems like I (wrongly) assumed that view models are always singleton and only an internal change which happened around the time of the framework update made it obvious to me that it doesn't work this way.

Sorry for mistaking this with a bug and thanks for pointing it out!
