### ISSUE TITLE
aurelia.enhance parses entire dom body

### ISSUE THREAD

**Issue by doubleaa93** [aurelia/framework#765]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework 1.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7 64bit

* **Node Version:**
6.10.1

* **NPM Version:**
3.10.10

* **Aurelia CLI OR JSPM OR Webpack AND Version**
webpack 2.3.3

* **Browser:**
all

* **Language:**
Typescript

I'm using Aurelia to enhance an element on an existing page using aurelia.enhance which works fine but,
aurelia parses the entire dom body and this page contains jquery templates like this

```
<script id="template-name" type="text/x-jquery-tmpl">
<div>A property ${myProperty}</div>
</script>
```

**EDIT**
I'm passing an element to aurelia.enhance
`aurelia.enhance(document.querySelector('my-component')`

When the page loads aurelia has remove all the` ${}` inside the jquery templates making the existing application not work correctly.

Can I prevent aurelia from parsing the entire body, but to do starting from a certain dom element.

**Comment by Gheoan** [comment]
Pass an `Element` as the second argument to `aurelia.enhance` to limit the enhancement. See http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/8.

**Comment by AshleyGrant** [comment]
@EisenbergEffect this may be closed.

**Comment by doubleaa93** [comment]
@Gheoan Sorry forgot to mention I am passing an element
`aurelia.enhance(document.querySelector('my-component')`

In html 
```
<body aurelia-app="main">
....
<div>
<my-component></my-component>
</div>
```

**Comment by Gheoan** [comment]
@doubleaa93, the `aurelia-app` attribute on the `body` element is not needed if you are using `enhance`.
