### ISSUE TITLE
Using Karma under the JSPM skeleton has issues with the lesser Aurelia framework imports

### ISSUE THREAD

**Issue by estaylorco** [aurelia/framework#766]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.10.0

* **NPM Version:**
4.3.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I should mention first that I'm using the default **karma.conf.json** file that came with the JSPM skeleton.

When importing from **aurelia-dependency-injection**, running **gulp test** errors out with the following error message:

> 404: /base/src/aurelia-dependency-injection.js
> Error: (SystemJS) XHR error (404 Not Found) loading src/aurelia-dependency-injection.js
        Error: XHR error (404 Not Found) loading src/aurelia-dependency-injection.js
        Error loading src/aurelia-dependency-injection.js as "aurelia-dependency-injection" from src/resources/common/messaging/messenger.js

However, when I change **aurelia-dependency-injection** to **aurelia-framework**, my tests run and everything is fine.  I can reproduce and eliminate the error at will by switching back and forth in the `import` statement.

**Expected/desired behavior:**
Should be acceptable to use the lesser framework imports.

* **What is the motivation / use case for changing the behavior?**
I don't mind switching over to **aurelia-framework**, but in a support exchange with Patrick, we had both incidentally harmonized on the idea that using the lesser imports is preferable.  Should it not be the case, though, that the lesser imports would work fine?  Is this a simple matter of altering the **karma.conf.js** file?

Thank you.

**Comment by EisenbergEffect** [comment]
It's because of how System.js work. You need to `jspm install aurelia-dependency-injection`. System.js can't directly import anything that isn't a root dependency, even if that module is already present. In my opinion, it's a design flaw, but that's how you fix it.

**Comment by estaylorco** [comment]
Thanks for the response.

Perhaps a future SystemJS release will address the issue.

But since I already have **aurelia-dependency-injection** installed, will this create a problem, for either the present or for the future (when updating)?

Thanks.

**Comment by EisenbergEffect** [comment]
It shouldn't cause any issues.

**Comment by estaylorco** [comment]
Got it.  Thank you!
