### ISSUE TITLE
Karma warning

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [aurelia/framework#769]
**I'm submitting a bug report**

* **Library Version:**
1.1.2 (According to npm:aurelia-framework in jspm_packages/.dependecies.json)

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.24.0

* **Browser:**
Chrome | Firefox

* **Language:**
ESNext

**Current behavior:**
When running au test --watch, the line
28 04 2017 18:02:24.939:WARN [web-server]: 404: /base/unit/setup.js
was printed on the console.

I recently applied the method described in [post](https://ilikekillnerds.com/2015/07/how-to-update-aurelia-javascript-framework/) to update the aurelia-framework and after that I installed and executed the according [npm-package](https://www.npmjs.com/package/aurelia-update).

I also believe I've updated the aurelia-cli according to [this](https://ilikekillnerds.com/2016/07/issue-updating-aurelia-cli-globally/) but I can't quite remember.

I don't know if any of this has to do with the above mentioned karma warning.

**Expected/desired behavior:**
I fixed the warning by changing line 67 in /cli-project/test/aurelia-karma.js from
    var allTestFiles = ['/base/unit/setup.js'];
to
    var allTestFiles = ['test/unit/setup.js'];

**Comment by EisenbergEffect** [comment]
@JeroenVinke Can you look into this?

**Comment by JeroenVinke** [comment]
Hey @JackLeEmmerdeur. Could you explain how you are using both aurelia-cli and JSPM? There currently is no support for JSPM in the CLI. If you are trying to update all dependencies of your CLI application, you should update the dependencies in package.json and run `npm install`. You shouldn't need JSPM for that. 

I have tried running the tests in a newly created ESNext project, but i'm not getting that warning. If you could provide more information on how to reproduce this issue I'll gladly take another look. Thanks!

**Comment by JackLeEmmerdeur** [comment]
Hi @JeroenVinke. I mixed JSPM and CLI by executing the "jspm install ..." command from the first link inside a CLI-Project. @Vheissu clearly mentions "This article is specifically for Jspm users". So I rather should have done the steps from the third link in my OP. 
So if you could not reproduce this with a new ESNext project (is this a synonym for CLI?), I suppose it's a waste of time to pay attention to my self-inflicted egde-case. Consider it closed? Thanks nevertheless for the attention.

**Comment by JeroenVinke** [comment]
> new ESNext project (is this a synonym for CLI?)

Yes it is, I should have made that more clear :)

> So if you could not reproduce this with a new ESNext project (is this a synonym for CLI?), I suppose it's a waste of time to pay attention to my self-inflicted egde-case. Consider it closed? Thanks nevertheless for the attention.

Sure, just reopen this issue if you encounter this warning in other projects. 

@EisenbergEffect could you close this issue?
