### ISSUE TITLE
Possible regression with binding

### ISSUE THREAD

**Issue by akircher** [aurelia/framework#77]
welcome.js
```
class Welcome {

  activate() {
    this.arr = [‘one’, ‘two’]

    setTimeout(() => {
       this.arr.push(‘three’)
    }, 1000) 

   }
}
```

welcome.html
```
<template>
<div>${arr}</div>
</template>
```
Outputs `one, two` and not `one, two, three`.  This is also broken for objects.  Strings seem to be okay.  This does seem to work as expected in repeat.for

**Comment by EisenbergEffect** [comment]
Quick note: this shouldn't be using change detection. Question: was this a regression? Did it actually work before?

**Comment by akircher** [comment]
Ok good to know - let me know if you want me to rename the issue.  I am not 100% positive its a regression as I have only installed 0.12.  On gitter, someone said that they were on 0.11 with "something similar" and it was working fine.  Thanks for looking into this!

**Comment by jdanyow** [comment]
Tested this against binding 0.3.7 (Feb 28th).  Output is the same.  Tried to go back further but the loader repo that was used back then no longer exists.

Doesn't seem to be a regression issue.

**Comment by EisenbergEffect** [comment]
@jdanyow Could we fix this for arrays? Perhaps, if we have a string interpolation and the item we are performing the toString operation on is an array, we could register for changes to that array and then refresh the toString output? Thoughts?

**Comment by jdanyow** [comment]
I think it's doable- let me throw something together for you to review.  Thinking there's two parts to this:  

1) subscribing to the array changes and refreshing the interpolation, ensuring the subscription is disposed.
2) within the existing propertyChanged handler, clean up the array subscription and creating a new one if necessary (in case someone does `this.arr = newArrayInstance;`)
