### ISSUE TITLE
[Question] Why you dont use Interfaces with typescript in Aurelia ?

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/framework#770]
Please see the examples 

```
export class App implements IRouteConfig {
  configureRouter(config, router){
  }
}
```

or

```
export class InterceptBindingBehavior implements IBindingBehavior {
  bind(binding, scope, interceptor) {
  }
  unbind(binding, scope) {
  }
}
```

and ...

I think most developers can remember names of interfaces easily but methods signatures seems to be more difficult. 

Why you dont use Interfaces with typescript in Aurelia ? you can use you conventions names  as names of interfaces.

**Comment by AshleyGrant** [comment]
https://github.com/aurelia/router/blob/master/src/interfaces.js#L4

Most of what you're asking for is already there. It isn't currently well documented, but each part of the Framework has a `d.ts` file that includes these very interfaces you're looking for.

**Comment by fgambino** [comment]
Do we have interfaces for functions that can be defined on a component? It would be nice to have one for `configureRouter` (e.g. ConfiguresRouter) so it can automatically be stubbed out. I think that's what @HamedFathi is referring to.

**Comment by HamedFathi** [comment]
@AshleyGrant 

Oooohhhhh, I think aurelia team should focus on documentation. so please update those.
like @fgambino I didn't know those existed !

**Comment by AshleyGrant** [comment]
Now that I think about it, these things actually are in our docs, just in the API docs. Check it out!

http://aurelia.io/hub.html#/doc/api/aurelia/router/1.3.0/interface/ConfiguresRouter

http://aurelia.io/hub.html#/doc/api/aurelia/templating/1.4.2/interface/ComponentBind

http://aurelia.io/hub.html#/doc/api/aurelia/templating/latest/interface/ComponentUnbind

We probably should create articles that highlight these though.

**Comment by AshleyGrant** [comment]
@EisenbergEffect please close this issue.
