### ISSUE TITLE
setInterval function resolving to NodeJS.Timer in browser

### ISSUE THREAD

**Issue by ejsmith** [aurelia/framework#773]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10

* **Node Version:**
7.9.0

* **NPM Version:**
4.5.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
Latest webpack/typescript version pulled from skeleton-navigation.

https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack

* **Browser:**
all

* **Language:**
TypeScript 2.3.2

**Current behavior:**
setInterval function resolving to NodeJS.Timer in browser

**Expected/desired behavior:**
Expect setInterval function to return a number while in the browser. It seems like something in aurelia is causing the nodejs type definitions to be pulled into the browser.

![screen shot 2017-05-16 at 4 11 32 pm](https://cloud.githubusercontent.com/assets/282584/26128625/b0950ea4-3a52-11e7-8540-6b3ce0e7be98.png)

**Comment by StrahilKazlachev** [comment]
To clarify, it is not being pulled in the *browser*, it just gets installed and TS picks it up.
I would just exclude `@types/node` regardless who is installing it. I had similar issue at work, non Aurelia related project, one of the dev deps was the culprit, but we couldn't run the build without it.

**Comment by ejsmith** [comment]
The whole node_modules folder is excluded. So not sure how I would exclude the node type def.

**Comment by AshleyGrant** [comment]
@EisenbergEffect I think this issue should be moved to the skeleton repo and assigned to @niieani so he can take a look at it.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/skeleton-navigation #831](https://github.com/aurelia/skeleton-navigation/issues/831) via [**ZenHub**](https://www.zenhub.com/)
