### ISSUE TITLE
SetRoot and enhance simultaneously

### ISSUE THREAD

**Issue by johan-v-r** [aurelia/framework#775]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.9.0

* **NPM Version:**
4.2.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
Aurelia CLI 0.27.0

* **Browser:**
Chrome 58.0.3029.110 | Firefox 53.0.2 | Brave 0.15.2

* **Language:**
ESNext

**Current behavior:**

`aurelia.setRoot()` & `aurelia.enhance()` works as expected individually, but fails to do both.

**Expected/desired behavior:**

I want to bind a view-model to an element on `index.html`, as well as start the Aurelia app in a separate element simultaneously.

See example here: https://gist.run/?id=0b20fbfe69f9243c6c29d10eb9ca1eae

* **What is the motivation / use case for changing the behavior?**

Converting a multilingual app that needs data-binding on the `index.html` for SEO reasons.

**Comment by EisenbergEffect** [comment]
Resolve the `TemplatingEngine` and use its `enhance` API as well. When you call it from the `aurelia` object it's an either/or with `setRoot` because it assumes you are setting up a single app. With the `TemplatingEngine` you can call `enhance` as many times as you want.

**Comment by johan-v-r** [comment]
Thanks for the reply. I eventually got it working with the `TemplatingEngine` as suggested (that original gist has been updated).

I then realized that I actually only needed one instance of `app` for both `index.html` and `<app></app>`, so my final solution is now:
```
aurelia.use.globalResources('app');

aurelia.start().then(a => {    
    let app = a.container.get(App);
    aurelia.enhance(app, document.body);
  });
```
