### ISSUE TITLE
Boot application from package

### ISSUE THREAD

**Issue by luboid** [aurelia/framework#778]
**I'm submitting a feature request**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.4.0

* **NPM Version:**
4.1.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
SystemJS 0.20.12, Aurelia node modules

* **Browser:**
all

* **Language:**
TypeScript 2.3.2

**Current behavior:**
systemjs.config.js
```javascript
{
    packages: {
      "the-app": {
        defaultExtension: 'js',
        main: "main",
        format: 'amd'
      }
   },
   map: {
       // "the-app": "the-app/"
   }
 }  
```
main.ts
```typescript
import 'bootstrap';
import { Aurelia } from 'aurelia-framework';

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging();

  aurelia.start().then(() => {
    return aurelia.setRoot((<any>aurelia).configModuleId + "/app");
  });
}
```
index.html
```html
<body aurelia-app="the-app">
```

**Expected/desired behavior:**
main.ts
```typescript
import 'bootstrap';
import { Aurelia } from 'aurelia-framework';

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging();

  aurelia.start().then(() => {
    return aurelia.setRoot();
  });
}
```
or least configModuleId to be public

* **What is the motivation / use case for changing the behavior?**
Better encapsulation/structure

**Comment by EisenbergEffect** [comment]
I believe you just need to do `<body aurelia-app="the-app/app">`

**Comment by luboid** [comment]
Where main need to go
