### ISSUE TITLE
If two custom-elements extends the same base class they will share the same __metadata__ property

### ISSUE THREAD

**Issue by bmarotta** [aurelia/framework#780]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework@1.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.27.0

* **Browser:**
all

* **Language:**
TypeScript 2.1.1 (but I assume it is not bound to the language)

**Current behavior:**
If two custom-elements extends the same class, they will share the __metadata__ property. As a consequence one will overwrite the metadata properties from the other (injection, aurelia::resource, etc.). In the last instance one of them will never be instantiated by the framework.

**Expected/desired behavior:**
Each custom-element should have its own __metadata__ description.

* **What is the motivation / use case for changing the behavior?**
Sharing the __metadata__ doesn't make sense. And inheritance is a needed pattern to avoid code duplication.

**Comment by gheoan** [comment]
https://github.com/aurelia/templating/issues/463

**Comment by EisenbergEffect** [comment]
Closing as a duplicate. I think we have a solution in the works. We haven't officially supported component inheritance yet.
