### ISSUE TITLE
Cannot use custom attribute with dynamicOptions in repeat

### ISSUE THREAD

**Issue by len-ro** [aurelia/framework#781]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
6.9.5

* **NPM Version:**
4.1.2

* **Aurelia CLI OR JSPM OR Webpack AND Version**
 JSPM 0.16.53

* **Browser:**
all 

* **Language:**
TypeScript X.X | ESNext

I am trying to use a customAttribute in a repeat. See: https://gist.run/?id=a2cbe8542e0733d8afcb13f793b6856d. 

This does not seem to work: `TypeError: Cannot read property 'setValue' of undefined`. 

Is this supported?

```html
<!--<div repeat.for="d of data">${d.a} ${d.b}</div> works-->
<!--<div repeat.for="d of data" my-attribute="a: ${d.a}; b: ${d.b}"></div> does not work-->
<div repeat.for="d of data" my-attribute="${d.c}"></div> does not work
```

**Comment by AshleyGrant** [comment]
You aren't setting any properties in your example. You have created a "simple attribute." To use dynamic options, you would do something like this: 

```html
<div repeat.for="d of data" my-attribute="a.bind: d.a; b.bind: d.b"></div>
```

See the gist here: https://gist.run/?id=8e366db800358bb1d4b5fbcad1d58ccf

@EisenbergEffect this issue may be closed.

**Comment by len-ro** [comment]
I was hoping to be also able to have something like:
`<div repeat.for="d of data" my-attribute="${d.c}"></div>` where c can contain a variable number of parameters. For instance `c  = 'a: aVal'` in one case, `c = 'a: aVal, b:bVal' in another but I can live with doing a bind for all parameters even the ones which are not present. 

Thank you.
