### ISSUE TITLE
Repeat for tr causes "too much recursion" (ffox) "Maximum call stack size exceeded" (chrome)

### ISSUE THREAD

**Issue by kyvanc** [aurelia/framework#783]
**I'm submitting a bug report**

* **Library Version:**
aurelia-skeleton-navigation-webpack@1.1.2

**Please tell us about your environment:**
* **Operating System:**
Linux (Arch)

* **Node Version:**
7.10.0-2

* **NPM Version:**
4.6.1-1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
Webpack 2.1.0-beta27 & 2.6.1

* **Browser:**
Firefox 53.0.3
Chromium 58.0.3029

* **Language:**
TypeScript 2.3.3

**Current behavior:**
When a table row is repeated in a composed view, it gives error:
Firefox:
"Unhandled rejection Error: Error invoking Repeat. Check the inner error for details.
Inner Error:
Message: too much recursion"

Chromium:
"Unhandled rejection Error: Error invoking Repeat. Check the inner error for details. (bluebird.js 1542)
Inner Error:
Message: Maximum call stack size exceeded
Inner Error Stack:
RangeError: Maximum call stack size exceeded"

**Expected/desired behavior:**
Rows are expected to be repeated. The simplest example I could give (after getting aurelia running following the guide at http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/setup-webpack/1 ) is, adding a simple page to the route which repeats a component 3 times. the component itself tries to repeat table rows for an array of numbers. 

test.html

```
<template>
  <h1>Test</h1>

  <div repeat.for="id of ids">
    <compose view-model="./components/table" model.bind="id"></compose>
   </div>

    
</template>
```

test.ts

```
export class testPage {
  ids: number[] = [1,2,3]
}
```

components/table.html

```
<template>
  <h2>Table for ${id}</h2>
  <div repeat.for="rows of tableData">${rows}</div>
  <table>
    <tbody>
      <tr repeat.for="crrow of tableData">
        <td>${crrow}</td>
      </tr>
    </tbody>
  </table>
</template>
```

components/table.ts

```
export class table  {
  id: number
  tableData: number[] = []

  activate(model)  {
    this.id = model
  }

  attached() {
    this.tableData = [1,2,3]
  }
}
```

in table.html, the repetition works for "div"  but not for "tr" (ie, if the tr is commented out the div gets repeated)
The example is shortened for sake of simplicity, the data will be loaded dynamically, it'll be a 2d array etc. but even this simple version does not run.

* **What is the motivation / use case for changing the behavior?**
To dynamically compose a view of several tables each of which has a dynamic number of rows/columns.

**Comment by AshleyGrant** [comment]
You don't have a `td` element in your table markup.

**Comment by kyvanc** [comment]
Indeed I forgot to add the td after changing the code many times. I corrected the markup in the bug report but it doesn't change the end result (actually my first tests included that td repeating for the second element of 2d number array)

**Comment by kyvanc** [comment]
Just tried with custom element instead of composing and this time, no errors, the table row is repeated!

**Comment by AshleyGrant** [comment]
Oh.. yeah... that would cause a bit of a problem :-)

If it makes you feel better, I had this type of self-induced bug bite me onstage at a conference last year.

I named my file `nav.html` instead of `nav-bar.html`. That caused a bit of a problem. I didn't realize what I had done until about an hour later.

**Comment by kyvanc** [comment]
Well, actually it made me feel better, thanks :) sometimes I think these are signs that yell at me "have a break for heaven's sake". thanks for the great framework by the way!
