### ISSUE TITLE
Binding radios model.bind before checked.bind

### ISSUE THREAD

**Issue by reeddunkle** [aurelia/framework#784]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

* **Operating System:**
Windows 10

* **Node Version:**
7.9.0

* **NPM Version:**
4.2.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
Webpack 2.2.1

* **Browser:**
Chrome 58.0.3029.110 | IE 11

* **Language:**
JavaScript

**Current behavior:**
When binding radio buttons with object arrays in Aurelia, setting the `model.bind` must come before setting the `checked.bind`.

We're using Material Design Lite's [radio button classes](https://getmdl.io/components/index.html#toggles-section/radio), though we haven't thoroughly tested whether this issue occurs independently of MDL.

**Expected/desired behavior:**

I wasn't aware that the order of attribute setting mattered. Now that I'm aware of it, I see that indeed all of Team Aurelia's examples set `model.bind` before `checked.bind`. If this is necessary, I expect the rule to be documented and easy to find. If it is unintended, I would expect the attribute order to be unrelated to its functionality.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you chime in on this? I don't think browsers guarantee the order of attributes. Do we have a bug here we need to address?

**Comment by jdanyow** [comment]
I don't know of an issue with attribute ordering and radios. @reeddunkle what's the issue you're seeing?

I can confirm that different DOM implementations list attributes differently. Some use alphabetical order, some use the order the attributes appear in the HTML.

**Comment by reeddunkle** [comment]
@jdanyow We ran into the issue while trying to get the radio group to display a pre-loaded value.

I'll see if I can get some screenshots, or an example together in a gist.

**Comment by reeddunkle** [comment]
Alright, three screenshots. The first is with `model.bind` set first, the second has alphabetized attributes, and the last also with alphabetized attributes but with all MDL classes removed. Once the MDL classes are removed, it behaves fine regardless of attribute order. It's more likely this is an MDL issue than an Aurelia issue.

![model.bind first](http://i.imgur.com/7owV0rZ.png)
![ABCs](http://i.imgur.com/VUiFfgK.png)
![no MDL](http://i.imgur.com/mXTt4gy.png)

**Comment by jdanyow** [comment]
Does anything change if you switch from if.bind to show.bind

**Comment by niemyjski** [comment]
I'm also running into this issue and we are using mdl, works sometimes other times it doesn't :\

**Comment by niemyjski** [comment]
@jdanyow did you find a solution?

**Comment by niemyjski** [comment]
I forked an older sample but I'm doing as simple as this and it fails:  https://gist.run/?id=6639c5ab681aeb274a84ec8c75e2ed0e

**Comment by niemyjski** [comment]
doh, I think I narrowed this down and it was not intuitive. I had a hidden (show.bind) custom element of the same component type (same yes/no control) bound to the same value (a bug). The name="blah" wasn't scoped between the two and it should have been.  Scoping the second component name solved this. I also verified if.bind would also solved this. I did both.

**Comment by reeddunkle** [comment]
@niemyjski For what it's worth, we have had better overall luck with the [MDC](https://github.com/material-components/material-components-web) library. (Though we aren't able to swap out MDL for MDC yet, we might in the future.)

**Comment by Alexander-Taran** [comment]
@reeddunkle is this still relevant to you?
if not, please close the issue 
And have a good day (-:
