### ISSUE TITLE
fix(typo) documentation says export instead of exports

### ISSUE THREAD

**Issue by Anthony-Mckale** [aurelia/framework#786]
**I'm submitting a bug report**

**Current behavior:**

http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-jspm/9

```
{
    "name":"jquery",
    "path":"../node_modules/jquery/dist",
    "main":"jquery.min",
    "export": "$"
  }
```

is incorrect

**Expected/desired behavior:**

```
{
    "name":"jquery",
    "path":"../node_modules/jquery/dist",
    "main":"jquery.min",
    "exports": "$"
  }
```

as per http://requirejs.org/docs/api.html

* **What is the motivation / use case for changing the behavior?**

avoid confusion for folks using old libraries

**Comment by Alexander-Taran** [comment]
fix merged, can be closed
