### ISSUE TITLE
Lifecycle callback 'attached' not being called for all instances of custom element

### ISSUE THREAD

**Issue by lyptt** [aurelia/framework#792]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.10.2

* **NPM Version:**
3.10.10

* **Aurelia CLI OR JSPM OR Webpack AND Version**
webpack 2.2.0

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I have a custom element with an `attached()` callback registered. I have 12 instances of the element on a page, the first four have their attached() callbacks fired successfully. The other 8 do not. The `bind()` callback is called for every instance.

**Expected/desired behavior:**
`attached()` to be called for every element

**Comment by lyptt** [comment]
One thing I should note is the components that do not have the callback invoked report `isAttached: false` in the aurelia inspector.

**Comment by AshleyGrant** [comment]
We're going to need a minimal repro of this (preferably a runnable gist for gist.run ) so that we can verify this and then fix it.

**Comment by lyptt** [comment]
I'm not sure how I can do that, the project's pretty big.

**Comment by lyptt** [comment]
For reference @AshleyGrant I'm using aurelia-router, and I know there's been some issues in the past with callbacks not being fired. If you have any information on how to set up a gist that uses aurelia-router then I can try to create one for you.

**Comment by AshleyGrant** [comment]
`attached` is a component lifecycle callback, not a router lifecycle callback, so using or not using the router *shouldn't* matter for this. That being said, it's easy to use the router on gist.run. Just use a `router-view` element and a `configureRouter` method like you would in any other Aurelia application. You just can't have folders.

**Comment by lyptt** [comment]
@AshleyGrant so it appears it's actually _another_ custom element on the page that prevents any further attachments being called. I'm not entirely sure what part of this is breaking aurelia, but here's the source code for the component in its entirety: https://gist.github.com/lyptt/af2d1a1311d359ba8793735e8c366db0

Removing this custom element from the page fixes all of the attached not being called issues.

**Comment by lyptt** [comment]
I think that this issue may be around rapidly modifying the dom internal to the custom element during the attachment / binding phase. By adding further guards to prevent modifying the DOM unneccesarily, it fixes the issue.

**Comment by AshleyGrant** [comment]
https://gist.github.com/lyptt/af2d1a1311d359ba8793735e8c366db0#file-slider-js-L41 

this line is probably unnecessary and could be accomplished with 

`<div ref="slider"></div>`

or similar in your code.

There's a fair amount of code in that gist that can be cleaned up using ES2015+ features :-)

I'm boarding a flight in about 90 minutes, but if you point me to the jquery plugin you're using, and send me the template for the custom element, maybe I can find some time to play with it while I fly. Though it will be a while before you hear back from me (11 hour flight).

**Comment by lyptt** [comment]
Hey @AshleyGrant - sure, it's noUiSlider: https://refreshless.com/nouislider/

**Comment by lyptt** [comment]
The template's probably as simple as you could get 😀

```html
<template>
  <div class="binding-context"></div>
</template>
```

**Comment by AshleyGrant** [comment]
Ah. Then yes, please switch to using the `ref="binding-context"` like I showed above.

Cheers!

**Comment by AshleyGrant** [comment]
```javascript
import {
  inject,
  bindable,
  bindingMode,
  inlineView,
  TaskQueue
} from 'aurelia-framework';
import { PLATFORM } from 'aurelia-pal';
// import formatter from './formatter';

@inject(TaskQueue)
@inlineView('<template><div ref="slider"></div></template>')
export class Slider {
  @bindable({ defaultBindingMode: bindingMode.twoWay }) start = 0;
  @bindable({ defaultBindingMode: bindingMode.twoWay }) end = 10;
  @bindable min = 0;
  @bindable max = 10;

  guard = false;

  constructor(taskQueue) {
    this.taskQueue = taskQueue;
  }

  bind() {
    if (typeof this.start === 'undefined') {
      this.start = this.min;
    }

    if (typeof this.end === 'undefined') {
      this.end = this.max;
    }
  }

  attached() {
    if (typeof this.start === 'undefined' || typeof this.end === 'undefined') {
      return;
    }

    this.performBinding();
  }

  detached() {
    this.performUnbinding();
  }

  performBinding() {
    const _min = Number(this.min);
    const _max = Number(this.max);
    const _start = Number(this.start);
    const _end = Number(this.end);

    PLATFORM.global.noUiSlider.create(this.slider, {
      start: [_start, _end],
      step: 1,
      range: {
        'min': [_min || 0],
        '60%': [(_max || 10) / 5],
        'max': [_max || 10]
      },
      connect: true
    });

    this.slider.noUiSlider.on('change', (_, __, [start, end]) => {
      this.guard = true;
      this.start = Math.round(start);
      this.end = Math.round(end);

      this.taskQueue.queueMicroTask(() => this.guard = false);
    });

    this.bindComplete = true;
  }

  performUnbinding() {
    this.slider.noUiSlider.off();
    this.slider.noUiSlider.destroy();
    this.slider.noUiSlider = null;
  }

  startChanged() {
    if (this.guard) {
      return;
    }
    this.slider.noUiSlider.set([this.start, null]);
  }

  endChanged() {
    if (this.guard) {
      return;
    }
    this.slider.noUiSlider.set([null, this.end]);
  }

  minChanged() {
    this.guard = true;
    this.start = this.min;
    this.performUnbinding();
    this.performBinding();
    this.taskQueue.queueMicroTask(() => this.guard = false);
  }

  maxChanged() {
    this.guard = true;
    this.end = this.max;
    this.performUnbinding();
    this.performBinding();
    this.taskQueue.queueMicroTask(() => this.guard = false);
  }
}
```

Try this out.

@EisenbergEffect this issue may be closed.
