### ISSUE TITLE
Dynamic Property Forwarding for Custom Elements

### ISSUE THREAD

**Issue by manueljuan3** [aurelia/framework#794]
Is there a way to forward all of an element's properties similar to how React can transfer all the props? [https://titobouzout.github.io/react/docs/transferring-props.html](url)

Was looking to use Dynamic Options Binding but it is only available for custom attributes and not elements. Any solutions?

**Comment by EisenbergEffect** [comment]
Not currently, no. It would make a nice contribution though :)

**Comment by bigopon** [comment]
There is a way to do it with Aurelia, though not obvious. For anyone curious, please have a read here https://discourse.aurelia.io/t/assign-all-new-attributes-to-specific-element-transparent-wrapper-components/1949

**Comment by bigopon** [comment]
@EisenbergEffect I think this issue can be closed, it's tracked in vnext, and has work around in vCurrent, together with a plugin that demonstrates its behavior, also with some ready made elements: https://github.com/aurelia-contrib/aurelia-global-binding
