### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by fabioluz** [aurelia/framework#798]
Hi! I'm creating this issue to list Aurelia features that are not documented yet. 

I can make the PR's to update the docs, but I want to be sure that I'm right before doing anything. So please, tell me if these changes are welcome.

Let's keep this list up to date!

# Documentation Improvement List

**Build Systems**

- [ ] CLI
  - [ ] CLI now supports SystemJS and Webpack. Update the docs with new information and new commands, including `au install`. 
  - [ ] Improve the documentaion about how to configure aurelia.json file.
- [ ] Webpack Skeleton
  - ?
- [ ] SystemJS Skeleton
  - ?

**Binding**
- [ ] Explain that `@computedFrom` doesn't observe array mutations. Show workaround.
- [x] Add docs about `@observable`
- [ ] Show `aurelia-computed` ?
- [ ] Advanced Scenarios
  - [ ] Add docs about how to observe objects and arrays via BindingEngine.

**Templating**
- [ ] Explain (with empahsis) that Kebab-case should be used when binding properties in the view.
- [ ] Explain that `<compose></compose>` is not a replacement for `<require></require><element></element>`. It should only be used in specific situations.
- [ ] Show that `if.bind` and ` repeat.for` can be used with `<template>`.
- [ ] Explain that declaring bindable properties in the view (`<template bindable="">`) only works for html-only components.
- [ ] Explain that if the bindable property is an array, its change handler won't be called for array mutations. The BindingEngine's CollectionObserver should be used instead.
- [ ] Explain that `@child` and `@children` need `<slot></slot>` to work.
- [ ] Show cool things that can be done with `@processContent`. Reference: https://stackoverflow.com/questions/43306744/using-custom-element-content-as-item-template
- [ ] Does `@useShadowDOM` really work?
- [ ] Show that `containerless` attribute can be used with `<router-view containerless>` and `<compose containerless>`
- [ ] Show cool examples of `<template replaceable part="">` and `<template replace-part="">` . Including usage with repeaters. Reference: https://stackoverflow.com/questions/44402632/in-aurelia-can-a-slot-be-used-in-a-repeat-for-binding
- [ ] Advanced Scenarios
  - [ ] Add docs about how to compose and enhance elements via TemplatingEngine.

**Router**
- [ ] Show how to get parent router params from child router. 
- [ ] Show how to get child router settings. Reference: https://stackoverflow.com/questions/44501708/aurelia-child-route-with-settings-parameter/44510523

**HttpServices**
- ?

**Validation**
- [ ] Explain how to add validation rules from JSON. 

**I18n**
- [ ] Update the sections about CLI and Webpack. 
- [ ] Show how to use a translated string as translation paramater. Reference: https://stackoverflow.com/questions/43733172/how-do-i-use-rt-binding-behavior-with-t-and-t-params-binding/

**Dialog**
- ?

**Testing**
- ?

**Troubleshooting/FAQ (New section proposal)** A list of most common doubts and mistakes. 
- [ ] Why my bindable properties aren't working?
- [ ] How to configure aurelia to work with my jquery library? - Common examples
- [ ] ...

**Comment by EisenbergEffect** [comment]
We'd love this 😀 Please send each one as a separate PR so we can review
independently.

**Comment by euglv** [comment]
Please add more info about `@processContent`, not only cool things. Please describe each function parameter (`compiler`, `resources`, `node`, `instruction`) and their members and how to use them.

**Comment by bigopon** [comment]
@euglv thanks for pointing this out. I may have a go at this, unless someone else from our community wants to tackle it, since I guess it's pretty commonly used.
