### ISSUE TITLE
fullstack generator?

### ISSUE THREAD

**Issue by honkskillet** [aurelia/framework#80]
Hi,
Is there any plan for an official fullstack aurelia generator (slush or yeoman)?  I really like the yeoman generator generator-angular-fullstack and it would be cool to see something similar in aurelia.

**Comment by kristianmandrup** [comment]
Fullstack generators are usually a bad idea. Tech fashions change too quickly. Better to use separate client and server generators IMO.

**Comment by kristianmandrup** [comment]
But if you want, we could tweak the KOAN full stack framework into one for Aurelia instead and then create a generator for it...?

KOAN Stack (Koa, Angular, Node, Mongo, WebSockets) for real-time full-stack JavaScript web development.

https://github.com/kristianmandrup/koan

**Comment by honkskillet** [comment]
I don't disagree entirely.  I think a good full stack generator is highly modular such that it is basically 2 or 3 separate generators that are mostly loosely tied together.  I'm working on a project right now based on generator-angular-fullstack, but if I were to start a MEAN stack from scratch today I might opt to use one of the standard front end and back end generators plus passport to handle auth.

I do thing that there is a real benefit to having a full stack generator for aurelia.  I got hooked on angular after playing with several MEAN stacks.  Being able to get something up and running with AUTH quickly was tremendously alluring.

**Comment by kristianmandrup** [comment]
I already started a full stack based on KOAN... you are most welcome to contribute!!
It also includes Auth via JWT and integrates with MongoDB. With minimal effort also with RethinkDB, both via Web Sockets for Real Time data sync...

https://github.com/kristianmandrup/koan

**Comment by Aaike** [comment]
there will be scaffolding built into the aurelia-cli , that will be much like the yeoman generator or slush, so yes there are plans for it.

**Comment by honkskillet** [comment]
Why build this into aurelia-cli and not use the more standard yeoman or slush generators?

**Comment by Aaike** [comment]
The main reason is they want to have control over how the generator works and how the api looks like, and to not be dependent on third party libraries. And perhaps to do some things that are specific to aurelia , that you would not be able to do with yeoman or slush because they are generalized generators.

**Comment by honkskillet** [comment]
I don't think I'd be wrong to say Yeoman is the  currently the industry standard generator.  Like many (most?) people doing this kind of programming I'd rather use Yeoman the leading generator than be forced to learn some custom cli just do to something simple like scaffolding.  For example, look at meanjs.org and mean.io .  The former uses Yeoman and the latter has it's own custom cli.  If you were going to spin up one of these two MEAN stacks to check it out, would you gravitate to the one with the standard yeoman generator and shy away from the one with it's own custom cli?  I would.

Also consider that just registering a yeoman generator gives that generator visibility in the yeoman generator registry... http://yeoman.io/generators/

**Comment by honkskillet** [comment]
Heck someone has already registered an aurelia generator on Yeoman and it has 16 stars.
https://github.com/zewa666/generator-aurelia

**Comment by kristianmandrup** [comment]
Yes, that one generates the skeleton-navigation app. It's primitive but gets the work done. 

I agree, that using a generator like Yeoman would make more sense and you have full freedom to customize as you like with almost no constraints. I've made several generators, such as [ember-config](https://github.com/kristianmandrup/ember-config)

Let's see how aurelia-cli turns out. In the meantime, you are welcome to contribute to my little fullstack skeleton and when wired up, we can see how to turn it into a generator.

**Comment by zewa666** [comment]
as @kristianmandrup mentioned the current generator-aurelia is just a simple tool to get you the latest version of the skeleton app. The Aurelia-CLI itself is going to incorporate much more logic and features and will fit in with future tools provided by Durandal Inc.

That said @honkskillet you are definitely welcome to contribute in any way you think feels right. No work done is useless and maybe can be reused somewhere else as well. If you're looking for a classic fullstack on Node and ExpressJS you might wanna take a look at https://github.com/zewa666/aurelia-node

**Comment by EisenbergEffect** [comment]
We are planning to build a "new project generator" post beta.
