### ISSUE TITLE
Question: Getting started with .NET is turning out to be difficult.  Is there a go-to "Getting Started" template for .NET users?

### ISSUE THREAD

**Issue by sb2059** [aurelia/framework#802]
This should likely be labeled as a question.

We're looking into upgrading our .NET (pre-Core, MVC4) Durandal app into .NET Core / Aurelia implementation.  The easiest way for me to learn new things is to build on top of existing things and pluck/play instead of starting from scratch.  

I know a big part of Aurelia's pitch is "unobtrusiveness" - I'm trying to do the bare-minimum amount of learning and work here to get a basic CRUD app working.  I'm surprised to find that there isn't much available out there (though my google-fu may be failing).  I've spent my morning looking for a "hello-aurelia" template to play with but I'm coming up short.

What would be amazing is a basic `.sln` that contains a single MVC SPA project file with everything that's needed for Aurelia to work.  I don't want to go off and learn VSCode when we're tooled with VS; I don't want to learn CLI commands any more than I have to.  I want an incremental learning experience here to reduce the cost of migration - I want to take a skeleton and animate it within VS.  I don't want to compose that skeleton or put a bunch of work into bringing it to life or teaching others how to do overhead.

I know this is essentially just a list of demands and hope it doesn't come off as disgruntled or anything; I've loved Durandal and I remember starting up with a ToDo app that has evolved to some pretty insane applications.  We eventually learned how the innards worked and how to get `main-built` generating on build etc - but we learned that when we needed to.  It would be great if we could build on top of a template that has:

 - ASP.NET Core to deliver the SPA (debug or optimized for production)
 - Basic clientside CRUD

That's it.  1) download 2) run 3) learn.  Then we could take our existing app, work in Entity Framework, Identity, and WebApi.   Is there any kind of .NET/Aurelia "starter kit" like this available?  If not, can there be?  I understand it's "one more thing to maintain" but I think it would help with adoption.

**Comment by Aniel** [comment]
Did you look at https://github.com/aspnet/JavaScriptServices ?

**Comment by weagle08** [comment]
https://github.com/aurelia/skeleton-navigation
in that github project you will find an example of using aurelia with .net core
