### ISSUE TITLE
ES5 generation issues

### ISSUE THREAD

**Issue by firelizzard18** [aurelia/framework#806]
**I'm submitting a bug report**

_This is a transpilation issue with the versions packaged for distribution via NPM/JSPM._

* **Library Version:**
  * bootstrapper: `^2.0.1`
    * framework: `1.0.8`

**Please tell us about your environment:**
* **Operating System:**
Tested in Windows 10

* **Node Version:**
7.7.3

* **NPM Version:**
4.1.2

* **JSPM**
JSPM 0.17.0-beta.42

* **Browser:**
Tested in Chrome 59

* **Language:**
ESNext

**Current behavior:**
Aurelia framework fails to load because `__useDefault` is not excluded from re-exporting during transpiled `export * from 'aurelia-<package>'` statements.

**Expected/desired behavior:**
Aurelia framework loads.

**'Fix'**
I have fixed this by replacing occurrences of `if (key === "default" || key === "__esModule") return;` with `if (key === "default" || key === "__esModule" || key === "__useDefault") return;`.

```javascript
var gulp = require('gulp'),
    replace = require('gulp-replace'),
    _;

gulp.task('fix-aurelia', function () {
    return gulp.src(['wwwroot/jspm/npm/aurelia-framework*/aurelia-framework.js'])
        .pipe(replace(/if \(key === "default" \|\| key === "__esModule"\) return;/g, 'if (key === "default" || key === "__esModule" || key === "__useDefault") return;'))
        .pipe(gulp.dest('wwwroot/jspm/npm'))
})
```

**Comment by EisenbergEffect** [comment]
I believe this is a bug in the Babel transpiler itself. Would you be willing to submit a PR with the gulp task that we could use to correct the Babel output?

**Comment by firelizzard18** [comment]
I would, but since I did this at work, it's a bit complicated. My boss was planning to talk to his boss about signing the CLA, but I haven't heard back.

**Comment by Alexander-Taran** [comment]
if (relevant) {
 tossCoin()==='eagle' ? close() : fixTask() & close();
}
