### ISSUE TITLE
Could the js file for a page/screen be optional ?

### ISSUE THREAD

**Issue by Aaike** [aurelia/framework#82]
I have a bunch of pages or screens in my app now where it's just documentation/text , or it just uses custom elements that have been globally registered.

So i have a lot of js files that are basically just empty classes...

I wonder if it would be possible to skip the need for js files for simple views that don't need any specific javascript, so some pages could just have an html and be done.

**Comment by EisenbergEffect** [comment]
Is this specifically related to the router? We might be able to do that.

**Comment by Aaike** [comment]
i suppose it might be for other thing also like `require`. there was just somebody on the chat with this question:

Is is possible to use <require from=".....html"></require> to just require a chunk of html? Without creating a backing .js file for a custom component?

**Comment by jdanyow** [comment]
@Aaike , @nyash  :point_up: [April 15 2015 11:44 AM](https://gitter.im/Aurelia/Discuss?at=552e87619be85f691f018d34)

use the **[compose element](http://aurelia.io/docs.html#compose)**

>The compose element also has a view attribute which can be used in the same way as view-model if you don't wish to leverage the standard view/view-model convention. If you specify a view but no view-model then the view will be databound to the surrounding context.

``` html
<compose view="...html"></compose>
```

**Comment by Aaike** [comment]
@zewa666 pointed out to me that [reusing an existing VM](http://aurelia.io/docs.html#reusing-an-existing-vm) might help out in this case , and yes it does , now i only have one empty javascript class that i reuse :)

But still maybe this could be setup to be like this by defuault ;)

**Comment by EisenbergEffect** [comment]
We now have the ability to require an html file in a view, and that will be converted into a custom element automatically.
