### ISSUE TITLE
Specific Debug Messages and Warnings

### ISSUE THREAD

**Issue by BretMishler** [aurelia/framework#821]
Please note that this was originally a [StackOverflow question](https://stackoverflow.com/questions/45889290/how-to-get-more-specific-debug-messages-and-warnings-from-aurelia). In a comment on that post, @AshleyGrant recommended that I follow up here.

**I'm submitting a feature request**

* **Library Version:**
Aurelia Framework 1.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.9.0

* **NPM Version:**
4.2.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Chrome 60.0.3112.113 (Official Build) (64-bit)

* **Language:**
TypeScript 2.3

**Current behavior:**
Let's say we have a _view_ that we're utilizing frequently throughout our project; this view is invoked in multiple files.

`<div repeat.for="document of documents">`
`<compose model.bind="document" view="document.html"></compose>`
`</div>`

In one instance of the code above, we made the mistake of writing: `view="document/document.html"`. As a result of this mistake, the errors that are logged to the console are as follows:

<img width="825" alt="screen shot 2017-08-29 at 4 10 29 pm" src="https://user-images.githubusercontent.com/8965315/29848339-c7d910ae-8cd4-11e7-9b06-67b7c30b9e44.png">

The error messages clearly tell the developer that "document/document.html" could not be found. What it fails to tell the developer is what file or line of code was attempting to access "document/document.html". The messages logged to the console only communicates to the developer that something went wrong in `system.src.js`, lines 122 and 1051, but this doesn't really help in our quest to find where were incorrectly tried to access "document/document.html".

Unfortunately, the stack trace also doesn't reveal any information on where the 404 was generated but instead only mentions Aurelia src and framework files:

system.src.js:1051 GET https://localhost:44336/dist/document/document.html 404 ()
G @ system.src.js:1051
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2802
(anonymous) @ system.src.js:3380
(anonymous) @ system.src.js:3694
(anonymous) @ system.src.js:4086
(anonymous) @ system.src.js:4549
(anonymous) @ system.src.js:4819
(anonymous) @ system.src.js:407
Promise resolved (async)
s @ system.src.js:401
i @ system.src.js:387
(anonymous) @ system.src.js:545
a @ system.src.js:341
(anonymous) @ system.src.js:847
Promise resolved (async)
import @ system.src.js:840
(anonymous) @ system.src.js:1801
DefaultLoader._import @ aurelia-loader-default.js?bust=1504041541443:209
loadText @ aurelia-loader-default.js?bust=1504041541443:118
loadTemplate @ aurelia-loader-default.js?bust=1504041541443:42
fetch @ aurelia-loader-default.js?bust=1504041541443:91
fetch @ aurelia-loader-default.js?bust=1504041541443:247
(anonymous) @ system.src.js:4544
(anonymous) @ system.src.js:4819
(anonymous) @ system.src.js:407
Promise resolved (async)
s @ system.src.js:401
i @ system.src.js:387
(anonymous) @ system.src.js:545
a @ system.src.js:341
(anonymous) @ system.src.js:847
Promise resolved (async)
import @ system.src.js:840
(anonymous) @ system.src.js:1801
DefaultLoader._import @ aurelia-loader-default.js?bust=1504041541443:209
loadTemplate @ aurelia-loader-default.js?bust=1504041541443:114
ensureRegistryEntry @ aurelia-templating.js?bust=1504041541443:3127
loadViewFactory @ aurelia-templating.js?bust=1504041541443:3195
loadViewFactory @ aurelia-templating.js?bust=1504041541443:568
compose @ aurelia-templating.js?bust=1504041541443:4582
processInstruction @ compose.js?bust=1504041541443:189
bind @ compose.js?bust=1504041541443:84
bind @ aurelia-templating.js?bust=1504041541443:3459
bind @ aurelia-templating.js?bust=1504041541443:1463
addView @ repeat.js?bust=1504041541443:261
_standardProcessInstanceChanged @ array-repeat-strategy.js?bust=1504041541443:113
instanceChanged @ array-repeat-strategy.js?bust=1504041541443:35
itemsChanged @ repeat.js?bust=1504041541443:157
bind @ repeat.js?bust=1504041541443:122
bind @ aurelia-templating.js?bust=1504041541443:3459
bind @ aurelia-templating.js?bust=1504041541443:1463
bind @ aurelia-templating.js?bust=1504041541443:3451
automate @ aurelia-templating.js?bust=1504041541443:3396
ready @ router-view.js?bust=1504041541443:195
swap @ router-view.js?bust=1504041541443:224
(anonymous) @ aurelia-router.js?bust=1504041541443:363
(anonymous) @ aurelia-router.js?bust=1504041541443:362
Promise resolved (async)
_commitChanges @ aurelia-router.js?bust=1504041541443:361
run @ aurelia-router.js?bust=1504041541443:210
next @ aurelia-router.js?bust=1504041541443:179
iterate @ aurelia-router.js?bust=1504041541443:1264
processActivatable @ aurelia-router.js?bust=1504041541443:1267
run @ aurelia-router.js?bust=1504041541443:1148
next @ aurelia-router.js?bust=1504041541443:179
iterate @ aurelia-router.js?bust=1504041541443:1177
processDeactivatable @ aurelia-router.js?bust=1504041541443:1180
run @ aurelia-router.js?bust=1504041541443:1136
next @ aurelia-router.js?bust=1504041541443:179
iterate @ aurelia-router.js?bust=1504041541443:1264
processActivatable @ aurelia-router.js?bust=1504041541443:1267
run @ aurelia-router.js?bust=1504041541443:1124
next @ aurelia-router.js?bust=1504041541443:179
Promise resolved (async)
run @ aurelia-router.js?bust=1504041541443:1411
next @ aurelia-router.js?bust=1504041541443:179
iterate @ aurelia-router.js?bust=1504041541443:1177
processDeactivatable @ aurelia-router.js?bust=1504041541443:1180
run @ aurelia-router.js?bust=1504041541443:1112
next @ aurelia-router.js?bust=1504041541443:179
(anonymous) @ aurelia-router.js?bust=1504041541443:615
Promise resolved (async)
run @ aurelia-router.js?bust=1504041541443:613
next @ aurelia-router.js?bust=1504041541443:179
run @ aurelia-router.js?bust=1504041541443:192
(anonymous) @ aurelia-router.js?bust=1504041541443:1740
Promise resolved (async)
_dequeueInstruction @ aurelia-router.js?bust=1504041541443:1713
(anonymous) @ aurelia-router.js?bust=1504041541443:1704
_queueInstruction @ aurelia-router.js?bust=1504041541443:1701
(anonymous) @ aurelia-router.js?bust=1504041541443:1635
Promise resolved (async)
loadUrl @ aurelia-router.js?bust=1504041541443:1634
_loadUrl @ aurelia-history-browser.js?bust=1504041541443:301
_checkUrl @ aurelia-history-browser.js?bust=1504041541443:294

**Expected/desired behavior:**
It would be extremely useful if the console provided more specific locations in the error messages. For example, had the above issue generated an error similar to:

GET https://localhost:44336/dist/document/document.html 404 ()      |     myFile.html:89

we would have immediately known where our issue was. Especially for developers learning the framework, console logs that state where the code failed will be just as useful, if not more so, than why. At the least, it would be useful if the stack trace logged more than just the framework calls as this doesn't help the developer easily find their error.

In my short time using Aurelia, I've noticed that many of my mistakes result in stack traces and error logs mentioning files that are within the Aurelia framework, not specific to my actual project. Therefore, I'm left in the dark and forced to spend quite some time hunting down where exactly my issues are. With large projects, this becomes quite difficult to debug. More significantly, this may cause confusion on if the bug is within the developer's project or within Aurelia.

Thank you very much.

**Comment by atsu85** [comment]
@BretMishler, Looks like this problem could be detected at build-time by [aurelia-template-lint](https://github.com/MeirionHughes/aurelia-template-lint). @MeirionHughes, is this already supported? I haven't done FE development recently, so don't remember if detecting this issue was already supported or not.

**Comment by Alexander-Taran** [comment]
Stale since mid 2017

**Comment by EisenbergEffect** [comment]
I think we'll address some of this through the build-time compilation work of vNext along with the accompanying new implementation of compose.
