### ISSUE TITLE
Aurelia Inspector

### ISSUE THREAD

**Issue by lpj145** [aurelia/framework#822]
Why aurelia debugger continue working after build app ? when i devel my produtcts i found it, and try on most case of builtaurelia, i can win aurelia-solitaire without touch only one card.

![image](https://user-images.githubusercontent.com/11980109/30028957-8f424598-915d-11e7-9f24-992325796615.png)

**Comment by StrahilKazlachev** [comment]
*Aurelia Inspector* is a browser extension. Do you want to disable/uninstall it or do you have another issue with it?

**Comment by lpj145** [comment]
i say about insecure applications with this extension, this works after build applications and can chanage many data on app.

**Comment by StrahilKazlachev** [comment]
I don't follow. This extension is for convenience. I can do everything it does, and more, just using the dev tools.

**Comment by lpj145** [comment]
after a run au build --env prod, this exentension continue to works, example, on aurelia-solitare app : http://jdanyow.github.io/aurelia-solitaire/ i can win with this extension, without touch any card. I say it because most importants part of my app can be changed by this extension, include security parts.

**Comment by AshleyGrant** [comment]
As mentioned above, all this extension does is inspect the DOM of the website that's currently loaded. This is no more a security issue than the existence of Dev Tools in the first place. This is simply part of the very nature of the web platform. It is your responsibility to guard your application against the client being able to access information they should not be able to access. This is why things like data validation must occur on the server side, even if you also implement client side validation. Even without tools like Dev tools or extensions like the Aurelia inspector, it's very simple to modify data using the URL bar to run JavaScript. 

@eisenbergeffect, please close.
