### ISSUE TITLE
cascading selects not working

### ISSUE THREAD

**Issue by cristimusat** [aurelia/framework#83]
hi, 

I created a simple app with only app.js and app.html to demo the situation:

app.js:
```
export class App {
    masters=[
      {id:1,details:['detail11','detail12','detail13']},
      {id:2,details:['detail21','detail22','detail23']},
      {id:3,details:['detail31','detail32','detail33']},
    ];
    selectedMaster = this.masters[0];
    selectedDetail = this.selectedMaster.details[0];
}
```

app.html
```
<template>
  <select value.bind="selectedMaster">
    <option model.bind="master" repeat.for="master of masters">${master.id}</option>
  </select>
  <select value.bind="selectedDetail">
    <option model.bind="detail" repeat.for="detail of selectedMaster.details">${detail}</option>
  </select>

  <p>
    Selected master:${selectedMaster.id}
  </p>
  <p>
    Selected detail:${selectedDetail}
  </p>

</template>
```

the problem here is that if I change the selection in the master select then the detail select gets reloaded but the selectedDetail variable is not binded. if I change the selection on the detail select then the selectedDetail variable is updated. 

The workaround i found was to listen to the change event on master select and set the selectedDetail variable to the first object in the details array.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?

**Comment by EisenbergEffect** [comment]
Fixed in master.
