### ISSUE TITLE
repeat.for fails to render map (Value for 'map' is non-repeatable)

### ISSUE THREAD

**Issue by einaradolfsen** [aurelia/framework#834]
I've implemented a feature using rendering of  a map in a aurelia-cli(v0.31.3) application (1. esnext). When trying to integrate this into our product application renering fails (Value for 'map' is non-repeatable)

map:
```
keys   = "A"|"B"|"C"...|"Z"
values = [{languageId:<number>, name:<string>}]
```
this is how I render the map:
```
<form  repeat.for="[k,v] of map">   
    <h2>${k} </h2>
    <div repeat.for="language of v">        
        <input type="checkbox" model.bind="language" checked.two-way="selectedLanguages">
            ${language.name}
    </div>
</form>
```

the same issue can be recreated in a test app
1) Create a minimum project following this [approach] (anwared by Jeremy Danyow)(https://stackoverflow.com/questions/32080221/how-to-set-up-minimal-aurelia-project-from-scratch)
2) jspm install aurelia-pal-browser
3) Modify app.js  see:  [Jeremy Danyow's response on issue [104]
](https://github.com/aurelia/templating-resources/issues/104)```
export class App {
    constructor(){
     this.map = new Map();
    this.map.set(0, 'foo');
    this.map.set(1, 'bar');
    this.map.set(2, 'baz');
    }
}
```
4) Modify app.html

<template>
   <ul>
      <li repeat.for="[k, v] of map"> ${k} = ${v}</li>
   </ul>
</template>


5) gulp serve
--> Value for 'map' is non-repeatable

Does anyone know how to fix this?

**Comment by bigopon** [comment]
@einaradolfsen 

The error report you gave likely comes when you assign an object instead of a map to `map` property, but if you can setup a minimal repro, that would be great for debugging. base: https://gist.run/?id=883568d7c8e2add9ed393150100f4744 (clone and update)

**Comment by einaradolfsen** [comment]
@bigopon 
Iterating over map works fine in the [gist](https://gist.run/?id=dc1192cce18ae9a421a0866094ff648c).
I think the issue is related to using jspm skeleton project and aurelia cli (v 0.31.3) esnext. 
If you setup the project using jspm and npm copying app.js and app.html from the gist
this error is thrown:
Error: Value for 'map' is non-repeatable
    at Repeat.itemsChanged (repeat.js:151)
    at Repeat.bind (repeat.js:122)
    at Controller.bind (aurelia-templating.js:3486)
    at View.bind (aurelia-templating.js:1475)
    at Controller.bind (aurelia-templating.js:3478)
    at Controller.automate (aurelia-templating.js:3423)
    at eval (aurelia-templating.js:4568)
    at <anonymous>

**Comment by Alexander-Taran** [comment]
pinging @bigopon

**Comment by bigopon** [comment]
To me this is a user unintended data assignment issue. The error says very clearly that its not a repeatable value, and the repeater support array, map, set, number, null, undefined. So that leaves only few left: boolean, string, symbol, other object types that are not instance of array, map or set.

**Comment by Alexander-Taran** [comment]
@bigopon could it be that skeleton uses some polyfill that changes the behavior of provided in gist code?

**Comment by bigopon** [comment]
Could be, as [these lines](https://github.com/aurelia/templating-resources/blob/master/src/repeat-strategy-locator.js#L28-L32) 

```js
    this.addStrategy(items => items === null || items === undefined, new NullRepeatStrategy());
    this.addStrategy(items => items instanceof Array, new ArrayRepeatStrategy());
    this.addStrategy(items => items instanceof Map, new MapRepeatStrategy());
    this.addStrategy(items => items instanceof Set, new SetRepeatStrategy());
    this.addStrategy(items => typeof items === 'number', new NumberRepeatStrategy());
    ...
```

help ensure it is the reference used by everything else. Unless somewhere in user code, he / she creates the map / set / array with one Map implementation, and then import a polyfill to override that, so the locator will fail to find repeat strategy as shown in the code block above. (I doubt this is the case though)

**Comment by Alexander-Taran** [comment]
@einaradolfsen looks like polifils fight each other.
If you require more assistance with that.
we need to see how your failing app is loaded
so package.json
config.js if any
the html that references scripts
main.js
app.js
and the vm that fails

for starters

**Comment by einaradolfsen** [comment]
@Alexander-Taran 
If this workflow of creating a jspm project is outdated, I think we can close the issue.
Do you know if au-cli has a way to use jspm as package manager?

I've created a project, you can have a look at, the issue is relevant.

We have moved to webpack, which seams to work better for us, Thanks

**Comment by EisenbergEffect** [comment]
We don't support using jspm via the CLI but we support using System.js. I'll close the issue.
