### ISSUE TITLE
Issue when it change the name from some components

### ISSUE THREAD

**Issue by dancespiele** [aurelia/framework#837]
**I'm submitting a bug report**

**Please tell us about your environment:**
* **Operating System:**
Linux Manjaro

* **Node Version:**
 v8.8.0

* **NPM Version:**
3.10.10
 5.5.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.27.0 | JSPM 0.16.53 | webpack 2.3.3
 Aurelia CLI -> 0.32.0

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When I change all the names from some component (component name and links) the framework doesn't render it and it doesn't show any error in browser console log. In this case only it can render if I use compose. The more curious point is if I change again all the names of this component (links etc) to the last name it works fine. It sounds that when there are changes in the name from some component the framework  doesn't register the new name.  

**Expected/desired behavior:**
 The component should render although change the name of the component.

* **What is the motivation / use case for changing the behavior?**

**Comment by StrahilKazlachev** [comment]
Can you provide a minimal repro of what you are trying to do?

**Comment by dancespiele** [comment]
For I have this: 
```
<template bindable="cols">
  <require from="./add-row/add-row"></require>
  <require from="./datatable.css"></require>

  <div class="datatable">
    <add-row cols.bind="cols"></add-row>
  </div>
</template>
```

I call in this example the component add-row and it render this

![captura de pantalla de 2017-10-29 12-04-39](https://user-images.githubusercontent.com/29615753/32142903-6c50584e-bca1-11e7-956b-2850594f7e58.png)

Now I change the name of the component: 
```
<template bindable="cols">
  <require from="./add-element/add-element"></require>
  <require from="./datatable.css"></require>

  <div class="datatable">
    <add-element cols.bind="cols"></add-element>
  </div>
</template>
```

You can see in this image that I change the name of everything regarding with the component:
![captura de pantalla de 2017-10-29 12-10-42](https://user-images.githubusercontent.com/29615753/32142934-3a16f594-bca2-11e7-9161-852b2581b973.png)

And it doesn't render the component:
Now I use compose

```
<template bindable="cols">
  <require from="./datatable.css"></require>

  <div class="datatable">
    <compose 
      view="./add-element/add-element.html"
      view-model="./add-element/add-element">
    </compose>
  </div>
</template>
```
Render the component without the checkbox because I'm not binding the 'cols' property
![captura de pantalla de 2017-10-29 12-15-44](https://user-images.githubusercontent.com/29615753/32143005-326a2b12-bca3-11e7-953a-c491d87d4bf6.png)

Now I change the component with the last name 'add-row':
```
<template bindable="cols">
  <require from="./add-row/add-row"></require>
  <require from="./datatable.css"></require>

  <div class="datatable">
    <add-row cols.bind="cols"></add-row>
  </div>
</template>
```
![captura de pantalla de 2017-10-29 12-19-05](https://user-images.githubusercontent.com/29615753/32143023-756542e4-bca3-11e7-93cd-415a48f0b6d7.png)

Nice! doing this I realise that even without change the name of the file of the component it render the component :). You can see it in the image.
![captura de pantalla de 2017-10-29 12-19-05](https://user-images.githubusercontent.com/29615753/32143060-03218ba6-bca4-11e7-96c9-167208422149.png)

**Comment by StrahilKazlachev** [comment]
1. Are you sure that after renaming the folder/file/component the app is being rebuild?
2. On one of the screenshots the file is marked that it has unsaved changes.
3. I could not see anywhere the source of `add-row.js`/`add-element.js`, when trying to use with the new name - `<add-element>`, are you also changing the name in the impl?
    - by convention approach - `class AddRowCustomElement` -> `class AddElementCustomElement`
    - explicit approach `@customElement('add-row')` -> `@customElement('add-element')`

**Comment by dancespiele** [comment]
Wow I didn't realise about it sorry. The class is the unique thing that I didn't change :(. 
But the log should something like `Not possible to find the addElement class` or something like this. I don't know it is possible.

![captura de pantalla de 2017-10-29 13-29-59](https://user-images.githubusercontent.com/29615753/32143671-48d6da6c-bcad-11e7-9ca2-4ff89ae71f81.png)

**Comment by Alexander-Taran** [comment]
@dancespiele It would not know that your custom tag is a custom element.

@StrahilKazlachev will it behave like that with as-element or compose?

**Comment by Alexander-Taran** [comment]
@bigopon maybe can be closed..
