### ISSUE TITLE
Behavior with index.js is not properly

### ISSUE THREAD

**Issue by dancespiele** [aurelia/framework#838]
**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
Linux Manjaro

* **Node Version:**

 v8.8.0

* **NPM Version:**
3.10.10
 5.5.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.27.0 | JSPM 0.16.53 | webpack 2.3.3
 Aurelia CLI 0.32.0

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When I import something from some folder which has index.js I have to include the name of this file, ex.
`import {PeopleService, AccountService} from './services/index' `

**Expected/desired behavior:**
 The index file has all the exported properties then only it should be necessary to indicate the name of the folder, ex:
`import {PeopleService, AccountService} from './services' `

* **What is the motivation / use case for changing the behavior?**

**Comment by StrahilKazlachev** [comment]
An import declaration is part of the ES specification, Aurelia has no saying in that.
If you are using the `feature` API of Aurelia, that is different, and does not reflect on the import declarations.

**Comment by Alexander-Taran** [comment]
Can be closed.. maybe

**Comment by EisenbergEffect** [comment]
Closed since the OP is describing the ECMA standard behavior for imports.
