### ISSUE TITLE
issue with repeat.for using p tags with hr inside

### ISSUE THREAD

**Issue by obedm503** [aurelia/framework#842]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
Linux (xubuntu 16.04)

* **Node Version:**
n/a

* **NPM Version:**
n/a

* **Aurelia CLI OR JSPM OR Webpack AND Version**
n/a

* **Browser:**
Chrome 62.0.3202.94 (haven't tested other)
* **Language:**
ESNext

**Current behavior:**
the repeater breaks when using a `p` tag with an `hr` tag inside it

**Expected/desired behavior:**

to not break and generate correct html
https://codepen.io/anon/pen/rYZLZB?editors=1010
using codepen because gist.run is outdated. wasn't able to test on the latest version (1.1.5) because cdnjs only has version 1.0.2, although the bug still happens on my local project using aurelia-framework 1.1.2

what caught my attention is that the same template works flawlessly if I used a `div` instead of a `p`, or if I used a `p` without an `hr` inside. the linked codepen demos several situations compared to using a `div`
* **What is the motivation / use case for changing the behavior?**
it's a bug and bugs should be fixed

**Comment by AshleyGrant** [comment]
Well, it definitely looks like a bug. @jdanyow what do you think?

**Comment by jdanyow** [comment]
It has to do with how the browser is parsing `<template><p><hr></p></template>`

Compare what the alert displays with the source html:
https://gist.run/?id=fdaeb456bcf33ff5c3d48009eea7100b

Reproduces in firefox too.

**Comment by jdanyow** [comment]
aurelia gist is up to date: https://gist.run/?id=7542e061bc940cde506b

**Comment by obedm503** [comment]
Why is this closed? Is it a browser bug then?

**Comment by StrahilKazlachev** [comment]
It's not a browser bug, you can not have [`<hr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr) inside of [`<p>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) - check *Permitted content* of `<p>` and the *Content categories* of `<hr>`. At least this is how I understand the spec.

**Comment by obedm503** [comment]
![https://memegenerator.net/img/instances/54575039/woah.jpg)

this is pretty mind blowing. but at least it's not a bug 😅
