### ISSUE TITLE
Android 4.4.2 webview issue

### ISSUE THREAD

**Issue by alexanderozerov** [aurelia/framework#844]
**I'm submitting a bug report**

* **Library Version:**
1.1.5

* **Operating System:**
Windows [10]

* **Node Version:**
8.9.1

* **NPM Version:**
5.3.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
 webpack 2.6.1

* **Browser:**
 Mobile Chrome XX | Android 4.4.2 Web Browser 

* **Language:**
 ESNext

**Current behavior:**

**Expected/desired behavior:**
I have very simple webview app (literally it consists of a gmap with some buttons). App works perfectly on Chrome and android 5 or higher but does not on android 4.4.2. . The only error i have is 
`Uncaught RangeError: Maximum call stack size exceeded", source: app.1aff1d7aac998375f47f.bundle.js`.

* **What is the motivation / use case for changing the behavior?**
In fact i dont have ant thougths what it can be. Does aurelia work on old android devices?

**Comment by AshleyGrant** [comment]
Typically, we only support the latest version of Chrome.

Is Chrome the browser that is used in a webview on Android 4.4.2?

**Comment by alexanderozerov** [comment]
App works on chrome (ver62) on android 4.4.2 too. But if I try it on default android browser it does not.

**Comment by alexanderozerov** [comment]
Solution founded in this case https://github.com/aurelia/skeleton-navigation/issues/821 .
