### ISSUE TITLE
aurelia-pal-browser doesn't isntall when installing aurelia framework as it's debpendency

### ISSUE THREAD

**Issue by amirqasemi74** [aurelia/framework#847]
Hi. 

Today I started to install Aurelia Using This command:
jspm install aurelia-framework aurelia-bootstrapper

as I started to run my project, it seem to not install aurelia-pal-browser as it's dependency

i fixed it by install it: jspm install aurelia-pal-browser

so it can be added to dependencies of framework when it's installing..

tanks

**Comment by Alexander-Taran** [comment]
bootstrapper lists pal-browser as a dependency in jspm section of package.json
https://github.com/aurelia/bootstrapper/blob/master/package.json
as far as I remember, you have to add it to config.js though, which you did by runing jspm install..

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 questionAnswered()
 let response = await getResponseFromOP( { timeout : 3weeks } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by Alexander-Taran** [comment]
Thanks @amirqasemi74
