### ISSUE TITLE
Multiline comments ignored in viewtemplate

### ISSUE THREAD

**Issue by arnonuem** [aurelia/framework#849]
**I'm submitting a bug report**

* **Library Version:**
latest

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.32.0 | webpack 3.5.5

* **Browser:**
Vivaldi 1.13.1008.32

* **Language:**
ESNext

**Current behavior:**
Comments are ignored if used like this:
```
<!--require from="./parameter/layout-parameter-add"></require>
<require from="./parameter/layout-parameter-listing"></require>
<require from="./parameter/layout-parameter-details"></require-->
```
but they are recognized when using like this:
```
<!--require from="./parameter/layout-parameter-add"></require-->
<!--require from="./parameter/layout-parameter-listing"></require-->
<!--require from="./parameter/layout-parameter-details"></require-->
```

**Expected/desired behavior:**
Both styles of commenting out code should be possible to use.

* **What is the motivation / use case for changing the behavior?**
annoying

**Comment by powerbuoy** [comment]
Multiline comments have always worked fine for me. Is it specific to `<require>` elements?

**Comment by arnonuem** [comment]
Not sure whether it is specific ONLY to these but there seems to be a problem with <require>. I have not tested every other possible command but the other ones i use seem to work.

**Comment by powerbuoy** [comment]
Multiline comments around `require` elements also work fine: https://gist.run/?id=711fd29206ad16202aa6662b6710fc61

**Comment by arnonuem** [comment]
yes but in my aurelia application they dont work if i require something which is not there yet (files are missing).
When these requirements are commented out they are still evaluated which leads to an error that the files are missing which should be ignored since they are commented out.

**Comment by Alexander-Taran** [comment]
@arnonuem can you reproduce the behavior with updated cli/webpack etc?

**Comment by Alexander-Taran** [comment]
@3cp 
```ts
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : fromYears(4) } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by 3cp** [comment]
Tested with latest skeleton, the multiline comments are ignored as expected.

```html
<template>
  <!--require from="./parameter/layout-parameter-add"></require-->
  <!--require from="./parameter/layout-parameter-listing"></require-->
  <!--require from="./parameter/layout-parameter-details"></require-->
  <h1>${message}</h1>
</template>
```

@bigopon can close this.
