### ISSUE TITLE
nested repeater failing to recognize a function in model

### ISSUE THREAD

**Issue by chandmk** [aurelia/framework#85]
Version: 0.11

//model
```javascript
export class Test{
  range(num) {
    return Array.apply(0, Array(num)).map((x,y) => y);
  }
}
```

// view
```html
<template>
  <table>
    <tr repeat.for="row of range(27)">
      <td repeat.for="col of range(17)">
        <input type="text" value="${row}${col}"</input>
      </td>
    </tr>
  </table>
</template>
```

Nested for is not recognizing the range function.

Error: range is not a function {stack: (...), message: "range is not a function"}message: "range is not a function"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: dapp-router.js:144 (anonymous function)es6-module-loader.src.js:1183 Oes6-module-loader.src.js:1142 Kes6-module-loader.src.js:930 7.y.whenes6-module-loader.src.js:821 7.v.runes6-module-loader.src.js:97 3.a._draines6-module-loader.src.js:62 3.a.draines6-module-loader.src.js:268 b

**Comment by PWKad** [comment]
When nested in a repeater you need to use `$parent.` to reference the parent context.

**Comment by EisenbergEffect** [comment]
Closing this, since @PWKad answered the question. We do hope to improve this in the future though.
