### ISSUE TITLE
BindPropertyChanged doesn't Fire

### ISSUE THREAD

**Issue by FunkMonkey33** [aurelia/framework#856]
**I'm submitting a bug report**

* **Library Version:**
"aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.1.0",

**Please tell us about your environment:**
Windows 10

* **Node Version:**
6.10.3

* **NPM Version:**
3.10.10

* **Aurelia CLI OR JSPM OR Webpack AND Version**
JSPM version 0.16.26

* **Browser:**
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* **Language:**
ES6

**Current behavior:**

If you handle the bind event in your view model, then any bindableChanged events don't fire.  This is the case even if the bind() handler is empty.

`@bindable myProperty

bind() {
  // even an empty method causes this behavior.
}
myPropertyChanged(newValue, oldValue) {
    debugger; // this method will never get called.
}
`

**Expected/desired behavior:**
Not that.  It's not really a big deal, because you probably won't ever need both bindableChanged and the bind event, but this tripped me up for several hours.  

* **What is the motivation / use case for changing the behavior?**
Save developers some time and some hair.

**Comment by StrahilKazlachev** [comment]
This is documented in the [3. bind(bindingContext: Object, overrideContext: Object)](http://aurelia.io/docs/templating/html-behaviors-introduction#html-behavior-lifecycle).

**Comment by AshleyGrant** [comment]
@StrahilKazlachev we probably could do a better job of calling this behavior out.

**Comment by bigopon** [comment]
Yes pls @StrahilKazlachev @AshleyGrant 😄

**Comment by FunkMonkey33** [comment]
I see it!  Thanks.

And yes, it could be bolder.

Thanks, guys.

Aaron

**Comment by AshleyGrant** [comment]
Done! PR Submitted

**Comment by Alexander-Taran** [comment]
PR looks legit (-:
@EisenbergEffect can you please merge it? 
or decline.. 
that would require reasoning though..
