### ISSUE TITLE
Aurelia Plunker

### ISSUE THREAD

**Issue by Aaike** [aurelia/framework#86]
The Aurelia skeleton navigation is working in Plunker !
An overview of available plunks that can be forked or used as base templates can be found [**here**](http://bit.ly/aurelia-plunker)

It can be used to reproduce a bug or show off a cool feature and communicate about it easier with the community.

**Comment by Aaike** [comment]
The Plunker version is now working with ES6 and on-the-fly compilation, thanks with help from Guy Bedford.

Anybody can now fork this plunker and use it to reproduce an error and communicate about it easier with the community.

**Comment by Aaike** [comment]
Here is an emptier version of the skeleton without a router. it only uses the app.js and app.html.
Might be better for some situations to test bugs or show off a feature.

http://plnkr.co/edit/sak5db

**Comment by EisenbergEffect** [comment]
Very cool stuff. What is involved in keeping this up to date as we do releases? How can we make this easy for the community to leverage?

**Comment by Aaike** [comment]
Plunker keeps a version history, so the plunker can be updated with new releases and users can still choose which version to fork, but it will default to the latest version.

And the only thing that needs to be updated with a new Aurelia release is the bundled version of Aurelia.
i'm keeping that in a distribution repository : https://github.com/distros/aurelia

I will add a package.json to it and the Aurelia license and readme etc... and tag a release for it as 0.12.0

When a new version is released a new bundle has to be made and new version tagged in that repository.
That's it !

**Comment by jdanyow** [comment]
updated link ^^^ to latest version, formerly `http://plnkr.co/users/Aaike`
