### ISSUE TITLE
possibility to render specific children passed to a component

### ISSUE THREAD

**Issue by jauniuse** [aurelia/framework#863]
**I'm submitting a feature request**

* **Library Version:**
1.1.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.4

* **NPM Version:**
5.5.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
webpack 2.3.3

* **Browser:**
all

* **Language:**
all

**Current behavior:**

Let's say I have a class called Wizard which accepts children:

```js
@inlineView(`
  <template>
     <slot></slot>
  </template>
`)
export class Wizard {
   @children('page') pages: Page[];
}
```

Page class looks like following:

```js
@inlineView(`
  <template>
     <slot></slot>
  </template>
`)
export class Page {
   @children('*') content: any;
}
```

If I use `Wizard` like below:

```html
<wizard>
    <page>
        <custom-element />
    </page>
    <page>
        <another-custom-element />
    </page>
</wizard>
```

in `Wizard`s` template I would like to render only one page instead of rendering all, ie something like this:

```html
 <div repeat.for="page of pages">
    <div if.bind="$first">
         <!-- render first page here -->
    </div>
</div>
```

instead of rendering all the passed pages in the place of `<slot></slot>`. It does not seem to be possible to do such thing currently, tried different approaches.

* **What is the motivation / use case for changing the behavior?**
This would be a nice to have feature since one can do a lot of cool things with it. One example is the `Wizard` above, with such feature possible to be done, one could add all pagination related functionality and ui to `Wizard` and the user of `Wizard` would not have to care about that at all.

**Comment by bagl** [comment]
I have no idea how to do it the "Aurelia way", but you can still go with the pure JS way:

```typescript
@inlineView(`
  <template>
     <slot></slot>
  </template>
`)
export class Wizard {
   @children('page') pages: Page[];
   pageIndex: number = 0;

   attached() {
       this.pages.forEach(e => e.hidden = true);
       this.pages[this.pageIndex].hidden = false;
   }
}
```

and go from there.

**Comment by AshleyGrant** [comment]
I'm on mobile and have a rather full day ahead of me, but I'd probably initially approach this using replaceable parts instead of slots. If that didn't work satisfactorily, I'd switch to some direct HTML manipulation using the `processContent` decorator, passing it a function to process everything.

**Comment by jauniuse** [comment]
HTML manipulation using `processContent` would work for me. Is it possible to access class props in `processContent `? I would need to access `currentPageNumber` prop from `Wizard` class.

**Comment by AshleyGrant** [comment]
Actually, now that I'm looking at this again and not on mobile, I want to completely change my advice. Check out this blog post: http://www.foursails.co/blog/semantic-template-parts/ for a good way to go about doing this.

**Comment by jauniuse** [comment]
thanks for the answer

using template parts would make it complicated to use the `wizard` api for its consumer imho. Of course, it could be properly documented, but I will think about a different solution :)

**Comment by Alexander-Taran** [comment]
@jauniuse could this be closed?

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 askOpIfCanBeClosed()
 let response = await getResponseFromOP( { timeout : someTime } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by EisenbergEffect** [comment]
Closing since this is more of a question for how to accomplish something, with several answers provided. Further discussion should take place on Discourse.
