### ISSUE TITLE
Changing "Binded Style Object" On Element does not cause style changes on element

### ISSUE THREAD

**Issue by amirqasemi74** [aurelia/framework#864]
Hi.
here in this document page in aurelia website ( http://aurelia.io/docs/binding/class-and-style ) has been mentioned that we can bind a style as Object to an element. it works fine but when your are going to change one object property, it dost not apply in element style... but a string works...

i am wondered why change object property does not cause to aurelia rerender style of that element...

**Comment by AshleyGrant** [comment]
I'm not exactly sure what you are asking. Please do two things to help us out. 
1. follow the issue template when you submit your issue, as we close all issues that do not follow this template (including this one)
2. Provide a [gist.run](https://gist.run/?id=6ad573e051f53c8e163d36dc31dc36b6&sha=cd64e3040dfd964b8c92e9dce868a832b0b32c20) or similar runnable example of what you are asking.

**Comment by amirqasemi74** [comment]
this is runnin App: 
https://gist.run/?id=1367379c93e787974fca01796290588b

this is the issue...

i also know that there are other way to solve this But this is a question for me why this state not Working!

**Comment by StrahilKazlachev** [comment]
Because what is being observed is *only* the property `style`, *not* what is inside the *value* of property `style`.

**Comment by amirqasemi74** [comment]
If the property 'style' only is being observed, So why when i change the 'color' property, DOM  is being rerenderd?

**Comment by StrahilKazlachev** [comment]
> DOM is being rerenderd?

If you mean `<p>h1 tag Color: ${style.color}</p>`, that is because you are binding against `style.color` - a chain, now both `style` and `color` properties are being observed for thatspecific binding.

**Comment by amirqasemi74** [comment]
I understood why....!
Thanks

**Comment by Alexander-Taran** [comment]
can be closed
