### ISSUE TITLE
Links in backers.md do not work

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/framework#867]
**I'm submitting a bug report**
Links in backers.md do not work

**Current behavior:**
most of the links are relative and lead to githubs 404

**Expected/desired behavior:**
links to profiles should work as expected

* **What is the motivation / use case for changing the behavior?**
decrease frustration and improve worlds order (-:

fixed by https://github.com/aurelia/framework/pull/866

**Comment by EisenbergEffect** [comment]
Thanks!
