### ISSUE TITLE
Consider moving aurelia-open-id-connect in to the Aurelia organization

### ISSUE THREAD

**Issue by shaunluttin** [aurelia/framework#872]
@AshleyGrant suggested that I open an issue here. It's about moving the https://github.com/shaunluttin/aurelia-open-id-connect repository in to the Aurelia organization. I have had less time recently to work on it, and we thought it might receive more attention if it were to live here instead.

**Comment by AshleyGrant** [comment]
He's right. I told him to file this issue. I want to start the conversation on whether we'd like to support this.

Thoughts?

**Comment by AshleyGrant** [comment]
Also, I gave him explicit permission to ignore the issue template.

**Comment by AshleyGrant** [comment]
That sounds like a good idea.

**Comment by Alexander-Taran** [comment]
@shaunluttin ping me, If you decide to move your repo to contrib.
I'll send you invite to organization.
Note that I'm not related in any way to core team.

**Comment by shaunluttin** [comment]
@Alexander-Taran We have decided to move the repo to contrib to improve visibility and collaboration.

**Comment by Alexander-Taran** [comment]
@shaunluttin l'invitation est envoyée.

**Comment by shaunluttin** [comment]
You're responsive. I've gone ahead and transferred ownership of the repository to aurelia-contrib.

**Comment by shaunluttin** [comment]
Question: Where do you think the demos should live? 

https://github.com/shaunluttin/aurelia-open-id-connect-demos

**Comment by Alexander-Taran** [comment]
@shaunluttin you mean iclude them in main repo or?
I think they should be close to the source.. and there should be a link to them in main.

**Comment by shaunluttin** [comment]
> @shaunluttin you mean iclude them in main repo or?

What I meant was that I think it would be good to move https://github.com/shaunluttin/aurelia-open-id-connect-demos in to the aurelia-contrib organization. Thoughts?

**Comment by Alexander-Taran** [comment]
@shaunluttin I think so too. They belong together.

from gitter:
*Veikko Eeva*  09:51
Alexander-Taran aurelia/framework#872 has been a sore point in the story. Demos needed for this, together with more advanced routing.

**Comment by Alexander-Taran** [comment]
main repo transfered:
demoes will follow, I guess.
can be closed.

@shaunluttin I guess there is a question of npm package. we probably should organize some credentials for contrib org. If you can walk me through this.

this issue can be closed

**Comment by shaunluttin** [comment]
Here is where the existing NPM packages live: 

https://www.npmjs.com/~shaunluttin
