### ISSUE TITLE
Array of string changes not trggering.

### ISSUE THREAD

**Issue by AbinayaSubbiah** [aurelia/framework#873]
Hi all

M not able to get array ite changes in my aurelia `propertyChange`  in custom component template

refer below link for demo

https://gist.run/?id=a6a17f6f9646c3f63149a71cb2d8656d

**Comment by Alexander-Taran** [comment]
duplicates https://github.com/aurelia/binding/issues/670

**Comment by Alexander-Taran** [comment]
can be closed
