### ISSUE TITLE
Package causes 'Out of stack space' error with IE11

### ISSUE THREAD

**Issue by johannes-maierhofer** [aurelia/framework#877]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
8.2.1

* **NPM Version:**
5.6.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.31.3

* **Browser:**
IE 11

* **Language:**
TypeScript

**Current behavior:**
Adding the package '@ aspnet/signalr-client' to the project causes an 'Out of stack memory' error in IE11. Chrome and Firefox are fine.

I reproduced this by simply setting up a sample CLI project (typescript with require.js) and referencing a class from that package. I include this very sample.
[test-require-1.zip](https://github.com/aurelia/framework/files/1884930/test-require-1.zip)

**Expected/desired behavior:**
Well. It's supposed to work, I guess. The reason why it doesn't is a complete mystery to me.

**Comment by Alexander-Taran** [comment]
please read this issues for hints
https://github.com/aurelia/skeleton-navigation/issues/821
https://github.com/aurelia/cli/issues/843

**Comment by johannes-maierhofer** [comment]
Thanks for the hints. I had seen them before.

As for missing polyfills, the example is a new project, and it includes the 'aurelia-polyfills' dependency per default. That seems to be what fixed it in the hints you sent. Could there be other polyfill missing? Which ones?

Another thing that might be relevant. The package in question has different versions. The default one is ES6. That doesn't work with IE11. So I referenced the ES5 version. That's the one causing the 'Out of stack space' error with IE11.

**Comment by Alexander-Taran** [comment]
side note.. @aspnet/signalr-client is just @aspnet/signalr now.

**Comment by johannes-maierhofer** [comment]
The new @aspnet/signalr library does not have that issue.

The reason why I use the older one is that it works with the current ASP.net Core server side version (2.0). The newer one (2.1) is still in preview only. Once it is released, I will switch. That hopefully will be before we have to release our app. In that sense, the issue for me hopefully is solved.

Still, I have no idea why this is happening. Even worse, with issues like these I don't even know where to start. In the end, problems related to adding packages were the most frustrating for me so far (wrong/missing typescript definitions, problems with require.js, using the correct syntax importing/referencing packages etc.).

**Comment by Alexander-Taran** [comment]
signalr as far as i know is not released at all.. But if server side package targets 2.1 then you are out of luck.
I'd suggest you ask David Fowler @ aspnet team on how to proceed

**Comment by johannes-maierhofer** [comment]
Thanks. This is good enought for me. Will have to switch to the new library sooner or later anyways.

**Comment by Alexander-Taran** [comment]
@johannes-maierhofer this one can be closed then?

**Comment by johannes-maierhofer** [comment]
That is up to you. For me personally, I have a solution. I will (later) switch to the newer package. Still it would have been good to know why this happens.

**Comment by Alexander-Taran** [comment]
can be closed
