### ISSUE TITLE
Aurelia and Vis

### ISSUE THREAD

**Issue by ilyasOne** [aurelia/framework#878]
Hi, 
i'm new in Aurelia and have a question about third party library useage.
i'll use http://visjs.org/ library and facing with different issues.

Can someone make a simple Aurelia example with a vis.network? 
http://visjs.org/examples/network/basicUsage.html

After installing with "npm install vis" 
Importing the vis library does not work !? Error look like below.
========== begin error=============
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:9000/dist/vis.js Failed to load resource: the server responded with a status of 404 (Not Found)
aurelia-logging-console.js:54 ERROR [app-router] Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/dist/vis.js
	Error: XHR error (404 Not Found) loading http://localhost:9000/dist/vis.js
	Error loading http://localhost:9000/dist/vis.js as "vis" from http://localhost:9000/dist/core/about/about.js
:9000/dist/vis.js Failed to load resource: the server responded with a status of 404 (Not Found)
aurelia-logging-console.js:54 ERROR [app-router] Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/dist/vis.js
	Error: XHR error (404 Not Found) loading http://localhost:9000/dist/vis.js
	Error loading http://localhost:9000/dist/vis.js as "vis" from http://localhost:9000/dist/core/about/about.js
========== end error=============

Any help is welcome.

**Comment by ilyasOne** [comment]
this can be removed.

**Comment by Alexander-Taran** [comment]
@ilyasOne care to share your own answer?

**Comment by ilyasOne** [comment]
Yes, sure. 
After installing with "npm install vis" you have to install it also with jspm as folow "jspm install npm:vis" this cause for registration in config.js file. Otherwise Aurelia comes with error "Can not find resource  ../dist/vis.js".

Thus run:

npm install vis
jspm install npm:vis

For the visualization of it you have to create an Div Attribute  element and call it from the code-behind, it works. Div Atrribute our idea because things like DOM getElementById() etc will not work in Aurelia concept.

Thus do: 

Create an Div tag Attribute element with use of Aurelia Element and call it form the js code-behind.


I hope this is clear so, if not please contact.

**Comment by Alexander-Taran** [comment]
great. It would probably just work with just `jspm install` unless you use typescript.. and npm package got typings in it. then it's a nice hack (-:
for referencing elements there are some tricks.
you can inject Element into attribute constructor
http://aurelia.io/docs/fundamentals/cheat-sheet#custom-attributes

or you can use `ref` custom attribute on some tag in your view to get a reference in your view-model
http://aurelia.io/docs/binding/basics#referencing-elements

**Comment by Alexander-Taran** [comment]
@ilyasOne that's weird.. because jspm downloads the package.. and I bet that the bundler picks the jspm one.. Still confident that npm only helped with typing.

**Comment by Alexander-Taran** [comment]
@bigopon can be closed
