### ISSUE TITLE
The attached method is firing before a component's HTML is actually in the DOM

### ISSUE THREAD

**Issue by martynchamberlin** [aurelia/framework#880]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.0

* **NPM Version:**
5.5.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
JSPM 0.16.47

* **Browser:**
all 

* **Language:**
ESNext

**Current behavior:**
The `attached()` method for components is firing before the HTML within them finishes mounting. Let's say I have an HTML component called `login.html` that looks like this:

```html
<!-- login.html -->
<template>
  <div class="form-control">
    <input type="text" id="username" />
  </div>
</template>
```

And then let's say I try to do this in the component: 

```js
// login.js
export class Login { 
  attached() {
    this.makeADomReference();
  }

  makeADomReference() {
    // logs "null" to the console because input#username
    // isn't actually in the DOM yet. This to me is a bug.
    console.log(document.getElementById('username'));
  }
}
```

We're seeing this behavior in a production context on (1) slower computers or even (2) faster computers with resource-heavy components. As a hack, for things that we want to occur as soon as the component gets attached, I'm having to use a scheduler, something like this: 

```js
// login.js
export class Login { 
  attached() {
    this.enqueueADomReference();
  }

  enqueueADomReference() {
    if (!document.getElementById('username')) {
      return setTimeout(this.enqueueADomReference.bind(this), 100);
    }
    this.makeADomReference(); 
  }

  makeADomReference() {
    // logs the expected DOM object
    console.log(document.getElementById('username'));
  }
}
```

**Expected/desired behavior:**
When `attached()` gets fired, all of the native HTML elements that reside in the component template should be attached and accessible. 

Notice that I'm specifically mentioning _native_ HTML elements. Custom Aurelia components needn't be attached yet per se. To use an example from another framework, VueJS sometimes calls a component's `mounted()` method (VueJS' equivalent to Aurelia's `attached()` method) on a parent Vue component before a child component's, and sometimes vice versa. In my year+ experience in Vue I've seen both situations. To me that's not a big deal. The big deal here is that the _native_ elements should all be there before `attached()` gets called. 

* **What is the motivation / use case for changing the behavior?**
If you're using anything like http://formvalidation.io then you need to talk directly to the DOM and you have a certain amount of setup that you want to do as soon as the DOM is ready. That was the whole point of having an `attached()` event but it's not behaving as expected.

Thanks!

**Comment by AshleyGrant** [comment]
What happens if you use the `ref` attribute instead of `document.getElementById`?

**Comment by AshleyGrant** [comment]
Also, just to check, the current release of the framework is `1.2.0` does this behavior happen in `1.2.0` or only in `1.0.0`?

**Comment by martynchamberlin** [comment]
Good questions. Regarding the `ref` question, it happens when using that as well, in terms of wrapping it in a jQuery object. If I have a `ref="username"` then I cannot access it like so in the ViewModel:

```js
$(this.username)
```

I'm checking to see if this exists in 1.2.0 or not...

**Comment by AshleyGrant** [comment]
@martynchamberlin if there's any chance you can conjure up a simple repro, that'd be awesome. @EisenbergEffect looks like we need to have @jdanyow and others give this one a look.

**Comment by martynchamberlin** [comment]
You know... I think I've been wasting ya'lls time on this one. I looked at our specific example more closely and we have a `if.bind` at the root of the component, which returns `true` once some data from a callback arrives. That explains why a hard page reload catches the problem whereas coming to it from elsewhere does not. Sorry for the confusion. I think it's safe to close this one.

**Comment by martynchamberlin** [comment]
I think I might have been a little bit premature here, but time will tell. 

We have two components. One in which that aforementioned `if.bind` was the holdup. The other in which this problem manifests itself does not have a `if.bind` anywhere in the component. We have some `show.bind` going on but that shouldn't cause this. 

This second problematic component only has this bug in Edge on a old, slow Surface edge in a production context using Aurelia 1.0.0. In other words, I don't have an easy way to replicate the problem using Aurelia 1.2. But as far as I can tell, this bug did indeed exists in Aurelia 1.0.0 though it may be hard to tease out except in an involved app and in a production context, and it may be unique to Edge as well. 

If I ever get more information on this, I'll weigh in here, thanks.

**Comment by AshleyGrant** [comment]
Do you have any other template controllers in the view containing the component? Maybe it's inside a `repeat.for`?

**Comment by martynchamberlin** [comment]
Not quite sure I'm following. Do you have a concrete example? 

If I had a component that looked like this, I'd expect `#username-0` to be immediately accessible upon `attached()`. That's the case, isn't it? Not following why a `repeat.for` would impact this, assuming `users` is immediately present upon the construction of the input. 

```html
<template>
  <div class="form-control" repeat.for="user in users">
    <input type="text" id.bind="`username-${$index}`" />
  </div>
</template>
```

We don't have a `repeat.for` in this particular case, for the record.

**Comment by doktordirk** [comment]
I'm having the same issue. (chrome currrent)

```
<button class="list-dropdown dropdown-toggle" 
    data-toggle="dropdown" 
     ref="dropdown">
...     
attached() {
  $(this.dropdown).dropdown(); // this.dropdown undefined  
  $('.dropdown-toggle').dropdown(); // not any better
}
```
with a breakpoint there, it is clearly visible in the browser, that nothing got attached yet

has no repeat.for, but does have an if.bind, hmm
