### ISSUE TITLE
Aurelia router documentation never mentions the need of PLATFORM.moduleName

### ISSUE THREAD

**Issue by johot** [aurelia/framework#883]
I got really stuck trying to make the router work now that the aurelia-cli uses WebPack.

Nowhere in the official router documentation is it mentioned that you need to wrap your `moduleId` part with `PLATFORM.moduleName(...)`.

I understand that everyone might not use webpack yet but are there any plans to adress this? I guess someone new to aurelia would get stuck very fast.

**Comment by greensponge** [comment]
I sent a pull request to aurelia/router where I attempted to provide that documentation here: [PR 594](https://github.com/aurelia/router/pull/594)

Let me know how I can assist in getting the request merged if it's not fully up to standards.

**Comment by AshleyGrant** [comment]
@davismj would please review the linked docs PR

**Comment by AshleyGrant** [comment]
@greensponge I just discovered your dotnet aurelia template. I'm gonna be playing with it this afternoon as it just so happens to be exactly what I am working on this afternoon for a client.

**Comment by greensponge** [comment]
@AshleyGrant Great if you find it useful! If you find any issues with it let me know. I'm very interested in keeping this particular repository up to date, as I use this type of project setup all the time for my projects. 👍

**Comment by davismj** [comment]
@EisenbergEffect can be closed
