### ISSUE TITLE
Aurelia: command not found?

### ISSUE THREAD

**Issue by teskonetic** [aurelia/framework#887]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
Operating System:
OSX 10.13.4

Node Version:
v8.11.2

NPM Version:
5.6.0

Aurelia CLI OR JSPM OR Webpack AND Version
aurelia-cli@0.33.1

Browser:
Safari: Version 11.1

Language:
both in TypeScript X.X  and ESNext

IDE: Sublime text, visual studio code, 
Current behavior:

Aurelia CLI was installed with this command globally and got its version: 
$ sudo npm install -g aurelia-cli

once you do all these above you see the versions installed in your local machine. All requirements and versions of apps are met (installed). But when you run this below command from terminal, it returns "command not found":
$ au -v
$ -bash: aurelia: command not found

Besides, other commands like I tested with au run or au --help, none of them works too

Expected/desired behavior:

brings an option that enable you to create a new Aurelia project or

**Comment by teskonetic** [comment]
Hi Alexander;

Thank you for your reply. I entered "au run" , and the response was
"command not found". Though i did many researches, none of the
recommendations helped me out

Thnaks again

**Comment by elmt1** [comment]
@teskonetic  you can install Aurelia CLI. One common way to do that is to run npm install -g aurelia-cli. That will install aurelia-cli globally.

There are a few books available that should give you a better learning experience than github issues and Google, and I believe some like [this one](https://www.syncfusion.com/ebooks/aurelia_succinctly) may be free.

**Comment by teskonetic** [comment]
Hi Alexander;

Yeah, I tried all these and gave up. Thanks though for your effort. I
prefer now to use other tools instead

Sincerely

**Comment by AshleyGrant** [comment]
Did you try restarting your bash editor? (shouldn't be necessary but who knows)

Also, is it possible for you to run `npm install -g aurelia-cli` without the `sudo`?

**Comment by teskonetic** [comment]
thanks Ashley, I did every thing you said but nothing helped me out!

**Comment by AshleyGrant** [comment]
In that case, I would recommend maybe uninstalling and then reinstalling Node and NPM on your computer. Just please understand that the issue you are having is with either Node, NPM, or your computer's PATH variable and not with the Aurelia CLI or Framework.

**Comment by paolocarrasco** [comment]
My two cents: maybe it was because of the fact that the installation of the aurelia-cli was performed using sudo: https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

**Comment by teskonetic** [comment]
I did all these things; install and uninstall, thanks

**Comment by teskonetic** [comment]
Hi Paolo;

with the link you provided, I installed and run on terminal. the most part
seemed working good, but when i run this:

npm list -g --depth=0


i got this below error message. do you have any suggestions?

└──  error: ENOENT: no such file or directory, stat
'/Users/chung/.npm-packages/lib/node_modules/npm


npm ERR! error in /Users/chung/.npm-packages/lib/node_modules/npm: ENOENT:
no such file or directory, stat
'/Users/chung/.npm-packages/lib/node_modules/npm'


Best

**Comment by paolocarrasco** [comment]
I see. There was an update in the link, now I realize. There is an easier path without using brew (it is similar to the [second option suggested by NPM](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory)):

- Install Node.js from https://nodejs.org/en/download/
- Update to the latest version of npm: `npm install npm -g` (don't use sudo)
- Make a new folder for the npm global packages: `mkdir ~/.npm-packages` (don't use sudo)
- Tell npm where to find/store them: `npm config set prefix ~/.npm-packages` (this is the most important step)

After this, it should work the last command and the CLI could be installed globally.

**Comment by teskonetic** [comment]
Thank you for your time again. Nothing changed. Am done and not interested
anymore in this framework, it's so so outrageous !. This framework is at
early stage of development and i don't recommend to use it for anyone. I do
write my bad experience and review on the founders page too.

Best

**Comment by EisenbergEffect** [comment]
@teskonetic I'm sorry to hear about your bad experience. However, the issues you have experienced are in no way related to Aurelia. They are issues with Node/NPM or with your machine's configuration. I highly recommend that you seek a solution to the root problems, otherwise, you are likely to have many issues like this with many frameworks and libraries in the future.

**Comment by DavidBawden1** [comment]
I had this issue, You need to add Aurelia to your PATH as the npn install aurelia-cli -g command does not do this for you. the Install dir will be something like C:\users\user\appdata\roaming\npm

**Comment by AshleyGrant** [comment]
@DavidBawden1 if the `npm` global install folder is not added to your path when you install Node, then I would recommend reinstalling Node. Also, sometimes Windows can require a reboot to recognize newly added paths on the PATH variable. In either case, these are issues with Node/NPM and not Aurelia.
