### ISSUE TITLE
Using Aurelia native modules

### ISSUE THREAD

**Issue by pragmaproducts** [aurelia/framework#892]
I would like to use the standard <script type="module"> as supported in the browser along with Aurelia.
I am looking for ways to get rid of bundlers and external module loaders in favor of the default browser.

I noticed you have a native modules folder but the inter dependencies does not use relative pathing. Because of this you can't use it in module scripts.

So this is both a how do I and a bug.
It's a bug in the sense that aurelia supposes a external module loader such as webpack, jspm or requirejs.
It is a how do I in that I am hoping there is a way to use Aurelia with just native browser supported features and I just don't know how.

Any assistance you may provide would be greatly appreciated.

**Comment by StrahilKazlachev** [comment]
Can you be more specific with * inter dependencies*?

**Comment by pragmaproducts** [comment]
If I want to initialize aurelia currently I do something like this.

```js
    <script async>
        function jspmLoaded() {
            System.import('aurelia-bootstrapper');
        }
    </script>
```

but what I want to do is this

```js
<script type="module">
    import from 'path to aurelia'
</script>
```
the problem here is that the module resolver has to have relative paths. e.g.
"/" or "./" ...

and this counts for inter dependencies also.
When aurelia refers to it's internal dependencies it does it like this.

```js
import { Loader } from 'aurelia-loader';
```

What the browser expects is the actual path including the extension

```js
import { Loader } from './../aurelia-loader.js';
```

It's simple to reproduce,
After installing aurelia-framework with npm, in your index.html file do the following

```html
<body>
    <script type="module">
        import * as aurelia from "./node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js";
    </script>
</body>
```
When you run it, you will get this

```
Uncaught TypeError: Failed to resolve module specifier "aurelia-logging". Relative references must start with either "/", "./", or "../".
```

**Comment by pragmaproducts** [comment]
https://discourse.aurelia.io/t/module-resolver-for-aurelia-packages/1233

**Comment by bigopon** [comment]
I think this is only related to how native import works, there is no module resolution. @pragmaproducts Please have a look at Aurelia script, which helps simplify similar usage like this https://github.com/aurelia/script

**Comment by bigopon** [comment]
@EisenbergEffect I think this can be closed
