### ISSUE TITLE
JSPM throws 'no version match found' on repos specifying dependencies containing multiple versions separated with '||'

### ISSUE THREAD

**Issue by bfil** [aurelia/framework#895]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
10.1.0

* **NPM Version:**
6.0.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all

* **Language:**
all

**Current behavior:**

`jspm install` started failing and throwing a `no version match found` error when resolving some of the aurelia dependencies, this started yesterday and it is happening for the following repositories:
- `aurelia-templating-binding`
- `aurelia-validation`

The reason seems to be that JSPM does not support version formats such as `^1.0.0 || ^2.0.0`, here's the examples I have of recent changes that caused this issue:

https://github.com/aurelia/validation/commit/2bf17ed92274298955789c38e6b6096c3e2c63f9#diff-0a08a7565aba4405282251491979bb6bR20

https://github.com/aurelia/templating-binding/commit/331746878939f43caf2f76377a424e2b22c799b5

I thought it would be worth raising this in the main framework repo rather than each individual one before the pattern spreads across a bunch of different repos.

This might be a jspm issue more than an aurelia issue, but it would be great to avoid breaking the skeletons as well and causing problems to everyone trying to use the framework.

The only solution is to fix the jspm dependency to the version before these changes have happened.

**Expected/desired behavior:**
`jspm install` should be able to resolve aurelia's dependencies.

**What is the motivation / use case for changing the behavior?**
`jspm install` used to work just fine and going forward this would prevent developers using jspm from updating their aurelia dependencies.

**Comment by wouth** [comment]
Seems that jspm doesn't support the || syntax.
https://gist.github.com/hmps/995583ff1c8755d5f795 states 'Remember that JSPM only supports the ranges specified above.'.

**Comment by bulldetektor** [comment]
There's a similar issue raised on JSPM's Github repo; https://github.com/jspm/jspm-cli/issues/2406

**Comment by AquilaSands** [comment]
I ran into this issue when trying to update some of the Aurelia packages. I managed to work around it by adding JSPM overrides for the affected package's dependencies to package.json in the `jspm` section.

    "overrides": {
      "npm:aurelia-framework@1.3.0-rc.2": {
        "dependencies": {
          "aurelia-binding": "^2.0.0",
          "aurelia-dependency-injection": "^1.0.0",
          "aurelia-loader": "^1.0.0",
          "aurelia-logging": "^1.0.0",
          "aurelia-metadata": "^1.0.0",
          "aurelia-pal": "^1.0.0",
          "aurelia-path": "^1.0.0",
          "aurelia-task-queue": "^1.0.0",
          "aurelia-templating": "^1.8.0-rc.1"
        }
      },
      "npm:aurelia-templating-binding@1.4.2": {
        "dependencies": {
          "aurelia-binding": "^2.0.0",
          "aurelia-logging": "^1.0.0",
          "aurelia-templating": "^1.3.0"
        }
      },
      "npm:aurelia-templating@1.8.0-rc.1": {
        "dependencies": {
          "aurelia-binding": "^2.0.0",
          "aurelia-dependency-injection": "^1.0.0",
          "aurelia-loader": "^1.0.0",
          "aurelia-logging": "^1.0.0",
          "aurelia-metadata": "^1.0.0",
          "aurelia-pal": "^1.0.0",
          "aurelia-path": "^1.0.0",
          "aurelia-task-queue": "^1.1.0"
        }
      }
    }

I did end up with a few forks I had to manually resolve.

**Comment by bigopon** [comment]
@EisenbergEffect @bfil @wouth @bulldetektor Probably we can close this, all core packages has been updated to work with JSPM. It would be awesome if anyone having issues still could update this or open a new one.
