### ISSUE TITLE
Change Website Search "not found" default text

### ISSUE THREAD

**Issue by gasolinewaltz** [aurelia/framework#898]
**I'm submitting a feature request**

**Current behavior:**
When searching the docs, when something isn't found the following text is displayed:

> Inconceivable!
> Looks like we couldn't find a matching result for "...".
> 

**Expected/desired behavior:**

Something more helpful, given the state of the docs.

* **What is the motivation / use case for changing the behavior?**

The Aurelia framework is so poorly documented that it insults my intelligence to read "inconceivable" on a daily basis. 

**Idea: make updating docs a required part of submitting pull requests** 

I say this as a senior dev working full-time on an enterprise app built with Aurelia. If the docs don't get better I'll be suggesting we move to react for future apps.

**Comment by EisenbergEffect** [comment]
@gasolinewaltz Thanks for your feedback. We hear a wide variety of feedback on our documentation. Some community members think we have the best docs they've used. Others hold an opinion that they need significant work. What we need from you is more concrete information on what you want us to add or change. We could go and do a lot of work, but if it doesn't meet your needs, then it would just be a waste of our time.

I'm closing this issue but feel free open up other issues on specific library issues detailing what we should add to the docs for that particular library.
