### ISSUE TITLE
Documentation Repository

### ISSUE THREAD

**Issue by kaleb** [aurelia/framework#9]
Where do I submit pull requests to fix some mistakes in the documentation? I cannot seem to find a aurelia.github.io repo.

**Comment by Serhioromano** [comment]
Speaking of documentation, why do not we use github wiki for that? I think that would be awesome to have all in one place like docs, issues, sources, releases, ... And with a little of work github wiki may be very convenient way to support and use documentation. 

Of course there should be generated documentation from the course, but that is different. I am talking about user documentation.

**Comment by EisenbergEffect** [comment]
We are working on a robust solution for long term :) Stay tuned.

On Wed, Jan 28, 2015 at 9:32 PM, Sergey Romanov <notifications@github.com>
wrote:

> Speaking of documentation, why do not we use github wiki for that? I think
> that would be awesome to have all in one place like docs, issues, sources,
> releases, ... And with a little of work github wiki may be very convenient
> way to support and use documentation.
>
> Of course there should be generated documentation from the course, but
> that is different. I am talking about user documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/framework/issues/9#issuecomment-71958705>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by EisenbergEffect** [comment]
We've got a temporary documentation repository now: https://github.com/aurelia/documentation
