### ISSUE TITLE
Possible issue binding to Maps

### ISSUE THREAD

**Issue by Dris101** [aurelia/framework#90]
The docs indicate that one can bind to an ES6 Map using
```code
<ul>
  <li repeat.for="[id, customer] of customers">${id} ${customer.fullName}</li>
</ul>
```
When I try it I find that no matter what you use for the second identifier in the destructuring bind before the `of`, you have to use ${value} in the binding and the identifier you used remains undefined.

**Comment by EisenbergEffect** [comment]
@martingust Can you look into this please?

**Comment by martingust** [comment]
@Dris101 @EisenbergEffect This should now be fixed in https://github.com/aurelia/templating-resources/pull/40.
