### ISSUE TITLE
Template binding: Internet Explorer does not support interpolation.

### ISSUE THREAD

**Issue by Germanaz0** [aurelia/framework#903]
**I'm submitting a bug report**

I am new into aurelia and I was debugging a project based on aurelia, I am having some issues regarding the browser, but I do not know where to look to fix this error.

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
v8.11.2

* **NPM Version:**
5.6.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.33.1 | aurelia-webpack-plugin 3.0.0-rc.1 | webpack 4.1.1

* **Browser:**
Chrome  67.0

* **Language:**
ESNext

**Current behavior:**

On browser I am having a console log info which says the following message:

```
INFO [templating-binding] Internet Explorer does not support interpolation in "style" attributes.  Use the style attribute's alias, "css" instead.
```

**Expected/desired behavior:**

I would like to give IE support to the project

**Comment by AshleyGrant** [comment]
Use the `css` attribute instead of `style`. That's what the error message tells you to do. If you use `css`, then IE works great with Aurelia.

**Comment by Germanaz0** [comment]
That's the problem, I have no style attribute into my HTM, but I do have `css`, for example:

```
<... css="border-top-color:${colors[item.sTypeCurie].barColor};border-top-width:3px"  .../>
```
