### ISSUE TITLE
[Question] Aurelia routing without hash

### ISSUE THREAD

**Issue by Germanaz0** [aurelia/framework#904]
Hello, I am using the latest stable version of aurelia with webpack, my question is the next one, on angular 1.4 I was able to has the routings without the "hash" (#). for example the route `/#/contacts ` would be `/contacts`.

Is that even possible using Aurelia ?

**Comment by weagle08** [comment]
You need to configure push state: https://aurelia.io/docs/routing/configuration#options

**Comment by Alexander-Taran** [comment]
Can be closed
