### ISSUE TITLE
Aurelia-router.d.ts is not a module error.

### ISSUE THREAD

**Issue by azaharafernandezguizan** [aurelia/framework#908]
I have just created a new Aurelia project with Aurelia.cli and I am trying to implement Aurelia routing following the official documentation. 
But when I do the import:

import {RouterConfiguration, Router} from 'aurelia-router';

it gives me this error:

[ts] File '../dist/aurelia-router.d.ts' is not a module.  

Anyone knows how to solve this issue?

**Comment by StrahilKazlachev** [comment]
Please follow the issue template. We do need the info from it, like TS version, loader/bundler, cli version, ...
Also do you get this error in the editor or during compilation?

**Comment by Alexander-Taran** [comment]
@azaharafernandezguizan and exact steps how you end up there as well. Please.

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : 4weeks } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```
