### ISSUE TITLE
AMD generated not that correctly

### ISSUE THREAD

**Issue by kanvuduc** [aurelia/framework#91]
@EisenbergEffect I think the AMD generator isn't working well. 

**AMD code**
```javascript
var _defaults = function (obj, defaults) { 
    var keys = Object.getOwnPropertyNames(defaults); 
    for (var i = 0; i < keys.length; i++) { 
        var key = keys[i]; 
        var value = Object.getOwnPropertyDescriptor(defaults, key); 
        if (value && value.configurable && obj[key] === undefined) { 
            Object.defineProperty(obj, key, value); 
        } 
    } 
    return obj; 
};
```

**SystemJS code**
```javascript
for (var _key in _aureliaDependencyInjection) {
    _export(_key, _aureliaDependencyInjection[_key]);
}
```
There is no check of  **configurable** in SystemJS, but there is in AMD, so there are no property exported for AMD as there are in SystemJS.

Curiously, is there a reason for exporting properties from other modules in this module? *(Sr, I don't know where to ask)*

**Comment by EisenbergEffect** [comment]
We discovered this issue recently. The next release should have aMD fixed.
Regarding re-exporting, the purpose of that is to define the public API. So, only things exported from the index are intended to be imported by consumers.

**Comment by EisenbergEffect** [comment]
Fixed in next release.
