### ISSUE TITLE
Downloadable "basic project" zip doesn't work on Linux.

### ISSUE THREAD

**Issue by trondhindenes** [aurelia/framework#911]
I Downloaded this url http://aurelia.io/downloads/basic-aurelia-project.zip from here: https://aurelia.io/docs/tutorials/creating-a-todo-app#setup and the zip seems damaged. Unzipping it on my linux machine, the src dir is empty and I'm seeing a bunch of strange `__MACOSX` folders around. It would be good to have a zip that worked on all os-es (for all I know it doesn't work on mac either, I'm not able to test that)

**Comment by EisenbergEffect** [comment]
@trondhindenes Apologies for the issues you are facing! Here's a version of the zip from my machine that unzips properly for me.

[basic-aurelia-project.zip](https://github.com/aurelia/framework/files/2436020/basic-aurelia-project.zip)

Can you give it a try? If it has issues as well, then we'll provide an alternate source for you.

@bigopon Can you test the attached file as well? I'm on OSX. I believe you're on Windows. It may be something specific to Linux that we need to track down.

@trondhindenes  Please let us know and again we apologize for the inconvenience.

**Comment by bigopon** [comment]
@EisenbergEffect  I'm having the same issue with @trondhindenes

**Comment by EisenbergEffect** [comment]
Very odd. Let me commit the raw files somewhere and see if you can create new zip @bigopon Then we can test it across all the platforms. Very strange stuff.

**Comment by bigopon** [comment]
@trondhindenes @EisenbergEffect I see where the confusion coming from. The base project setup is for starting up the application the traditional way, with `<script src="aurelia..." />`. And it's meant for following the tutorial in the doc. So `src` folder should be empty and later filled up with content from the tutorial. I think it works fine. Can you check again @trondhindenes

**Comment by trondhindenes** [comment]
Thanks @EisenbergEffect this one looks good, output for ref:
```
~/Downloads  unzip basic-aurelia-project.zip 
Archive:  basic-aurelia-project.zip
  inflating: favicon.ico             
  inflating: index.html              
  inflating: jsconfig.json           
   creating: scripts/
  inflating: scripts/.DS_Store       
   creating: __MACOSX/
   creating: __MACOSX/scripts/
  inflating: __MACOSX/scripts/._.DS_Store  
  inflating: scripts/aurelia-core.js  
  inflating: scripts/aurelia-core.min.js  
  inflating: scripts/aurelia-routing.js  
  inflating: scripts/aurelia-routing.min.js  
   creating: scripts/babel/
   creating: scripts/babel/systemjs-plugin-babel@0.0.12/
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/.jspm-hash  
   creating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/asyncToGenerator.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/classCallCheck.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/createClass.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/defaults.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/defineEnumerableProperties.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/defineProperty.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/extends.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/get.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/inherits.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/instanceof.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/interopRequireDefault.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/interopRequireWildcard.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/jsx.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/newArrowCheck.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/objectDestructuringEmpty.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/objectWithoutProperties.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/possibleConstructorReturn.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/selfGlobal.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/set.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/slicedToArray.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/slicedToArrayLoose.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/taggedTemplateLiteral.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/taggedTemplateLiteralLoose.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/temporalRef.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/temporalUndefined.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/toArray.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/toConsumableArray.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers/typeof.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/babel-helpers.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/plugin-babel.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/regenerator-runtime.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/systemjs-babel-browser.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12/systemjs-babel-node.js  
  inflating: scripts/babel/systemjs-plugin-babel@0.0.12.json  
  inflating: scripts/config-esnext.js  
  inflating: scripts/config-typescript.js  
  inflating: scripts/system.js       
   creating: src/
  inflating: src/.DS_Store           
   creating: __MACOSX/src/
  inflating: __MACOSX/src/._.DS_Store  

```

**Comment by trondhindenes** [comment]
@bigopon I think I understand what you mean. I read `you need to swap its src so that it points at scripts/config-esnext.js` but at that point there is no file at `scripts/config-esnext.js` but that's okay? tbh I stopped reading because I was pointing at a non-existing file.
It would probably make sense to have a note in the walkthrough about the fact that those dirs are expected to be empty at this point in the tutorial.

**Comment by bigopon** [comment]
@trondhindenes Sounds like some todo for @EisenbergEffect :)

**Comment by EisenbergEffect** [comment]
There should be a file at `scripts/config-esnext.js` but no content under the `src` folder yet.

**Comment by trondhindenes** [comment]
ok. let me recheck. sorry for the conundrum

**Comment by Alexander-Taran** [comment]
![image](https://user-images.githubusercontent.com/1029452/47046759-946cdb00-d19e-11e8-99a2-ef250febf549.png)
![image](https://user-images.githubusercontent.com/1029452/47046777-9d5dac80-d19e-11e8-8108-3c897c803c4d.png)
everything works fine on linux

**Comment by trondhindenes** [comment]
Since this was my bad, I guess I get to close it. Thanks for the help everyone!
