### ISSUE TITLE
Observing variables not contained in repeated item in a repeater doesn't seem to work.

### ISSUE THREAD

**Issue by alankila** [aurelia/framework#913]
**I'm submitting a bug report**

* **Library Version:**
0.35.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.0

* **Node Version:**
10.12.0

* **NPM Version:**
6.4.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.35.1 | webpack 4.22.0

* **Browser:**
all (only tested on Firefox 63 and Chrome 69, but I expect the problem to be general.)

* **Language:**
TypeScript 3.1.3

**Current behavior:**

Have a simple static list, and in template, reference to a value in your module that is not member of the list, e.g. some variable from the top level object. For instance, this fragment in some module will do:

```typescript
someList = [1, 2, 3];
someValue?: string;

setSomeValue() {
   this.someValue = "x";
}
```

Then, have the following code in the corresponding template file:

```html
${someValue}
<div repeat.for="x of someList">${x} ${someValue}</div>
<button click.delegate="setSomeValue()">Click me</button>
```

On running this code, you will see a sequence of divs with text content "1", "2", "3". When you click the button, "x" appears before the "1", but the items with numbers do not get transformed to "1 x", "2 x", etc.

**Expected/desired behavior:**

The expected rendered content of the list should look like "x", "1 x", "2 x", "3 x". Each item in the repeat depends on the someValue, and Aurelia is capable of observing this value as long as reference to someValue occurs outside the repeater. This is surprising and unexpected.

The desired behavior can be simulated if someList is transformed into a computed property with @computedFrom annotation that makes the template's dependency on someValue explicit:

```typescript
@computedFrom("someValue")
get someList() {
    return [1,2,3];
}
```

* **What is the motivation / use case for changing the behavior?**

Improving the consistency of behavior when observing values both inside and outside of a repeater would remove one surprise from using Aurelia. Note that this situation occurs quite commonly when you have e.g. a list of buttons, and clicking one of the buttons sets the active item, and you want to do something like

```html
<button repeat.for="x of items" class.bind="activeItem == x ? 'active' : ''" click.delegate="setActiveItem(x)">${x}</button>
```

Setting the activeItem does not cause the class to be added until the list is redrawn, which might never happen.

**Comment by bigopon** [comment]
@alankila When a binding tries to find value of `someValue` expression, it walks up the scope tree, which is `repeat ---> app` and looks for property `someValue` along the way. If none of the scope has that property, it will be then defined in the current level, which is the scope created on the fly by `repeat`, and the binding will be bound against that. Thus, app `scope` changes won't be seen by the binding. What you can do is to always initialize property `someValue` on list container to make bindings "see" it.

```ts
someValue?: string = undefined; // or an empty string
```

**Comment by alankila** [comment]
Thank you for helping me to understand this issue. This indeed also fixes the issue. I understand that the situation is tricky, because the unresolved reference must be created in some scope, and in this case the choice just happens to be wrong.

Since my code is in typescript, with some class metadata included, I wonder if some introspection could be added to Aurelia to discover the existence of the property directly from the class metadata?

**Comment by alankila** [comment]
Never mind. I imagined that such class metadata would exist in the first place, but based on some investigation, it appears that the use cases for metadata are limited to just examining the presence of various decorators. The "someValue?: string" appears to just vanish in the compilation process.

As far as I'm concerned, this issue is probably unfixable and may be closed.
