### ISSUE TITLE
jspm install fails on demo app

### ISSUE THREAD

**Issue by rhoffmann** [aurelia/framework#92]
Hello Aurelia Team,

This is a possible duplication of #42, but it still does not seem possible to install the example app with `jspm install`:

```
 jspm install -y                                                                                     
     Updating registry cache...
     Looking up npm:font-awesome
ok   Up to date - font-awesome as npm:font-awesome@^4.3.0 (4.3.0)

err  Error locating github:aurelia/http-client
     TypeError: Cannot read property 'redirect' of undefined

warn Installation changes not saved.
```

sometimes it stops on `github:aurelia/dependency-injection` or `github:aurelia/bootstrapper` with the same error.

I am using node 0.12.2 (current stable), jspm 0.11.3, npm 2.7.4 on OSX10.10, zshell.

Any ideas?

**Comment by BrettMN** [comment]
Is that the latest version of jspm?

It looks like a similar issue to this https://www.wipdeveloper.com/2015/04/18/jspm-err-error-locating-github/ Maybe try deleting the config for jspm.

**Comment by rhoffmann** [comment]
Thank you @BrettMN!

This really helped, it seems the .jspm configuration files for an older version of jspm~0.11 were the problem. I deleted the ~/.jspm folder and jspm seems to work now. Also i needed to check out the last tagged version of the repository, not the master branch.

Using the `generator-aurelia` with yeoman also worked.
