### ISSUE TITLE
Ability of changeing state twice in on action | dispatching action inside another | disposing actions in async way

### ISSUE THREAD

**Issue by ConductedClever** [aurelia/framework#921]
**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

* **Operating System:**
Windows 10

* **Node Version:**
11.2.0

* **NPM Version:**
6.4.1

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 1.0.0-beta.6

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
In our company an skeleton (template) is developed to be used in many projects. The main idea of this skeleton is to use aurelia-store as the main manager for data, services and etc.

The solution is this way: In viewmodel instead of doing main jobs or extracting the main job to a service, we dispatch one or more actions and inside it all jobs get done. For example the action gets some params from viewmodel, sends them to a remote server (web api) and then change the state.

Using this skeleton we have 3 following issues:

1. The very main issue is that dispatching actions are scheduled in an async queue. So that, when there are many components side by side, and there are many action dispatches inside them, all of them are queued to be done one after another and not async to each other.
2. The second issue is that, as the state can be changed one time along each action dispatch, we can not do some related jobs aside each other. For example assume that I want to display a loading indicator before calling web api and hide it after data retrieved. For making the mask disappear, I can change the loading state at the time data is received and I am putting the data into store, but for showing loading, I need to change the state once before data retrieved and once after that (which is impossible).
3. And the last one is, dispatching one action inside another one. Additional to second issue, maybe I want to wrap the first state update into another action and dispatch the second one inside first one. But in the actions, there is no access to store, and hence there is no access to dispatch.

**Expected/desired behavior:**
1. Move the async queue behaviour into the state changing part. So that, the other lines of code will run asynchronously and the state update part being queued in an async queue.
2. Like the observables in rxjs, let the developer to send next state more that one time. For example instead of returning next state, call a predefined function named `nextState(nextState);`.
3. Let an action see the store as its `this` scope and call dispatch function on it.

* **What is the motivation / use case for changing the behavior?**
The motivation of these features is to let action replace the use cases of service (login layer) and be more generic in using purposes.

* **Additional comments**
There is another solution to not facing these issues. The solution will be to place a service layer before action dispatch. So that inside the service as data update in store is needed, a dispatch will be called.
But in our skeleton, we want to reduce the layers count and remove service layer as it is not necessary.

**Comment by zewa666** [comment]
Hi @ConductedClever, could you move over/recreate this issue to the [aurelia-store](https://github.com/aurelia/store) repo so we continue the discussion over there?

**Comment by ConductedClever** [comment]
Hi @zewa666, ofcourse.

**Comment by ConductedClever** [comment]
Successfully moved [here](https://github.com/aurelia/store/issues855)
