### ISSUE TITLE
Returning a ModifyArrayObserver in SortValueConverter results in infinite task queue loop

### ISSUE THREAD

**Issue by mreiche** [aurelia/framework#927]
**I'm submitting a bug report**

* **Library Version:**
aurelia-task-queue@^1.3.1
aurelia-binding@^2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
11.6.0

* **NPM Version:**
6.5.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
webpack@4.29.6

* **Browser:**
all | Chrome  72.0.3626.12

* **Language:**
typescript@3.3.4000

**Current behavior:**
I've implemented a SortValueConverter  like https://aurelia.io/docs/binding/value-converters#multiple-parameters-composing-converters with slightly changes.

But sometimes, when sorting select values like
```html
 <div
        class="form-check form-check-inline"
        repeat.for="option of definition.scheme.selectAvailable|sort"
    >
        <label class="form-check-label">
            <input class="form-check-input" type="checkbox" model.bind="option" disabled.bind="disabled" checked.bind="_stringValueList">
            ${option}
        </label>
    </div>
```
the browser freezes due an infinite loop. I've tried to debug that and saw, that the SortValueConverter is called infinitely and results and the aurelia task queue fills more and more.

This also seems only to happen, when this code above exists twice in the DOM (with the exact same array to sort).

Code of the SortValueConverter:
```typescript
toView(array:any[], propertyName:string, factor:number=1) {
        if (array instanceof Array === false) {
            return [];
        }
        let propertyPath;
        if (propertyName) {
            propertyPath = propertyName.split('.');
        } else {
            propertyPath = [];
        }
       const sorted = array.sort((a, b) => {
            const aVal = SortValueConverter.getPropertyByPath(a, propertyPath);
            const bVal = SortValueConverter.getPropertyByPath(b, propertyPath);
            if (typeof aVal === 'number') {
                return (aVal - bVal) * factor;
            } else if (typeof aVal === 'string') {
                return aVal.localeCompare(bVal) * factor;
            } else return 0;
        });
        console.log(array, sorted);
        return sorted;
    }
```

Console output:
```
(3) ["xxx", "yyy", "aaa", __array_observer__: ModifyArrayObserver]
(3) ["aaa", "xxx", "yyy", __array_observer__: ModifyArrayObserver]
```
I fixed that, by not returning the same array, but a new copy of that. which is not observable.

 ```typescript
const sorted = array.slice(0).sort();
```

**Comment by bigopon** [comment]
@mreiche The behavior you described is an expected behavior. What happens when you have the following template:

```html
<div repeat.for="item of items | sort :firstName>${item.firstName}</div>
<div repeat.for="item of items | sort :lastName>${item.lastName}</div>
```

There will be 2 `repeat` instances, observing mutation on the same array. Because `sort` mutates the array so sorting the `repeat(1)` will trigger `repeat(2)` change handler, and make it reevaluate the expression, and `repeat(2)` has `sort` in its expression, so it trigger change handler in `repeat(1)`, and it continues.

The safest way to do it is to `.slice(0)` before doing sort, as you have already done in your referenced commit. Note that Aurelia is able to observe the array even with value converter returning new array.

**Comment by mreiche** [comment]
@bigopon Thanks for your answer. As you can see, I've already implemented the bugfix. But you should consider to update the code in the example SortValueConverter here: https://aurelia.io/docs/binding/value-converters#multiple-parameters-composing-converters
```
return array.sort((a, b) => {
    return (a[propertyName] - b[propertyName]) * factor;
});
```

**Comment by bigopon** [comment]
@mreiche thanks. Let's ping @EisenbergEffect 😆

**Comment by EisenbergEffect** [comment]
We'd be happy to take a PR to the documentation. It can be found here: https://github.com/aurelia/documentation/blob/master/current/en-us/4.%20binding/8.%20value-converters.md
