### ISSUE TITLE
 After building my project, the dist folder is not loading the vendor files

### ISSUE THREAD

**Issue by IsaacHub** [aurelia/framework#928]
I have created a new aurelia project using `au new`, and when I run using `au run`, everything works fine, but after I build using `au build --env prod` I got a `dist` folder and successfully built as it should be.. 

Here's my project specs:

![aurelia_issue](https://user-images.githubusercontent.com/20126441/56281754-08c30f80-612b-11e9-84d1-77247b66169c.png)

Now I moved the dist folder to other location and opened up the `index.html` in chrome, here is what I got:

![aurelia_issue2](https://user-images.githubusercontent.com/20126441/56281738-fc3eb700-612a-11e9-804b-1d0cc2c18f0f.png)

As you can see the `<script>` tag has `src="/vendor.."` because of the leading forward slash`(/) ` the relative path makes no sense at all. 

**COULD SOMEONE HELP ME OUT? THIS IS FRUSTRATING.**   This is unbelievable. A modern framework does not have a proper documentation for build process.. Every time I have to remove those slashes manually, what is the workaround?

**Comment by IsaacHub** [comment]
I created a virtualhost and it worked.

**Comment by bigopon** [comment]
@IsaacHub it sort of always requires a web server, or what you would call virtualhost to work. I guess what we can improve, as you suggested, is to generate html with path to bundle without leading slash so that if someone chooses to have everything in 1 bundle, it will just work.

cc @huochunpeng

**Comment by huochunpeng** [comment]
Most browser doesn't support relative resource path when opening a html page directly from file system.

The easiest way to get a web server to verify static files.
```
npm i -g http-server
```
Then in the folder, run
```
http-server
```

**Comment by huochunpeng** [comment]
Sorry, I missed the original question. I tried to find out how to remove the absolute path in https://github.com/jantimon/html-webpack-plugin#options but webpack is just too much for my primitive brain to understand.
