### ISSUE TITLE
How to fetch data from a JSON file in aurelia framework?

### ISSUE THREAD

**Issue by IsaacHub** [aurelia/framework#929]
I'm trying to fetch data from external JSON file using [aurelia-fetch-client](https://aurelia.io/docs/plugins/http-services#aurelia-fetch-client) but it gives 404 not found error.

I have tried implementing the basic setup suggested by the official docs.

Here is my code:

```
import {HttpClient } from 'aurelia-fetch-client';

let httpClient = new HttpClient();
export class ChangeRequest {
constructor(){
  httpClient.fetch('sample.json')
    .then(response => response.json())
    .then(res => {
      console.log(res);
 }
}
}
```

I should get the result of the JSON data, but I'm getting the following error:

![error](https://i.imgur.com/Slap6Oe.png)

Here's my folder structure which was created using `aurelia-cli`

![](https://i.imgur.com/IDTdmQD.png)

As you can see the `sample.json` is inside the `src` folder, and I have tried putting it inside the `src/Assets` folder but same result.

**Comment by EisenbergEffect** [comment]
Can you share what you are seeing in the raw response? The browser's network panel should be able to show that to you. It will help us better diagnose what's going on here.

**Comment by AshleyGrant** [comment]
Also, what Aurelia CLI setup are you using? Are you using Webpack or the built-in bundler?

**Comment by AshleyGrant** [comment]
Nevermind.. I see you're using Webpack from your StackOverflow question... @EisenbergEffect please close this issue.

**Comment by EisenbergEffect** [comment]
Thanks @AshleyGrant !
