### ISSUE TITLE
How to bind repeat.for on the async array variable?

### ISSUE THREAD

**Issue by Bibis97** [aurelia/framework#930]
I'm fetching json from a file which is inside `static` folder and I retrieve the keys and push it into an array and trying to bind in the html.

I have the following code in `home.js`: 

```
export class Home {
headArr = [];
  async attached() {
    const fetchedData = await fetch('sample.json')
      .then(response => response.json());
    console.log('JSON loaded via fetch', fetchedData);
   let col = [];
    for (let i = 0; i < fetchedData.length; i++) {
      for (let key in fetchedData[i]) {
        if (fetchedData[i].hasOwnProperty(key) && col.indexOf(key) === -1) {
          col.push(key);
        }
      }
    }
this.headArr = col;
  }
}
```

and then in `home.html` I have the following:

```
<li repeat.for = "head of headArr ">
       ${head}
</li>
```

**Because we fetch the json asynchronously the `headArr` is empty when the page is loaded. In Angular we have `async` pipe to fix this, similarly how to fix this in aurelia?**

**Comment by weagle08** [comment]
What you have shown should be working. The async fetch doesn't matter here. You might could try to do a this.headArr.splice(0) and push the new values into the existing array reference rather than do a reassignment and see if that fixes it.

**Comment by StrahilKazlachev** [comment]
I don't understand your issue. Nothing shows, things show later than expected or ...?
Also the way the binding is shown seems a bit awkward to me, all those spaces.
> `<li repeat.for = "head of headArr ">`

**Comment by Bibis97** [comment]
Ok.. Now it's working, and I have another issue: I have html in JSON as seen below `<i>` tag for font awesome icon, and it is being rendered as normal text string. How to render as html element?
```
[
    {
        "id":1001,
        "Change Request Name":"High Power Output",
        "System":"Cylinder Head&valve Mechanism",
        "Owner":"Juho",
        "Status":"<i class='fa  fa-vimeo-square fa-rotate-90'></i>  Review"
    },
    {
        "id":1002,
        "Change Request Name":"Value Packages",
        "System":"Ancilary Systems",
        "Owner":"Petteri",
        "Status":"<i class='fa-retweet fa'></i> Development"
    }
]

```

**Comment by Bibis97** [comment]
Ok done, I achieved it with `<span innerHTML.bind="val"></span>`

**Comment by bigopon** [comment]
@Bibis97 please note that the correct syntax is
```html
<span innerhtml.bind="val"></span>
```
Just html is case insensitive, so it will see `innerHTML.bind="..."` as `innerhtml.bind="..."`, so it worked as intended.
