### ISSUE TITLE
set object that has observed properties breaks the observing system

### ISSUE THREAD

**Issue by ilsergente1993** [aurelia/framework#935]
**I'm submitting a bug** ( even question and feature request)

**Current behavior:**
To observe an object that has several properties I'm using an array that collects the subscribes performed through the `BindingEngine`.
I use this code:
```Javascript
for (let o in this.obj) {
      this.propObserverSubscription.push(this.be.propertyObserver(this.obj, o)
          .subscribe((_new, _old) => {
                console.log(o, ":", _old, "-->", _new)
          }
))}
```
Where `be` is the `BindingEngine` instance and to cancel the subscription I just perform the `unscribe()` on each element of the array.

So, if I directly set a property of the object `obj` I get the log in the console (i.e.: `this.obj.p1='hey'`).
But, if I set all the object I lose everything around the object's properties.
The following operation breaks my observation system:
```Javascript
public resetBadObj() {
    this.obj = { p1: "asd", p2: 10, p3: true };
  }
```
a workaround is:
```Javascript
public resetObj() {
    this.obj.p1 = "asd"
    this.obj.p2 = 10;
    this.obj.p3 = true;
  }
```
Since I've no idea how the binding engine performs the subscriptions I can only suppose it's really javascript reference's stuff related.

**Expected/desired behavior:**
To have the observer still working after setting all the object.

**What is the motivation / use case for changing the behavior?**
Obviously, it's not comfortable to have such a breaking way. Is it a solvable bug?

By the way, I would suggest to change the signature and accordingly edit the function to have the possibility to pass an array of property names.
`propertyObserver(obj: Object, propertyName: string | string[]): PropertyObserver | PropertyObserver[];` in cases like mine where any change on the passed property names has the same function to call (for example a db update).

Am I missing something? because I didn't find any resource that explains how to use the other provided functions (`expressionObserver`, `parseExpression`, `registerAdapter`)

**Comment by bigopon** [comment]
@ilsergente1993 thanks for filing this issue.

The behavior you experienced is the expected behavior. Observing an object does not and should not observe other objects. In your example, I would observe both `obj` and its property for changes, so it would look like the following:

```ts
import { PropertyObserver } from 'aurelia-binding'; // or 'aurelia-framework'

export class MyClass {
  
  @bindable obj: object;

  subscriptions: Disposable[];
  
  objChanged(newObj) {
    if (this.subscriptions) {
      this.subscriptions.forEach(subscription => subscription.dispose());
      this.subscriptions = undefined;
    }
    if (newObj) {
      this.subscriptions = this.observeObj(newObj);
    }
  }

  /**
   * Return a list of disposables, each mapped to a subscription of corresponding property on a given obj 
   */
  observeObj(obj: object): Disposable[] {
    return Object.keys(obj).forEach(propertyName => {
      this.be.propertyObserver(obj, propertyName).subscribe((newValue, oldValue) => {
        // do something with new value
      });
    }); 
  }
}
```

**Comment by ilsergente1993** [comment]
Thanks for the code @bigopon 
I got your point to keep it flexible but, in my opinion, the framework should offer easy ways for common scenarios.
First of all, if I have an object with several properties, I expect one function to observe all the object properties, at least till the first nested level, that share the same callback, like: 
```Javascript
this.be.propertyObserver(obj).subscribe((newValue, oldValue) => {
        // do something with new value
      });
```
and this can return the array of subscriptions or
```Javascript
propertyObserver(obj: Object, propertyName: string | string[]): PropertyObserver | PropertyObserver[]; 
```
as I wrote before.

Then, actually, I don't understand why this `this.obj = { p1: "asd", p2: 10, p3: true };` should not fire the callback and should break the observing system. If I observe only `p1` of `obj`, doing `this.obj = { p1: "asd", p2: 10, p3: true };` I actually change `p1` property value.

So why shouldn't it fire the callback?

Thanks for the explanation 😄

**Comment by bigopon** [comment]
The API propery observer is:
```ts
  propertyObserver(obj: object, propertyName: string): PropertyObserver;
```

It reads like this: for a given `obj`, and a `propertyName`, create a observer on `obj` for that `propertyName`.

So you can see that what we create is an observer of an object. It doesn't care if you threw that object away to replace it with something else. It only cares about its job: observe `propertyName` property on  object `obj`.

Probably what you want is to use expression observer:

```ts
bindingEngine.expressionObserver(this, 'obj.p1').subscribe(newP1Value => {
  // react to new value of this.obj.p1
});
```
Using expression observer above, you are observing the whole path specified in that expression, so replacing object will set up new observer properly for you.

**Comment by ilsergente1993** [comment]
> It reads like this: for a given obj, and a propertyName, create a observer on obj for that propertyName.
Now I got it, thanks for the explanation @bigopon 

And the expression observer now has a reason to be there 😄 
Again, thanks
