### ISSUE TITLE
Publish Aurelia project with visual studio 2017. 

### ISSUE THREAD

**Issue by UMANGAWASTHY** [aurelia/framework#939]
As I am new to Aurelia, Can any one please sent me the steps to deploy Aurelia application to IIS using Visual Studio 2017.
I am using web api, which is build on dotnet 4.7.1 framework for server side and aurelia framework for client side.
I want to publish aurelia project to IIS with web deploy package.

**Comment by EisenbergEffect** [comment]
Hello @UMANGAWASTHY I think the best place to get a response to that question is in our community forum. You can find that at discourse.aurelia.io.
