### ISSUE TITLE
Cache busting with Aurelia

### ISSUE THREAD

**Issue by smolinari** [aurelia/framework#94]
Is there a way to cache bust the dist files and also replace smartly the calls to the files with the proper file names too? I've added gulp-rev to the build.js file, but it also breaks Aurelia, because the framework is looking for "app.js" and not "app-01123c47.js". How can I do cache busting properly with Aurelia?

Thanks for any help in advance.

Scott

**Comment by cristimusat** [comment]
I also tried gulp-rev with no success. From Aurelia docs I understood that app.js is a convention which can be overwritten but my problem was that views and model-views had different names.
Gulp-rev adds a different hash to the end of each file.
What I can see as a possible solution would be something like gulp-rev to add version number to the files. This I didn't found yet.

**Comment by Aaike** [comment]
JSPM can be used for [cache busting](https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader#custom-extension-example---cache-busting-extension)
it requires you to create an extension for systemjs , but an example is provided.

**Comment by smolinari** [comment]
Since I am a bit of a noob, would it be too much to ask for an example extension written for Aurelia? This must be something standard everyone needs to deploy changes, isn't it?

Scott

**Comment by Aaike** [comment]
@smolinari 
change your index.html to add the extension right before you import the `aurelia-bootstrapper`

```
<script>
      var systemLocate = System.locate;
      System.locate = function(load) {
        var System = this;
        return Promise.resolve(systemLocate.call(this, load)).then(function(address) {
          if(address.lastIndexOf("html.js") > -1) return address;
          return address + System.cacheBust;
        });
      };
      System.cacheBust = '?bust=' + Date.now();
      
      System.import('aurelia-bootstrapper');
    </script>
```

**Comment by cristimusat** [comment]
@smolinari 
you need to add also 
```
if(address.lastIndexOf("css.js") > -1) return address;
```

**Comment by smolinari** [comment]
Thanks for that and I obviously have a lot to learn, because this is what just happened to me.

https://www.youtube.com/watch?v=wCy8MpT45gk

Scott

**Comment by kristianmandrup** [comment]
Should be added to documentation somewhere ;)

**Comment by t3hmrman** [comment]
+1
Just ran into this -- modified app.html wasn't being picked up by Aurelia/SystemJS, which was causing lots of confusion for me. At first I thought it was Flask (which it partially was), and then I ran into this issue thread. Would be nice if I could turn caching off with an option somewhere.

For now I'll be copy-pasting @Aaike 's suggestion. Maybe it's my fault for not being a SystemJS expert, and realizing it was doing the caching earlier, and realizing how "easy" it is to write an extension. But I kind of think it sucks that SystemJS is forcing me to dive into writing an extension just to get such basic dev-required functionality. 

I'd expect to have to deal with/straighten up my caching/bundling strategy when I'm ready to deploy, not 5 mins into regular development.

**Comment by Aaike** [comment]
i'd like to note though that it's not SystemJS that is doing the caching it is your browser. Every loader out there need to implement an anti-cache.

That said it would indeed be nice it this could be a simple configuration option in systemjs, you could ask for it to be added in their repo, however an issue for this has been opened in the past i think. I'm not sure what their thought is on making a simple option for it.

**Comment by t3hmrman** [comment]
Ah but I was setting cache headers on my files (through Flask) -- I wasn't even seeing a request for app.html/app.js at all, which is what lead me to think that SystemJS was optimizing away the loads somewhere. That's what led me to think it was SystemJS and not just browser-level caching (which I should have been able to control with file-sent headers)

**Comment by VagyokC4** [comment]
@cristimusat @Aaike Why must you exclude files ending in 'html.js' and 'css.js' from cache busting?

> https://github.com/aurelia/framework/issues/94#issuecomment-100272659
> https://github.com/aurelia/framework/issues/94#issuecomment-100270135

**Comment by shaunluttin** [comment]
Our preferred implementation is to change the directory name. This requires changing two files: 

config.js

```
System.config({
  defaultJSExtensions: true,
  transpiler: "none",
  paths: {
    "*": "dist-001/*",                                                  < Increment this.
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
```

build/paths.js

```
var appRoot = 'src/';
var outputRoot = 'dist-001/';      < Increment this.
var exporSrvtRoot = 'export/'
```

**Comment by shaunluttin** [comment]
This is how we're handling it. 

Find `dist` and replace the following instances with `dist[verson]` E.g. dist001.

    bundles.js
      "dist001/app-build"
    
    paths.js 
      "dist001/aurelia"
    
    config.js
      "*": "dist001/*"
    
    package.json
      "main": "dist001/main.js"
      
 Then run `gulp bundle`. 
 
 Finally, FTP the following to the web root. 
 
     styles
     src
     jspm_packages
     dist001
     web.config
     index.js
     index.html
     config.js

**Comment by httpJunkie** [comment]
I like to put my cache busting js code into it's own file and then use SystemJs to bring it in:

```
    //Remove the follwoing line for production (use cacheBuster)
    //unComment the follwoing line for development(do not use cacheBuster)
    System.import("cacheBuster");
```

**Comment by lmj0011** [comment]
@VagyokC4 
>@cristimusat @Aaike Why must you exclude files ending in 'html.js' and 'css.js' from cache busting?

I excluded that line after seeing that it had no effect on my requests.

I believe the unexplained code that @cristimusat suggested, is suppose to prevent double appending of the cacheBust

ex. `app.css?v0.0.0-1?v=0.0.0-1`
or
ex. `app.html?v0.0.0-1?v=0.0.0-1`

However, I still saw request like the above example in the console. It doesn't tamper with the file request since the query will be parse like:

v: `0.0.0-1?v=0.0.0-1`

So it's ok to ignore it.

**Comment by manyrootsofallevil** [comment]
I tried @Aaike's suggestion but the application is severely broken

In short this is the error i get:

> Error loading http://localhost:49850/dist/app.html?bust=1491418021855!http://localhost:49850/jspm_packages/github/systemjs/plugin-text@0.0.8.js

The bundled application file has this 

`a("app.html!github:systemjs/plugin-text@0.0.8.js", ....`

so perhaps unsurprisingly, it can't find it

Any ideas?

**Comment by manyrootsofallevil** [comment]
this **seems** to be working for me

```
 <script>
        var systemLocate = System.locate;
        System.locate = function (load) {
            var System = this;
            return Promise.resolve(systemLocate.call(this, load)).then(function (address) {
                if (address.lastIndexOf(".html") > -1) return address;
                if (address.lastIndexOf(".css") > -1) return address;
              

                return address + System.cacheBust;
            });
        };
        System.cacheBust = '?bust=' + Date.now();       
        System.import('aurelia-bootstrapper');
    </script>
```

Using ASP.NET Core

**Comment by jamesond** [comment]
@manyrootsofallevil I have implemented your solution awhile ago but I still am having some caching issues with my html files it seems. Are you still using the above code?
