### ISSUE TITLE
execute function in template

### ISSUE THREAD

**Issue by pianoboysai** [aurelia/framework#95]
I wrote code like this
app.html
```
<template>
    <div class="split-me-container">
        <div class="split-me">
            <div> Left Side</div>
            <div> Right Side</div>
        </div>
    </div>
    <script>${welcome()}</script>
</template>
```

app.js
```
import $ from 'jquery';
import 'touch-splitter-jquery/src/jquery.touchsplitter';

export class ReadList {
    constructor() {
        this.name= 'sai';
    }

    welcome()
    {
        alert(`Welcome, ${this.name}!`);
        var splitter = $('.split-me');
    }
}
```
now I have 3 questions
1. the "jquery.touchsplitter" depends on jquery
"
import $ from 'jquery';
import 'touch-splitter-jquery/src/jquery.touchsplitter';" 
" 
but since module loading is asynchronous like this,  I still can't confirm jquery loading before jquery.touchsplitter,  how could I solve? I really don't want to modify jquery.touchsplitter code

2. every time I load this page, it call "welcome()" twice!

3. the $('.split-me'); always return [], I guess it's due to the div hasn't been created that time, so, how could I get a chance to initialize data with "jquery" ?

appreciate if someone could help me, thanks.

**Comment by PWKad** [comment]
@pianoboysai Please direct code review type questions to our [official gitter](https://gitter.im/Aurelia/Discuss).  Someone is usually available to point out issues you have.

**Comment by jdanyow** [comment]
@pianoboysai @PWKad can we close this?

**Comment by danielarhi** [comment]
I`ve faced the same problem. The ${welcome()} will be called automatically when the page has loaded and not when the user has entered to the <script> tag. There is a solution which solves the problem, but this have some problems: 

See the detailed answer on StackOverflow: http://stackoverflow.com/questions/32048859/call-a-aurelia-function-from-script

Sometimes needs much time to call the function, and data binding doesn`t work if you are not in app.html/js. Is there a better solution?
