### ISSUE TITLE
Kendo UI Documentation/Strategy

### ISSUE THREAD

**Issue by lelong37** [aurelia/framework#98]
Could we have a doc similar to http://durandaljs.com/documentation/KendoUI.html for Kendo UI integration?

**Comment by gordon-matt** [comment]
+1

**Comment by kburge** [comment]
+1 here too

**Comment by dfstewart3** [comment]
+1

**Comment by ftaljaard** [comment]
+1

**Comment by johncclayton** [comment]
+1

**Comment by volak** [comment]
Kendo UI doesn't support web components - yet -
Looking at Q3 2015 last I heard http://www.telerik.com/blogs/announcing-the-telerik-kendo-ui-q3-2015-roadmap

Once that happens I'm sure it will be fairly trivial to use them in aurelia or any app.  

Kendo's own binding stuff probably won't be easy or even possible to integrate - at least not nearly as easy as in Durandal.  So if you are hoping for this feature expect to be working on the very latest kendo ui and not using their binding system

/2cents

**Comment by zewa666** [comment]
@charlespockert maybe you can tell us what you've done so far with your Kendo UI integration for Aurelia?

**Comment by CharlesPockert** [comment]
Ah well it's mostly just a lot of plugging standard Aurelia features into the kendo datasource.

It's all I really need, I'm not doing anything more advanced than reads, no updates (I use pop-up forms for edits, but not kendo ones). I've not really touched kendo observables.

https://gist.github.com/CharlesPockert/1ef96e44f3f15ab60f5e

There's a trick in there to compile cell templates so you can use aurelia in the templates.

Other thing is that I didn't like passing js objects to kendo either in the vm or view, I prefer HTML in the view so the kendo grid custom element preprocesses the view to parse out html elements as key/value pairs for the grid.

Hope it helps someone, it's not really a full kendo integration in any way but it works for me

**Comment by EisenbergEffect** [comment]
Closing this for now. If a community member using Kendo would like to write an article on integration we would be happy to feature it on the official blog or include it in the new upcoming docs though.

The best path forward for is going to be to work with web components-based libraries, since those will "just work" for the most part.

**Comment by adriatic** [comment]
Update: check http://blog.durandal.io/2016/01/28/aurelia-and-kendo-ui/

**Comment by kburge** [comment]
This is excellent news! Thanks Rob and team.

Ken

On Thu, Jan 28, 2016 at 9:43 PM, Nikolaj Ivancic <notifications@github.com>
wrote:

> Update: check http://blog.durandal.io/2016/01/28/aurelia-and-kendo-ui/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/framework/issues/98#issuecomment-176556356>.
>



-- 
Thanks,
Ken

**Comment by EisenbergEffect** [comment]
Thanks goes to @adriatic and the group he's assembled to work on UI library implementations.

@adriatic Before I forget, would your team mind authoring an article that we can put into our official docs. We have an "integration" section that would be a good place to talk about using Kendo UI with Aurelia. It doesn't have to be a long article, just something to introduce the library and then point people to your site. It would be good for it to be there. As people poke around they'll find it and then head over to check it out.

**Comment by adriatic** [comment]
Yes, of course - I know about this "integration" section and it's a good idea to contribute to that.
