### ISSUE TITLE
How to use aurelia in qiankun

### ISSUE THREAD

**Issue by crazy365966834** [aurelia/framework#987]
I need to use aurelia in [qiankun](https://qiankun.umijs.org/guide/tutorial)。 but no doc in tutorial of qiankun 。I really need help to solve this problem。
       Can someone give me a demo？
       Thanks very much!
 
      I've tried to test but failed  ,my code at https://github.com/crazy365966834/qiankun-demo.git。

**Comment by johnmanko** [comment]
https://stackoverflow.com/questions/tagged/aurelia

**Comment by Alexander-Taran** [comment]
@crazy365966834 
 I'd suggest going to forums : https://discourse.aurelia.io and looking for volunteers to help you integrate the two.
On the topic of microfrontends there are other solutions available 
checkout: https://github.com/dumberjs/examples/tree/master/runtime-composition-aurelia
