### ISSUE TITLE
Feature Request: Global callback for views/viewmodels for each local callback

### ISSUE THREAD

**Issue by delebash** [aurelia/framework#99]
ie. a Global_attached() method that corresponds to attached() instance method

Something I am running into now is that I would like to be able to fire off some code each time a view is loaded.  I can use the attached method but if I want that same code to run on every class then I either have to copy the attached method to every class or extend each class with a base class that has the attached method defined.  Extending the class is ok, but still I have to touch each class by importing the base class and adding extends to it.

Instead if we had a global method for each local method ie global_attached, global_canActivate, then it would be easy to define code one place maybe app.js for any local event.  If we pass the view instance to the global callback then we can also do something like if viewInstance.name starts with "s" then run code or if viewInstance.property=X run code, we can filter out views or apply it to all views.

One possible solution is to use inheritance and define a base class, but instead of  having to manually add that class, we could just have a property in the Aurelia config that says baseClass="myBaseClass.js" and this gets applied to any class that the Router processes.  In this way not only do we make global's for Auriela's callbacks we also can add our own methods to the base class.  If we want to override the global_Attached method we just define attached for that class or we can also inherit and override by calling super.

There may be a better way to do this, as I am not a javascript expert by any means , but at least having global hooks that correspond to each local hook could be very useful.

What do you all think?

**Comment by EisenbergEffect** [comment]
Can you give me a concrete example of what you would like to accomplish with this?

**Comment by delebash** [comment]
What made me think of this is the problem I am running into with some Jquery css frameworks where they need the initialization code to run after each view is loaded, and instead of having to put that code it class I could call it from a global method, I just posted the example to gitter. 

Gitter quote
 >I am running into some problems with Jquery frameworks, specifically two but basically they are the same issue. Using materializecss and bootstrap-material-design, with Aurelia, they are not designed for a site that loads partial views or on-demand like Aurelia does. In materializecss all of the initialization code that affects the dom looks for document.ready and of course this fires once on app.html, but not on the view that is loaded. Each view that is loaded needs to have the initialization code run in order for materialize to work correctly at least from what I can tell so far. Materialize does not have a nice method that says Materialize.init so I would have to figure out each initialization method and add it the attach method of each class or add it to attach method of a base class and inherit that base class. Even if it did have one init method I would still have to call that method for every class loaded. Instead since I suspect that many jquery plugins rely on document.ready to fire for their initialization what do you think could be a good way to solve this? Maybe some way to trigger the document.ready callback after a view is loaded, this way it tricks the code into runinng its document.ready methods when each new view is loaded.
Ideas??


I think there might be a better solution to the problem that I am running into with the Jquery frameworks ,the problem I just posted on gitter, then what is posted here but in trying to solve the Jquery framework problem it made me think of why I might want this type of capability as a possible feature.

Another use could be maybe each view you want to do log when a user enters and leaves that view, send an alert, maybe just send data to server to for stats of users entering and leaving view, how long they stayed on that page ect, maybe you need to run initialization or cleanup code for each view that you classified a certain type, just a few reasons to have the same code execute on all views.  So instead of repeating that code in each activate or other method you define it as global for any activate method and can then include or exclude views in the global_method via a filter.  Just makes it easier instead of repeating the same code in each local method or having to inherit a base class on each view manually.

Hope this makes sense and is logical, it is to me but that does not necessarily mean its true :)

**Comment by navels** [comment]
Same kind of thing with our app built with Durandal.  We have some common AJAX requests that go in activate(), jquery init stuff in compositionComplete(), and some cleanup in deactivate().  We have a "BasePage" class that implements the lifecycle methods that the top-level views inherit from.

**Comment by andy-scott** [comment]
I have a similar issue where a plugin caches elements on load but these elements get added and removed when views are loaded/unloaded.  
I have sent a pull request to add a pipeline step that fires after the view is loaded into the DOM.  In our scenario it sets the elements on the plugin's global variable, this removes the need for a base class as the code is run by the router after the view is loaded into the DOM.

**Comment by kiryaka** [comment]
I'm new to the framework and don't know how bad this practice is, but I just use the ready.bind="ready()" binding on the first tag in the view. So in a template it looks like this:
```html
<template>
...
  <h1 ready.bind="ready()">Title</h1>
...
</template>
```
It works, but anyhow I'm vote +1 to implement it as a general handler for the view so there will be the place to put the code that will be executed when my view is in the DOM, but not showed yet and I can do some preprocessing and it will not blink.

I currently need it to convert the basic <select> tag to the complicated select2 lib tag selector. I also see a lot of other uses for that. All the charts and maps and other visualization stuff have to be started when the view is ready and in the DOM. There is no specific user intent for this sort of things it's just some view preprocessing.

**Comment by EisenbergEffect** [comment]
This can now be accomplished with view pipeline resource hooks.

**Comment by balazsmeszegeto** [comment]
Could you give an example how can this view pipeline should be used?
